### ISSUE TITLE
Printing jazzy generated documentation

### ISSUE THREAD

**Issue by asseeger** [realm/jazzy#1001]
Though this is not really an issue, I wanted to ask for some tips on how to easily print the generated documentation?

I do love the html result, but need to print for an appendix of a thesis, and don't want to do it manually (by opening up all the links manually before printing to pdf)...

Any hints?

**Comment by johnfairh** [comment]
I expect this is too late for any real use but for posterity: the easiest way would be to copy the theme you're using and edit it so that it always works like the dash/docset view (which doesn't have the open/close parts).

**Comment by asseeger** [comment]
Thanks, it really might be too late for the project I had been working on, but it might help for future ones. So thanks for getting back to me at all and for contributing to this nice piece of software, @johnfairh
