### ISSUE TITLE
Not Documenting private classes even after setting minimum privacy level flag to be private

### ISSUE THREAD

**Issue by eabhishekarora** [realm/jazzy#1003]
So I have been trying to generate the documentation with Jazzy in my project.

I am using Xcode 9.4 with swift 4.1.

So even after running the command "jazzy --min-acl private".

I am only getting the documentation for open and public classes.

**Comment by jpsim** [comment]
Can you share steps to reproduce your issue? From what you shared I can't give you any advice.

**Comment by eabhishekarora** [comment]
So I do:
1) gem install jazzy
2) Navigate to my project root directory and run jazzy --min-acl private
3) Still after specifying the minimum flag to be private, only the open declarations get documented

Thanks for your time

**Comment by johnfairh** [comment]
Closing, inactive.

**Comment by jbarros35** [comment]
Same issue.
