### ISSUE TITLE
Jazzy does not reuse derived data

### ISSUE THREAD

**Issue by ilyapuchka** [realm/jazzy#1005]
When running jazzy with custom derived data path it clears the content of `Build` sub-directory in this path which does not allow xcodebuild to reuse it and results and extra time spent on building something that was already built, i.e. with Carthage.

Here is the command that I use to run jazzy

```
bundle exec jazzy     --clean     --module BabylonAuthSDK     --xcodebuild-arguments -workspace,../Babylon.xcworkspace,-scheme,BabylonAuthSDK,-derivedDataPath,DerivedData/BabylonSDK,-configuration,Production,     --hide-documentation-coverage     --min-acl public     --module_version      --author "Babylon Partners LTD"     --readme ../SDK/BabylonAuthSDK/README.md     --output ../sdk-docs/BabylonAuthSDK     --sdk iphoneos
```

**Comment by jpsim** [comment]
Unfortunately, Xcode or xcodebuild doesn't provide a reliable way to get compiler the arguments which are needed to generate documentation from libclang or SourceKit. The only way I know of to reliably get these compiler arguments is to perform a clean build. If you come up with another reliable way to programmatically get compiler arguments for a given module, please let me know.

**Comment by johnfairh** [comment]
Closing this, inherent in the current xcodebuild layer.
