### ISSUE TITLE
function with many arguments get truncated in generated document 

### ISSUE THREAD

**Issue by mihirpmehta** [realm/jazzy#1008]
If the function has many argument as parameter it gets truncated
for example 
`/**
     Acquire token
     
     - parameter acceptLanguage: (header) Gets or sets the language code. 
     - parameter xAppVersion: (header) Gets or sets the string application version. 
     - parameter xDeliveryChannel: (header) Gets or sets the string delivery channel identifier. 
     - parameter acquireTokenRequestModel: (body) The acquire token request model. (optional)
     - parameter xGeoLocation: (header) Gets or sets Geo Location in comma separated format {Latitude}, {Longitude}, {Accuracy}, {Altitude}, {AltitudeAccuracy} (optional)
     - parameter xApiVersion: (header)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func authAcquireTokenPost(acceptLanguage: String,
                                         xAppVersion: String,
                                         xDeliveryChannel: String,
                                         acquireTokenRequestModel: AcquireTokenRequestModel? = nil,
                                         xGeoLocation: String? = nil,
                                         xApiVersion: String? = nil,
                                         completion: @escaping ((_ data: AcquireTokenResponseModel?,_ error: Error?) -> Void)) {
        authAcquireTokenPostWithRequestBuilder(acceptLanguage: acceptLanguage, xAppVersion: xAppVersion, xDeliveryChannel: xDeliveryChannel, acquireTokenRequestModel: acquireTokenRequestModel, xGeoLocation: xGeoLocation, xApiVersion: xApiVersion).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }`

This method's document is generated as [this](https://ibb.co/jZ0GRp)

**Comment by johnfairh** [comment]
Closing in favour of #995 that has a potential solution.
You could do `--theme fullwidth` in the interim.
