### ISSUE TITLE
The Old 'Could not parse compiler arguments from `xcodebuild` output.' Issue

### ISSUE THREAD

**Issue by LittleGreenViper** [realm/jazzy#1009]
I've looked through everything here, and seen the issue come up several times, with various 'RTFM' answers.

I would be thrilled to have an 'RTFM' answer. I have no pride or self-respect whatsoever. I just want the durn thing to work.

I use Jazzy in this project: https://cocoapods.org/pods/BMLTiOSLib

It works excellent.

However, in a new project I'm doing (also a Swift Framework), I am getting the abovementioned error.

xcodebuild has no errors. Everything builds, and the framework ends up in the "build" output. If I run it directly from the CLI.

If I CD to the project dir, and go 'jazzy', then the build works, the project gets delivered, and I get the following helpful advice from Jazzy:

Running xcodebuild

Could not parse compiler arguments from `xcodebuild` output.

Please confirm that `xcodebuild` is building a Swift module.

Saved `xcodebuild` log file: /var/folders/xl/p6_dc4sj19lcyhdphd3f3hgm0000gn/T/xcodebuild-4F846E06-3CD8-4A86-8E1B-E1F931FEB65C.log

Failed to generate documentation
	from /Library/Ruby/Gems/2.3.0/gems/jazzy-0.9.3/lib/jazzy/sourcekitten.rb:230:in `run_sourcekitten'
	from /Library/Ruby/Gems/2.3.0/gems/jazzy-0.9.3/lib/jazzy/doc_builder.rb:66:in `block in build'
	from /Library/Ruby/Gems/2.3.0/gems/jazzy-0.9.3/lib/jazzy/doc_builder.rb:64:in `chdir'
	from /Library/Ruby/Gems/2.3.0/gems/jazzy-0.9.3/lib/jazzy/doc_builder.rb:64:in `build'
	from /Library/Ruby/Gems/2.3.0/gems/jazzy-0.9.3/bin/jazzy:15:in `<top (required)>'
	from /usr/local/bin/jazzy:22:in `load'
	from /usr/local/bin/jazzy:22:in `<main>'

I can provide the xcodebuild log, but I don't think it will be helpful. It just says that everything went perfectly according to plan.

But Jazzy does nothing.

Here's my jazzy.yaml file:

xcodebuild_arguments:
    - "-project"
    - "WhiteDragon.xcodeproj"
    - "-scheme"
    - "WhiteDragon"

It happens the same; with or without the .yaml file.

"WhiteDragon" is the project name. It has the CocoaPods structure, with the .xcworkspace. Running xcodebuild seems to ignore the workspace, and just run the .xcodeproj.

I am running High Sierra, with Xcode 10 (Full release versions of both).

**Comment by LittleGreenViper** [comment]
[xcodebuild-A4E38442-6377-46C2-B838-E85FD407350E.log](https://github.com/realm/jazzy/files/2429298/xcodebuild-A4E38442-6377-46C2-B838-E85FD407350E.log)

**Comment by saveknut** [comment]
I started getting the same issue after halting (`Ctrl+C`) the documentation build. It was halfway through, I killed it, and now I get the same error before it ever gets to parsing.

```
Running xcodebuild
Could not parse compiler arguments from `xcodebuild` output.
Please confirm that `xcodebuild` is building a Swift module.
Saved `xcodebuild` log file: /var/folders/<...>.log
Failed to generate documentation
/Users/bernardo.pereira/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/jazzy-0.9.3/lib/jazzy/executable.rb:36:in `execute_command': /Users/bernardo.pereira/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/jazzy-0.9.3/bin/sourcekitten ["doc", "--module-name", "<redacted>", "--"] (RuntimeError)

Running xcodebuild

Could not parse compiler arguments from `xcodebuild` output.

Please confirm that `xcodebuild` is building a Swift module.

Saved `xcodebuild` log file: /var/folders/r3/<...>.log

Failed to generate documentation
	from /Users/bernardo.pereira/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/jazzy-0.9.3/lib/jazzy/sourcekitten.rb:230:in `run_sourcekitten'
	from /Users/bernardo.pereira/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/jazzy-0.9.3/lib/jazzy/doc_builder.rb:66:in `block in build'
	from /Users/bernardo.pereira/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/jazzy-0.9.3/lib/jazzy/doc_builder.rb:64:in `chdir'
	from /Users/bernardo.pereira/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/jazzy-0.9.3/lib/jazzy/doc_builder.rb:64:in `build'
	from /Users/bernardo.pereira/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/jazzy-0.9.3/bin/jazzy:15:in `<top (required)>'
	from /Users/bernardo.pereira/.rbenv/versions/2.4.0/bin/jazzy:22:in `load'
	from /Users/bernardo.pereira/.rbenv/versions/2.4.0/bin/jazzy:22:in `<main>'
```

The generated `xcodebuild` log ends with `** BUILD SUCCEEDED **`, in case you're wondering. Using Xcode 10 in High Sierra.

(redacted some things above with `<>`)

**Comment by LittleGreenViper** [comment]
I have since upgraded to Mojave, and still get the same problem. I don't think I ever interrupted the build.

**Comment by LittleGreenViper** [comment]
Yeah, went and built Jazzy from the current master branch (A couple of checkin comments made me think it might have been fixed).

No dice.

[xcodebuild-CE2BE741-C145-4BFA-B0DC-96346D718126.log](https://github.com/realm/jazzy/files/2442964/xcodebuild-CE2BE741-C145-4BFA-B0DC-96346D718126.log)

**Comment by smarchant-owlet** [comment]
My guess is Jazzy doesn't understand the new Xcode build system.  You can force build to use the legacy Xcode build, just for your build config, by adding the `-UseModernBuildSystem=NO` flag to xcodebuild.

So your .jazzy.yaml file might have a line that looks like this:
```
xcodebuild_arguments: [-workspace, MyWorkspace.xcworkspace, -scheme, MyScheme, -UseModernBuildSystem=NO]
```

Credit for the special `UserModernBuildSystem` flag goes to this answer on StackOverflow:

https://stackoverflow.com/a/51205222/1516011

**Comment by LittleGreenViper** [comment]
Awesome!

I’ll give it a try.

Chris Marshall
Geek
Email: cmarshall@mac.com
Web Site: http://cmarshall.com

**Comment by LittleGreenViper** [comment]
Unfortunately, I have to report that this did not work. I tried building the older project with Jazzy, and it worked, but I have not yet updated the older project.

This isn't a huge priority for me now, and I don't have the time it would take to do the update and testing of the older project (but I need to get off my lardass and do it). I'll see if it still works after I update the BMLTiOSLib project.

One big difference between the two is the target OS. The BMLTiOSLib project targets iOS9 and above, while the White Dragon project is iOS11 and up.

**Comment by LittleGreenViper** [comment]
I don't think it's the project format. I'm just starting a new project, and that uses Xcode 10 compatible format.
It's also a framework, but so far, has no real code in it.
Jazzy works so far (and produces nothing -as it should).
This time, I'll keep running it as I build up the project, so I'll see where it borks (if it does).

**Comment by danielgaston** [comment]
Same problem here. Mojave - Xcode10

**Comment by LittleGreenViper** [comment]
OK. I figured it out.
The module name needed to be explicitly added to the jazzy command line. It was making up a name, I guess based on the folder name, as opposed to the output of xcodebuild.

**Comment by danjimilk** [comment]
@LittleGreenViper 

Your research helps me so much thanks.

**Comment by tobitech** [comment]
Please I need help. Here is a snippet from my log file
```
** BUILD FAILED **
The following build commands failed:
	Ld /Users/oluwatobiomotayo/Desktop/hollaport_ios_project_files/Hollaport/build/Hollaport.build/Release-iphoneos/HollaportNotificationServiceExtension.build/Objects-normal/armv7/HollaportNotificationServiceExtension normal armv7
	Ld /Users/oluwatobiomotayo/Desktop/hollaport_ios_project_files/Hollaport/build/Hollaport.build/Release-iphoneos/HollaportNotificationServiceExtension.build/Objects-normal/arm64/HollaportNotificationServiceExtension normal arm64
(2 failures)
```
It seems it couldn’t build a Notification extension

**Comment by johnfairh** [comment]
@tobitech probably means xcodebuild is being given the wrong parameters.

If that doesn't help then please open a new issue and fully explain what you are trying to do, the parameters etc. to jazzy and all the output log files, along with what versions of macOS/Swift/jazzy you are using.

**Comment by tobitech** [comment]
I got it to work with this command 
`jazzy -x -workspace,Hollaport.xcworkspace,-scheme,Hollaport --min-acl internal`
