### ISSUE TITLE
cant install jazzy

### ISSUE THREAD

**Issue by rehinaloc** [realm/jazzy#1011]
`➜  ~ sudo gem install jazzy`
                        
`ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /usr/bin directory.` 

I tried to install this but with sudo but still getting error of permissions. 
I looked it up but could not find anything useful

**Comment by johnfairh** [comment]
This seems to be a perennial problem installing gems on macOS stock Ruby.  There are lots of hits on google, I'll leave a link to the [Jekyll instructions](https://jekyllrb.com/docs/installation/macos/) and close this one.
