### ISSUE TITLE
Running Jazzy with bundler fails

### ISSUE THREAD

**Issue by kimdv** [realm/jazzy#1014]
Hi, 

I have installed and updated Jazzy with bundler. 
When I run `bundle exec jazzy` it fails. 
```
bundler: command not found: jazzy
Install missing gem executables with `bundle install`
```

As you see below, it is updated to latest version with bundler.
```
....
Using jazzy 0.9.3
Bundle updated!
```

**Comment by johnfairh** [comment]
You should just be able to run the `jazzy` script, it does the `bundler/setup` step.

That said, macOS 10.14.2 / ruby 2.5 via rbenv / `bundle install jazzy` using a minimal Gemfile enables `bundle exec jazzy` fine for me.  If you really think this is a problem with the way jazzy's gem is configured then I think we'll need more info.

**Comment by johnfairh** [comment]
Closing, inactive.
