### ISSUE TITLE
Apple theme : footer overlap when text on multiple lines

### ISSUE THREAD

**Issue by FabienLydoire** [realm/jazzy#1016]
Apple theme : footer overlap when text on multiple lines
I proposed a fix : #1013
The CI test fails since it compares the CSS (which I changed) with the previous CSS.

Can someone of the core team review and accept my PR ?

Thanks !

**Comment by jpsim** [comment]
There are instructions on how to update the integrations specs in [CONTRIBUTING.md](https://github.com/realm/jazzy/blob/master/CONTRIBUTING.md#updating-the-integration-specs)

**Comment by johnfairh** [comment]
Fixed in master by #1039.
