### ISSUE TITLE
Not able to generate docs for XCUITests

### ISSUE THREAD

**Issue by jineshqa** [realm/jazzy#1017]
I'm trying to generate documentation for my automated XCUITests to give an overview to others about what is automated. Despite of me explicitly specifying folder path, jazzy skip all the files and does not generate any documentation.

Thanks,
Jinesh

**Comment by jineshqa** [comment]
@jpsim @segiddins @pcantrell @esad Sorry to tag you all. Trying to get some attention to this completely missing feature in jazzy. Despite using -i or --include test automation code is completely ignored.

Thanks,
Jinesh

**Comment by jpsim** [comment]
Jazzy is designed to document frameworks, not app or test bundles.
