### ISSUE TITLE
Non-conflicting type declarations cause error

### ISSUE THREAD

**Issue by stephencelis** [realm/jazzy#1028]
> Found conflicting type declarations with the same name, which may indicate a build issue or a bug in Jazzy: static variable image, static variable image, static variable image, static variable image

Given the following example:

``` swift
struct Id<A> {
  let rawValue: A
}

extension Id where A == Int {
  static let one = Id(rawValue: 1)
}

extension Id where A == Double {
  static let one = Id(rawValue: 1.0)
}
```

This is perfectly valid Swift but unfortunately Jazzy does not take constrained extensions into account at all. I have a library that heavily utilized constrained extensions in its API, but without any indication in its output, Jazzy does not provide usable docs.

**Comment by jpsim** [comment]
Jazzy uses the Swift compiler's USR, so it's odd that it conflicts here. Have you filed a bug at bugs.swift.org?

**Comment by johnfairh** [comment]
I can't recreate the `conflicting type declarations` error: like JP says that means the compiler has given two declarations the same internal ID, which is bad --- usually this message turns up in jazzy only when there is conditional/multipass compilation going on.

You're right though that jazzy doesn't display generic requirements.  We need to do a SourceKit change to plumb them through (and visual design...).  There might be an issue to dup this one to.

**Comment by johnfairh** [comment]
Closing, covered in #717.
