### ISSUE TITLE
`gem install jazzy` fails building native extension on macOS 10.14 Xcode Version 10.1 (10B61)

### ISSUE THREAD

**Issue by alfwatt** [realm/jazzy#1029]
watt@demos:~/Source/Darwin/sdk sudo gem install jazzy
Password:
Building native extensions.  This could take a while...
ERROR:  Error installing jazzy:
	ERROR: Failed to build gem native extension.

    current directory: /Library/Ruby/Gems/2.3.0/gems/redcarpet-3.4.0/ext/redcarpet
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby -r ./siteconf20181203-88440-1yy5avm.rb extconf.rb
creating Makefile

current directory: /Library/Ruby/Gems/2.3.0/gems/redcarpet-3.4.0/ext/redcarpet
make "DESTDIR=" clean

current directory: /Library/Ruby/Gems/2.3.0/gems/redcarpet-3.4.0/ext/redcarpet
make "DESTDIR="
make: *** No rule to make target `/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/include/ruby-2.3.0/universal-darwin18/ruby/config.h', needed by `autolink.o'.  Stop.

make failed, exit code 2

Gem files will remain installed in /Library/Ruby/Gems/2.3.0/gems/redcarpet-3.4.0 for inspection.
Results logged to /Library/Ruby/Gems/2.3.0/extensions/universal-darwin-18/2.3.0/redcarpet-3.4.0/gem_make.out

**Comment by alfwatt** [comment]
Looks like `redcarpet` isn't update for Mojave: https://github.com/vmg/redcarpet/issues/668

**Comment by jpsim** [comment]
Tracking in https://github.com/realm/jazzy/issues/593 and vmg/redcarpet#668

**Comment by adtrevor** [comment]
Any news on this? I can't install jazzy

**Comment by jpsim** [comment]
@adtrevor have you tried the workaround shared in the linked ticket? `gem install --user-install jazzy`

**Comment by MathPlayer** [comment]
As I mentioned in https://github.com/vmg/redcarpet/issues/668#issuecomment-453925989, the install seems to work only with Xcode 10, not with an older version (I tried with 9.4.1).

**Comment by adtrevor** [comment]
@jpsim The command you mentioned didn't work either unfortunately! 
Here is the error:
```
Fetching: redcarpet-3.4.0.gem (100%)
WARNING:  You don't have /Users/adtrevor/.gem/ruby/2.3.0/bin in your PATH,
	  gem executables will not run.
Building native extensions.  This could take a while...
ERROR:  Error installing jazzy:
	ERROR: Failed to build gem native extension.

    current directory: /Users/adtrevor/.gem/ruby/2.3.0/gems/redcarpet-3.4.0/ext/redcarpet
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby -r ./siteconf20190114-32425-lttsir.rb extconf.rb
creating Makefile

current directory: /Users/adtrevor/.gem/ruby/2.3.0/gems/redcarpet-3.4.0/ext/redcarpet
make "DESTDIR=" clean

current directory: /Users/adtrevor/.gem/ruby/2.3.0/gems/redcarpet-3.4.0/ext/redcarpet
make "DESTDIR="
make: *** No rule to make target `/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/include/ruby-2.3.0/universal-darwin18/ruby/config.h', needed by `autolink.o'.  Stop.

make failed, exit code 2

Gem files will remain installed in /Users/adtrevor/.gem/ruby/2.3.0/gems/redcarpet-3.4.0 for inspection.
Results logged to /Users/adtrevor/.gem/ruby/2.3.0/extensions/universal-darwin-18/2.3.0/redcarpet-3.4.0/gem_make.out
```

**Comment by johnfairh** [comment]
@mathplayer different error message, different problem - Xcode9 has darwin17 architecture - see discussion in eg. #409.

I'm going to lock this issue in an attempt to keep all the discussion in #593.
