### ISSUE TITLE
NS_ERROR_ENUM is not recognized correctly by jazzy

### ISSUE THREAD

**Issue by jarhoax** [realm/jazzy#1030]
I have some `NS_ERROR_ENUM`s in my Objective-C code but neither of them gets recognized by Jazzy. See following example:

```
/** This comment is recognized by jazzy */
FOUNDATION_EXPORT NSErrorDomain const LSTestDomain;

/**
 This does NOT get recognized
 */
NS_ERROR_ENUM(LSTestDomain)
{   /** Neither this... */
    LSFirst = 42,
    /** ...nor this gets recognized */
    LSSecond = 43
};
```

However looking at the `undocumented.json` I see them recognized as `sourcekitten.source.lang.objc.decl.enum`.

Any help would be appreciated.

**Comment by johnfairh** [comment]
That version of `NS_ERROR_ENUM` declares an anonymous enum type; jazzy only documents types that have names (there's a tiny clue in that the `undocumented.json` has an empty name field).

You should be able to use the two-arg version of the macro that generates a named type:
```c
typedef NS_ERROR_ENUM(LSTestDomain, LSTestErrorEnum)
etc etc
```

**Comment by jarhoax** [comment]
Ok thanks. 

I already tried the two-arg version of the macro before filing this issue, but I'd prefer the anonymous enum type here. 

However if there is no other option to get such anonymous types documented I think I'll have to use the two-arg version then anyway.
