### ISSUE TITLE
Jazzy fails in combination of xcode 10.1, objective-c and tvos

### ISSUE THREAD

**Issue by uvo-karlmax** [realm/jazzy#1033]
We are developing a tvOS framework with objective-c and jazzy documentation worked fine until we updated Xcode to version 10.1. 

Now we experience the `fatal error: could not build module 'Foundation'` error (`gems/ruby-2.2.2/gems/jazzy-0.9.4/lib/jazzy/sourcekitten.rb:230:in run_sourcekitten`).

This only happens for a tvOS framework. A different framework we develop for iOS (also in objective-c) works fine with Xcode 10.1. Also the same tvOS framework is being documented without problems, when we switch back to Xcode 9.4.2.

Our .jazzy.yaml file looks like this:

```
objc: true
umbrella_header: .../....h
framework_root: ./
sdk: appletvsimulator
clean: true
hide_documentation_coverage: true
module: ... 
output: docs/
```

Any help would be great! Thank you in advance!

**Comment by johnfairh** [comment]
See #993 but I'm not that hopeful, not sure how jazzy-objc uses DerivedData.

I think we'd need a complete failing example to figure this out: I had a quick play with a dummy tvOS framework and everything seemed fine.

All jazzy does with the `--sdk` option is look up its full path to pass to clang -- you could maybe try `xcrun --show-sdk-path --sdk appletvsimulator` and see if anything is amiss, but I feel you would likely have more problems were something wrong here.

**Comment by uvo-karlmax** [comment]
Hi johnfairh,

thank you for your answer. You are right, neither #993, nor the `--sdk` option helps (checking the path didn´t show anything unusual).

Here is a very basic dummy tvOS framework, which shows the failing behavior. So hopefully it can help finding the issue.

[JazzyTestProject.zip](https://github.com/realm/jazzy/files/2732553/JazzyTestProject.zip)

Thank you.

**Comment by johnfairh** [comment]
On my setup jazzy works fine against that project -- it's pretty much what I tried before.

Xcode 10.1 10B61 / macOS 10.14.2.  Not sure where to go from here I'm afraid.

**Comment by uvo-karlmax** [comment]
Maybe you can try to rename your Xcode.app to Xcode10_1 and run `sudo xcode-select -s /Applications/Xcode10_1.app/Contents/Developer/`

This should switch your path to Xcode and could maybe provoke the error. At least this is true for my functioning Xcode 9.4.2 version: After changing the name and selecting it, I receive the same error as above. Or is there anything else I must do to switch between different Xcode versions on my machine?

**Comment by johnfairh** [comment]
Interesting yes that does make it happen - goes away when I delete that `build` dir and, um, won't come back without renaming Xcode again to a further new thing, even if I put the dir back.  The error is not at our level but looks to be triggered by the over-enthusiastic include-path generation -- in the scenario I get to where regular jazzy gives the error calling sk manually works:

```
/Users/johnf/project/jazzy/bin/sourcekitten doc
  --objc
  /Users/johnf/project/JazzyTestProject/JazzyTestProject/JazzyTestProject.h --
  -x objective-c
  -isysroot /Applications/Xcode10_1.app/Contents/Developer/Platforms/AppleTVSimulator.platform/Developer/SDKs/AppleTVSimulator11.4.sdk
  -I /Users/johnf/project/JazzyTestProject
  -fmodules
```
No idea if this is what you're seeing but trying deleting `build`.  On the jazzy side we should really make the include-path generation better -- I thought there already was an issue about this overflowing the shell param limit but can't see it right now.

**Comment by johnfairh** [comment]
Added to objective-c docs in master.
