### ISSUE TITLE
Failing to generate docs in a parent project setup

### ISSUE THREAD

**Issue by sudeepkzd** [realm/jazzy#1036]
To explain this I've uploaded the relevant project [here](https://github.com/sudeepkzd/jazzy_issue). If you have cloned it, please open CombinedSDK project. 
So there's SampleSDK project and MockSampleSDK project (whose documentation I need to generate)
MockSampleSDK depends on SampleSDK, but to specify the dependency one needs to make SampleSDK a child project (which is something we didn't want to do). So we have MockSampleSDK and SampleSDK as sibling projects. Their parent project is CombinedSDK (which specifies the dependency and the order in which they should build etc.).

```
cd CombinedSDK
```

When I try to run jazzy (I'm trying to generate docs for MockSampleSDK):
`jazzy     --objc     --clean     --author Zendrive Inc.     --author_url https://www.zendrive.com     --module-version 5.7.0-beta-2     --xcodebuild-arguments --objc,../MockSampleSDK/MockSampleSDK/API/MockSampleSDK.h,--,-x,objective-c,-isysroot,$(xcrun --show-sdk-path),-I,$(pwd)     --umbrella-header  ../MockSampleSDK/MockSampleSDK/API/MockSampleSDK.h     --sdk iphonesimulator     --hide-documentation-coverage     --skip-undocumented     --hide-declarations swift     --output docs     --module CMockSampleSDK`

It fails with error message:
```
../MockSampleSDK/MockSampleSDK/API/MockSampleSDK.h:10:9: fatal error: 'SampleSDK/SampleTypes.h' file not found
100% documentation coverage with 0 undocumented symbols
included 3 symbols
building site
building search index
jam out ♪♫ to your fresh new docs in `docs`
```

It's trying to search for SampleTypes.h in SampleSDK library. Ideally I would want to not document/search for SampleTypes.h since it is in a completely different library.

Can someone comment on how to get this going?

**Comment by johnfairh** [comment]
For objc, all you need to worry about is the header files starting with `umbrella-header` all resolving.  No need to think about xcodebuild/schemes/etc.  So this should get you started:
```shell
; pwd
/Users/johnf/project/jazzy_issue
; jazzy --objc --umbrella-header MockSampleSDK/MockSampleSDK/API/MockSampleSDK.h --framework-root . --exclude 'SampleSDK/**/*h'
75% documentation coverage with 1 undocumented symbol
included 4 symbols
building site
building search index
jam out ♪♫ to your fresh new docs in `docs`
; 
```
Your header file explicitly includes `SampleSDK.h` so you can't avoid having Jazzy read it and then exclude its decls.

**Comment by sudeepkzd** [comment]
Thanks @johnfairh! That worked smoothly enough. I have two follow questions:

- What is **framework-root** option?
- Suppose I have a enum in my SampleTypes.h which gets used in MockSampleSDK API (I've updated the project). When I generate the docs:
jazzy --objc --umbrella-header MockSampleSDK/MockSampleSDK/API/MockSampleSDK.h --framework-root . --exclude 'SampleSDK/**/*h'

I get the following output:
```
/Users/sudeepkumar/jazzy_issue/MockSampleSDK/MockSampleSDK/API/MockSampleSDK.h:32:4: error: expected a type
80% documentation coverage with 1 undocumented symbol
included 5 symbols
building site
building search index
jam out ♪♫ to your fresh new docs in `docs`
```

In the generated docs, I have the enum replaced by objective c "id"
<img width="738" alt="screenshot 2019-01-10 at 2 31 13 pm" src="https://user-images.githubusercontent.com/43813226/50957525-70dad780-14e4-11e9-8160-09c23beedd28.png">

**Comment by johnfairh** [comment]
That error looks like a compiler error, saying there's something wrong with the enum declaration/use.

`--framework-root` effectively means "resolve #include/#import paths from here and in in all directories under here."

`--xcodebuild-arguments` is used to pass arguments to `xcodebuild` in Swift mode, or, in ObjC mode, to specify the complete set of `clang` arguments required to compile the umbrella header file when jazzy's defaults are not enough: see the examples in the readme.

**Comment by sudeepkzd** [comment]
I'm not sure what's the issue. I'm just using an enum from the SampleSDK library in MockSampleSDK library (I've updated the repo in case you wanna have a look). 
Building the static library works just fine.

`jazzy --clean --objc --umbrella-header MockSampleSDK/MockSampleSDK/API/MockSampleSDK.h --framework-root . --exclude 'SampleSDK/**/*h'`

Output:
```
/Users/sudeepkumar/jazzy_issue/MockSampleSDK/MockSampleSDK/API/MockSampleSDK.h:32:26: error: expected a type
80% documentation coverage with 1 undocumented symbol
included 5 symbols
building site
building search index
jam out ♪♫ to your fresh new docs in `docs`


```

Generated documentation has enum converted to objective-c id.
<img width="1440" alt="screenshot 2019-01-15 at 5 48 30 pm" src="https://user-images.githubusercontent.com/43813226/51180230-da485500-18ed-11e9-8051-0dfce11a0ed3.png">

**Comment by sudeepkzd** [comment]
I resolved this by having a custom setup:

- move mock project headers in MockSampleSDK folder
- move sample sdk project headers in SampleSDK folder(in parallel with MockSampleSDK folder)
- execute ` jazzy --clean --objc --umbrella-header MockSampleSDK/MockSampleSDK.h --framework-root . --include 'MockSampleSDK/*'`

This generates documentation without converting SampleSDK enums to int.

<img width="1440" alt="screenshot 2019-01-15 at 5 48 30 pm" src="https://user-images.githubusercontent.com/43813226/51248026-daf7ee80-19b4-11e9-902d-770b4c9c2b87.png">

**Comment by johnfairh** [comment]
Ok, glad you solved it.
