### ISSUE TITLE
Referencing to an external library.

### ISSUE THREAD

**Issue by sudeepkzd** [realm/jazzy#1038]
I want to link to an external library documentation from my library. I know there is `[text](url)` format. But this usually turns out to be long and cumbersome, since I need to add each link.

What I'm looking for is something like [javadocs linkoffline](https://stackoverflow.com/questions/699771/how-to-write-javadoc-links). So that I can just add references using \`SomeExternalLibraryClass\` notation (which is there for referencing to classes within the same library.)

Is this possible in jazzy?

**Comment by johnfairh** [comment]
Jazzy doesn't support this; it comes up sometimes usually in relation to system modules that have well-known documentation formats/locations.  You need to write out the link long-hand or post-process the html.

Both jazzy and quick help markdown support the footnote style of link-writing that prevents you having to put URLs directly inline:
```markdown
text text [clickable text][footnote-id] more text
<more markdown>

[footnote-id]: http://www.example.org/ "Example Hovertext"
```

**Comment by johnfairh** [comment]
Closing, answered.
