### ISSUE TITLE
How to sort methods and properties?

### ISSUE THREAD

**Issue by hervehobbes** [realm/jazzy#1043]
Hello,

First thank you for this project.

Is it possible to first display properties sorted by alphabetical order then to show methods sorted by alphabetical order?

Currently, properties and methods seems to be display in their declaration order.

**Comment by johnfairh** [comment]
This isn't possible: jazzy can only do its default task-based ordering today.  This kind of request comes up from time to time; supporting an alternative layout like this would definitely be a good feature to add.
