### ISSUE TITLE
Generate raw Markdown

### ISSUE THREAD

**Issue by dendeli-msft** [realm/jazzy#1044]
It seems that Jazzy produces HTML output from code. Are there any plans to introduce support for building raw Markdown files, without processing those through the HTML template?

**Comment by jpsim** [comment]
Jazzy basically just converts the raw data from [SourceKitten](https://github.com/jpsim/SourceKitten)'s `doc` command and wraps it all up in a static site.

You could just operate on SourceKitten's response directly if you wanted to make Markdown docs of your choosing.

There's [SourceDocs](https://github.com/eneko/SourceDocs) which does exactly that today which you might want to look at.

**Comment by dendeli-msft** [comment]
I will try it out, thank you @jpsim!
