### ISSUE TITLE
*.md link not converted to *.html link

### ISSUE THREAD

**Issue by SteffenL** [realm/jazzy#1046]
I run jazzy with parameters like `--readme docs/.index.md` and `--documentation 'docs/**/*.md'`.

`docs/.index.md` has a link to another `*.md` file in the same directory:

```
[Other Page](Other Page.md)
```

In the generated HTML, this link points to `Other Page.md` instead of the generated `other-page.html`.

Should jazzy be able to replace these links? I guess I could write a script that replaces the links but what is the jazzy way to deal with this?

By the way, the index file is named `.index.md` to prevent it from showing up as a link under "Guides". Although it works fine, is that the intended way to hide it when not using custom categories?

**Comment by johnfairh** [comment]
Jazzy doesn't rewrite these these links itself - #775.

If you are tied to the directory structure/file layout that you describe then using the . prefix works I guess!

**Comment by SteffenL** [comment]
Thanks for your response! Okay, so this is a duplicate issue.
