### ISSUE TITLE
Jazzy Documentation takes huge time to generate document

### ISSUE THREAD

**Issue by ankitthakur** [realm/jazzy#1050]
Hi team,

I am developing one module for my organisation, and used Jazzy Documentation. There are only 40 swift files in the code. The build time with lint is instant approx 1-2 secs. But when I am adding Jazzy script in `Run Script`, then build times take 5-10 minutes. Documentation is getting generated, but huge time is consumed. The project is purely swift.

Here is the script

```
 jazzy \
--clean \
--author 'Organisation Name' \
--author_url 'org url' \
--module 'moduleName' \
--source-directory . \
--documentation 'Guides/*.md' \
--output docs 
```

**Comment by johnfairh** [comment]
Jazzy runs `xcodebuild` under the covers so you must take care with your Xcode config to avoid recursion.

How long does it take to run if you:
1 - remove jazzy from the run script phase; and then
2 - run the jazzy command manually from the terminal.

?

**Comment by nickkarpov** [comment]
@ankitthakur looks like adding jazzy to a project's scripts phase causes a loop (recursion)...thats why it takes minutes until the process is killed (by the system?) I guess.
If you want the generating docs will be a part of your project consider to add a separate target for it that just runs the jazzy command with desired parameters. Or just run it from command line as was suggested earlier.

**Comment by johnfairh** [comment]
Closing this one now, old/inactive.
