### ISSUE TITLE
Need a way to use no theme

### ISSUE THREAD

**Issue by nancymic2** [realm/jazzy#1054]
I need a way to use no theme. We don't use any of the Jazzy CSS and Jazzy adds more than 400 spans to a single document. This times a hundred documents is unnecessary for us. How can I pass an option to use no theme?

**Comment by johnfairh** [comment]
Probably best to write your own theme, start with eg. `apple` and strip out whatever you don't need?  The minimum a theme needs is a `doc.mustache`.

Or [SourceDocs](https://github.com/eneko/SourceDocs) may be a better fit for what you're trying to do.

**Comment by nancymic2** [comment]
Great thanks I thought of an empty theme. I'll try that!
