### ISSUE TITLE
Jazzy requires xcodeproj alongside source code (can't exist in separate sibling folders)

### ISSUE THREAD

**Issue by heidiproske** [realm/jazzy#1055]
I'm trying to build docs for a project (with Xcode 10.1) where there's a root workspace and an example  project in a subfolder, that utilizes local pods (off the parent directory)
```
MyProject.xcworkspace
MyProject.podspec

|-- Example/
    |-- MyProject.xcodeproject

|-- libraries/
    |-- libraryA
    |-- libraryB
    |-- libraryC

|-- Pods/
    |-- LibraryA
    |-- LibraryB
    |-- LibraryC
```

where the Podfile makes use of subspecs for our different libraries similar to:
```
project 'Example/MyProject.xcodeproj'
platform :ios, '10.3'

def main_pods
    pod 'MyProject', :path => './', :inhibit_warnings => false
    pod 'MyProject/LibraryA', :path => './', :inhibit_warnings => false, :testspecs => ['UnitTests']
    pod 'MyProject/LibraryB', :path => './', :inhibit_warnings => false, :testspecs => ['UnitTests']
...
```

- If I run `xcodebuild -workspace MyProject.xcworkspace -scheme MyProject` from the root directory, it runs fine (or with `target` etc).
- If I run `jazzy` from inside of the `Example` folder, it runs fine (although it's excluding documentation from my libraries)
- If I run `jazzy` with the same arguments or trying all other variations, the short log output always gives me a 1 line error saying `xcodebuild: error: The directory /Users/XXX/my_project does not contain an Xcode project.` because it expects the `.xcodeproj` to exist on the top level (even when I specify a workspace / target / scheme as is supported by `xcodebuild`).

After seeing https://github.com/realm/jazzy/issues/177 which seemed similar (but there's another `.xcodeproj` file in the libraries folder that can be utilized), I tried to use the `-s` flag to specify the source_directory containing the `.xcodeproj` but get an error too:
```
$ jazzy -s './Example/'
/Users/XXX/.rvm/gems/ruby-2.3.0@my_project/gems/jazzy-0.9.4/lib/jazzy/doc_builder.rb:58:in `read': Is a directory @ io_fread - /Users/XXX/my_project/Example (Errno::EISDIR)
```

Seems like Jazzy isn't able to handle the change in directories... (here the xcodeproj will be linking to files in a directory above it) whereas xcodebuild does. 

Curious if this is supported and I'm just doing something wrong?

**Comment by johnfairh** [comment]
`-s` is short for `--sourcekitten-sourcefile`, but all `--source-directory` does is cd into that directory before running `xcodebuild`.

If the first bullet above (`xcodebuild` from root) means that the command not only runs but also can build the Swift module to be documented, then `jazzy -x -workspace,MyProject.xcworkspace,-scheme,MyProject` should work from that same place -- the parameters are passed unprocessed to `xcodebuild` -- maybe double-check how the parameters are being passed in (no spaces, just commas)?  It always helps to see the failing CLI session verbatim.

(or try `jazzy --podspec MyProject.podspec` maybe if that is what is aiming to be documented.)

**Comment by heidiproske** [comment]
@johnfairh Aaah thank you. (sorry re the typo `-s` - updated the description accordingly)

**Comment by heidiproske** [comment]
@johnfairh Thanks for the super quick response!

Running `jazzy -x -workspace,MyProject.xcworkspace,-scheme,MyProject` as you suggested does work (Had forgotten to specify the `-x` flag).

Am using it via a .jazzy.yaml config file successfully now, thank you!

```
xcodebuild_arguments: [-workspace,MyProject.xcworkspace,-scheme,MyProject]
```
