### ISSUE TITLE
submodules need umbrella

### ISSUE THREAD

**Issue by Troublebreaker** [realm/jazzy#1056]
error: inferred submodules require a module with an umbrella.

**Comment by johnfairh** [comment]
We need more info about what you're trying to do.  The error message sounds like it is coming from a slightly obscure corner of the build system so the failing project/a minimal recreate would be ideal.

**Comment by kubacizek** [comment]
I'm getting same error. I have a project written in Swift & objc. It also uses Cocoapods which is imported to header files in **Project-Bridging-Header.h**. Is there some solution or I must write separate umbrella file which does not include cocoapods?

`jazzy --objc --umbrella-header 'My Skoda/My Skoda-Bridging-Header.h' --framework-root . --sdk iphoneos`

[https://imgur.com/zmrU31z](url)

**Comment by jpsim** [comment]
Does your framework not have an umbrella header @kubacizek? Umbrella headers are the norm for Objective-C frameworks, so you can do `#import <Skoda/Skoda.h>` and get the entire public interface available.

**Comment by kubacizek** [comment]
I'm not sure if we understand each other. I'm trying to generate objc documentation for entire application which includes iOS App, Watch App, and Widget extension. The project is using cocoapods like GoogleMaps, HockeySDK, FacebookSDK etc. So am I not supposed to use umbrella header as  a parameter for jazzy?

**Comment by jpsim** [comment]
Jazzy is more designed to document frameworks rather than apps, so you'll be fighting the tool if you try to do that.

**Comment by kubacizek** [comment]
Oh I see. Anyway thank you for answers
