### ISSUE TITLE
Should upgrade Sourcekitten to an Xcode 10.2 compatible version

### ISSUE THREAD

**Issue by FabienLydoire** [realm/jazzy#1057]
Jazzy fails on workspace doc generation using Xcode 10.2 and Swift 5.0.
Seems like it does not find the project (or at least the Signing details).

```
Build settings from command line:
    CODE_SIGN_IDENTITY = 
    CODE_SIGNING_REQUIRED = NO

note: Using new build system

** CLEAN SUCCEEDED **

note: Using new build system
note: Planning build
note: Constructing build description
Build system information
error: An empty identity is not valid when signing a binary for the product type 'Application'. (in target '<Edited>')

** BUILD FAILED **
```

Building Sourcekitten from the master branch (commit 2b5d4448b67a9de790f9fbb02cbac92e5a92060d) and embedding the newly build version into Jazzy (replacing `/Library/Ruby/Gems/2.3.0/gems/jazzy-0.9.5/bin/sourcekitten` ) fixes the issue.

**Comment by johnfairh** [comment]
Thanks; will be updating sourcekitten in the next few days.

However, that is not the underlying problem: latest sourcekitten still passes `CODE_SIGN_IDENTITY=` when it has to do `xcodebuild clean` -- it just usually manages to avoid doing that kind of build (by parsing the llbuild manifest).

This error is new in Xcode 10.2 only with the new build system; playing around with a signed project it looks like adding `CODE_SIGNING_ALLOWED=NO` does the trick and is harmless on other configs.

**Comment by FabienLydoire** [comment]
Thanks @johnfairh 
Would you mind describing how you can add `CODE_SIGNING_ALLOWED=NO` in the Jazzy configuration file ?

**Comment by johnfairh** [comment]
You could try `jazzy -x CODE_SIGNING_ALLOWED=NO`; I was looking at `xcodebuild` itself.

**Comment by FabienLydoire** [comment]
`xcodebuild_arguments: [CODE_SIGNING_ALLOWED=NO]` worked.

Thanks @johnfairh !

**Comment by JavieriOSninja** [comment]
It is still not working for me, this is the output that I receive:

Using config file /Users/ios/Documents/iOS_Projects/SecretSanta/App/Code/.jazzy.yaml
Running xcodebuild
Could not parse compiler arguments from `xcodebuild` output.
Please confirm that `xcodebuild` is building a Swift module.
Saved `xcodebuild` log file: /var/folders/2d/4_sk5c1j0rz2bwl37yqj018h0000gn/T/xcodebuild-B1C7BB3A-7083-4D3E-807B-0C40004E1572.log
Failed to generate documentation
/Library/Ruby/Gems/2.3.0/gems/jazzy-0.9.5/lib/jazzy/executable.rb:36:in `execute_command': /Library/Ruby/Gems/2.3.0/gems/jazzy-0.9.5/bin/sourcekitten ["doc", "--", "-workspace", "****.xcworkspace", "-scheme", "****", "-UseModernBuildSystem\\=NO", "CODE_SIGNING_ALLOWED\\=NO"] (RuntimeError)

Running xcodebuild

Could not parse compiler arguments from `xcodebuild` output.

Please confirm that `xcodebuild` is building a Swift module.

Saved `xcodebuild` log file: /var/folders/2d/4_sk5c1j0rz2bwl37yqj018h0000gn/T/xcodebuild-B1C7BB3A-7083-4D3E-807B-0C40004E1572.log

Failed to generate documentation
	from /Library/Ruby/Gems/2.3.0/gems/jazzy-0.9.5/lib/jazzy/sourcekitten.rb:230:in `run_sourcekitten'
	from /Library/Ruby/Gems/2.3.0/gems/jazzy-0.9.5/lib/jazzy/doc_builder.rb:65:in `block in build'
	from /Library/Ruby/Gems/2.3.0/gems/jazzy-0.9.5/lib/jazzy/doc_builder.rb:63:in `chdir'
	from /Library/Ruby/Gems/2.3.0/gems/jazzy-0.9.5/lib/jazzy/doc_builder.rb:63:in `build'
	from /Library/Ruby/Gems/2.3.0/gems/jazzy-0.9.5/bin/jazzy:15:in `<top (required)>'
	from /usr/local/bin/jazzy:22:in `load'
	from /usr/local/bin/jazzy:22:in `<main>'

**Comment by FabienLydoire** [comment]
@JavieriOSninja You did not specify the workspace _file_ nor the scheme.
```
xcodebuild_arguments: [-workspace, MyApp.xcworkspace, -scheme, MyApp, -configuration, Debug, CODE_SIGNING_ALLOWED=NO]
```

**Comment by JavieriOSninja** [comment]
My yaml looks like this one:
xcodebuild_arguments: [-workspace, *****.xcworkspace, -scheme, ******, -configuration, Debug, -UseModernBuildSystem=NO, CODE_SIGNING_ALLOWED=NO]

**Comment by FabienLydoire** [comment]
Look at the logs mentioned in the output, there may be information about the failure.
```
Saved xcodebuild log file: /var/folders/2d/4_sk5c1j0rz2bwl37yqj018h0000gn/T/xcodebuild-B1C7BB3A-7083-4D3E-807B-0C40004E1572.log
```

**Comment by freak4pc** [comment]
Sorry to bump this - is there any progress here? I'm still facing this issue in 0.9.6. 
Running `jazzy -x CODE_SIGNING_ALLOWED=NO` doesn't seem to solve it. 

Build log seems clean with a `** BUILD SUCCEEDED **` at the end.

**Comment by johnfairh** [comment]
@freak4pc I think it sounds like you have a different problem to this issue given that you have a clean xcodebuild and that the code-signing-allowed flag doesn't help: probably worth a new issue with full details.  The only xcode10.2/swift 5 fix in trunk sourcekitten is embedding the code-signing-allowed thing you've already tried.

**Comment by freak4pc** [comment]
Alright, thank you. I'll open a new issue 🙏

**Comment by johnfairh** [comment]
Fixed in master.
