### ISSUE TITLE
Properties of type NSArray or NSDictionary with lightweight generic annotations are not documented

### ISSUE THREAD

**Issue by CrisBarreiro** [realm/jazzy#1066]
When generating the documentation of an ObjC interface, properties of type NSArray or NSDictionary with lightweight generic annotations are ignored, while all the other properties are documented. Example below:

## Source code

```objc
#import <Foundation/Foundation.h>

#import "SITBuilding.h"
#import "SITFloor.h"

/**
  A building and its dependencies: floors, POIs and events
 */
@interface SITBuildingInfo : NSObject

@property (nonatomic, strong) SITBuilding *building;

/**
 Array containing the floors of the building
 */
@property (nonatomic, strong) NSArray<SITFloor *> *floors;

@end
```

## Result

![Screenshot 2019-04-23 at 13 08 03](https://user-images.githubusercontent.com/6297834/56576506-dbfa7680-65c8-11e9-881b-07917e3a2bcd.png)

## Relevant info

* Version of Jazzy: 0.9.6
* Command Line Tools: It happens with both Xcode 9.4 or 10.2.1

**Comment by segiddins** [comment]
Out of curiosity, what happens if you remove the lightweight generic annotation?

**Comment by CrisBarreiro** [comment]
@segiddins In that case, the documentation is generated

**Comment by johnfairh** [comment]
This normally works fine - example below - so I think we need a more complete reproducible example to understand what clang doesn't like about your code (I'm guessing something to do with what exactly `SITFloor` is).

```objective-c
#import <Foundation/Foundation.h>

/** Some object */
@interface MySomeObject : NSObject

/** Floors */
@property (nonatomic, strong) NSArray<MySomeObject *> *floors;

@end
```
->
![Screenshot 2019-04-23 at 17 08 53](https://user-images.githubusercontent.com/26768470/56597512-88992000-65ea-11e9-8568-13cfb744eff6.png)

**Comment by CrisBarreiro** [comment]
I just realized that `jazzy --objc --umbrella-header SitumSDK/SitumSDK.h --sdk iphonesimulator --framework-root .` generates the documentation correctly, while `jazzy --objc --umbrella-header SitumSDK/SitumSDK.h --sdk iphoneos --framework-root .` does not

**Comment by johnfairh** [comment]
Great.  I think there's probably a compiler error being overlooked on the `iphoneos` version that requires additional clang flags to make the import resolve.

**Comment by johnfairh** [comment]
Closing, answered.
