### ISSUE TITLE
xcodebuild error: Embedded binary is not signed with the same certificate as the parent app

### ISSUE THREAD

**Issue by iliaskarim** [realm/jazzy#1067]
I'm getting the following xcodebuild error reported from jazzy using Xcode 10.2.1. The target is a workspace with the scheme for an iPhone app which I'm setting from the jazzy command line interface and the iPhone app also has a WatchKit companion app.

```
Build settings from command line:
    CODE_SIGN_IDENTITY = 
    CODE_SIGNING_ALLOWED = NO
    CODE_SIGNING_REQUIRED = NO
    EXPANDED_CODE_SIGN_IDENTITY = -
    EXPANDED_CODE_SIGN_IDENTITY_NAME = -

note: Using new build system

** CLEAN SUCCEEDED **

...

error: Embedded binary is not signed with the same certificate as the parent app. Verify the embedded binary target's code sign settings match the parent app's.

		Embedded Binary Signing Certificate:	Not Code Signed
		Parent App Signing Certificate:		- (Ad Hoc Code Signed)


** BUILD FAILED **
```

Have you seen this before?

**Comment by iliaskarim** [comment]
The build works with `xcodebuild` but using jazzy generated the following error for the application target, WatchKit target and WatchKit extension. 
```
Build system information
error: An empty identity is not valid when signing a binary for the product type ..
```
This error led me to further specify `CODE_SIGNING_ALLOWED=NO` which then led to the `Embedded binary is not signed with the same certificate as the parent app` error.

**Comment by johnfairh** [comment]
Assuming you're using latest version of jazzy.

A workaround might be to pass `clean build` into xcodebuild -- `jazzy -x clean,build`.  That should skip the step that jazzy/sourcekitten believe need to be done without signing [I don't know why].

I can't recreate the error by just creating an Xcode workspace including the pieces you mention -- need more details or a minimal example.  It will definitely be to do with the undocumented (?) changes in Xcode 10.2 / new build system.

**Comment by iliaskarim** [comment]
Thanks @johnfairh, I tried this using the latest jazzy and cocoapods 1.6.1 and still get similar results. Pods may have something to do with it. Time permitting I'll try to make a sample workspace.

**Comment by iliaskarim** [comment]
Even if I run jazzy with CODE_SIGNING_REQUIRED=YES the log will display
```
Build settings from command line:
    CODE_SIGN_IDENTITY = 
    CODE_SIGNING_REQUIRED = NO
```

**Comment by johnfairh** [comment]
Closing this one as inactive/mysterious for now, can reopen if more reproducible reports show up.
