### ISSUE TITLE
Generating doc for Obj-C project

### ISSUE THREAD

**Issue by bvirlet** [realm/jazzy#1068]
I'm trying to generate the documentation for an ObjC framework.

Unfortunately, I cannot make Jazzy work. 

The framework is part of a workspace, so I'm trying to use the `xcodebuild-arguments` option as follow:

```
jazzy \
  --objc \
  --clean \
  --xcodebuild-arguments -scheme,MyScheme,-workspace,MyWorkspace \
  --output docs/
```

But I'm getting the following error:
```
Unrecognized arguments: -schem, -workspace
/Users/bruno/Downloads/jazzy/lib/jazzy/executable.rb:36:in `execute_command': /Users/bruno/Downloads/jazzy/bin/sourcekitten ["doc", "-scheme", "MyScheme", "-workspace", "MyWorkspace"] (RuntimeError)

Unrecognized arguments: -schem, -workspace
	from /Users/bruno/Downloads/jazzy/lib/jazzy/sourcekitten.rb:230:in `run_sourcekitten'
	from /Users/bruno/Downloads/jazzy/lib/jazzy/doc_builder.rb:66:in `block in build'
	from /Users/bruno/Downloads/jazzy/lib/jazzy/doc_builder.rb:64:in `chdir'
	from /Users/bruno/Downloads/jazzy/lib/jazzy/doc_builder.rb:64:in `build'
	from /Users/bruno/Downloads/jazzy/bin/jazzy:15:in `<main>'
```

It looks like at some point the arguments are cut out (`scheme` becomes `schem`). Not sure why? And even without considering that, `-workspace` is presented as an unrecognized arguments.

Do you know what could be the issue here? 

Also a more general question: is generating documentation for an Objective-C framework still supported?

Thanks a lot!

**Comment by jpsim** [comment]
Jazzy unfortunately doesn't support automatically generating compiler arguments from an xcodebuild invocation, unlike its Swift support.

You'll need to pass all the necessary arguments that would be passed to `clang` to make your framework compile. See the Objective-C examples in the readme for some examples: https://github.com/realm/jazzy#objective-c

**Comment by bvirlet** [comment]
Thank you @jpsim. I have tried the listed commands but couldn't get much to work (mostly problems finding headers, my project isn't very standard in terms of file hierarchy). 

To make sure I understand correctly that there won't be a way to build a scheme in a workspace, I would have to build large xcodebuild command gathering all the input files?

**Comment by jpsim** [comment]
If you read through the `xcodebuild` log for your project, you should be able to extract the arguments to clang needed to build your framework. That's what jazzy needs.

**Comment by jimadamsss** [comment]
I have much the same issue. I build a framework for iOS and the directories in the project don't look like the group names in the project. What are the clang parameters you are looking for?

**Comment by jpsim** [comment]
> What are the clang parameters you are looking for?

What are all the arguments that clang needs to build your framework?

**Comment by jimadamsss** [comment]
This is the xcodebuild command line:
['xcodebuild', 'build', '-project', xcodebuild.projectFile.name, '-target', scheme, '-sdk', 'iphonesimulator', "SYMROOT=${xcodebuild.symRoot.getAbsolutePath()}"]

**Comment by jimadamsss** [comment]
I will also note that it looks like it is attempting to include my .git directory

**Comment by jpsim** [comment]
Those are `xcodebuild` command arguments. Not `clang`.

**Comment by johnfairh** [comment]
When you do `jazzy --objc --umbrella-header MyMod/MyMod.h --framework-root . --sdk iphonesimulator` then jazzy guesses at `clang` flags to successfully compile `MyMod/MyMod.h`.

If this doesn't work then you need to manually supply all the `clang` flags in the format shown in the readme.  At minimum that probably means `jazzy --objc --xcodebuild-arguments --objc,MyMod/MyMod.h,--,-x,-objective-c,-isysroot,$(xcrun --show-sdk-path --sdk iphonesimulator),-I,$(pwd),-fmodules`.

A common problem with jazzy is when your directory structure does not reflect the include/import statements -- eg. you have `#import <MyMod/MyMod.h>` but the directory containing `MyMod.h` is called `Sources/Headers`.  Then whatever `-I,path` pair you pass the compile fails complaining about not finding files.

There is no neat solution.  Some users' directory structures are simple enough that they can just symlink `Sources/Headers` -> `MyMod` to make a directory structure matching the `#include`s.  Others manually create the required directory structure, populated only by the header files required by the umbrella, in a temp place to run jazzy against.  More examples and discussion from #667.

**Comment by jimadamsss** [comment]
So, when I build my project, I see clang for .m files, not .h files. I tried what you mentioned about copying the header files somewhere else in the correct structure but I got an unspecified error from source kitten.
jazzy --objc --xcodebuild-arguments --objc,SASCollector/SASCollector.h,--,-x,-object-c,-isysroot,$(xcrun --show-sdk-path --sdk iphonesimulator),-I,$(pwd)/headers,-fmodules
/Library/Ruby/Gems/2.3.0/gems/jazzy-0.9.6/lib/jazzy/executable.rb:36:in `execute_command': /Library/Ruby/Gems/2.3.0/gems/jazzy-0.9.6/bin/sourcekitten ["doc", "--objc", "SASCollector/SASCollector.h", "--", "-x", "-object-c", "-isysroot", "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.2.sdk", "-I", "/Users/sasjaa/Documents/CI/CISDK/headers", "-fmodules"] (RuntimeError)

	from /Library/Ruby/Gems/2.3.0/gems/jazzy-0.9.6/lib/jazzy/sourcekitten.rb:230:in `run_sourcekitten'
	from /Library/Ruby/Gems/2.3.0/gems/jazzy-0.9.6/lib/jazzy/doc_builder.rb:65:in `block in build'
	from /Library/Ruby/Gems/2.3.0/gems/jazzy-0.9.6/lib/jazzy/doc_builder.rb:63:in `chdir'
	from /Library/Ruby/Gems/2.3.0/gems/jazzy-0.9.6/lib/jazzy/doc_builder.rb:63:in `build'
	from /Library/Ruby/Gems/2.3.0/gems/jazzy-0.9.6/bin/jazzy:15:in `<top (required)>'
	from /usr/local/bin/jazzy:22:in `load'
	from /usr/local/bin/jazzy:22:in `<main>'

**Comment by johnfairh** [comment]
`objective-c` not `-object-c` --- partially a mistake in my comment, fixed now.

**Comment by jimadamsss** [comment]
I replaced object-c with objective-c and now I just get a RuntimeError
jazzy --objc --xcodebuild-arguments --objc,SASCollector/SASCollector.h,--,-x,-objective-c,-isysroot,$(xcrun --show-sdk-path --sdk iphonesimulator),-I,$(pwd)/headers,-fmodules
/Library/Ruby/Gems/2.3.0/gems/jazzy-0.9.6/lib/jazzy/executable.rb:36:in `execute_command': /Library/Ruby/Gems/2.3.0/gems/jazzy-0.9.6/bin/sourcekitten ["doc", "--objc", "SASCollector/SASCollector.h", "--", "-x", "-objective-c", "-isysroot", "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.2.sdk", "-I", "/Users/sasjaa/Documents/CI/CISDK/headers", "-fmodules"] (RuntimeError)

	from /Library/Ruby/Gems/2.3.0/gems/jazzy-0.9.6/lib/jazzy/sourcekitten.rb:230:in `run_sourcekitten'
	from /Library/Ruby/Gems/2.3.0/gems/jazzy-0.9.6/lib/jazzy/doc_builder.rb:65:in `block in build'
	from /Library/Ruby/Gems/2.3.0/gems/jazzy-0.9.6/lib/jazzy/doc_builder.rb:63:in `chdir'
	from /Library/Ruby/Gems/2.3.0/gems/jazzy-0.9.6/lib/jazzy/doc_builder.rb:63:in `build'
	from /Library/Ruby/Gems/2.3.0/gems/jazzy-0.9.6/bin/jazzy:15:in `<top (required)>'
	from /usr/local/bin/jazzy:22:in `load'
	from /usr/local/bin/jazzy:22:in `<main>'

Any idea where the log would be? Or what the issue might be?

**Comment by johnfairh** [comment]
The command pasted above has `-objective-c` not `objective-c`.  Very opaque error-reporting here.

**Comment by jimadamsss** [comment]
Well, that changed it slightly. Now it says 
error: error reading 'SASCollector/SASCollector.h'
./headers/SASCollector/SASCollector.h is there

**Comment by johnfairh** [comment]
Ok well now you're just into C compiler errors, you have to add `-I,<path>` type pairs so it can find the files to start with.

**Comment by jimadamsss** [comment]
I got further. I changed the initial .h location to its real path and left the headers in the -I area and it generated the docs! Unfortunately it is only showing me the objective C version and not the swift equivalencies .

**Comment by jimadamsss** [comment]
Ah. It is only for the initial file that I only have objective c documentation

**Comment by jimadamsss** [comment]
I was able to get around by creating a dummy file that just contained an import of my base tree. Now everything is working.

**Comment by RaymondChan1** [comment]
The clang flags work well in terminal but if I were to put it inside the .jazzy.yaml file it complains with

**warning: no such sysroot directory: '$(xcrun --show-sdk-path --sdk iphonesimulator)' [-Wmissing-sysroot]**

It seems like it doesn't execute the command but literally takes that string as the path.

**Comment by jpsim** [comment]
> It seems like it doesn't execute the command but literally takes that string as the path.

Correct.

**Comment by nrudnyk** [comment]
@jimadamsss What exactly you did, to have both swift and obj-c in your headers?
I'm facing similar issues, and while using --build-tool-arguments I don't have swift counterpart in generated docs. Without using --build-tool-arguments, and using generator continues to try generate (like infinite loop), and if stop it shows the following error

`
#<Thread:0x00007fdf86574a50@/Library/Ruby/Gems/2.6.0/gems/open4-1.3.4/lib/open4.rb:186 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
        7: from /Library/Ruby/Gems/2.6.0/gems/open4-1.3.4/lib/open4.rb:188:in `block (2 levels) in run'
        6: from /Library/Ruby/Gems/2.6.0/gems/open4-1.3.4/lib/open4.rb:351:in `block (4 levels) in spawn'
        5: from /Library/Ruby/Gems/2.6.0/gems/open4-1.3.4/lib/open4.rb:254:in `relay'
        4: from /Library/Ruby/Gems/2.6.0/gems/open4-1.3.4/lib/open4.rb:211:in `to'
        3: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:76:in `timeout'
        2: from /Library/Ruby/Gems/2.6.0/gems/open4-1.3.4/lib/open4.rb:211:in `block in to'
        1: from /Library/Ruby/Gems/2.6.0/gems/open4-1.3.4/lib/open4.rb:254:in `block in relay'
/Library/Ruby/Gems/2.6.0/gems/open4-1.3.4/lib/open4.rb:254:in `gets': stream closed in another thread (IOError)
`

So what is my options? Is there any ideas what I'm doing wrong?

**Comment by johnfairh** [comment]
If you post your test project then I can take a look at it.   Not sure if a typo, but It should be `--umbrella-header` not `--umbrella_header`.  And `--framework-root` which should probably be `.` rather than the subdirectory -- so that `#import <JazzyTest/foo.h>` works.

A common reason why the Swift version of APIs are absent is that the header files defining the  ObjC versions are not standalone.  You can check this by trying to compile them on their own.

**Comment by nrudnyk** [comment]
[JazzyTest.zip](https://github.com/realm/jazzy/files/3693442/JazzyTest.zip)
uploaded test with 2 outputs.
the one is generated using:
  jazzy \
  --objc \
  --clean \
  --build-tool-arguments --objc,JazzyTest/JazzyTest.h,--,-x,objective-c,-isysroot,$(xcrun --sdk iphonesimulator --show-sdk-path),-I,JazzyTest \
  --sdk iphonesimulator \
  --output docs_build-tool-arguments

and while using --build-tool-arguments there is no swift counterpart:
<img width="727" alt="no-swift" src="https://user-images.githubusercontent.com/20221382/66257486-8397e980-e7a2-11e9-99ea-31c3678fa540.png">

another one is generated using:
jazzy --objc --clean --framework_root . --umbrella_header JazzyTest/JazzyTest.h --sdk iphonesimulator --output docs_obj-c
and the latter produces both, obj-c and swift:
<img width="716" alt="obj-c-swift" src="https://user-images.githubusercontent.com/20221382/66257492-a6c29900-e7a2-11e9-98ff-33d26cfa09fb.png">

**Comment by nrudnyk** [comment]
also, since I'm already here, is it a good idea to generate docs from headers from framework? 
e.g. `JazzyTest.framework/Headers/` сontains everything needed - umbrella + needed headers.

**Comment by johnfairh** [comment]
Looks like SourceKit needs the full path to resolve the headers - `jazzy --objc --clean --build-tool-arguments --objc,JazzyTest/JazzyTest.h,--,-x,objective-c,-isysroot,$(xcrun --sdk iphonesimulator --show-sdk-path),-I,$(pwd)/JazzyTest` works for me.  The pathname expansion is done automatically on the other path.

All jazzy does is run the C compiler against the "umbrella header".  You can move the files around wherever you want / run against derived data or sources provided clang can resolve `#include` paths.

So, yes, if your headers are in a framework and you use `-F` to point at that framework then it sounds reasonable that `#include <Framework/foo.h>` will resolve.  Haven't tried it though!

**Comment by johnfairh** [comment]
Added to objective-c docs in master.
