### ISSUE TITLE
Unable to generate document for Selected App Target

### ISSUE THREAD

**Issue by Ankush-Redapple** [realm/jazzy#1075]
While I run `jazzy --min-acl internal` its always generate document for Notification Extension Service, which is added as extension. I have search a lot to generate document for specific target (i.e. my actual application). No codes works for me `--module MyModule` or `-workspace,MyWorkspace.xcworkspace`. Please help me out

**Comment by johnfairh** [comment]
You're on the right lines: you should set `--module` correctly and also give the `-xcodebuild` parameters required to actually build that module.  Can't be more specific: depends how your Xcode project/workspaces are set up.  But you can experiment with `xcodebuild` directly on the CLI, you want to make it output Swift compilation commands for your module.

**Comment by johnfairh** [comment]
Closing, answered.
