### ISSUE TITLE
Search Documentation Option in Theme fullwidth Opens search.json?

### ISSUE THREAD

**Issue by RaymondChan1** [realm/jazzy#1079]
Is the search option in the top right corner that you see in the fullwidth theme supposed to only open the search.json file? Whatever I enter it just opens the json file.

**Comment by johnfairh** [comment]
It should do a normal search.  The usual reason I see the search.json file is that I'm using a `file://` url and haven't disabled local file restrictions.

**Comment by RaymondChan1** [comment]
@johnfairh Yes, I just disabled local file restrictions and it worked. But other than the file:// url is there another way of opening it? I'm completely ignorant on this web stuff.

**Comment by johnfairh** [comment]
When the files are local then `file://` is the easiest way to access them -- you could run a local web server if you really wanted to. Most projects serve their built docs from somewhere, often GitHub pages for projects on here.

**Comment by mahavrani** [comment]
For me also search.json file is opening whatever i type in search bar of the generated document.Please suggest.Is this a issue jazzy ?
