### ISSUE TITLE
jazzy run time error in UIKit.UIScrollView 

### ISSUE THREAD

**Issue by vtkumaresan** [realm/jazzy#1080]
cmd: jazzy --min-acl internal

Log,

  key.name: "setContentOffset(_:animated:)",

  key.usr: "c:objc(cs)UIScrollView(im)setContentOffset:animated:",
.......
  key.is_system: 1,

  key.typeusr: "$s_8animatedySo7CGPointV_SbtcD",

  key.containertypeusr: "$sSo12UIScrollViewCD",

  key.modulename: "UIKit.UIScrollView"

  key.containertypeusr: "$sSo12UIScrollViewCD",
  key.modulename: "UIKit.UIScrollView"
}/Library/Ruby/Gems/2.3.0/gems/jazzy-0.10.0/lib/jazzy/executable.rb:36:in `execute_command': /Library/Ruby/Gems/2.3.0/gems/jazzy-0.10.0/bin/sourcekitten ["doc", "--"] (RuntimeError)

**Comment by jpsim** [comment]
Can you share steps to reproduce the issue you're seeing? This isn't enough info to help you.

**Comment by vtkumaresan** [comment]
Created custom class file by extending UITableView and added new public method.

**Comment by vtkumaresan** [comment]
Found the reason, 

`
import UIKit
class JazzyTableView: UITableView {

    /*
    // Only override draw() if you perform custom drawing.
    // An empty implementation adversely affects performance during animation.
    override func draw(_ rect: CGRect) {
        // Drawing code
    }
    */
    
    
    public func test() {
        /*
         print("test")
         */
        
        // stop scrolling
        setContentOffset(contentOffset, animated: false)
    }
    

}
`


Solution,
By removing below comment works,
         /*
         print("test")
         */
