### ISSUE TITLE
Error trying to generate documents

### ISSUE THREAD

**Issue by jbarros35** [realm/jazzy#1082]
My project is fine, 100% working there is no reason I can't generate these documents.

MacBook-Pro:loxy4-native-ios Jose$ jazzy \
> --clean \
> --author Jose \
> --xcodebuild-arguments -scheme,loxy4-app \
> --module loxy4-app \
> --output docs\swift_output \
> --theme docs/themes
Ignoring unf_ext-0.0.7.5 because its extensions are not built.  Try: gem pristine unf_ext --version 0.0.7.5
Running xcodebuild
Checking xcodebuild -showBuildSettings
Running xcodebuild
Could not parse compiler arguments from `xcodebuild` output.
Please confirm that `xcodebuild` is building a Swift module.
Saved `xcodebuild` log file: /var/folders/hj/fj8cjz113wq8vgv255ndqt680000gp/T/xcodebuild-657688C7-3356-45AC-BEB0-48FE7BC432AB.log
Failed to generate documentation
/Library/Ruby/Gems/2.3.0/gems/jazzy-0.10.0/lib/jazzy/executable.rb:36:in `execute_command': /Library/Ruby/Gems/2.3.0/gems/jazzy-0.10.0/bin/sourcekitten ["doc", "--module-name", "loxy4-app", "--", "-scheme", "loxy4-app"] (RuntimeError)

Running xcodebuild

Checking xcodebuild -showBuildSettings

Running xcodebuild

Could not parse compiler arguments from `xcodebuild` output.

Please confirm that `xcodebuild` is building a Swift module.

Saved `xcodebuild` log file: /var/folders/hj/fj8cjz113wq8vgv255ndqt680000gp/T/xcodebuild-657688C7-3356-45AC-BEB0-48FE7BC432AB.log

Failed to generate documentation
	from /Library/Ruby/Gems/2.3.0/gems/jazzy-0.10.0/lib/jazzy/sourcekitten.rb:230:in `run_sourcekitten'
	from /Library/Ruby/Gems/2.3.0/gems/jazzy-0.10.0/lib/jazzy/doc_builder.rb:65:in `block in build'
	from /Library/Ruby/Gems/2.3.0/gems/jazzy-0.10.0/lib/jazzy/doc_builder.rb:63:in `chdir'
	from /Library/Ruby/Gems/2.3.0/gems/jazzy-0.10.0/lib/jazzy/doc_builder.rb:63:in `build'
	from /Library/Ruby/Gems/2.3.0/gems/jazzy-0.10.0/bin/jazzy:15:in `<top (required)>'
	from /usr/local/bin/jazzy:22:in `load'
	from /usr/local/bin/jazzy:22:in `<main>'

**Comment by johnfairh** [comment]
The answer is in the xcodebuild log file mentioned.  My guess though is that your module name is actually `loxy4_app` -- the dash isn't alphanumeric.  Apple have rearranged their dev docs website such that the link I had to where the product module name rules are documented doesn't work.

**Comment by johnfairh** [comment]
Closing, answered/inactive.
