### ISSUE TITLE
Adding assets catalog to generated docs directory.

### ISSUE THREAD

**Issue by SzymonMatysik** [realm/jazzy#1084]
Hi, i'd like to add assets catalog (with images added in .md files) automatically during generation of docs directory. Same as it's done with custom documentation in .yaml file:
`
documentation: ../project/guides/*.md
`

for assets i'd like something like:

`
assets: ../project/assets
`

Is it possible, or is there any other approach?

**Comment by johnfairh** [comment]
You have to do this manually right now.  See #853 for the most recent discussion on what adding the feature might look like.

**Comment by SzymonMatysik** [comment]
Thank You @johnfairh .

**Comment by johnfairh** [comment]
Closing, answered.
