### ISSUE TITLE
Needs newer sourcekitten version to work with Xcode 11?

### ISSUE THREAD

**Issue by TrondKjeldas** [realm/jazzy#1086]
Fails to generate documentation for my Xcode 11 beta 3 project, with the error "Could not parse compiler arguments from `xcodebuild`output.", which I belive originates from sourcekitten.

After looking at the latest commits to the sourcekitten repo it seems like there is some fixes related to Xcode 11 done for the 0.24.0 release.

The xcodebuild log file:

[xcodebuild-3893E2F0-7905-49B6-9D69-BCB6B7B1C220.log](https://github.com/realm/jazzy/files/3419102/xcodebuild-3893E2F0-7905-49B6-9D69-BCB6B7B1C220.log)

**Comment by johnfairh** [comment]
The log file shows some Objective-C code being compiled and linked.  The error message you mention is from the Swift side of sourcekitten.

Can you rewind a bit please and say what you're trying to do and share the command/params you are using along with the full output from jazzy.

I don't think there are any Xcode 11-specific changes in sourcekitten; latest jazzy seems to work fine with the latest beta -- so you may well have found something new here.

**Comment by TrondKjeldas** [comment]
My project is Swift Packet Manager based, and is pure swift, but it has a couple of dependencies, and one of them is Obj-C based.

I use the Swift Packet Manager to generate the .xcodeproj project used by Jazzy.

The command line used to run jazzy is:

jazzy --output docs --theme fullwidth --author Trond Kjeldås --skip-undocumented --module KnxBasics2 --swift-version 5.1 --exclude Source/DispacthQueueOnce.swift

Maybe I somehow need to prevent the dependecies from being built when xcodebuild is being run?

I do not have access to my computer now, but will update with more information later today.

**Comment by johnfairh** [comment]
Looking at the log file in more detail, it is building just the `CocoaAsyncSocket` target and nothing else.  This means that the default `xcodebuild` command is doing that --- interesting that you generate this from SPM, that could be the Xcode 11 change.  Not sure that function is very well specified!

I think you'll need to pass `--xcodebuild-arguments` to persuade `xcodebuild` to build your `KnxBasics2` target.

**Comment by TrondKjeldas** [comment]
Seems like the .xcodeproj generated with SPM is somewhat broken, as it will not build correctly in Xcode either.

If I manually create a new project (with Xcode 11) and add the package as a dependency, I can get both the project and jazzy to build.

Worth noting that Xcode 11 does not actually require an .xcodeproj, I can open the Package.swift in 
Xcode and it will load the whole "project" and build the targets in the package correctly. 

Hopefully somewhere down the road jazzy will support SPM projects directly, as described in #487.

Anyway, sorry for troubling you with my broken Xcode project.
