### ISSUE TITLE
Could not parse compiler arguments from `xcodebuild` output

### ISSUE THREAD

**Issue by Mini-Stef** [realm/jazzy#1088]
Went through the docs, and no way to make it work properly, I always get the following error.
sudo jazzy does not solve the problem

> xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
> Running xcodebuild
> Checking xcodebuild -showBuildSettings
> Running xcodebuild
> Could not parse compiler arguments from `xcodebuild` output.
> Please confirm that `xcodebuild` is building a Swift module.
> Saved `xcodebuild` log file: /var/folders/9r/8wny4fv104z6hpdv5k8m5gsc0000gn/T/xcodebuild-9897869D-03BB-43F4-AF08-2A605A0B74DB.log
> Failed to generate documentation
> /Library/Ruby/Gems/2.3.0/gems/jazzy-0.10.0/lib/jazzy/executable.rb:36:in `execute_command': /Library/Ruby/Gems/2.3.0/gems/jazzy-0.10.0/bin/sourcekitten ["doc", "--"] (RuntimeError)
> 
> xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
> 
> Running xcodebuild
> 
> Checking xcodebuild -showBuildSettings
> 
> Running xcodebuild
> 
> Could not parse compiler arguments from `xcodebuild` output.
> 
> Please confirm that `xcodebuild` is building a Swift module.
> 
> Saved `xcodebuild` log file: /var/folders/9r/8wny4fv104z6hpdv5k8m5gsc0000gn/T/xcodebuild-9897869D-03BB-43F4-AF08-2A605A0B74DB.log
> 
> Failed to generate documentation
> 	from /Library/Ruby/Gems/2.3.0/gems/jazzy-0.10.0/lib/jazzy/sourcekitten.rb:230:in `run_sourcekitten'
> 	from /Library/Ruby/Gems/2.3.0/gems/jazzy-0.10.0/lib/jazzy/doc_builder.rb:65:in `block in build'
> 	from /Library/Ruby/Gems/2.3.0/gems/jazzy-0.10.0/lib/jazzy/doc_builder.rb:63:in `chdir'
> 	from /Library/Ruby/Gems/2.3.0/gems/jazzy-0.10.0/lib/jazzy/doc_builder.rb:63:in `build'
> 	from /Library/Ruby/Gems/2.3.0/gems/jazzy-0.10.0/bin/jazzy:15:in `<top (required)>'
> 	from /usr/local/bin/jazzy:22:in `load'
> 	from /usr/local/bin/jazzy:22:in `<main>'
> 

And the xcodebuild log file just says:

> xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

**Comment by johnfairh** [comment]
This error message is `xcode-select` asking you to point it at Xcode.

So `sudo xcode-select -s /Applications/Xcode.app/Contents/Developer` or wherever you have Xcode installed.

**Comment by Mini-Stef** [comment]
Thanks for the answer. Still no luck. It's obviously going further, but is bugging me with tons of messages that are ending by "Failed to generate documentation".
I won't waste my time (and yours) with such an immature tool.
Thanks again for your time and the intend to help.
