### ISSUE TITLE
ignoring the --output directory ?

### ISSUE THREAD

**Issue by pitoneux** [realm/jazzy#1090]
Hi There,

Jazzy is ignoring the --output directory ?

> /usr/local/bin/jazzy --source-directory "." --min-acl internal --clean --author ADC -- xcodebuild-arguments -scheme,iSAS --output **iSAS_RF/iSAS_RF_Docs** --theme docs/themes
> 
> creating doc in iSAS_RF/iSAS_RF_Docs
> Running xcodebuild
> Checking xcodebuild -showBuildSettings
> Running xcodebuild
> Parsing _[removed]_
> 95% documentation coverage with 4 undocumented symbols
> included 80 internal, public, or open symbols
> skipped 29 private or fileprivate symbols (use `--min-acl` to specify a different minimum ACL)
> building site
> building search index
> jam out ♪♫ to your fresh new docs in **`docs`**

**Comment by johnfairh** [comment]
What version of jazzy are you using?  I can't make this fail on latest, don't remember any fixes to this, and I don't recognize the _creating doc in_ printf.  Anything else unusual about your setup?

Does it actually create the docs in the wrong directory or just print it out wrongly?  (Not that I can see how these two would diverge...)

**Comment by johnfairh** [comment]
Closing, inactive.
