### ISSUE TITLE
Wrong parsing with chinese

### ISSUE THREAD

**Issue by frankxiongsir** [realm/jazzy#1091]
Thanks for great project!

Jazzy just works fine with english characters but I found that it has some problem when using unicode characters (like Chinese.) in jazzy.json like below:

`
"theme": "fullwidth",
    "documentation": "doc/MarkDown/*.md",
"custom_categories": [{
        "name": "简介",
        "children": [
            "名词说明",
            "功能介绍",
            "工程配置",
        ]
    }]
`

Jazzy can’t  generate  `名词说明.html` that match the dictionary key ‘children’

**Comment by johnfairh** [comment]
This is related to the discussion in #945.  As you've found out, non-ascii characters in documentation file names get stripped out.  When there are no other characters in the filename, the thing doesn't work at all.

I think I got disheartened by the back-compatibility part last time I looked at it, will have another go!
