### ISSUE TITLE
Could not parse compiler arguments from `xcodebuild` output.

### ISSUE THREAD

**Issue by joshbernfeld** [realm/jazzy#1099]
When running `jazzy` I am getting the following error:

```
Using config file /Users/joshbernfeld/Repositories/PhotoVideoEditorSDKSource/.jazzy.yaml
Running xcodebuild
Checking xcodebuild -showBuildSettings
Running xcodebuild
Could not parse compiler arguments from `xcodebuild` output.
Please confirm that `xcodebuild` is building a Swift module.
Saved `xcodebuild` log file: /var/folders/ds/l1t4lqms3_3dqqznnbf23hzc0000gn/T/xcodebuild-5DE269AA-CE04-49EA-9752-D2F2479DCAB1.log
Failed to generate documentation
/Library/Ruby/Gems/2.3.0/gems/jazzy-0.10.0/lib/jazzy/executable.rb:36:in `execute_command': /Library/Ruby/Gems/2.3.0/gems/jazzy-0.10.0/bin/sourcekitten ["doc", "--module-name", "PhotoVideoEditorSDKFramework", "--", "-workspace", "PhotoVideoEditorSDKFramework.xcworkspace", "-scheme", "PhotoVideoEditorSDKFramework", "-sdk", "iphonesimulator"] (RuntimeError)

Running xcodebuild

Checking xcodebuild -showBuildSettings

Running xcodebuild

Could not parse compiler arguments from `xcodebuild` output.

Please confirm that `xcodebuild` is building a Swift module.

Saved `xcodebuild` log file: /var/folders/ds/l1t4lqms3_3dqqznnbf23hzc0000gn/T/xcodebuild-5DE269AA-CE04-49EA-9752-D2F2479DCAB1.log

Failed to generate documentation
	from /Library/Ruby/Gems/2.3.0/gems/jazzy-0.10.0/lib/jazzy/sourcekitten.rb:230:in `run_sourcekitten'
	from /Library/Ruby/Gems/2.3.0/gems/jazzy-0.10.0/lib/jazzy/doc_builder.rb:65:in `block in build'
	from /Library/Ruby/Gems/2.3.0/gems/jazzy-0.10.0/lib/jazzy/doc_builder.rb:63:in `chdir'
	from /Library/Ruby/Gems/2.3.0/gems/jazzy-0.10.0/lib/jazzy/doc_builder.rb:63:in `build'
	from /Library/Ruby/Gems/2.3.0/gems/jazzy-0.10.0/bin/jazzy:15:in `<top (required)>'
	from /usr/local/bin/jazzy:22:in `load'
	from /usr/local/bin/jazzy:22:in `<main>'
```

The [build file](https://github.com/realm/jazzy/files/3593068/xcodebuild-5DE269AA-CE04-49EA-9752-D2F2479DCAB1.log) says `** BUILD SUCCEEDED **` and I am using the following .jazzy.yaml config file:

```
module: PhotoVideoEditorSDKFramework
xcodebuild_arguments: ["-workspace","PhotoVideoEditorSDKFramework.xcworkspace","-scheme","PhotoVideoEditorSDKFramework","-sdk","iphonesimulator"]
output: docs/swift_output
theme: apple
sdk: iphonesimulator
```

I am using Xcode version 10.3 and macOS 10.14.6 (both the latest). Any help is greatly appreciated.

**Comment by johnfairh** [comment]
The build file shows two Swift modules being built: `GPUImage2` and `PhotoVideoEditorSDK`.

So I think either the `module` line in the config file has a typo or you need to supply different `xcodebuild` flags to build the `PhotoVideoEditorSDKFramework` module.

**Comment by joshbernfeld** [comment]
Great catch. The `module` line should have been `PhotoVideoEditorSDK` not `PhotoVideoEditorSDKFramework`.

**Comment by michal-drobny** [comment]
I am facing the similar issue but it is not related to typo in module name.

```
drobas@drobas-mac HPAiOS % jazzy
Using config file /Users/drobas/Work/Morosystems/Source/HPAiOS/.jazzy.yaml
2020-05-20 15:27:10.603 xcodebuild[21123:265763]  DTDeviceKit: deviceType from e21db8c2c823fdf72a6a07f67c12f45043f70201 was NULL
Running xcodebuild
Checking xcodebuild -showBuildSettings
Running xcodebuild
Could not parse compiler arguments from xcodebuild output.
Please confirm that xcodebuild is building a Swift module.
Saved xcodebuild log file: /var/folders/lt/nnp3lkv96knbxmfwvw08j9km0000gn/T/xcodebuild-B2E5E3C5-FEAF-4A74-BCCC-7662B98DAEA7.log
Failed to generate documentation
Traceback (most recent call last):
	7: from /Users/drobas/.gems/bin/jazzy:23:in <main>
	6: from /Users/drobas/.gems/bin/jazzy:23:in load
	5: from /Users/drobas/.gems/gems/jazzy-0.13.3/bin/jazzy:15:in <top (required)>
	4: from /Users/drobas/.gems/gems/jazzy-0.13.3/lib/jazzy/doc_builder.rb:76:in build
	3: from /Users/drobas/.gems/gems/jazzy-0.13.3/lib/jazzy/doc_builder.rb:76:in chdir
	2: from /Users/drobas/.gems/gems/jazzy-0.13.3/lib/jazzy/doc_builder.rb:78:in block in build
	1: from /Users/drobas/.gems/gems/jazzy-0.13.3/lib/jazzy/sourcekitten.rb:266:in run_sourcekitten
/Users/drobas/.gems/gems/jazzy-0.13.3/lib/jazzy/executable.rb:36:in execute_command: /Users/drobas/.gems/gems/jazzy-0.13.3/bin/sourcekitten ["doc", "--module-name", "DN\\ Managed\\ Services", "--", "-workspace", "cocoapods/DN\\ Managed\\ Services.xcworkspace", "-scheme", "DN\\ Managed\\ Services"] (RuntimeError)
2020-05-20 15:27:10.603 xcodebuild[21123:265763]  DTDeviceKit: deviceType from e21db8c2c823fdf72a6a07f67c12f45043f70201 was NULL
Running xcodebuild
Checking xcodebuild -showBuildSettings
Running xcodebuild
Could not parse compiler arguments from xcodebuild output.
Please confirm that xcodebuild is building a Swift module.
Saved xcodebuild log file: /var/folders/lt/nnp3lkv96knbxmfwvw08j9km0000gn/T/xcodebuild-B2E5E3C5-FEAF-4A74-BCCC-7662B98DAEA7.log
Failed to generate documentation
```
 
The [build file](https://github.com/realm/jazzy/files/4657176/xcodebuild-B2E5E3C5-FEAF-4A74-BCCC-7662B98DAEA7.log) also says `** BUILD SUCCEEDED **`

Could you please help me with that?

**Comment by jerrin15** [comment]
got a similar issue if someone could help out. I have verified that my module name is properly set. Following is the error

Using config file /Users/admin/sample-demo/.jazzy.yaml
Running xcodebuild
Checking xcodebuild -showBuildSettings
Running xcodebuild
Could not parse compiler arguments from `xcodebuild` output.
Please confirm that `xcodebuild` is building a Swift module.
Saved `xcodebuild` log file: /var/folders/w1/061yd3pn555byfrmswxlcjwc0000gn/T/xcodebuild-F558D682-52E9-4727-8641-3AF29D59D80B.log
Failed to generate documentation
/Library/Ruby/Gems/2.3.0/gems/jazzy-0.13.5/lib/jazzy/executable.rb:36:in `execute_command': /Library/Ruby/Gems/2.3.0/gems/jazzy-0.13.5/bin/sourcekitten ["doc", "--module-name", "Sample_demo", "--", "-workspace", "Sample\\ demo.xcworkspace", "-scheme", "Sample\\ demo"] (RuntimeError)

Running xcodebuild

Checking xcodebuild -showBuildSettings

Running xcodebuild

Could not parse compiler arguments from `xcodebuild` output.

Please confirm that `xcodebuild` is building a Swift module.

Saved `xcodebuild` log file: /var/folders/w1/061yd3pn555byfrmswxlcjwc0000gn/T/xcodebuild-F558D682-52E9-4727-8641-3AF29D59D80B.log

Failed to generate documentation
	from /Library/Ruby/Gems/2.3.0/gems/jazzy-0.13.5/lib/jazzy/sourcekitten.rb:266:in `run_sourcekitten'
	from /Library/Ruby/Gems/2.3.0/gems/jazzy-0.13.5/lib/jazzy/doc_builder.rb:78:in `block in build'
	from /Library/Ruby/Gems/2.3.0/gems/jazzy-0.13.5/lib/jazzy/doc_builder.rb:76:in `chdir'
	from /Library/Ruby/Gems/2.3.0/gems/jazzy-0.13.5/lib/jazzy/doc_builder.rb:76:in `build'
	from /Library/Ruby/Gems/2.3.0/gems/jazzy-0.13.5/bin/jazzy:15:in `<top (required)>'
	from /usr/local/bin/jazzy:23:in `load'
	from /usr/local/bin/jazzy:23:in `<main>'

**Comment by johnfairh** [comment]
You'll need to read the log file mentioned to figure out why it can't build your module.  If you still have problems then you can open a new issue including all the log files and the jazzy command/config you're using.
