### ISSUE TITLE
No documentation generated using jazzy 0.11.0

### ISSUE THREAD

**Issue by p0nraje** [realm/jazzy#1107]
Hi,

I get an issue that ``` WARNING: No documented top-level declarations match name specified in categories file ```

What does this error mean? The documentation is not generated because of this.

**Comment by johnfairh** [comment]
The warning is a result of jazzy not finding a declaration that matches a string from the `custom_categories`.

We need to know a lot more to help debug this: version of Xcode, macOS, how you're running jazzy, what all the output is.

If you've recently changed Xcode then may be worth deleting the DerivedData for the project.

**Comment by johnfairh** [comment]
Also try adding `-x USE_SWIFT_RESPONSE_FILE=NO` to the jazzy args.

**Comment by p0nraje** [comment]
In this case, by mistake a "\" was added into the --xcodebuild-arguments. Hence jazzy was giving this issue. I removed the "\" and it worked fine, hence closing the ticket.

**Comment by johnfairh** [comment]
Oh that's good to know - thanks for coming back.
