### ISSUE TITLE
Language preference when running against Sourcekitten output

### ISSUE THREAD

**Issue by joesus** [realm/jazzy#1110]
**Background** 

I've hacked together a simple ruby script that combines the output from running Sourcekitten twice, once for Swift and once for Objective-C.

Sourcekitten for Swift
```
system "sourcekitten doc -- -workspace #{workspace} -scheme #{swiftKit} > tmpSwift"`
```

Sourcekitten for ObjC
```
system "sourcekitten doc --objc #{header_file} \
      -- -x objective-c  -isysroot $(xcrun --show-sdk-path --sdk iphonesimulator) \
      -I #{moreSourceCode} > tmpObjC
```

Run Jazzy on the combined output
```
system "jazzy \
  --config #{File.dirname(File.dirname(__FILE__))}/.jazzy.yaml \
  --output docs/#{kit} \
  --sourcekitten sourceKittenJSON"
```

When the `.jazzy.yaml` omits the `objc: true` argument, the Objective-C declarations are not included:

![image](https://user-images.githubusercontent.com/4922820/65446553-7580bb00-dde9-11e9-9aae-91926fd7cec3.png)

But the Swift declarations are included:

![image](https://user-images.githubusercontent.com/4922820/65446638-9f39e200-dde9-11e9-8839-c307d2d7fe12.png)

---

If I do include `objc: true` then the Objective-C declarations include both Swift and Objective-C sections:

![image](https://user-images.githubusercontent.com/4922820/65446760-e7f19b00-dde9-11e9-843a-c212d324e062.png)

but the Swift declarations are listed as Objective-C and are incomplete

![image](https://user-images.githubusercontent.com/4922820/65446802-00fa4c00-ddea-11e9-88db-1a4226b9ff96.png)

I think this may have to do with this code for determining language but not certain: https://github.com/realm/jazzy/blob/master/lib/jazzy/doc.rb#L31-L37

Is there an easy fix for this that you can think of? Alternately, extensive searching suggesting that there is not but if there is an easier way to generate mixed documentation please share. :)

**Comment by johnfairh** [comment]
Jazzy doesn't support mixed-language docs - it has a global opinion on whether it is dealing with Swift or ObjC.  [These notes](https://github.com/realm/jazzy/issues/447#issuecomment-453235721) are still a valid plan about how to go about improving this.

**Comment by johnfairh** [comment]
Closing this, covered by #447.
