### ISSUE TITLE
[Question] What is the proper way of defining and using NS_ENUM (NS_OPTIONS) in docs

### ISSUE THREAD

**Issue by nrudnyk** [realm/jazzy#1115]
I have the following enum

```
/**
 * Opt enum is used somewhere.
 */
typedef NS_ENUM(NSUInteger, JZTEnum) {
    /**
     * A option.
     */
    JZTEnum_A,
    
    /**
     * B option.
     */
    ZJTEnum_B,
};
```

and no matter how I reference options `JZTEnum_A`, or anything else, it doesn't get referenced, `JZTEnum` does have reference though. 
av
What I'm missing here? Thanks in advance.

**Comment by johnfairh** [comment]
If you mean auto-linking to the enum element decl, then it looks like you need to do eg. <code>\`JZTEnum.JZTEnum_A\`</code>.  I guess C enums are the only thing that are hierarchically defined but not referenced.  You could post-process the html after site generation to remove the unwanted prefix.

**Comment by nrudnyk** [comment]
yeah, I've tried that, doesn't seems to work... just greyed out without link
<img width="208" alt="image" src="https://user-images.githubusercontent.com/20221382/66394844-c8a85f80-e9de-11e9-8ede-d59a40786996.png">

[JazzyTest.zip](https://github.com/realm/jazzy/files/3702279/JazzyTest.zip)

**Comment by johnfairh** [comment]
It works fine - I tested before posting.  In your sample zip file there are a few typos of "ZJT" instead of "JZT".

**Comment by nrudnyk** [comment]
oh, you definitely write, sorry for bothering with such a stupid mistake. Thanks for pointing that, everything works now.
