### ISSUE TITLE
[Question] Proper way of mixing markdown/html/markdown

### ISSUE THREAD

**Issue by nrudnyk** [realm/jazzy#1116]
In some places I need to document obj-c and swift code (also maybe Xamarin.iOS), and it would be great to do that in tabbed table. Since guides are in markdown, I was trying to insert html there, which works, but then if I insert markdown into html - it became bare text without syntax highlighting (I can use `pre` tag to keep it in place). Is there a way to do that properly? Or is there a better way to document multiple languages? Simplified version is showcased below:

<img width="379" alt="image" src="https://user-images.githubusercontent.com/20221382/66436591-1e592800-ea30-11e9-89e9-eccd53b5be3d.png">

which produces 

<img width="199" alt="image" src="https://user-images.githubusercontent.com/20221382/66436648-4f395d00-ea30-11e9-9cef-5a0c188375ab.png">

Thanks in advance.

**Comment by johnfairh** [comment]
Markdown passes HTML block elements through to the output without looking at their contents.  So nothing inside the `div` is parsed as markdown.

You could take an all-html approach, using one of the js code formatters instead of what jazzy provides; or leave the tabbed-table stuff out of your .md and add those pieces in afterwards to the generated html.

**Comment by nrudnyk** [comment]
I would rather use markdown with same syntax highlighting to be consistent with other places, but it seems, that markdown doesn't allow 
```
multiplelinesofcode
```
in table cell. So it looks some js syntax highlighter would be a good option, unless you know how to place code inside md cells. Do you?

**Comment by johnfairh** [comment]
I think you're right, you can force simple line breaks with `<br/>` but formatted codeblocks seem impossible.

**Comment by nrudnyk** [comment]
eventually decided to go with Prism highlighter with bare html for such cases.
Thanks for help. Have a good day!
