### ISSUE TITLE
[QUESTION] Is there a way to auto link Foundation classes such as NSObject

### ISSUE THREAD

**Issue by nrudnyk** [realm/jazzy#1118]
Is there anything I missing to make that happen? At the moment - no links for Foundation classes. I'm documenting obj-c framework.

**Comment by johnfairh** [comment]
You're not missing anything: this isn't a feature.  There is a sketch of how to proceed in a branch that uses an Xcode-internal database to resolve references to the Apple SDK.  Ruby and basic SQL skills needed to take it further.

**Comment by nrudnyk** [comment]
got it. Thanks for the reply. It's rather nice to have than worth considering it as something major, but would be nice to have out of the box though.

**Comment by nrudnyk** [comment]
is this can be considered as feature request - let's mark it that way, otherwise - I suspect you can close this thread. Thanks!

**Comment by johnfairh** [comment]
OK -- it's issue #13 -- finishing off that branch is on my list to do after some Swift extension declaration work.
