### ISSUE TITLE
Jazzy fails to document development pod with resource_bundles, script_phase and prepare_command sections

### ISSUE THREAD

**Issue by froi-travelperk** [realm/jazzy#1119]
Stack:

XCode	11.1
Ruby	2.6.4
Cocoapods	1.8.0
Jazzy  0.11.2

Hi,

We are currently documenting our modularised project. It worked with most of the pods, but we have trouble with one specific. We have double checked Podspec file and all seems fine, but when we removed this section, it worked fine:

s.resource_bundles = ...
s.script_phase = ...
s.prepare_command = ...

Thanks.

**Comment by johnfairh** [comment]
Can you say more about the trouble you had or help us recreate it?  I added those settings (with fairly dummy values) to a working podspec project and everything worked fine.  Do you think the trouble could be to do with the contents of those settings in your project?

**Comment by johnfairh** [comment]
Closing, inactive.
