### ISSUE TITLE
[Question] Is there a way to have relative links between written docs? 

### ISSUE THREAD

**Issue by nrudnyk** [realm/jazzy#1122]
As per title, is there a way to have relative links between written markdown? 

e.g. I Have `-- documentation: "guides/*.md"` and I have the following files:

```
+-- guides
|   +-- Main.md
|   +-- Additional.md
```

and I want to reference `Additional.md` from `Main.md`. What is the proper way of doing that? 
Or I should provide full relative html link which will be generated later?

**Comment by nrudnyk** [comment]
Also, I'm interested if the images can be used from custom assets directory (how to use it if possible), or maybe I can use custom theme, which includes `custom-theme/assets/img/` folder, and which is accessible in generated html.

**Comment by johnfairh** [comment]
You can use [markdown link syntax](https://www.markdownguide.org/basic-syntax/#links) -- you need to see what jazzy is naming the `.html` version of your `.md` and link to that, eg. in `Main.md`, eg.
```markdown
...see [additional docs](additional.html) for more.
```

For images/other resources you need to manually copy them into the docs directory; see that same markdown syntax page for how to link to images.

**Comment by nrudnyk** [comment]
ok, as I suspected, need to look the jazzy naming and use the end-result. Thanks.
(btw, that might be considered as feature somewhere in future, would be cool to use relative article naming)

Anyways. thanks for your time!

**Comment by johnfairh** [comment]
>considered as feature

Agreed -- #775, #853.
