### ISSUE TITLE
Changing Image Size?

### ISSUE THREAD

**Issue by colincornaby** [realm/jazzy#1124]
We're including Retina quality images in our documentation, but I can't resize them down in order to double their DPI. I've tried using the semi-standard forms of Markdown image resize, and none of them work in Jazzy. It looks like the underlying Markdown library doesn't support these extra attributes.

Is there anything I've missed on how to resize images? Any way to embed the HTML directly as a workaround?

If not, it would be a great feature enhancement.

**Comment by johnfairh** [comment]
Jazzy uses [Redcarpet](https://github.com/vmg/redcarpet) to render the markdown.  I don't think it supports anything to do with size.

Redcarpet will pass through HTML block elements, so you should be fine to write a &lt;div> containing the &lt;img> you want.

**Comment by johnfairh** [comment]
Closing, answered.
