### ISSUE TITLE
My enumerations are not getting documented

### ISSUE THREAD

**Issue by migueldeicaza** [realm/jazzy#1126]
I have many enumerations in a single file, and only the first enumeration is being documented, the others are flagged as undocumented.

Example: github.com/migueldeicaza/SkiaKit

It contains a Makefile at the toplevel with the Jazzy invocation

**Comment by migueldeicaza** [comment]
Mhm, it looks like if I switch to "///" comments instead of "/**" it works.

**Comment by johnfairh** [comment]
What's an example of one that's not coming out right?  On latest jazzy + Xcode 11.2 it looks like the only `undocumented` enums are those without doc comments, even in the committed docs/swift_docs/index.html site.  I might have missed one though.

(see `grep -B1 decl.enum\" docs/swift_output/undocumented.json`)

**Comment by johnfairh** [comment]
Closing, answered/inactive.
