### ISSUE TITLE
Bulleted lists with asterisks not working without other content

### ISSUE THREAD

**Issue by grundoon** [realm/jazzy#1132]
From superficial observation, it seems that a bulleted list fails to actually bullet unless it is followed by additional unformatted description text.

A bulleted list followed only by delimiters is swallowed into the description. The bullet symbols disappear entirely, leaving just the list items' text.

A numbered list does not exhibit this behavior. 

This in Swift code, using `///` style doc comments.

**Comment by johnfairh** [comment]
Easiest workaround is to use `-` instead of `*` as your bullet symbol.  If every line in a doc comment begins with `*` then it looks like sourcekitten strips them out, accidentally thinking it's decoding a 'wall of asterisks' type block-comment.

**Comment by grundoon** [comment]
Well, except that `-`, `+` and `*` all yield the same result.

```swift
/// Summary line.
///
/// Description line 1,
/// description line 2.
///
/// - list item 1
/// - list item 2
///
/// - Note: This is a test.
///
/// - Requires: Something.
/// - Parameter string: A string.
/// - Throws: 5xx error for some reason.
/// - Returns: UUID.
func testJazzy(with string: String) throws -> UUID {
    guard let uuid = UUID(string) else {
        throw Abort(.internalServerError, reason: "nope")
    }
    return uuid
}
```
generates

![Screen Shot 2019-11-25 at 10 25 30](https://user-images.githubusercontent.com/876321/69567682-cbe7b280-0f6e-11ea-9c19-b3b7c4cb08de.png)

and adding literally any text

```swift
/// - list item 2
///
/// .
///
/// - Note: This is a test.
```

seems the only workaround

![Screen Shot 2019-11-25 at 10 27 22](https://user-images.githubusercontent.com/876321/69567810-208b2d80-0f6f-11ea-99cc-b4def35d82e4.png)

**Comment by johnfairh** [comment]
Oh ok - was guessing what you meant earlier.  Looks like #785, thrown off by the following callout.

**Comment by grundoon** [comment]
Ah, yes, sorry – both missed that one and was too in a rush for dinner to properly describe. I did manage to find that my other issue

```swift
extension Future where T: User { ... }
extension Future where T: UserProfile { ... }
```
would have been a duplicate of https://github.com/realm/jazzy/issues/717 though. 🙂

**Comment by johnfairh** [comment]
No problem - this way we found a new bug 🙃 
Both your actual issues should be fixed in the next release.

**Comment by grundoon** [comment]
This one seems to now be working nicely in 0.13.0 and can close – yay!
And the https://github.com/realm/jazzy/issues/717 work looks really great... though presumably the last entry isn't precisely what's intended?

![Screen Shot 2019-12-11 at 22 59 59](https://user-images.githubusercontent.com/876321/70690295-3e44dc00-1c6b-11ea-82f9-ad85df42b2b3.png)

**Comment by johnfairh** [comment]
Guess: is there a `// MARK:` comment _inside_ the `UserProfile` extension?  If so then jazzy will use that instead of the auto-generated one.  Will need to see the source code otherwise!

**Comment by grundoon** [comment]
You mean the one used for testing workarounds that I'd totally forgotten about and just happened to be alphabetically last? That's a pretty good guess. 🙂
