### ISSUE TITLE
Extensions with where clauses aren't documented completely

### ISSUE THREAD

**Issue by skhavari** [realm/jazzy#1134]
**Repro**
* Define an [extension with a where clause](https://docs.swift.org/swift-book/LanguageGuide/Generics.html#ID553)
    `extension Sequence where Iterator.Element == String`
* Define another extension on the same type with different `where` clause
    `extension Sequence where Iterator.Element == String`
* Run `jazzy`

**Expect**

* Either a single page for `Sequence` with distinct section for each  `where` clause- or 
* Two different pages, one for each of the `where` clauses - or
* Some other approach that clearly documents each distinct extension

**Actual**

* Get a single page for the `Sequence` extension
* Title only contains one of the extension definitions (one `where` clause)

**Comment by johnfairh** [comment]
Fixed in master via #1131 (& then #1133).
