### ISSUE TITLE
Doc is not generated for custom Obj-c "setter" with non void return type.

### ISSUE THREAD

**Issue by dashchak** [realm/jazzy#1142]
In our SDK we have readonly property:
`@property (nonatomic, readonly) NSUInteger routeRequestInterval;`

and custom non-void setter in order to return some error:
`-(NMANavigationError)setRouteRequestInterval:(NSUInteger)interval;`

Doc is generated only for property. Setter is not shown at all.
When I try to explicitly add (setter = setRouteRequestInterval:),
 I get Jazzy error:  `type of setter must be void`
Looks like a Jazzy issue as doc is generated by Xcode when I Opt+click the property or setter.
We can not modify the setter as it is public header in SDK and will affect users.

Is there any workaround?

**Comment by johnfairh** [comment]
Sourcekitten filters out property getters + setters, they're usually not interesting.  You could probably teach it to spot getters and setters that have unusual return types [around here](rejectPropertyMethods).

The `type of setter must be void` is coming from clang, maybe you need to set some special flag to disable that error.

**Comment by johnfairh** [comment]
Closing, answered.
