### ISSUE TITLE
If a class has no variables, its class documentation renders incorrectly

### ISSUE THREAD

**Issue by zablaetna** [realm/jazzy#1143]
I had class documentation render strangely for a particular class of mine. It was merging the full "Classes Reference" with part of the specific class documentation. \

After much debugging, I narrowed it down to the fact that the class doesn't have any variables. The same happens if it only has private variables. Here's an example:

```
public class Separator: UIView {
    private static var foo = 0

    override init(frame: CGRect) {
        super.init(frame: frame)
    }

    required init?(coder: NSCoder) {
        super.init(coder: coder)
    }
}
```
If I flip the private variable public, it will render correctly:

```
public class Separator: UIView {
    public static var foo = 0

    override init(frame: CGRect) {
        super.init(frame: frame)
    }

    required init?(coder: NSCoder) {
        super.init(coder: coder)
    }
}
```

The class documentation should render correctly even if it doesn't have any variables.

**Comment by johnfairh** [comment]
Are you able to share the versions of everything you're using, the jazzy command/config, and post a screenshot of the bad behavior?

On latest everything your sample seems to work fine, `--min-acl internal`.

![Screenshot 2019-12-18 at 20 08 48](https://user-images.githubusercontent.com/26768470/71119556-5f10b280-21d2-11ea-960b-d1187c562268.png)

![Screenshot 2019-12-18 at 20 09 45](https://user-images.githubusercontent.com/26768470/71119577-6637c080-21d2-11ea-89c2-f7b69b574677.png)

**Comment by johnfairh** [comment]
Closing, inactive.
