### ISSUE TITLE
CI Bitrise Badge

### ISSUE THREAD

**Issue by cbm-mghebaji** [realm/jazzy#1144]
Hello,

I have question about using CI Badge, i use Bitrise for CI so i want to get the status of the build.
The default index.html file use Travis, i can change it with the Bitrise URL but when i regenrate the doc i will use Travis. 
How can i deal with it to use always Bitrise ?

**Comment by johnfairh** [comment]
The `index.html` is generated from `README.md` / `README.markdown` / `README.mdown` / `README` / the `--readme` option.  Failing that a simple page is generated that does not refer to Travis CI.

**Comment by johnfairh** [comment]
Closing, answered.
