### ISSUE TITLE
Combine abstract and discussion in page overview

### ISSUE THREAD

**Issue by luketheobscure** [realm/jazzy#115]
I've got the following file in my project:

``` swift
/**
    Protocol for storing information about a diff.

    Two things that kind of suck:
        - As of XCode 6.1.1, There's some kind of bug between the @NSManaged directive, protocols, and the compiler, so we can't set these as actual @NSManaged properties in out models, thus the weird names
        - We have to add the @objc or else the compiler won't let us assign back to these variables, despite having defined setters.
*/

@objc
public protocol Diffable {
    var diffUrlString: String? { get set }
    var diffString: String? { get set }
}
```

As expected, the whole comment shows up in the "Protocols available globally section" under "Diffable". But if I document the two variables "Diffable" gets it's own section, and we only get the first line of the comment. Removing the blank line gives me two lines of documentation, but we don't get the list. See attached.

_Properties not documented:_
![screen shot 2014-12-14 at 8 01 25 am](https://cloud.githubusercontent.com/assets/1163812/5427929/856b3a86-8367-11e4-8be6-ff80860b0d3c.png)

_Properties documented (documentation is truncated):_
![screen shot 2014-12-14 at 7 59 22 am](https://cloud.githubusercontent.com/assets/1163812/5427920/3b2e9b52-8367-11e4-9552-8f8bcca98322.png)

**Comment by luketheobscure** [comment]
I'm not sure this worked. Here's the documentation generated with Jazzy 0.0.19: http://luketheobscure.github.io/BlargBucket/Protocols/Diffable.html

Here's the file that was parsed:
https://github.com/luketheobscure/BlargBucket/blob/master/BlargBucket/Models/Base%20Classes/Diffable.swift

**Comment by jpsim** [comment]
That change hasn't been pushed to rubygems yet. You'll have to run from the current master branch to see the change.
