### ISSUE TITLE
[Question] How to add anchor before sections headers, like in GitHub?

### ISSUE THREAD

**Issue by nrudnyk** [realm/jazzy#1151]
Is there a built-in way to add anchors like below:

<img width="458" alt="image" src="https://user-images.githubusercontent.com/20221382/72415937-44ecd480-377e-11ea-922c-d053253c33f1.png">

That would allow quick copy of the proper link to the section and sharing it easily. Thank you in advance!

**Comment by johnfairh** [comment]
I recommend [AnchorJS](https://www.bryanbraun.com/anchorjs/). jazzy puts a class called `heading` on all the headings so `anchors.add('.heading')`  should get you started.

**Comment by nrudnyk** [comment]
hello @johnfairh, thanks for quick response. I integrated it with ease. Thanks a lot!
