### ISSUE TITLE
Add usage examples

### ISSUE THREAD

**Issue by rickwierenga** [realm/jazzy#1155]
Is it possible to add usage examples defined in a docstring in the generated docs? Thanks.

**Comment by johnfairh** [comment]
Maybe, can you add an example of what you mean?

**Comment by rickwierenga** [comment]
Never mind, I created this issue too quick. Sorry for that.

For future reference, this out [this article](https://medium.com/@arpit.cor/easy-documentation-for-your-swift-project-using-jazzy-9117f6a8709a).
