### ISSUE TITLE
Explain in the readme that jazzy will document the first build target

### ISSUE THREAD

**Issue by bskendig** [realm/jazzy#1157]
I'm developing a framework. The main directory contains its `.xcodeproj` file, a directory named `MyFramework` with the source code for it, and a directory named `MyExample` with the source code for a sample app that uses it.

When I ran jazzy from the main directory, it would generate documentation for MyExample, which is not what I wanted. I tried specifying `--source-directory MyFramework` but then jazzy would die with errors because it couldn't find the project.

I figured out that the reason it was documenting MyExample was that this is the **first build target in my project file**. I moved MyFramework above it, and that solved the problem.

Please document this so that it helps someone else. I recommend changing the Usage section of the readme file:

> If your Swift module is the first thing to build, and it builds fine when running xcodebuild or swift build without any arguments from the root of your project, then just running jazzy (without any arguments) from the root of your project should succeed too!

to say this instead:

>`jazzy` will generate documentation for the first build target in your Xcode project. If that builds successfully when you run `xcodebuild` or `swift build` without any arguments from the root of your project, then just running jazzy (without any arguments) from the root of your project should succeed too! (If you want it to document a different build target, then drag that to the top of the targets list in Xcode.)

(Alternately, it might be nice to have an argument to `jazzy` to point it to a specific build target.)

**Comment by johnfairh** [comment]
Agree that para leaves you hanging if it doesn't just work -- will make an edit mentioning what options to explore first.
