### ISSUE TITLE
Install fails (Xcode 10.3 + Catalina)

### ISSUE THREAD

**Issue by Ahmadalsofi** [realm/jazzy#1165]
i got the following error while i'm trying to install Jazzy 

> Building native extensions.  This could take a while...
> ERROR:  Error installing jazzy:
> 	ERROR: Failed to build gem native extension.
> 
>     current directory: /Library/Ruby/Gems/2.3.0/gems/sassc-2.2.1/ext
> /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby -r ./siteconf20191019-10733-17dptcw.rb extconf.rb
> mkmf.rb can't find header files for ruby at /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/include/ruby.h
> 
> extconf failed, exit code 1
> 
> Gem files will remain installed in /Library/Ruby/Gems/2.3.0/gems/sassc-2.2.1 for inspection.
> Results logged to /Library/Ruby/Gems/2.3.0/extensions/universal-darwin-18/2.3.0/sassc-2.2.1/gem_make.out
> 

would you please assist what it the issue exactly should i downgrade my (Xcode or OS) or upgrade to solve the issue ?

**Comment by johnfairh** [comment]
The system looks a bit unusual -- if you cannot upgrade to latest macOS & XCode then probably the easiest way to a working Ruby is to install with homebrew.

**Comment by ppamorim** [comment]
I am experiencing a similar issue (macOS 10.15.4):

```
MacBook-Pro:hi me$ sudo gem install jazzy
Fetching jazzy-0.13.2.gem
Fetching sassc-2.2.1.gem
Building native extensions. This could take a while...
ERROR:  Error installing jazzy:
        ERROR: Failed to build gem native extension.

    current directory: /usr/local/lib/ruby/gems/2.6.0/gems/sassc-2.2.1/ext
/usr/local/opt/ruby/bin/ruby -I /usr/local/lib/ruby/site_ruby/2.6.0 -r ./siteconf20200405-63135-5833n7.rb extconf.rb
creating Makefile

current directory: /usr/local/lib/ruby/gems/2.6.0/gems/sassc-2.2.1/ext
make "DESTDIR=" clean

current directory: /usr/local/lib/ruby/gems/2.6.0/gems/sassc-2.2.1/ext
make "DESTDIR="
compiling ./libsass/src/units.cpp
In file included from ./libsass/src/units.cpp:1:
In file included from ./libsass/src/sass.hpp:55:
In file included from /usr/local/opt/llvm/bin/../include/c++/v1/string:505:
In file included from /usr/local/opt/llvm/bin/../include/c++/v1/string_view:176:
In file included from /usr/local/opt/llvm/bin/../include/c++/v1/__string:57:
In file included from /usr/local/opt/llvm/bin/../include/c++/v1/algorithm:642:
In file included from /usr/local/opt/llvm/bin/../include/c++/v1/cstring:61:
/usr/local/opt/llvm/bin/../include/c++/v1/string.h:61:15: fatal error: 'string.h' file not found
#include_next <string.h>
              ^~~~~~~~~~
1 error generated.
make: *** [units.o] Error 1

make failed, exit code 2

Gem files will remain installed in /usr/local/lib/ruby/gems/2.6.0/gems/sassc-2.2.1 for inspection.
Results logged to /usr/local/lib/ruby/gems/2.6.0/extensions/x86_64-darwin-18/2.6.0/sassc-2.2.1/gem_make.out
```

**Comment by johnfairh** [comment]
That looks like a problem with your C compiler building libsass.  You could try asking in [sassc/sassc-ruby](https://github.com/sass/sassc-ruby) if you are sure the llvm tools in /usr/local/opt are working/configured properly.

**Comment by ppamorim** [comment]
@johnfairh https://stackoverflow.com/a/59231159/2430555

**Comment by johnfairh** [comment]
Closing this one now.
