### ISSUE TITLE
Install failed with Xcode 11.4 and Catalina 10.15.4

### ISSUE THREAD

**Issue by AllonJunior** [realm/jazzy#1175]
I failed to install jazzy with `sudo gem install jazzy` and get errors like this:
`Building native extensions. This could take a while...
ERROR:  Error installing jazzy:
	ERROR: Failed to build gem native extension.

    current directory: /usr/local/lib/ruby/gems/2.7.0/gems/ffi-1.12.2/ext/ffi_c
/usr/local/opt/ruby/bin/ruby -I /usr/local/Cellar/ruby/2.7.1/lib/ruby/2.7.0 -r ./siteconf20200415-58256-u4vp8l.rb extconf.rb
checking for ffi.h... no
checking for ffi.h in /usr/local/include,/usr/include/ffi... no
checking for shlwapi.h... no
checking for rb_thread_call_without_gvl()... yes
checking for ruby_native_thread_p()... yes
checking for ruby_thread_has_gvl_p()... yes
creating extconf.h
creating Makefile

current directory: /usr/local/lib/ruby/gems/2.7.0/gems/ffi-1.12.2/ext/ffi_c
make "DESTDIR=" clean

current directory: /usr/local/lib/ruby/gems/2.7.0/gems/ffi-1.12.2/ext/ffi_c
make "DESTDIR="
Configuring libffi
configure: error: in `/usr/local/lib/ruby/gems/2.7.0/gems/ffi-1.12.2/ext/ffi_c/libffi-x86_64-darwin19':
configure: error: C++ preprocessor "/lib/cpp" fails sanity check
See `config.log' for more details
make: *** ["/usr/local/lib/ruby/gems/2.7.0/gems/ffi-1.12.2/ext/ffi_c/libffi-x86_64-darwin19"/.libs/libffi_convenience.a] Error 1
`

I have run `xcode-select --install`, after searched, I found that there was no `/lib/cpp` on Mac OS file system.

**Comment by johnfairh** [comment]
You may have better luck asking on the [ffi repo](https://github.com/ffi/ffi) or for general macOS + Ruby help on that error message.  I don't recognize what is wrong with your compiler/Ruby config.

**Comment by johnfairh** [comment]
Closed, inactive.
