### ISSUE TITLE
Unable to find an Xcode with swift version 4.2. (RuntimeError)

### ISSUE THREAD

**Issue by kamathpuneeth** [realm/jazzy#1180]
I get below error messages when I try to generate jazzy docs using the command,
`jazzy --swift-version 4.2 --min-acl internal`

Error message:
**Unable to find an Xcode with Swift version 4.2. (RuntimeError)**

**Note**: I'm using XCode 11.4. Jazzy generates doc seamlessly on Swift 5 projects. When I try to generate do for my project which is on Swift 4.2, it's throwing above error.

Complete log from the terminal after running `jazzy --swift-version 4.2 --min-acl internal`

```
_Traceback (most recent call last):
	8: from /Users/.rvm/gems/ruby-2.7.0/bin/ruby_executable_hooks:24:in `<main>'
	7: from /Users/.rvm/gems/ruby-2.7.0/bin/ruby_executable_hooks:24:in `eval'
	6: from /Users/.rvm/gems/ruby-2.7.0/bin/jazzy:23:in `<main>'
	5: from /Users/.rvm/gems/ruby-2.7.0/bin/jazzy:23:in `load'
	4: from /Users/.rvm/gems/ruby-2.7.0/gems/jazzy-0.13.2/bin/jazzy:15:in `<top (required)>'
	3: from /Users/.rvm/gems/ruby-2.7.0/gems/jazzy-0.13.2/lib/jazzy/doc_builder.rb:76:in `build'
	2: from /Users/.rvm/gems/ruby-2.7.0/gems/jazzy-0.13.2/lib/jazzy/doc_builder.rb:76:in `chdir'
	1: from /Users/.rvm/gems/ruby-2.7.0/gems/jazzy-0.13.2/lib/jazzy/doc_builder.rb:78:in `block in build'
/Users/.rvm/gems/ruby-2.7.0/gems/jazzy-0.13.2/lib/jazzy/sourcekitten.rb:259:in `run_sourcekitten': Unable to find an Xcode with swift version 4.2. (RuntimeError)_
```

**Comment by johnfairh** [comment]
Xcode 11.4 supports Swift 4.2 so you don't need to use any special flags as long as `xcodebuild` correctly builds your project.

**Comment by johnfairh** [comment]
Closing, answered.
