### ISSUE TITLE
[Ruby 2.7] Warning - URI.escape is obsolete

### ISSUE THREAD

**Issue by Kaspik** [realm/jazzy#1185]
Opening as issue based on comment by @johnfairh here: https://github.com/realm/jazzy/commit/d91ba7e27b60a927df83c718376bc54157193a46

## Issue:
`/Users/kaspik/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/jazzy-0.13.3/lib/jazzy/doc_builder.rb:381: warning: URI.escape is obsolete`

**Comment by Kaspik** [comment]
Just FYI - this method is deprecated for almost 10 years (just as an alias) - https://docs.knapsackpro.com/2020/uri-escape-is-obsolete-percent-encoding-your-query-string

**Comment by johnfairh** [comment]
Fixed in master via #1197.
