### ISSUE TITLE
The Dash docset URL is incorrect

### ISSUE THREAD

**Issue by sindresorhus** [realm/jazzy#1188]
Jazzy config: https://github.com/sindresorhus/KeyboardShortcuts/blob/a1550ae2c7fc96e07648cc045855eb89ab621b87/.jazzy.yml

I think it's because I upload the docs to a sub-path: https://sindresorhus.com/KeyboardShortcuts/ (not visible as I'm hiding it for now with JavaScript)

The Dash feed URL ends up being `dash-feed://https%3A%2F%2Fsindresorhus%2Ecom%2Fdocsets%2FKeyboardShortcuts%2Exml`, where the URL decoded is `https://sindresorhus.com/docsets/KeyboardShortcuts.xml`, while it should have been `https://sindresorhus.com/KeyboardShortcuts/docsets/KeyboardShortcuts.xml`. The URL in the XML is also incorrect.

I tried setting `dash_url: https://sindresorhus.com/KeyboardShortcuts/docsets/KeyboardShortcuts.xml`, but that didn't help.

**Comment by johnfairh** [comment]
Thanks - looks like this has never worked when there's a path component in the URL ([Yikes](https://www.honeybadger.io/blog/why-is-uri-join-so-counterintuitive/)).

**Comment by sindresorhus** [comment]
Thanks for looking into this. I'll just wait until this is properly fixed. The Dash link is not important for me and my current workaround works fine for now.

**Comment by johnfairh** [comment]
Fixed in master via #1197.
