### ISSUE TITLE
Support GitHub relative image URLs

### ISSUE THREAD

**Issue by sindresorhus** [realm/jazzy#1189]
I'm used to be able to use relative image URLs for readme's on GitHub. It would be nice if Jazzy would handle those. Currently, I'm getting broken images when the repo readme is rendered on the generated doc website.

These formats:

- `![](image.png)`
- `<img src="image.png">`

**Comment by johnfairh** [comment]
If I understand correctly: I think both those formats render fine in the generated html.  But there's no way today to tell jazzy about media that needs to be included in the docs, you'll need to copy the files in manually.

**Comment by sindresorhus** [comment]
Ideally, Jazzy would see that there are relative images referenced and copy those correctly.

Another solution would be to automatically expand relative URLs to the absolute raw GitHub URL for the assets when `github_url` is set.

**Comment by johnfairh** [comment]
Ok, I did understand.  Dup #843.

**Comment by sindresorhus** [comment]
I think you linked to the wrong issue.
