### ISSUE TITLE
How to ignore Other Classes, Other function from Jazzy Report.

### ISSUE THREAD

**Issue by amolpict** [realm/jazzy#1193]
I ran the Jazzy command on iOS project and report is generated but report size is too much. Around 1.5 GB.

I have defined **custom_categories** in .**yml** file and want report for those sections only. But I see Other Classes, Other function etc created which I don't want.
I want to ignore Other Classes, Other function etc. which jazzy provides default in report and there  classes to reduce the size of report.

Any one has idea on same ?

**Comment by johnfairh** [comment]
The features for this are listed under 'Controlling what is documented' in the [readme](https://github.com/realm/jazzy).

**Comment by amolpict** [comment]
Closing the issue as I don't need this thing to implement.
