### ISSUE TITLE
Generating documentation for multiple SPM modules

### ISSUE THREAD

**Issue by MortenGregersen** [realm/jazzy#1194]
I have a SPM package with multiple libraries. I want to generate documentation for the types in all the libraries (1 main library and 2 support libraries for testing and SwiftUI bindings).

I thought I could just run the `jazzy` command with a wildcard `--include=` but it only takes the files from the specified module.

`jazzy --module Fluxor --swift-build-tool spm --include="Sources/FluxorSwiftUI/*.swift"`

How do I generate documentation for types in all the libraries in my package?

**Comment by johnfairh** [comment]
You'll have to grab each module separately then merge them:
```shell
sourcekitten doc --spm --module-name Module1 > mod1.json
sourcekitten doc --spm --module-name Module2 > mod2.json
sourcekitten doc --spm --module-name Module3 > mod3.json
jazzy --sourcekitten-sourcefile mod1.json,mod2.json,mod3.json
```

**Comment by MortenGregersen** [comment]
Thanks! It works 👍
