### ISSUE TITLE
Documented swift protocol and struct are reported undocumented

### ISSUE THREAD

**Issue by MortenGregersen** [realm/jazzy#1195]
I have documentation for every public symbol in my project, but jazzy reports that a protocol (´Interceptor`) and a struct (`Reducer`) are undocumented. In the output the types also show as undocumented.

I've included the contents of undocumented.json and the first 10 lines of the two files mentioned.

How do I get jazzy to recognize the documentation?

Interceptor.swift:
```swift
/**
 * Fluxor
 *  Copyright (c) Morten Bjerg Gregersen 2020
 *  MIT license, see LICENSE file for details
 */

/// A type which intercepts all `Action`s and the  `State` changes happening in a `Store`.
public protocol Interceptor {
    /// The type of `State` the `Interceptor` will get.
    associatedtype State
```

Reducer.swift:
```swift
/**
 * Fluxor
 *  Copyright (c) Morten Bjerg Gregersen 2020
 *  MIT license, see LICENSE file for details
 */

/// A type which takes a `State` and `Action` returns a new `State`.
public struct Reducer<State> {
    /// A pure function which takes the a `State` and an `Action` and returns a new `State`.
    public let reduce: (inout State, Action) -> Void
```

undocumented.json:
```json
{
  "warnings": [
    {
      "file": "/Users/morten/Fluxor/Sources/Fluxor/Interceptor.swift",
      "line": 8,
      "symbol": "Interceptor",
      "symbol_kind": "source.lang.swift.decl.protocol",
      "warning": "undocumented"
    },
    {
      "file": "/Users/morten/Fluxor/Sources/Fluxor/Reducer.swift",
      "line": 8,
      "symbol": "Reducer",
      "symbol_kind": "source.lang.swift.decl.struct",
      "warning": "undocumented"
    }
  ],
  "source_directory": "/Users/morten/Fluxor"
}
```

**Comment by johnfairh** [comment]
You can tell this is a Swift bug because the doc comment does not appear in Xcode Quick Help.

Workaround is to stop encoding the file header block comment as a doc comment ('/**' intro) -- it's not a doc comment and that is confusing things.  Or insert something like an `import` or an empty non-doc-comment between the two.

[SR-6605](https://bugs.swift.org/browse/SR-6605) that I should probably do something with if only unassign...

**Comment by MortenGregersen** [comment]
Thank you @johnfairh. It works when I changed the header block to use '/*'
