### ISSUE TITLE
Vulnerability analysis upset about jquery below 3.5.0

### ISSUE THREAD

**Issue by Tyler-Keith-Thompson** [realm/jazzy#1196]
So several vulnerability scanning tools are flagging my documentation with a vulnerability because jazzy generation is using an older version of JQuery.

To repro simply use: https://owasp.org/www-project-dependency-check/ once documentation is generated

It reports the issue reliably

**Comment by johnfairh** [comment]
Fixed in master; will try to find time to do a release in the next few days.  In the interim you can drop in the latest jQuery from upstream if you need.
