### ISSUE TITLE
Support multiple modules/targets

### ISSUE THREAD

**Issue by DanielCardonaRojas** [realm/jazzy#1199]
Is there a way to document a project with more than one target ? 

I passed multiple target arguments to xcodebuild_arguments and the generated documentation did not include docs from those targets.

**Comment by johnfairh** [comment]
You'll need to generate each module separately then merge - see #1194 for outline.

**Comment by DanielCardonaRojas** [comment]
Thanks works great! 

It would be nice if classes/structs/enums could include some information about the target they belonged to, as this information is lost on merge.

**Comment by johnfairh** [comment]
You're completely right; I should have explained this is an ad-hoc workaround -- Jazzy itself doesn't understand multiple modules per docset, which means that you can't tell what module a thing come from, cross-module extensions are not clear, and types that share names in separate modules get merged (or worse).  #564 is the tracker for adding this as a full feature.

**Comment by 1ec5** [comment]
Depending on whether the modules have any interdependencies, you might be able to create a fake CocoaPods podspec for a combined module and run jazzy over that podspec instead of your normal project.
