### ISSUE TITLE
Generate docsets for Xcode

### ISSUE THREAD

**Issue by jpsim** [realm/jazzy#120]

**Comment by istx25** [comment]
What's the status on this? From my understanding this has already been completed?

**Comment by 1ec5** [comment]
No, jazzy doesn't generate Xcode docsets yet.

**Comment by istx25** [comment]
My apologies. Thanks for the response @1ec5. Misunderstood.

**Comment by jpsim** [comment]
@istx25 note the difference between a "Dash" docset and an Xcode docset. They're different formats.

**Comment by istx25** [comment]
Yup! My apologies.

**Comment by 1ec5** [comment]
appledoc splits the Xcode docset generation process into three steps:

https://github.com/tomaz/appledoc/blob/12dd17471508624bd9d0b0006aa5d9da9959cc0f/Generating/GBDocSetOutputGenerator.m
https://github.com/tomaz/appledoc/blob/12dd17471508624bd9d0b0006aa5d9da9959cc0f/Generating/GBDocSetInstallGenerator.m
https://github.com/tomaz/appledoc/blob/12dd17471508624bd9d0b0006aa5d9da9959cc0f/Generating/GBDocSetPublishGenerator.m

**Comment by 1ec5** [comment]
From the [Xcode 8.3 release notes](https://developer.apple.com/library/prerelease/content/releasenotes/DeveloperTools/RN-Xcode/Chapters/Introduction.html#//apple_ref/doc/uid/TP40001051-CH1-SW160):

> 3rd party docset support is now deprecated and will no longer be supported in a future release of Xcode. (30584489)

**Comment by jpsim** [comment]
Well that keeps things simple!~
