### ISSUE TITLE
Cannot generate document using iPhone only sdk

### ISSUE THREAD

**Issue by phongle-wgu** [realm/jazzy#1203]
I've been trying to get document generate with only using the iPhone SDK. My project is just a swift package that has code that reference UIFont. Ive been running this but it seems like the macOS sdk is ran against it when I look at the logs. 

`jazzy --sdk iphoneos`

**Comment by johnfairh** [comment]
The `--sdk` is to do with Objective-C.

You'll need to pass the same arguments that you are passing to `swift build` or `xcodebuild` to build the iPhone target using `--build-tool-arguments`.

**Comment by johnfairh** [comment]
Closing, inactive.
