### ISSUE TITLE
Unable to generate document

### ISSUE THREAD

**Issue by rehannali** [realm/jazzy#1204]
I'm unable to generate document with `jazzy`. It always throw me error about bridging header.
My project compile with fastlane but got error while generating document.

### Console Logs
<details>
<pre>
❯ jazzy \
--min-acl private \
--copyright © 2020 OneLoad. All rights reserved. \
--output ./Documentation \
--author Rehan Ali \
--title OneLoad iOS App
Running xcodebuild
Could not successfully run `xcodebuild`.
Please check the build arguments.
Saved `xcodebuild` log file: /var/folders/6r/j3t_l0vs7_bbxm7ktnkkbxl80000gq/T/xcodebuild-89E5FAFB-3397-4F65-B882-D8F609B7D420.log
Failed to generate documentation
Traceback (most recent call last):
	9: from /usr/local/bin/ruby_executable_hooks:24:in `<main>'
	8: from /usr/local/bin/ruby_executable_hooks:24:in `eval'
	7: from /usr/local/bin/jazzy:23:in `<main>'
	6: from /usr/local/bin/jazzy:23:in `load'
	5: from /usr/local/lib/ruby/gems/2.7.0/gems/jazzy-0.13.4/bin/jazzy:15:in `<top (required)>'
	4: from /usr/local/lib/ruby/gems/2.7.0/gems/jazzy-0.13.4/lib/jazzy/doc_builder.rb:76:in `build'
	3: from /usr/local/lib/ruby/gems/2.7.0/gems/jazzy-0.13.4/lib/jazzy/doc_builder.rb:76:in `chdir'
	2: from /usr/local/lib/ruby/gems/2.7.0/gems/jazzy-0.13.4/lib/jazzy/doc_builder.rb:78:in `block in build'
	1: from /usr/local/lib/ruby/gems/2.7.0/gems/jazzy-0.13.4/lib/jazzy/sourcekitten.rb:266:in `run_sourcekitten'
/usr/local/lib/ruby/gems/2.7.0/gems/jazzy-0.13.4/lib/jazzy/executable.rb:36:in `execute_command': /usr/local/lib/ruby/gems/2.7.0/gems/jazzy-0.13.4/bin/sourcekitten ["doc", "--"] (RuntimeError)

Running xcodebuild

Could not successfully run `xcodebuild`.

Please check the build arguments.

Saved `xcodebuild` log file: /var/folders/6r/j3t_l0vs7_bbxm7ktnkkbxl80000gq/T/xcodebuild-89E5FAFB-3397-4F65-B882-D8F609B7D420.log

Failed to generate documentation
</pre>
</details>

### File Error
<details>
<pre>
/Users/rehanali/Documents/Development/ios/Oneload/Oneload-Bridging-Header.h:8:9: error: 'RadioButton/RadioButton.h' file not found with <angled> include; use "quotes" instead
#import <RadioButton/RadioButton.h>
        ^
1 error generated.
<unknown>:0: error: failed to emit precompiled header '/Users/rehanali/Documents/Development/ios/build/SharedPrecompiledHeaders/Oneload-Bridging-Header-swift_17QM9LPH5KFJ8-clang_1TZN70PDYP7EH.pch' for bridging header '/Users/rehanali/Documents/Development/ios/Oneload/Oneload-Bridging-Header.h'

** BUILD FAILED **

The following build commands failed:
	CompileSwift normal arm64
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(2 failures)
</pre>
</details>

I also use quotes instead of `<>` but still got error on bridging header.

**Comment by johnfairh** [comment]
The error messages are saying that `xcodebuild` is not working.  You should figure out what flags it needs to build your module and then pass them to jazzy using `--build-tool-arguments`.

**Comment by rehannali** [comment]
@johnfairh Thanks for quick reply. It fixed by providing workspace path, scheme and other flags.
