### ISSUE TITLE
what is the mean's of `-I,$(pwd)`

### ISSUE THREAD

**Issue by looseyi** [realm/jazzy#1205]
what is the `-I` stands for and pass to

**Comment by johnfairh** [comment]
Probably [this](https://clang.llvm.org/docs/ClangCommandLineReference.html#include-path-management)?

**Comment by looseyi** [comment]
great, and thanks.
yesterday, i found [-fmoudles](https://clang.llvm.org/docs/ClangCommandLineReference.html#cmdoption-clang-fmodules), but don't find the `-I`

**Comment by looseyi** [comment]
@johnfairh how to recursive create docs in source directory?
once the Source folder contains another folder, the created document will not be included

**Comment by johnfairh** [comment]
Jazzy normally includes all the source files in the module / `#include` hierarchy.  If you post an example where this isn't happening then I can take a look.

**Comment by looseyi** [comment]
here is the [Demo](https://github.com/looseyi/Cocoa-Documentation-Example),
i generate by Pods.project, or you can use AFNetworking's repo
![WechatIMG12.png](http://ww1.sinaimg.cn/large/8157560cly1gfyzo504r8j212s0h0gql.jpg)
the problem is that we can't generate the UIKit+AFNetworking folder's files

```
$ lib_name=AFNetworking
lib_path=$(pwd)/Pods/$lib_name
umbrella_header="$lib_path/$lib_name/$lib_name-umbrella.h"
sdk_path=`xcrun --show-sdk-path --sdk iphonesimulator`

bundle exec jazzy -o docs/$lib_name \
--objc \
--sdk iphoneos \
--build-tool-arguments \
--objc,$umbrella_header,--,-x,objective-c,-isysroot,$sdk_path,-I,$lib_path
```

here is what im doing https://juejin.im/post/5ef0bc8ae51d45741709b21b

**Comment by johnfairh** [comment]
After cloning and `pod install` the command looks to be:

```shell
jazzy --objc --sdk iphonesimulator --framework-root Pods/AFNetworking --umbrella-header Pods/Target\ Support\ Files/AFNetworking/AFNetworking-umbrella.h
```

It seems to include everything properly.
![Screenshot 2020-06-22 at 18 17 12](https://user-images.githubusercontent.com/26768470/85316424-a5620980-b4b4-11ea-8cd8-34de720fafc2.png)

**Comment by johnfairh** [comment]
Closing, answered.
