### ISSUE TITLE
Xcode Build

### ISSUE THREAD

**Issue by mikeKane** [realm/jazzy#1208]
Does Jazzy have to build the entire project in order to parse docs? I'd rather it skipped the build phase as my CI has already done this for all relevant schemes.

**Comment by johnfairh** [comment]
(I was sure I'd replied to this already but obviously not -- sorry about the delay.)

Jazzy needs a build of the module that is being documented -- this can be a no-op incremental build though.  If you are using `xcodebuild` then you may be able to pass flags to build just the module target in question, or to have `xcodebuild` reuse the DerivedData build products.  In Xcode 12 / Swift 5.3 we should be able to build some documentation directly from a `.swiftmodule`.

**Comment by mikeKane** [comment]
No worries thanks for your reply!

How can we build docs from the .swiftmodule?

I would like to call jazzy after I build from my ci as a post script

**Comment by johnfairh** [comment]
PR #1171 will add `.swiftmodule` support with Swift 5.3.

**Comment by mikeKane** [comment]
🕺🏼 🕺🏼 🕺🏼

Thank you!!

**Comment by johnfairh** [comment]
Closing, answered.
