### ISSUE TITLE
Document generation using Jazzy for Swift

### ISSUE THREAD

**Issue by RanjithApps11** [realm/jazzy#1210]
I am trying to use Jazzy in my ios swift project app will be working fine but when am trying  to generate documentation it's not working

issue

Using config file /Users/ranjith/Desktop/****/*****/.jazzy.yaml
Traceback (most recent call last):
	4: from /usr/local/bin/jazzy:23:in `<main>'
	3: from /usr/local/bin/jazzy:23:in `load'
	2: from /Library/Ruby/Gems/2.6.0/gems/jazzy-0.13.5/bin/jazzy:15:in `<top (required)>'
	1: from /Library/Ruby/Gems/2.6.0/gems/jazzy-0.13.5/lib/jazzy/config.rb:464:in `parse!'
/Library/Ruby/Gems/2.6.0/gems/jazzy-0.13.5/lib/jazzy/config.rb:522:in `parse_config_file': undefined method `each' for nil:NilClass (NoMethodError)

**Comment by johnfairh** [comment]
Looks like there’s a problem with the config file — if you can’t see what’s wrong with the YAML then you can post it here.

**Comment by RanjithApps11** [comment]
Please provide any documentation for integrating jazzy in my ios swift project

**Comment by johnfairh** [comment]
See the readme; if you have a specific question then please ask.

**Comment by johnfairh** [comment]
Closing, inactive.
