### ISSUE TITLE
XCode auto generated triple slash comments for Obj-C cause raw header output in jazzy docs

### ISSUE THREAD

**Issue by dpanzer** [realm/jazzy#1215]
This may be a silly question but I've searched the issues at length here and can't seem to find anything about this. At least as of XCode 11, the automatic documentation style (i.e. when you press `Cmd + Opt + /`) used for Obj-C is the triple slash style (I think this used to not be the case? Wasn't it previously the `/* .... */` block style?). So with a method documented as follows:

```
/// This is a method description
/// @param myParam This describes my parameter
- (void)myMethod:(NSInteger)myParam;
```

When I run jazzy with `objc=true`, it parses the comments correctly but *also* for some reason outputs the entire raw header file on top of the structured docs like so:

![image](https://user-images.githubusercontent.com/1000133/89492940-d5bde880-d780-11ea-9110-676302b8c609.png)

Any idea what is going on here? Thanks

**Comment by johnfairh** [comment]
I'm not sure about the Xcode default doc-comment format.

The thing you're seeing here is fixed by putting a doc-comment (can be empty) on the `@interface MyClass` declaration -- this has some effect on how libclang reports AST info back to us.

**Comment by dpanzer** [comment]
Thanks @johnfairh this worked!
