### ISSUE TITLE
Help with piping output into an S3 bucket

### ISSUE THREAD

**Issue by WilliamKatz** [realm/jazzy#1216]
I am trying to automate this process so that my team can upload the output of jazzy to a static S3 bucket.   

```
#!/usr/bin/env ruby

require 'bundler/inline'

gemfile do
    source 'https://rubygems.org'
    gem 'jazzy', '~> 0.13.5'
end

require 'jazzy'

puts 'Gems installed and loaded!'
puts Jazzy::VERSION

config = Jazzy::Config.instance = Jazzy::Config.parse!
#config.command_line = ["-sdk","exampleSDK","-project","Example.xcodeproj","-scheme","ExampleScheme"]
Jazzy::DocBuilder.build(config)
```

I need to pass in flags for the xcodebuild command or else the build fails.

Afterwards, ill upload each file in the doc to the S3 bucket. 

Im open to suggestions, this just seemed like a straightforward way to accomplish this task.

**Comment by johnfairh** [comment]
If you're asking _how_ to pass args into jazzy when invoking it this way and you don't want to use a config file, you could change `ARGV` around the `Config#parse` call:
```ruby
ARGV.clear()
ARGV.append(["-sdk","exampleSDK","-project","Example.xcodeproj","-scheme","ExampleScheme"])
```

If you're asking something else then please try again!

**Comment by WilliamKatz** [comment]
Hi, that is exactly what I was asking, thanks for parsing that out.

So I tried what you suggested but each time I got the same error that makes it seem like the arguments re not being passed in.  

### Code
```
config = Jazzy::Config.instance = Jazzy::Config.parse!
ARGV.clear()
ARGV.append(["-sdk","exampleSDK","-project","Example.xcodeproj","-scheme","ExampleScheme"])
Jazzy::DocBuilder.build(config)
```
and 
```
ARGV.clear()
config = Jazzy::Config.instance = Jazzy::Config.parse!
ARGV.append(["-sdk","exampleSDK","-project","Example.xcodeproj","-scheme","ExampleScheme"])
Jazzy::DocBuilder.build(config)
```
and 
```
ARGV.clear()
ARGV.append(["-sdk","exampleSDK","-project","Example.xcodeproj","-scheme","ExampleScheme"])
config = Jazzy::Config.instance = Jazzy::Config.parse!
Jazzy::DocBuilder.build(config)
```

### Error
```/Library/Ruby/Gems/2.6.0/gems/jazzy-0.13.5/lib/jazzy/executable.rb:36:in `execute_command': /Library/Ruby/Gems/2.6.0/gems/jazzy-0.13.5/bin/sourcekitten ["doc", "--"] (RuntimeError)```

**Comment by johnfairh** [comment]
This is the correct form because `ARGV` access happens inside `parse!`:
```ruby
ARGV.clear()
ARGV.append(["-sdk","exampleSDK","-project","Example.xcodeproj","-scheme","ExampleScheme"])
config = Jazzy::Config.instance = Jazzy::Config.parse!
Jazzy::DocBuilder.build(config)
```

But - my fault for not paying attention - you need to pass args as though to the jazzy CLI, which those guys are not, they're `xcodebuild` args.  So you want something like:
```ruby
ARGV.clear()
ARGV.append(["--build-tool-flags","-sdk,exampleSDK,-project,Example.xcodeproj,-scheme,ExampleScheme"])
config = Jazzy::Config.instance = Jazzy::Config.parse!
Jazzy::DocBuilder.build(config)
```

Can try it out line-by-line in `irb` and see what is happening.

**Comment by WilliamKatz** [comment]
So I ended up using the config file `.jazzy.yaml` because the arguments were not being passing properly.  Im not a ruby expert, so reading the source code is tough for me. 

For future reference my .jazzy.yaml file looks like:

xcodebuild_arguments:
 - -sdk
 - iphonesimulator
 - -project
 - Example.xcodeproj
 - -scheme
 - ExampleScheme
