### ISSUE TITLE
Meta description

### ISSUE THREAD

**Issue by vaind** [realm/jazzy#1217]
Is there a way to specify/configure generation of `<meta name="description" content="...">` for each generated page? Looking for this to include a good description to show in search engines.

**Comment by johnfairh** [comment]
You can use `--head` to inject the same fixed string into all pages' `<head>` blocks.

If you're thinking about changing the content of the tags on a per-page basis to reflect the content then no, there's no way to do that today -- it could be an interesting feature to explore, maybe allowing the `--head` to support string substitution with some built-in variables generated from the page itself.

**Comment by vaind** [comment]
> If you're thinking about changing the content of the tags on a per-page basis to reflect the content 

Yes, that's what I'm trying to do. Have `<meta name="description"` with the content corresponding to each page.

Thanks for the answer, I see I'd have to have a script that updates generated `.html` files to accomplish what I need.
