### ISSUE TITLE
Tag rewriting script suitable for Jazzy

### ISSUE THREAD

**Issue by rashenoy** [realm/jazzy#1218]
Not an issue with Jazzy per say, but more of necessity for some kind of helper. Existing project is in Objc. Current documentation consists of tags that are not just limited to the ones allowed by Jazzy. Is there any script/utility/helper with which the documentation headers can be pre-processed so the out maybe directly compiled with Jazzy ?

**Comment by johnfairh** [comment]
Nothing special I'm aware of.  The existing objc tag mapping happens [here](https://github.com/jpsim/SourceKitten/blob/88740765af9142c2d904a23384045ec4a37dd8c2/Source/SourceKittenFramework/Clang%2BSourceKitten.swift#L187) if you're interested in augmenting it, see [this pr](https://github.com/jpsim/SourceKitten/pull/632) for an example.

**Comment by johnfairh** [comment]
Closing, answered.
