### ISSUE TITLE
Two problems running jazzy on multi-module Swift Package

### ISSUE THREAD

**Issue by rudifa** [realm/jazzy#1219]
**Problems:**

While learning the ways of Swift Packages and of jazzy docs, I came across the package [Burritos](https://github.com/guillermomuntaner/Burritos) which contains 13 modules, but none of them named `Burritos`.

```
Burritos % jazzy
...
Could not find SPM module 'Burritos'. Here are the modules available:
...
Failed to generate documentation
```

Now, after I add a small module/target named `Burritos` to the package, **jazzy** does generate the documentation for a single module, whichever is the first listed in the `Package.swift`.

**Workaround:**

Following the advice by @johnfairh  in Issue #1194 I wrote a quick-and-dirty script below which solves both issues and successfully generated the docs for `Burritos`.

**Suggestion**

It would be nice to add to **sourcekitten** a function returning the list of modules in a Swift Package, and use it in **jazzy** to loop over the list and generate the combined docs.

```
#!/usr/bin/ruby

# generate jazzy docs for a multi-module Swift Package
# ⓒ 2020 Rudi Farkas @rudifa

def ensure_file_exists(filepath)
    if (!File.exist?(filepath))
        puts '*** file ' + filepath + ' not found'
        exit(1) 
    end
end

def ensure_command_exists(command)
    `which #{command}`
    if (!$?.success?)
        puts '*** command ' + command + ' not found'
        exit(1) 
    end
end

def remove_dir(path)
    if File.directory?(path)
        Dir.foreach(path) do |file|
            puts file
            if ((file.to_s != ".") and (file.to_s != ".."))
                remove_dir("#{path}/#{file}")
            end
        end
        Dir.delete(path)
    else
        File.delete(path) if File.exist?(path)
    end
end

def create_clean_dir(dir_path)
    remove_dir(dir_path)
    Dir.mkdir(dir_path)
end


def spm_module_names()
    lines = File.readlines(".build/debug.yaml").grep /#{'module-name:'}/i
    names = []
    lines.each do |line|
        names.append(/module-name: \"(\w+)\"/.match(line)[1])
    end
    names
end

###

ensure_command_exists('jazzy')
ensure_command_exists('sourcekitten')
ensure_file_exists('Package.swift')
ensure_file_exists('.build/debug.yaml')

lines = File.readlines(".build/debug.yaml").grep /#{'module-name:'}/i

puts lines.count

modules = spm_module_names()
puts modules.count

tempdir = '.jazzy_temp'

create_clean_dir(tempdir)

filepaths = []
modules.each do |modul|
    filepath = "#{tempdir}/#{modul}.json"
    jsonText = `sourcekitten doc --spm --module-name #{modul}`
    File.write(filepath, jsonText)
    puts filepath
    filepaths.append(filepath)
end

filepaths_joined = filepaths.join(",")
puts filepaths_joined

`jazzy --clean --sourcekitten-sourcefile #{filepaths_joined}` 

remove_dir('.jazzy_temp')

puts 'OK'


```

**Comment by johnfairh** [comment]
The bad default value for `--module` is being picked up from the `Burritos.podspec`.  I don't like the way jazzy does this but it's always done this & when we accidentally broke it people saw a variety of bad consequences due to unknowingly relying on it.

Using the podspec -- `jazzy --podspec Burritos.podspec` eventually generates one site covering all the files.

**Comment by johnfairh** [comment]
Closing this now, answered/inactive -- in general it's not safe to combine multiple modules like this in jazzy: it doesn't understand multiple modules per docset, which means that you can't tell what module a thing come from, cross-module extensions are not clear, and types that share names in separate modules get merged (or worse). #564 is the tracker for adding this as a full feature.
