### ISSUE TITLE
0.11.2 works, but 0.13.5 does not. Is this due to the code signing bug?

### ISSUE THREAD

**Issue by Mozahler** [realm/jazzy#1220]
Hi. Love my jazzy 🎶

I was surprised this morning that my jazzy is so out-dated (0.11.2), so I installed the latest version via gems (0.13.5)
But when I tried using it on a couple of projects the version fails every time. I removed the new version and tried again with the older version and everything works fine.

> Running xcodebuild
> Could not successfully run `xcodebuild`.
> Please check the build arguments.
> Saved `xcodebuild` log file: /var/folders/by/cr9r24wn2fn47wpyjnrq73qc0000gn/T/xcodebuild-1725ACAF-548E-415D-A5CF-2DC4700A71BE.log
> Failed to generate documentation
> Traceback (most recent call last):
> 	7: from /Users/Alex/.rvm/gems/ruby-2.6.1/bin/jazzy:23:in `<main>'
> 	6: from /Users/Alex/.rvm/gems/ruby-2.6.1/bin/jazzy:23:in `load'
> 	5: from /Users/Alex/.rvm/gems/ruby-2.6.1/gems/jazzy-0.13.5/bin/jazzy:15:in `<top (required)>'
> 	4: from /Users/Alex/.rvm/gems/ruby-2.6.1/gems/jazzy-0.13.5/lib/jazzy/doc_builder.rb:76:in `build'
> 	3: from /Users/Alex/.rvm/gems/ruby-2.6.1/gems/jazzy-0.13.5/lib/jazzy/doc_builder.rb:76:in `chdir'
> 	2: from /Users/Alex/.rvm/gems/ruby-2.6.1/gems/jazzy-0.13.5/lib/jazzy/doc_builder.rb:78:in `block in build'
> 	1: from /Users/Alex/.rvm/gems/ruby-2.6.1/gems/jazzy-0.13.5/lib/jazzy/sourcekitten.rb:266:in `run_sourcekitten'
> /Users/Alex/.rvm/gems/ruby-2.6.1/gems/jazzy-0.13.5/lib/jazzy/executable.rb:36:in `execute_command': /Users/Alex/.rvm/gems/ruby-2.6.1/gems/jazzy-0.13.5/bin/sourcekitten ["doc", "--", "-target", "One", "-sdk", "iphoneos"] (RuntimeError)
> 
> Running xcodebuild
> 
> Could not successfully run `xcodebuild`.
> 
> Please check the build arguments.
> 
> Saved `xcodebuild` log file: /var/folders/by/cr9r24wn2fn47wpyjnrq73qc0000gn/T/xcodebuild-1725ACAF-548E-415D-A5CF-2DC4700A71BE.log
> 
> Failed to generate documentation

I  can provide more information if you need it, just let me know what is required. 
**Perhaps the solution is obvious to someone already?**  

Here's the beginning of the contents of the output:

cat /var/folders/by/cr9r24wn2fn47wpyjnrq73qc0000gn/T/xcodebuild-1725ACAF-548E-415D-A5CF-2DC4700A71BE.log
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -target One -sdk iphoneos

Build settings from command line:
    SDKROOT = iphoneos13.7

Resolve Package Graph

Resolved source packages:
  swift-composable-architecture: https://github.com/pointfreeco/swift-composable-architecture.git @ 0.8.0
  combine-schedulers: https://github.com/pointfreeco/combine-schedulers @ 0.1.2
  Realm: https://github.com/realm/realm-cocoa.git @ 5.3.3
  RealmCore: https://github.com/realm/realm-core @ 6.0.14
  swift-case-paths: https://github.com/pointfreeco/swift-case-paths @ 0.1.2

note: Using new build system
note: Planning build
note: Constructing build description
CompileC /Users/Alex/Library/Developer/Xcode/DerivedData/One-dradzpqnuhxgvxahzqajcplwwpwf/SourcePackages/checkouts/realm-cocoa/build/Realm.build/Release-iphoneos/Realm.build/Objects-normal/arm64/object_notifier.o /Users/Alex/Library/Developer/Xcode/DerivedData/One-dradzpqnuhxgvxahzqajcplwwpwf/SourcePackages/checkouts/realm-cocoa/Realm/ObjectStore/src/impl/object_notifier.cpp normal arm64 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'Realm' from project 'Realm')
    cd /Users/Alex/Library/Developer/Xcode/DerivedData/One-dradzpqnuhxgvxahzqajcplwwpwf/SourcePackages/checkouts/realm-cocoa
    export LANG=en_US.US-ASCII
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x c++ -target arm64-apple-ios11.0 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=c++1z -fmodules -gmodules -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/var/folders/by/cr9r24wn2fn47wpyjnrq73qc0000gn/C/org.llvm.clang/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror=non-modular-include-in-framework-module -fmodule-name=Realm -Wno-trigraphs -fpascal-strings -Os -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-return-type -Wno-non-virtual-dtor -Wno-overloaded-virtual -Wno-exit-time-destructors -Wno-missing-braces -Wparentheses -Wswitch -Wno-unused-function -Wno-unused-label -Wno-unused-parameter -Wno-unused-variable -Wunused-value -Wno-empty-body -Wno-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wno-constant-conversion -Wno-int-conversion -Wno-bool-conversion -Wno-enum-conversion -Wno-float-conversion -Wno-non-literal-null-conversion -Wno-objc-literal-conversion -Wshorten-64-to-32 -Wno-newline-eof -Wno-c++11-extensions -DSWIFT_PACKAGE -DREALM_SPM=1 -DREALM_COCOA_VERSION=@\"5.3.3\" -DREALM_VERSION=\"6.0.14\" -DREALM_NO_CONFIG -DREALM_INSTALL_LIBEXECDIR= -DREALM_ENABLE_ASSERTIONS=1 -DREALM_ENABLE_ENCRYPTION=1 -DREALM_VERSION_MAJOR=6 -DREALM_VERSION_MINOR=0 -DREALM_VERSION_PATCH=14 -DREALM_VERSION_EXTRA=\"\" -DREALM_VERSION_STRING=\"6.0.14\" -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.7.sdk -fstrict-aliasing -Wdeprecated-declarations -Winvalid-offsetof -g -fvisibility-inlines-hidden -Wno-sign-conversion -Wno-infinite-recursion -Wno-move -Wno-comma -Wno-block-capture-autoreleasing -Wno-strict-prototypes -Wno-range-loop-analysis -Wno-semicolon-before-method-body -fembed-bitcode-marker -I/Users/Alex/Library/Developer/Xcode/DerivedData/One-dradzpqnuhxgvxahzqajcplwwpwf/SourcePackages/checkouts/realm-core/src -I/Users/Alex/Library/Developer/Xcode/DerivedData/One-dradzpqnuhxgvxahzqajcplwwpwf/SourcePackages/checkouts/realm-cocoa/build/Release-iphoneos/include -I/Users/Alex/Library/Developer/Xcode/DerivedData/One-dradzpqnuhxgvxahzqajcplwwpwf/SourcePackages/checkouts/realm-cocoa/include -I/Users/Alex/Library/Developer/Xcode/DerivedData/One-dradzpqnuhxgvxahzqajcplwwpwf/SourcePackages/checkouts/realm-cocoa -I/Users/Alex/Library/Developer/Xcode/DerivedData/One-dradzpqnuhxgvxahzqajcplwwpwf/SourcePackages/checkouts/realm-cocoa/include -I/Users/Alex/Library/Developer/Xcode/DerivedData/One-dradzpqnuhxgvxahzqajcplwwpwf/SourcePackages/checkouts/realm-cocoa/Realm/ObjectStore/src -I/Users/Alex/Library/Developer/Xcode/DerivedData/One-dradzpqnuhxgvxahzqajcplwwpwf/SourcePackages/checkouts/realm-cocoa/build/Realm.build/Release-iphoneos/Realm.build/DerivedSources-normal/arm64 -I/Users/Alex/Library/Developer/Xcode/DerivedData/One-dradzpqnuhxgvxahzqajcplwwpwf/SourcePackages/checkouts/realm-cocoa/build/Realm.build/Release-iphoneos/Realm.build/DerivedSources/arm64 -I/Users/Alex/Library/Developer/Xcode/DerivedData/One-dradzpqnuhxgvxahzqajcplwwpwf/SourcePackages/checkouts/realm-cocoa/build/Realm.build/Release-iphoneos/Realm.build/DerivedSources -F/Users/Alex/Library/Developer/Xcode/DerivedData/One-dradzpqnuhxgvxahzqajcplwwpwf/SourcePackages/checkouts/realm-cocoa/build/Release-iphoneos -F/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Frameworks -fmodule-map-file=/Users/Alex/Library/Developer/Xcode/DerivedData/One-dradzpqnuhxgvxahzqajcplwwpwf/SourcePackages/checkouts/realm-cocoa/build/GeneratedModuleMaps/iphoneos/RealmCore.modulemap -DXcode -MMD -MT dependencies -MF /Users/Alex/Library/Developer/Xcode/DerivedData/One-dradzpqnuhxgvxahzqajcplwwpwf/SourcePackages/checkouts/realm-cocoa/build/Realm.build/Release-iphoneos/Realm.build/Objects-normal/arm64/object_notifier.d --serialize-diagnostics /Users/Alex/Library/Developer/Xcode/DerivedData/One-dradzpqnuhxgvxahzqajcplwwpwf/SourcePackages/checkouts/realm-cocoa/build/Realm.build/Release-iphoneos/Realm.build/Objects-normal/arm64/object_notifier.dia -c /Users/Alex/Library/Developer/Xcode/DerivedData/One-dradzpqnuhxgvxahzqajcplwwpwf/SourcePackages/checkouts/realm-cocoa/Realm/ObjectStore/src/impl/object_notifier.cpp -o /Users/Alex/Library/Developer/Xcode/DerivedData/One-dradzpqnuhxgvxahzqajcplwwpwf/SourcePackages/checkouts/realm-cocoa/build/Realm.build/Release-iphoneos/Realm.build/Objects-normal/arm64/object_notifier.o
fatal error: module map file '/Users/Alex/Library/Developer/Xcode/DerivedData/One-dradzpqnuhxgvxahzqajcplwwpwf/SourcePackages/checkouts/realm-cocoa/build/GeneratedModuleMaps/iphoneos/RealmCore.modulemap' not found
warning: Could not read serialized diagnostics file: Cannot Load File: Failed to open diagnostics file (in target 'Realm' from project 'Realm')

**Comment by johnfairh** [comment]
This is saying that `xcodebuild -target One -sdk iphoneos` is failing; you'll need to experiment and figure out what extra flags you need to pass.

Probably why this has happened to your project now:
- Some time ago (early 2018?) a bug crept in meaning we could ignore xcodebuild errors
- Depending on the kind of error you might not see any problems, or get a couple of broken declarations, or get completely empty docs
- This bug got fixed in jazzy 0.13.something

**Comment by johnfairh** [comment]
Closing, answered.
