### ISSUE TITLE
Jazzy document generation fails for Swift Package with UIKit

### ISSUE THREAD

**Issue by ios-fun-dev** [realm/jazzy#1222]
I am trying to generate documentation for my Swift Package which uses `UIKit` for iOS using *jazzy* by executing the below command:

`jazzy --min-acl internal --clean --author "MyTeam" --copyright "© Me" --module-version "4.0.0" --swift-build-tool spm --sdk iphoneos --module MyUIKit --output docs/MyUIKit`

But I get the following error:

![Screen Shot 2020-10-15 at 11 30 53 AM](https://user-images.githubusercontent.com/22396001/96190992-072d0000-0ef8-11eb-8598-bd189dce661a.png)

I have a sample package with a similar structure to the original that I am trying to generate documents for testing. This is the current test Package.swift file:

![Screen Shot 2020-10-15 at 11 20 55 AM](https://user-images.githubusercontent.com/41760545/96172180-e30ef600-0eda-11eb-97a9-14f8a7d50013.png)

The file containing UIKit:

![Screen Shot 2020-10-15 at 11 39 46 AM](https://user-images.githubusercontent.com/41760545/96172355-26696480-0edb-11eb-8b77-6eb571ae6db6.png)

Are there any additional parameters that I need to add for generating Jazzy docs for a package with platform `.iOS(.v11)` (any version). When I add os check for UIKit and a check to see if UIKit can be imported for any code that needs UIKit, I can get the documents generated. However, since my original package has dependency on a 3rd party as well as internal package, I would need to add these as local packages and even then I am not sure if it would work.

![Screen Shot 2020-10-15 at 2 00 27 PM](https://user-images.githubusercontent.com/41760545/96187464-e8c40600-0ef1-11eb-9dfb-b51b0ee51300.png)

For my original packages, when I run jazzy (after adding the check for os and see if UIKit can be imported as in the test package), it generates the below error (although I have set the sdk to `iphoneos`): 

![Screen Shot 2020-10-15 at 2 18 45 PM](https://user-images.githubusercontent.com/41760545/96187429-d8139000-0ef1-11eb-8127-9dd57c8ad95d.png)

But when I add `.macOS(.v10_15)` in the *platforms*, then the documentation gets generated successfully (I also have to keep the check for os and see if UIKit can be imported). I am trying to figure out what is causing this issue. It seems to me like although I have set `--sdk iphoneos` it still is building for macosx by default. Is this a known issue and do I need to make any changes to my setup/files?

**Comment by johnfairh** [comment]
The `swift build` command will give you the same _no such module UIKit_ error -- as far as I know, you can't get the SwiftPM CLI to build for other targets.  So jazzy can't do it either using its Swift PM mode.

The Apple direction though seems to be to use `xcodebuild` for this kind of thing.  Somewhat counterintuitively, `xcodebuild` is capable of building from `Package.swift` (without an explicit `swift package generate-xcodeproj`).  The command you are looking for is something like:
```shell
jazzy --module MyUIKit --swift-build-tool xcodebuild --build-tool-arguments -scheme,JazzyFun,-sdk,iphoneos
```

* `--module MyUIKit` this is the Swift module to build (document) that follows the SwiftPM 'target' names
* `-scheme,JazzyFun` this is the scheme auto-generated by `xcodebuild` that seems to follow the package name -- you can check yours by doing `xcodebuild -list` in the directory containing the `Package.swift`.

**Comment by ios-fun-dev** [comment]
@johnfairh Thanks a lot for the help John! It worked when I used the config like you mentioned.
