### ISSUE TITLE
'--module-version' | 'module_version' not shown in the documentation generated

### ISSUE THREAD

**Issue by eMdOS** [realm/jazzy#1226]
I am currently using the `.yaml` file to set the jazzy configuration.

I am setting the `module_version` value but it is completely ignored.

I also tried using the CLI setting the `--module-version` param, but the result is the same.

Looking into the code seems like the `docs.rb` evaluates `config.version_configured` from `config.rb`, and apparently `version_configured` does not even exist - then the result is that "module version" value is ignored.

**Comment by johnfairh** [comment]
Maybe check you're on the latest version?  This feature gets used in the spec tests and seems to work OK there:
<img width="446" alt="Screenshot 2020-10-30 at 19 34 37" src="https://user-images.githubusercontent.com/26768470/97749483-0c3ca280-1ae7-11eb-93ad-47db7aa81dc8.png">

`Config#version_configured` is defined [here](https://github.com/realm/jazzy/blob/73329aeed2e5a2119bdb199968764ef55a511144/lib/jazzy/config.rb#L254) via some Ruby magic.

**Comment by johnfairh** [comment]
Closing, answered/inactive.
