### ISSUE TITLE
Fail to intall jazzy on Catalina 10.15.7 and Xcode 12.2

### ISSUE THREAD

**Issue by michel-blanchard** [realm/jazzy#1229]
Here is the log I get.
[mkmf.log](https://github.com/realm/jazzy/files/5565569/mkmf.log)

**Comment by johnfairh** [comment]
Xcode 12.2 has the macOS 11 (darwin20 / Big Sur) SDK but you are running macOS 10.15 (darwin19 / Catalina).

Either use an older version of Xcode (just to install jazzy, not to run it,) install a private Ruby via rvm/rbenv (or install Big Sur (kidding)).

**Comment by carolinw20** [comment]
I am experiencing a similar issue. I am also on Catalina 10.15.7 and Xcode 12.2, therefore I have universal-darwin20 instead of the required universal-darwin19. Downgrading my Xcode version or installing a private Ruby is not an option for me. Is there any other solution to this?

**Comment by johnfairh** [comment]
Just to be clear you don't need to downgrade anything, just grab Xcode 11 and select it while installing jazzy.

Apple ships Ruby in two parts, one in the OS and one in the Xcode SDK.  You need a matching pair to build Ruby extensions.  So if you can't use eg. homebrew rbenv to avoid the Apple Ruby then Xcode seems like the easiest option.

**Comment by michel-blanchard** [comment]
Installed Xcode 11.7 with the Dev Tools for that version, temporarily removed sdk for macOS 11, temporarily renamed Xcode 12 to "Xcode 12.2" with a space. Install was successful. Thank you for your help.

**Comment by Stephan-AppFabrik** [comment]
For future people:

- Downloaded Xcode 11.7 from https://developer.apple.com/download/more/
- Add Xcode 11.7 to Application folder
- (Optional: Rename them, that you know which version is which one)
- sudo gem install jazzy -n /usr/local/bin worked for me
- if not, change the selected Xcode version: $ sudo xcode-select -s /Applications/Xcode11.7.app/Contents/Developer
- sudo gem install jazzy -n /usr/local/bin should worked now
- Select new current Xcode version again: $ sudo xcode-select -s /Applications/Xcode12.4.app/Contents/Developer
- That's how it worked for me
