### ISSUE TITLE
Log File 

### ISSUE THREAD

**Issue by mcharland-ims** [realm/jazzy#1230]
Is there a way to redirect the log file to a certain location?

I'm running a build on an Azure server and it's failing with the following:

```
Running xcodebuild
Could not successfully run `xcodebuild`.
Please check the build arguments.
Saved `xcodebuild` log file: /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/xcodebuild-4AF88DF3-1D39-4B64-83FE-FC0524D811D2.log
Failed to generate documentation
/usr/local/lib/ruby/gems/2.7.0/gems/jazzy-0.13.5/lib/jazzy/executable.rb:36:in `execute_command': /usr/local/lib/ruby/gems/2.7.0/gems/jazzy-0.13.5/bin/sourcekitten ["doc", "--module-name", "TripDetectionUmbrella", "--", "-workspace", "../../SDK\\\\ Integration\\\\ Tests.xcworkspace", "-scheme", "TripDetectionUmbrella", "-sdk", "iphoneos14.2"] (RuntimeError)

Running xcodebuild

Could not successfully run `xcodebuild`.

Please check the build arguments.

Saved `xcodebuild` log file: /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/xcodebuild-4AF88DF3-1D39-4B64-83FE-FC0524D811D2.log

Failed to generate documentation
	from /usr/local/lib/ruby/gems/2.7.0/gems/jazzy-0.13.5/lib/jazzy/sourcekitten.rb:266:in `run_sourcekitten'
	from /usr/local/lib/ruby/gems/2.7.0/gems/jazzy-0.13.5/lib/jazzy/doc_builder.rb:78:in `block in build'
	from /usr/local/lib/ruby/gems/2.7.0/gems/jazzy-0.13.5/lib/jazzy/doc_builder.rb:76:in `chdir'
	from /usr/local/lib/ruby/gems/2.7.0/gems/jazzy-0.13.5/lib/jazzy/doc_builder.rb:76:in `build'
	from /usr/local/lib/ruby/gems/2.7.0/gems/jazzy-0.13.5/bin/jazzy:15:in `<top (required)>'
	from /usr/local/lib/ruby/gems/2.7.0/bin/jazzy:23:in `load'
	from /usr/local/lib/ruby/gems/2.7.0/bin/jazzy:23:in `<main>'
```

I have the verbose setting on but there isn't anything useful in the log.

I don't have access to the build server so I can't get: /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/xcodebuild-4AF88DF3-1D39-4B64-83FE-FC0524D811D2.log

**Comment by johnfairh** [comment]
It looks like that path comes from `NSTemporaryDirectory()` which is not easily hookable.  It is visible as `$TMPDIR` [overwriting this does nothing] in the shell though so maybe you could suck down that directory or copy it somewhere at the end of your job.

Or, run the xcodebuild command in your CI environment?  Start with `xcodebuild` then everything mentioned in the sourcekitten error line after the -- (maybe with fewer quotes and backslashes.)

**Comment by mcharland-ims** [comment]
Thx for the response, adding sh "cat $TMPDIR/`ls -pArt $TMPDIR | grep -v / | tail -n 1`" to the Fastfile allowed me to see the output

**Comment by johnfairh** [comment]
Closing, resolved.
