### ISSUE TITLE
I can't install, did someone see this error? 

### ISSUE THREAD

**Issue by arthurfaccioly** [realm/jazzy#1231]
**Command:**
(base) arthurfaccioly@Arthurs-MBP-2 ~ % sudo gem install jazzy
Password:
Fetching mustache-1.1.1.gem
Fetching open4-1.3.4.gem
Fetching redcarpet-3.5.0.gem
Fetching rouge-3.25.0.gem
Fetching sassc-2.4.0.gem
Fetching liferaft-0.0.6.gem
Fetching xcinvoke-0.3.0.gem
Fetching jazzy-0.13.6.gem
Successfully installed mustache-1.1.1
Successfully installed open4-1.3.4
Building native extensions. This could take a while...
ERROR:  Error installing jazzy:
	ERROR: Failed to build gem native extension.

    current directory: /Library/Ruby/Gems/2.6.0/gems/redcarpet-3.5.0/ext/redcarpet
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby -I /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0 -r ./siteconf20201128-22437-1qcc2x7.rb extconf.rb
creating Makefile

current directory: /Library/Ruby/Gems/2.6.0/gems/redcarpet-3.5.0/ext/redcarpet
make "DESTDIR=" clean

current directory: /Library/Ruby/Gems/2.6.0/gems/redcarpet-3.5.0/ext/redcarpet
make "DESTDIR="
make: *** No rule to make target `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0/universal-darwin19/ruby/config.h', needed by `autolink.o'.  Stop.

make failed, exit code 2

Gem files will remain installed in /Library/Ruby/Gems/2.6.0/gems/redcarpet-3.5.0 for inspection.
Results logged to /Library/Ruby/Gems/2.6.0/extensions/universal-darwin-19/2.6.0/redcarpet-3.5.0/gem_make.out
(base) arthurfaccioly@Arthurs-MBP-2 ~ % pwd
/Users/arthurfaccioly
(base) arthurfaccioly@Arthurs-MBP-2 ~ % exit

[Process completed]

**File gem_make.out contents:**
current directory: /Library/Ruby/Gems/2.6.0/gems/redcarpet-3.5.0/ext/redcarpet
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby -I /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0 -r ./siteconf20201128-22437-1qcc2x7.rb extconf.rb
creating Makefile

current directory: /Library/Ruby/Gems/2.6.0/gems/redcarpet-3.5.0/ext/redcarpet
make "DESTDIR=" clean

current directory: /Library/Ruby/Gems/2.6.0/gems/redcarpet-3.5.0/ext/redcarpet
make "DESTDIR="
make: *** No rule to make target `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0/universal-darwin19/ruby/config.h', needed by `autolink.o'.  Stop.

make failed, exit code 2

**Comment by johnfairh** [comment]
macOS 11 SDK + darwin19 -> #1229 ?

**Comment by johnfairh** [comment]
Closing, answered/inactive.
