### ISSUE TITLE
Could not successfully run `xcodebuild`. Failed to generate documentation

### ISSUE THREAD

**Issue by PanArtemG** [realm/jazzy#1232]
Hi! 
In one project everything worked perfectly! And he does not want this, tell me, please, what is the problem?
Requests - Please check the build arguments.
Where to check them and what are these arguments?

`artem@MacBook-Pro-Artem DealogerFSPS %  jazzy --config jazzy.yaml

Using config file /Users/artempanasenko/Developer/Work/Dealoger/DealogerFSPS/jazzy.yaml
Running xcodebuild
Could not successfully run `xcodebuild`.
Please check the build arguments.
Saved `xcodebuild` log file: /var/folders/1w/c3b0gf5j2l55vr4378wkqm580000gn/T/xcodebuild-4E888831-E94C-4E09-8223-3B4C54ED273C.log
Failed to generate documentation
Traceback (most recent call last):
	7: from /usr/local/bin/jazzy:23:in `<main>'
	6: from /usr/local/bin/jazzy:23:in `load'
	5: from /Library/Ruby/Gems/2.6.0/gems/jazzy-0.13.6/bin/jazzy:15:in `<top (required)>'
	4: from /Library/Ruby/Gems/2.6.0/gems/jazzy-0.13.6/lib/jazzy/doc_builder.rb:79:in `build'
	3: from /Library/Ruby/Gems/2.6.0/gems/jazzy-0.13.6/lib/jazzy/doc_builder.rb:79:in `chdir'
	2: from /Library/Ruby/Gems/2.6.0/gems/jazzy-0.13.6/lib/jazzy/doc_builder.rb:81:in `block in build'
	1: from /Library/Ruby/Gems/2.6.0/gems/jazzy-0.13.6/lib/jazzy/sourcekitten.rb:266:in `run_sourcekitten'
/Library/Ruby/Gems/2.6.0/gems/jazzy-0.13.6/lib/jazzy/executable.rb:36:in `execute_command': /Library/Ruby/Gems/2.6.0/gems/jazzy-0.13.6/bin/sourcekitten ["doc", "--"] (RuntimeError)

Running xcodebuild

Could not successfully run `xcodebuild`.

Please check the build arguments.

Saved `xcodebuild` log file: /var/folders/1w/c3b0gf5j2l55vr4378wkqm580000gn/T/xcodebuild-4E888831-E94C-4E09-8223-3B4C54ED273C.log

Failed to generate documentation`

**Comment by johnfairh** [comment]
First step is to read that `xcodebuild` log file -- you'll probably need some extra args to make it build your Swift module.

**Comment by PanArtemG** [comment]
@johnfairh thanks! Where to find him?

**Comment by johnfairh** [comment]
See the output you pasted in OP 😄 

> Saved xcodebuild log file: /var/folders/1w/c3b0gf5j2l55vr4378wkqm580000gn/T/xcodebuild-4E888831-E94C-4E09-8223-3B4C54ED273C.log

**Comment by PanArtemG** [comment]
@johnfairh here is what i found:

Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild CODE_SIGN_IDENTITY= CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO

Build settings from command line:
    CODE_SIGN_IDENTITY = 
    CODE_SIGNING_ALLOWED = NO
    CODE_SIGNING_REQUIRED = NO

note: Using new build system
note: Using codesigning identity override: 
note: Planning build
note: Using build description from disk
CompileC /Users/artempanasenko/Developer/Work/Dealoger/DealogerFSPS/build/FileStorageProviderService.build/Release/CNIOLinux.build/Objects-normal/x86_64/shim.o /Users/artempanasenko/Developer/Work/Dealoger/DealogerFSPS/.build/checkouts/swift-nio/Sources/CNIOLinux/shim.c normal x86_64 c com.apple.compilers.llvm.clang.1_0.compiler (in target 'CNIOLinux' from project 'FileStorageProviderService')
    cd /Users/artempanasenko/Developer/Work/Dealoger/DealogerFSPS
    export LANG\=en_US.US-ASCII
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x c -target x86_64-apple-macos10.10 -fmessage-length\=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit\=0 -fmodules -gmodules -fmodules-prune-interval\=86400 -fmodules-prune-after\=345600 -fbuild-session-file\=/var/folders/1w/c3b0gf5j2l55vr4378wkqm580000gn/C/org.llvm.clang/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror\=non-modular-include-in-framework-module -fmodule-name\=CNIOLinux -Wno-trigraphs -fpascal-strings -Os -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-return-type -Wno-missing-braces -Wparentheses -Wswitch -Wno-unused-function -Wno-unused-label -Wno-unused-parameter -Wno-unused-variable -Wunused-value -Wno-empty-body -Wno-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wno-constant-conversion -Wno-int-conversion -Wno-bool-conversion -Wno-enum-conversion -Wno-float-conversion -Wno-non-literal-null-conversion -Wno-objc-literal-conversion -Wno-shorten-64-to-32 -Wpointer-sign -Wno-newline-eof -DSWIFT_PACKAGE\=1 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk -fasm-blocks -fstrict-aliasing -Wdeprecated-declarations -g -Wno-sign-conversion -Wno-infinite-recursion -Wno-comma -Wno-block-capture-autoreleasing -Wno-strict-prototypes -Wno-semicolon-before-method-body -I/Users/artempanasenko/Developer/Work/Dealoger/DealogerFSPS/build/Release/include -I/Users/artempanasenko/Developer/Work/Dealoger/DealogerFSPS/.build/checkouts/swift-nio/Sources/CNIOLinux/include -I/Users/artempanasenko/Developer/Work/Dealoger/DealogerFSPS/build/FileStorageProviderService.build/Release/CNIOLinux.build/DerivedSources-normal/x86_64 -I/Users/artempanasenko/Developer/Work/Dealoger/DealogerFSPS/build/FileStorageProviderService.build/Release/CNIOLinux.build/DerivedSources/x86_64 -I/Users/artempanasenko/Developer/Work/Dealoger/DealogerFSPS/build/FileStorageProviderService.build/Release/CNIOLinux.build/DerivedSources -F/Users/artempanasenko/Developer/Work/Dealoger/DealogerFSPS/build/Release -F/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks -MMD -MT dependencies -MF /Users/artempanasenko/Developer/Work/Dealoger/DealogerFSPS/build/FileStorageProviderService.build/Release/CNIOLinux.build/Objects-normal/x86_64/shim.d --serialize-diagnostics /Users/artempanasenko/Developer/Work/Dealoger/DealogerFSPS/build/FileStorageProviderService.build/Release/CNIOLinux.build/Objects-normal/x86_64/shim.dia -c /Users/artempanasenko/Developer/Work/Dealoger/DealogerFSPS/.build/checkouts/swift-nio/Sources/CNIOLinux/shim.c -o /Users/artempanasenko/Developer/Work/Dealoger/DealogerFSPS/build/FileStorageProviderService.build/Release/CNIOLinux.build/Objects-normal/x86_64/shim.o

Ditto /Users/artempanasenko/Developer/Work/Dealoger/DealogerFSPS/build/FileStorageProviderService.build/Release/CNIOLinux.build/module.modulemap /Users/artempanasenko/Developer/Work/Dealoger/DealogerFSPS/build/Release/CNIOLinux.framework/Versions/A/Modules/module.modulemap (in target 'CNIOLinux' from project 'FileStorageProviderService')
    cd /Users/artempanasenko/Developer/Work/Dealoger/DealogerFSPS
    builtin-copy -exclude .DS_Store -exclude CVS -exclude .svn -exclude .git -exclude .hg -strip-debug-symbols -strip-tool /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/strip -resolve-src-symlinks /Users/artempanasenko/Developer/Work/Dealoger/DealogerFSPS/build/FileStorageProviderService.build/Release/CNIOLinux.build/module.modulemap /Users/artempanasenko/Developer/Work/Dealoger/DealogerFSPS/build/Release/CNIOLinux.framework/Versions/A/Modules

CompileC /Users/artempanasenko/Developer/Work/Dealoger/DealogerFSPS/build/FileStorageProviderService.build/Release/CNIOLinux.build/Objects-normal/arm64/shim.o /Users/artempanasenko/Developer/Work/Dealoger/DealogerFSPS/.build/checkouts/swift-nio/Sources/CNIOLinux/shim.c normal arm64 c com.apple.compilers.llvm.clang.1_0.compiler (in target 'CNIOLinux' from project 'FileStorageProviderService')
    cd /Users/artempanasenko/Developer/Work/Dealoger/DealogerFSPS
    export LANG\=en_US.US-ASCII
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x c -target arm64-apple-macos10.10 -fmessage-length\=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit\=0 -fmodules -gmodules -fmodules-prune-interval\=86400 -fmodules-prune-after\=345600 -fbuild-session-file\=/var/folders/1w/c3b0gf5j2l55vr4378wkqm580000gn/C/org.llvm.clang/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror\=non-modular-include-in-framework-module -fmodule-name\=CNIOLinux -Wno-trigraphs -fpascal-strings -Os -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-return-type -Wno-missing-braces -Wparentheses -Wswitch -Wno-unused-function -Wno-unused-label -Wno-unused-parameter -Wno-unused-variable -Wunused-value -Wno-empty-body -Wno-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wno-constant-conversion -Wno-int-conversion -Wno-bool-conversion -Wno-enum-conversion -Wno-float-conversion -Wno-non-literal-null-conversion -Wno-objc-literal-conversion -Wno-shorten-64-to-32 -Wpointer-sign -Wno-newline-eof -DSWIFT_PACKAGE\=1 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk -fstrict-aliasing -Wdeprecated-declarations -g -Wno-sign-conversion -Wno-infinite-recursion -Wno-comma -Wno-block-capture-autoreleasing -Wno-strict-prototypes -Wno-semicolon-before-method-body -I/Users/artempanasenko/Developer/Work/Dealoger/DealogerFSPS/build/Release/include -I/Users/artempanasenko/Developer/Work/Dealoger/DealogerFSPS/.build/checkouts/swift-nio/Sources/CNIOLinux/include -I/Users/artempanasenko/Developer/Work/Dealoger/DealogerFSPS/build/FileStorageProviderService.build/Release/CNIOLinux.build/DerivedSources-normal/arm64 -I/Users/artempanasenko/Developer/Work/Dealoger/DealogerFSPS/build/FileStorageProviderService.build/Release/CNIOLinux.build/DerivedSources/arm64 -I/Users/artempanasenko/Developer/Work/Dealoger/DealogerFSPS/build/FileStorageProviderService.build/Release/CNIOLinux.build/DerivedSources -F/Users/artempanasenko/Developer/Work/Dealoger/DealogerFSPS/build/Release -F/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks -MMD -MT dependencies -MF /Users/artempanasenko/Developer/Work/Dealoger/DealogerFSPS/build/FileStorageProviderService.build/Release/CNIOLinux.build/Objects-normal/arm64/shim.d --serialize-diagnostics /Users/artempanasenko/Developer/Work/Dealoger/DealogerFSPS/build/FileStorageProviderService.build/Release/CNIOLinux.build/Objects-normal/arm64/shim.dia -c /Users/artempanasenko/Developer/Work/Dealoger/DealogerFSPS/.build/checkouts/swift-nio/Sources/CNIOLinux/shim.c -o /Users/artempanasenko/Developer/Work/Dealoger/DealogerFSPS/build/FileStorageProviderService.build/Release/CNIOLinux.build/Objects-normal/arm64/shim.o

CompileC /Users/artempanasenko/Developer/Work/Dealoger/DealogerFSPS/build/FileStorageProviderService.build/Release/CNIOLinux.build/Objects-normal/arm64/ifaddrs-android.o /Users/artempanasenko/Developer/Work/Dealoger/DealogerFSPS/.build/checkouts/swift-nio/Sources/CNIOLinux/ifaddrs-android.c normal arm64 c com.apple.compilers.llvm.clang.1_0.compiler (in target 'CNIOLinux' from project 'FileStorageProviderService')
    cd /Users/artempanasenko/Developer/Work/Dealoger/DealogerFSPS
    export LANG\=en_US.US-ASCII
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x c -target arm64-apple-macos10.10 -fmessage-length\=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit\=0 -fmodules -gmodules -fmodules-prune-interval\=86400 -fmodules-prune-after\=345600 -fbuild-session-file\=/var/folders/1w/c3b0gf5j2l55vr4378wkqm580000gn/C/org.llvm.clang/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror\=non-modular-include-in-framework-module -fmodule-name\=CNIOLinux -Wno-trigraphs -fpascal-strings -Os -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-return-type -Wno-missing-braces -Wparentheses -Wswitch -Wno-unused-function -Wno-unused-label -Wno-unused-parameter -Wno-unused-variable -Wunused-value -Wno-empty-body -Wno-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wno-constant-conversion -Wno-int-conversion -Wno-bool-conversion -Wno-enum-conversion -Wno-float-conversion -Wno-non-literal-null-conversion -Wno-objc-literal-conversion -Wno-shorten-64-to-32 -Wpointer-sign -Wno-newline-eof -DSWIFT_PACKAGE\=1 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk -fstrict-aliasing -Wdeprecated-declarations -g -Wno-sign-conversion -Wno-infinite-recursion -Wno-comma -Wno-block-capture-autoreleasing -Wno-strict-prototypes -Wno-semicolon-before-method-body -I/Users/artempanasenko/Developer/Work/Dealoger/DealogerFSPS/build/Release/include -I/Users/artempanasenko/Developer/Work/Dealoger/DealogerFSPS/.build/checkouts/swift-nio/Sources/CNIOLinux/include -I/Users/artempanasenko/Developer/Work/Dealoger/DealogerFSPS/build/FileStorageProviderService.build/Release/CNIOLinux.build/DerivedSources-normal/arm64 -I/Users/artempanasenko/Developer/Work/Dealoger/DealogerFSPS/build/FileStorageProviderService.build/Release/CNIOLinux.build/DerivedSources/arm64 -I/Users/artempanasenko/Developer/Work/Dealoger/DealogerFSPS/build/FileStorageProviderService.build/Release/CNIOLinux.build/DerivedSources -F/Users/artempanasenko/Developer/Work/Dealoger/DealogerFSPS/build/Release -F/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks -MMD -MT dependencies -MF /Users/artempanasenko/Developer/Work/Dealoger/DealogerFSPS/build/FileStorageProviderService.build/Release/CNIOLinux.build/Objects-normal/arm64/ifaddrs-android.d --serialize-diagnostics /Users/artempanasenko/Developer/Work/Dealoger/DealogerFSPS/build/FileStorageProviderService.build/Release/CNIOLinux.build/Objects-normal/arm64/ifaddrs-android.dia -c /Users/artempanasenko/Developer/Work/Dealoger/DealogerFSPS/.build/checkouts/swift-nio/Sources/CNIOLinux/ifaddrs-android.c -o /Users/artempanasenko/Developer/Work/Dealoger/DealogerFSPS/build/FileStorageProviderService.build/Release/CNIOLinux.build/Objects-normal/arm64/ifaddrs-android.o
error: Build input file cannot be found: '/Users/artempanasenko/Developer/Work/Dealoger/DealogerFSPS/.build/checkouts/swift-nio/Sources/CNIOLinux/ifaddrs-android.c' (in target 'CNIOLinux' from project 'FileStorageProviderService')

CompileC /Users/artempanasenko/Developer/Work/Dealoger/DealogerFSPS/build/FileStorageProviderService.build/Release/CNIOLinux.build/Objects-normal/x86_64/ifaddrs-android.o /Users/artempanasenko/Developer/Work/Dealoger/DealogerFSPS/.build/checkouts/swift-nio/Sources/CNIOLinux/ifaddrs-android.c normal x86_64 c com.apple.compilers.llvm.clang.1_0.compiler (in target 'CNIOLinux' from project 'FileStorageProviderService')
    cd /Users/artempanasenko/Developer/Work/Dealoger/DealogerFSPS
    export LANG\=en_US.US-ASCII
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x c -target x86_64-apple-macos10.10 -fmessage-length\=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit\=0 -fmodules -gmodules -fmodules-prune-interval\=86400 -fmodules-prune-after\=345600 -fbuild-session-file\=/var/folders/1w/c3b0gf5j2l55vr4378wkqm580000gn/C/org.llvm.clang/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror\=non-modular-include-in-framework-module -fmodule-name\=CNIOLinux -Wno-trigraphs -fpascal-strings -Os -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-return-type -Wno-missing-braces -Wparentheses -Wswitch -Wno-unused-function -Wno-unused-label -Wno-unused-parameter -Wno-unused-variable -Wunused-value -Wno-empty-body -Wno-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wno-constant-conversion -Wno-int-conversion -Wno-bool-conversion -Wno-enum-conversion -Wno-float-conversion -Wno-non-literal-null-conversion -Wno-objc-literal-conversion -Wno-shorten-64-to-32 -Wpointer-sign -Wno-newline-eof -DSWIFT_PACKAGE\=1 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk -fasm-blocks -fstrict-aliasing -Wdeprecated-declarations -g -Wno-sign-conversion -Wno-infinite-recursion -Wno-comma -Wno-block-capture-autoreleasing -Wno-strict-prototypes -Wno-semicolon-before-method-body -I/Users/artempanasenko/Developer/Work/Dealoger/DealogerFSPS/build/Release/include -I/Users/artempanasenko/Developer/Work/Dealoger/DealogerFSPS/.build/checkouts/swift-nio/Sources/CNIOLinux/include -I/Users/artempanasenko/Developer/Work/Dealoger/DealogerFSPS/build/FileStorageProviderService.build/Release/CNIOLinux.build/DerivedSources-normal/x86_64 -I/Users/artempanasenko/Developer/Work/Dealoger/DealogerFSPS/build/FileStorageProviderService.build/Release/CNIOLinux.build/DerivedSources/x86_64 -I/Users/artempanasenko/Developer/Work/Dealoger/DealogerFSPS/build/FileStorageProviderService.build/Release/CNIOLinux.build/DerivedSources -F/Users/artempanasenko/Developer/Work/Dealoger/DealogerFSPS/build/Release -F/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks -MMD -MT dependencies -MF /Users/artempanasenko/Developer/Work/Dealoger/DealogerFSPS/build/FileStorageProviderService.build/Release/CNIOLinux.build/Objects-normal/x86_64/ifaddrs-android.d --serialize-diagnostics /Users/artempanasenko/Developer/Work/Dealoger/DealogerFSPS/build/FileStorageProviderService.build/Release/CNIOLinux.build/Objects-normal/x86_64/ifaddrs-android.dia -c /Users/artempanasenko/Developer/Work/Dealoger/DealogerFSPS/.build/checkouts/swift-nio/Sources/CNIOLinux/ifaddrs-android.c -o /Users/artempanasenko/Developer/Work/Dealoger/DealogerFSPS/build/FileStorageProviderService.build/Release/CNIOLinux.build/Objects-normal/x86_64/ifaddrs-android.o
error: Build input file cannot be found: '/Users/artempanasenko/Developer/Work/Dealoger/DealogerFSPS/.build/checkouts/swift-nio/Sources/CNIOLinux/ifaddrs-android.c' (in target 'CNIOLinux' from project 'FileStorageProviderService')

** BUILD FAILED **


The following build commands failed:
	CompileC /Users/artempanasenko/Developer/Work/Dealoger/DealogerFSPS/build/FileStorageProviderService.build/Release/CNIOLinux.build/Objects-normal/arm64/ifaddrs-android.o /Users/artempanasenko/Developer/Work/Dealoger/DealogerFSPS/.build/checkouts/swift-nio/Sources/CNIOLinux/ifaddrs-android.c normal arm64 c com.apple.compilers.llvm.clang.1_0.compiler
	CompileC /Users/artempanasenko/Developer/Work/Dealoger/DealogerFSPS/build/FileStorageProviderService.build/Release/CNIOLinux.build/Objects-normal/x86_64/ifaddrs-android.o /Users/artempanasenko/Developer/Work/Dealoger/DealogerFSPS/.build/checkouts/swift-nio/Sources/CNIOLinux/ifaddrs-android.c normal x86_64 c com.apple.compilers.llvm.clang.1_0.compiler
(2 failures)

**Comment by PanArtemG** [comment]
@johnfairh I don't know what the problem was, I pulled off the project and everything worked as it should! I'm sorry to trouble you.

**Comment by johnfairh** [comment]
ok!
