### ISSUE TITLE
*** missing separator.  Stop.

### ISSUE THREAD

**Issue by lexuanquynh** [realm/jazzy#1233]
I use Makefile with code:
https://gist.github.com/lexuanquynh/44c3ff59cc23fb89a4ee6cec08bedcb0

and when I run command line:
`make documentation`
I got a error:
 *** missing separator.  Stop.
why that script make error? can every body help me fix it?

**Comment by johnfairh** [comment]
This is an error from `make`, check the syntax -- [stackoverflow](https://stackoverflow.com/questions/920413/make-error-missing-separator) would be a better place to ask questions about makefiles.
