### ISSUE TITLE
Check for documentation validity/completeness

### ISSUE THREAD

**Issue by Cedrick84** [realm/jazzy#1236]
Hi all,

Been playing around with this tool and so far I love it. The only question I have is it possible (in Swift mode) to check that all parameters are documented? If I write documentation and add a parameter to a method signature for example jazzy still tells me that my class is 100% documented. Is it possible to have the equivalent of  clangs"-wdocumentation"?

Many thanks

**Comment by johnfairh** [comment]
Jazzy doesn't support this - it only looks at whether the declaration has any doc comment.  I think it would be possible to add, looks like there might be enough info in the data.  Be worth checking if SwiftLint does this, don't think it looks at the structure of the doc comments though.

**Comment by johnfairh** [comment]
I'm going to close this as out of scope, recommend [DrString](https://github.com/dduan/DrString) to address this need.
