### ISSUE TITLE
Linking to a property derived from parent class

### ISSUE THREAD

**Issue by rashenoy** [realm/jazzy#1239]
I am using Jazzy to document my objc framework. It works for almost everything. But I am facing one issue.

I have a Parent 

@interface Parent : NSObject
 @property NSstring * lastName. 

I have a derived class Child 

@interface Child : Parent

In the documentation, I want to refer to Child.lastName. If I use {@link Child.lastName}, it doesnt generate the link. It is misleading to use {@link Parent.lastName} as it will appear as Parent.lastName.

I could not find how to do this anywhere in the documentation.

**Comment by johnfairh** [comment]
If you want to write 'Child.lastName' and have that link to the docs for 'Parent.lastName' then you will need to write the link yourself using markdown syntax.

**Comment by rashenoy** [comment]
Is there a way to show all the inherited properties in the documentation of the derived class ?

**Comment by johnfairh** [comment]
No, the tools don't provide that information

**Comment by johnfairh** [comment]
Closing, answered.
