### ISSUE TITLE
Could not parse compiler arguments from `xcodebuild` output with Xcode12.4 mac 10.15.7

### ISSUE THREAD

**Issue by yusheng-jia** [realm/jazzy#1241]
run command : jazzy --build-tool-arguments -project,XalManager.xcodeproj,-scheme,XalManager
Running xcodebuild
Checking xcodebuild -showBuildSettings
Running xcodebuild
Could not parse compiler arguments from `xcodebuild` output.
Please confirm that `xcodebuild` is building a Swift module.
Saved `xcodebuild` log file: /var/folders/r9/3cv2lp0s09dg2dn2jdthpsv40000gn/T/xcodebuild-6EDC82FF-CD81-44DA-A989-E5C6A3950BE9.log
Failed to generate documentation
/usr/local/lib/ruby/gems/3.0.0/gems/jazzy-0.13.6/lib/jazzy/executable.rb:36:in `execute_command': /usr/local/lib/ruby/gems/3.0.0/gems/jazzy-0.13.6/bin/sourcekitten ["doc", "--", "-project", "XalManager.xcodeproj", "-scheme", "XalManager"] (RuntimeError)

Running xcodebuild

Checking xcodebuild -showBuildSettings

Running xcodebuild

Could not parse compiler arguments from `xcodebuild` output.

Please confirm that `xcodebuild` is building a Swift module.

Saved `xcodebuild` log file: /var/folders/r9/3cv2lp0s09dg2dn2jdthpsv40000gn/T/xcodebuild-6EDC82FF-CD81-44DA-A989-E5C6A3950BE9.log

Failed to generate documentation
	from /usr/local/lib/ruby/gems/3.0.0/gems/jazzy-0.13.6/lib/jazzy/sourcekitten.rb:266:in `run_sourcekitten'
	from /usr/local/lib/ruby/gems/3.0.0/gems/jazzy-0.13.6/lib/jazzy/doc_builder.rb:81:in `block in build'
	from /usr/local/lib/ruby/gems/3.0.0/gems/jazzy-0.13.6/lib/jazzy/doc_builder.rb:79:in `chdir'
	from /usr/local/lib/ruby/gems/3.0.0/gems/jazzy-0.13.6/lib/jazzy/doc_builder.rb:79:in `build'
	from /usr/local/lib/ruby/gems/3.0.0/gems/jazzy-0.13.6/bin/jazzy:15:in `<top (required)>'
	from /usr/local/bin/jazzy:23:in `load'
	from /usr/local/bin/jazzy:23:in `<main>'

**Comment by yusheng-jia** [comment]
Also i checked the log :
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -project XalManager.xcodeproj -scheme XalManager clean build CODE_SIGN_IDENTITY= CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO

Build settings from command line:
    CODE_SIGN_IDENTITY = 
    CODE_SIGNING_ALLOWED = NO
    CODE_SIGNING_REQUIRED = NO

note: Using new build system
note: Building targets in parallel
note: Using codesigning identity override: 

** CLEAN SUCCEEDED **

note: Using new build system
note: Building targets in parallel
note: Using codesigning identity override: 
note: Planning build
note: Constructing build description
...
...
...

PBXCp /Users/admin/Development/Xsens/xsensdot_ios_algorithm_library/XalManager/XalManager/XalDefine.h /Users/admin/Library/Developer/Xcode/DerivedData/XalManager-ehlteewkrmunjwegaxpjoifosjks/Build/Products/Debug-iphoneos/include/XalManager/XalDefine.h (in target 'XalManager' from project 'XalManager')
    cd /Users/admin/Development/Xsens/xsensdot_ios_algorithm_library/XalManager
    builtin-copy -exclude .DS_Store -exclude CVS -exclude .svn -exclude .git -exclude .hg -resolve-src-symlinks /Users/admin/Development/Xsens/xsensdot_ios_algorithm_library/XalManager/XalManager/XalDefine.h /Users/admin/Library/Developer/Xcode/DerivedData/XalManager-ehlteewkrmunjwegaxpjoifosjks/Build/Products/Debug-iphoneos/include/XalManager

** BUILD SUCCEEDED **

**Comment by yusheng-jia** [comment]
I also confused about  the log shows build succeeded, but jazzy run errors.

**Comment by johnfairh** [comment]
This means the tools think that the  "..." section of the build log did not compile any Swift modules.

**Comment by yusheng-jia** [comment]
> This means the tools think that the "..." section of the build log did not compile any Swift modules.

So how can i solve it? The project is an objective-c project.

**Comment by johnfairh** [comment]
You should use jazzy in Objective-C mode instead of Swift mode.  See the readme etc. for examples, something like:
```shell
jazzy --objc --framework-root . --umbrella-header MyModule/MyModule.h
```

**Comment by yusheng-jia** [comment]
> You should use jazzy in Objective-C mode instead of Swift mode. See the readme etc. for examples, something like:
> 
> ```shell
> jazzy --objc --framework-root . --umbrella-header MyModule/MyModule.h
> ```

Thank you , will close it
