### ISSUE TITLE
Property of type NSMutableArray not being documented (Objc)

### ISSUE THREAD

**Issue by abdulajet** [realm/jazzy#1243]
I have pretty much the same issue as here #1066 but switching the SDK did not work for me. 

property:

`@property (nonatomic, readonly, nonnull) NSMutableArray<NXMCallMember *> *otherCallMembers;`

I tried using `NSMutableArray<NSString *>` and that didn't seem to work. Is there a way to make Jazzy be verbose in the issue it is having?

**Comment by johnfairh** [comment]
I think any clang errors are shown on stderr, though I haven't verified this on recent Xcode.  If you can provide a complete example of a header file that's not working along with the jazzy command you're using then I can take a look.

**Comment by abdulajet** [comment]
Annoyingly it started working using `--sdk iphonesimulator` just after i posted this. Not sure what fixed it, _i think_ it was deleting the `build` folder. I Will try repo tomorrow

**Comment by abdulajet** [comment]
Cant seem to break it again. Cheers for the help
