### ISSUE TITLE
SymbolGraph mode misses out param docs

### ISSUE THREAD

**Issue by jamgzj** [realm/jazzy#1244]
jazzy \
--clean \
--module ...SDK \
--swift-build-tool symbolgraph \
--sdk iphoneos \
--build-tool-arguments  --target,arm64-apple-ios11.0 \
--swift-version 5.3.2 \
--output /.../.../...

I use jazzy like above, and i got docs without parameters' introduction of functions

**Comment by johnfairh** [comment]
Thanks - yes I see this.  There's an extra bit of valid parameter validation against SourceKit output that needs working around.

**Comment by johnfairh** [comment]
Thanks again - fixed in #1250, will be in next release, should be this week.
