### ISSUE TITLE
Kramdown footnotes don't seem to work?

### ISSUE THREAD

**Issue by aufflick** [realm/jazzy#1246]
Jazzy uses kramdown (according to the git logs that I've skimmed), and Kramdown has a footnote syntax: https://kramdown.gettalong.org/quickref.html#footnotes But when I try to use that syntax in raw .md files included by Jazzy, the HTML just includes literal "[^1]" body text.

I don't see any options that Kramdown needs to render this.

**Comment by johnfairh** [comment]
Jazzy uses [redcarpet](https://github.com/vmg/redcarpet) for its markdown rendering.  It looks like there's a footnote option available that isn't turned on -- I haven't checked how the default HTML renderer copes with it, would be worth investigating.

**Comment by aufflick** [comment]
Ah I see - I didn't notice there were two Markdown parser libraries in use :) I'll play with enabling that option and see if there are any negative consequences.

**Comment by johnfairh** [comment]
I had a go at this in #1253.

**Comment by aufflick** [comment]
This is amazing - I just tried it out and it works perfectly :D

**Comment by johnfairh** [comment]
Great - will be in next release.
