### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by Ogerets** [realm/jazzy#1266]
I run  ```sudo gem install jazzy``` in order to install jazzy. Instead of success it asks me to overwrite the executables of other utils, which seems to be wrong

```
xcodeproj's executable "xcodeproj" conflicts with /usr/local/bin/xcodeproj
Overwrite the executable?
```
&
```
cocoapods's executable "pod" conflicts with /usr/local/bin/pod
Overwrite the executable?
```

MacOS 11.4

**Comment by johnfairh** [comment]
These are both from gem dependencies.  Sounds like you're maybe installing using a Ruby env that is different to the one that has installed into `/usr/local`.

**Comment by johnfairh** [comment]
Closing, answered/inactive.
