### ISSUE TITLE
Jazzy running exceptionally slow on small-ish project

### ISSUE THREAD

**Issue by jrtibbetts** [realm/jazzy#1275]
I have an SDK that consists of about 50 source files. I've been using Jazzy 0.13.7 for several months with this project. A couple weeks ago, some change I made to the project itself caused Jazzy to stop working using either its default settings or my custom YAML configuration. I fixed this by creating an entirely new framework target. Now, however, Jazzy _works_, but now it's exceptionally slow--it took 31 minutes to parse the first 6 files, before I killed the process. How can I begin debugging this?

```
it-C00179:arcxp-video-sdk-ios tibbettsj$ time jazzy
Using config file /Users/tibbettsj/Developer/arcxp-video-sdk-ios/.jazzy.yaml
Running xcodebuild
Checking xcodebuild -showBuildSettings
Assuming New Build System is used.
Parsing AVPlayerExtensions.swift (1/46)
Parsing AVPlayerItemExtensions.swift (2/46)
Parsing AVPlayerViewController+PlayerController.swift (3/46)
Parsing ArcPlayer.swift (4/46)
Parsing DelegatingMediaEventSubscriber.swift (5/46)
Parsing PlayerController.swift (6/46)
^C#<Thread:0x00007fa58b4dca78@/Library/Ruby/Gems/2.6.0/gems/open4-1.3.4/lib/open4.rb:186 run> terminated with exception (report_on_exception is true):
...
real	31m18.231s
user	0m4.674s
sys	0m2.023s
```

Using the default config instead of my `.jazzy.yaml` file makes no difference. Updating to `0.14.0` also makes no difference.

There are only three third-party dependencies: Google IMA Ads, Google Programmatic Access Library, and Open Measurement. These same dependencies have been used for several months, including when jazzy ran quickly before I broke the project.

The system is not under any load whatsoever.

<img width="924" alt="Screen Shot 2021-08-18 at 1 32 02 PM" src="https://user-images.githubusercontent.com/708510/129945055-54c0a862-0431-4fb7-81ef-fbc2e27860fd.png">

**Comment by jrtibbetts** [comment]
It seems to be intermittent, which isn't helpful.

**Comment by johnfairh** [comment]
I haven't seen this myself.

The part being slow is the `sourcekitten` run - that part is querying sourcekit file-by-file for info, which involves running the frontend of the compiler once on each file: I think if you did debug into `sourcekitten` it would just show sourcekit calls blocking.

I can tell from the sourcekitten output ('Assuming New Build System is used.') that it is using a cached build record to determine the CLI args and source files in the project.  This could be going wrong, perhaps picking up something from your previous target config?  So it's worth trying deleting any build directories and your DerivedData for the project --- I know this sounds like typical 'Xcode being weird, delete deriveddata' advice, but there is some thought to it!

(Also, given the time of year, if you've been running Xcode 13 betas as well as Xcode 12 on this project there could be some compatibility mixup there, again on the build records in derived data.)

**Comment by jrtibbetts** [comment]
That was it--I was running Xcode 12 and the 13 beta side-by-side. When I used `xcode-select` to target 13 beta, the problem went away. Thanks for putting me on the right track!
