### ISSUE TITLE
How to include files in my dependent frameworks.

### ISSUE THREAD

**Issue by onato** [realm/jazzy#1276]
I have my modules organized in frameworks that are linked into the App Target, similar to this example project. 

[DemoAppWithFramework.zip](https://github.com/realm/jazzy/files/7173627/DemoAppWithFramework.zip)

<img width="1512" alt="Screen Shot 2021-09-16 at 10 37 28 AM" src="https://user-images.githubusercontent.com/107999/133519152-b0b9d691-5799-4f7a-af76-f828bff190cc.png">

When I run…

```
❯ jazzy --version
jazzy version: 0.14.0

❯ jazzy --min-acl private
Running xcodebuild
Checking xcodebuild -showBuildSettings
Assuming New Build System is used.
Parsing AppDelegate.swift (1/3)
Parsing SceneDelegate.swift (2/3)
Parsing ViewController.swift (3/3)
0% documentation coverage with 14 undocumented symbols
included 14 private, fileprivate, internal, public, or open symbols
building site
building search index
jam out ♪♫ to your fresh new docs in `docs`
```

I get documentation generated for the files in the main App target, but not for those in the framework.

<img width="1017" alt="Screen Shot 2021-09-16 at 10 27 00 AM" src="https://user-images.githubusercontent.com/107999/133518531-164d53f1-a47c-4a72-b2b4-ed255b15d2e5.png">

I expected jazzy to generate docs for files in the app target's dependencies as well.

Do I need to generate the docs for frameworks in a separate step using https://github.com/realm/jazzy#docs-from-swiftmodules-or-frameworks or is there something else I am missing?

**Comment by johnfairh** [comment]
Running jazzy this way generates documentation for one module - see _Usage_ in the readme for tips on how to pick the right module.

If you want to try putting multiple modules into the same docset then see #1194, #594 for the workaround -- things should mostly work as long as your structure is not too complex and there are no name clashes.

**Comment by onato** [comment]
Worked like a charm.

```bash
#!/bin/sh
set -euo pipefail
IFS=$'\n\t'

modules=(
    "App"
    "Authentication"
    "Utils"
  )

cleanup() {
    for module in ${modules[@]}; do
        rm "$module.json" || true
    done
}
trap cleanup 0

FILENAMES=""
for module in ${modules[@]}; do
    filename="$module.json"
    if [ ! -f $filename ]; then
        echo "Processing $module"
        sourcekitten doc -- -workspace MyApp.xcworkspace -scheme "$module" > "$filename"
    fi
    FILENAMES="$FILENAMES,$filename"
done

jazzy \
  --clean \
  --author Acme \
  --author_url https://example.com \
  --source-host github \
  --source-host-url https://github.com/example/my-app \
  --build-tool-arguments -scheme,MyApp \
  --root-url https://github.com/example/my-app/ \
  --output docs/reference \
  --min-acl private \
  --sourcekitten-sourcefile "${FILENAMES:1}"

```
