### ISSUE TITLE
HTML validation issues

### ISSUE THREAD

**Issue by zorgiepoo** [realm/jazzy#1280]
While integrating jazzy (v0.14.0) in our project's website using the `jony` theme, we ran into a couple issues with our CI validating the HTML. Some of these issues were invalid in our validator, but I think it caught a couple valid ones. They are also pointed out by a better [online HTML validator for our website](https://html5.validator.nu/?doc=https%3A%2F%2Fsparkle-project.github.io%2Fdocumentation%2Fapi-reference%2F). Notably:

* There is an extraneous closing `</div>` tag right before the ending `</html>` that doesn't have a matching opening `<div>`
* `img` tags, eg `<img id="carat" src="img/carat.png" />` don't have an `alt` attribute which is [apparently required](https://www.w3schools.com/tags/tag_img.asp).
* The online validator seems to be complaining about duplicate `rel` attributes, eg `rel="noopener" rel="external"`, likely it wants `rel="noopener external"`

I'm not sure if there are other errors on other pages. [Our website is here](https://sparkle-project.github.io/documentation/api-reference/), although I think some of these issues surface in the example websites on this project and for other themes. Web browsers, or at least Safari, seem to present the webpages well so this is just overall a correctness issue (P.S, otherwise jazzy was great to integrate 👍)

**Comment by johnfairh** [comment]
Thanks for this, will look at fixing at least some of the errors.
