### ISSUE TITLE
Error with generate documentation in docker

### ISSUE THREAD

**Issue by gulivero1773** [realm/jazzy#1283]
jazzy:
#  image: norionomura/jazzy
  image: swift:latest
  stage: build
  script:
    - git clone https://github.com/jpsim/SourceKitten
    - cd SourceKitten
    - swift build
    - make install
    - export PATH=$PATH:/usr/local/bin
    - env | grep PATH
    - sourcekitten help
    - cd ../
    - apt update
    - apt install -y curl
    - curl -sSL https://rvm.io/mpapis.asc | gpg --import -
    - curl -sSL https://rvm.io/pkuczynski.asc | gpg --import -
    - curl -sSL https://get.rvm.io | bash -s stable
    - source /etc/profile.d/rvm.sh
    - rvm requirements
    - rvm install 2.6
    - rvm use 2.6.6 --default
    - ruby --version
    - gem install jazzy
    #- snap install ruby --classic
    - ls -la
    - jazzy
    #- jazzy --config .jazzy.yaml
    - ls -Rla
    
I Use this code

Using config file /builds/dealoger/web-app/iPassportAuthWebApp/.jazzy.yaml
/usr/local/rvm/gems/ruby-2.6.6/gems/jazzy-0.14.1/bin/sourcekitten: 1: /usr/local/rvm/gems/ruby-2.6.6/gems/jazzy-0.14.1/bin/sourcekitten: Syntax error: "(" unexpected
/usr/local/rvm/gems/ruby-2.6.6/gems/jazzy-0.14.1/lib/jazzy/executable.rb:39:in `execute_command': /usr/local/rvm/gems/ruby-2.6.6/gems/jazzy-0.14.1/bin/sourcekitten ["doc", "--spm", "--", "-Xswiftc", "-swift-version", "-Xswiftc", "5"] (RuntimeError)
/usr/local/rvm/gems/ruby-2.6.6/gems/jazzy-0.14.1/bin/sourcekitten: 1: /usr/local/rvm/gems/ruby-2.6.6/gems/jazzy-0.14.1/bin/sourcekitten: Syntax error: "(" unexpected
	from /usr/local/rvm/gems/ruby-2.6.6/gems/jazzy-0.14.1/lib/jazzy/sourcekitten.rb:269:in `run_sourcekitten'
	from /usr/local/rvm/gems/ruby-2.6.6/gems/jazzy-0.14.1/lib/jazzy/doc_builder.rb:82:in `block in build'
	from /usr/local/rvm/gems/ruby-2.6.6/gems/jazzy-0.14.1/lib/jazzy/doc_builder.rb:80:in `chdir'
	from /usr/local/rvm/gems/ruby-2.6.6/gems/jazzy-0.14.1/lib/jazzy/doc_builder.rb:80:in `build'
	from /usr/local/rvm/gems/ruby-2.6.6/gems/jazzy-0.14.1/bin/jazzy:16:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.6.6/bin/jazzy:23:in `load'
	from /usr/local/rvm/gems/ruby-2.6.6/bin/jazzy:23:in `<main>'
	from /usr/local/rvm/gems/ruby-2.6.6/bin/ruby_executable_hooks:24:in `eval'
	from /usr/local/rvm/gems/ruby-2.6.6/bin/ruby_executable_hooks:24:in `<main>'

**Comment by johnfairh** [comment]
Closing, answered.
