### ISSUE TITLE
Xcodebuild problem

### ISSUE THREAD

**Issue by ezgiozkan** [realm/jazzy#1285]
Running swift build
Build failed, saved `swift build` log file: /var/folders/zn/fwsz2z1n3x99254x7shljch00000gp/T/swift-build-7BF5C915-24F7-4CA6-AC48-C7454D69EA8A.log
Error: Failed to generate documentation
Traceback (most recent call last):
	7: from /usr/local/bin/jazzy:23:in `<main>'
	6: from /usr/local/bin/jazzy:23:in `load'
	5: from /Library/Ruby/Gems/2.6.0/gems/jazzy-0.14.1/bin/jazzy:16:in `<top (required)>'
	4: from /Library/Ruby/Gems/2.6.0/gems/jazzy-0.14.1/lib/jazzy/doc_builder.rb:80:in `build'
	3: from /Library/Ruby/Gems/2.6.0/gems/jazzy-0.14.1/lib/jazzy/doc_builder.rb:80:in `chdir'
	2: from /Library/Ruby/Gems/2.6.0/gems/jazzy-0.14.1/lib/jazzy/doc_builder.rb:82:in `block in build'
	1: from /Library/Ruby/Gems/2.6.0/gems/jazzy-0.14.1/lib/jazzy/sourcekitten.rb:269:in `run_sourcekitten'
/Library/Ruby/Gems/2.6.0/gems/jazzy-0.14.1/lib/jazzy/executable.rb:39:in `execute_command': /Library/Ruby/Gems/2.6.0/gems/jazzy-0.14.1/bin/sourcekitten ["doc", "--spm", "--"] (RuntimeError)

note: Using new build system
note: Using codesigning identity override: 
note: Planning build
note: Constructing build description
Build system information
unexpected service error: build aborted due to an internal error: unable to write manifest to

**Comment by johnfairh** [comment]
The jazzy backtrace shows you running it in SPM mode but what I assume is the swift-build logfile mentioned below looks more like an `xcodebuild` log?

Either way, you should get your module building using one build tool or the other first and then pass those same arguments to jazzy.  If this still fails then you'll need to share a recreating project to let us debug it.

People who have thumbs-up-ed this: what do you mean?  Do you also have this problem?  You need to give more info, it's possible something is broken with new Xcode/macOS/jazzy, but there's nothing really to go on here.
