### ISSUE TITLE
Cannot generate documentation for Swift Package Manager

### ISSUE THREAD

**Issue by vikihleblya** [realm/jazzy#1289]
Hi! I have SPM package written on Swift, which has a dependency SPM written on Objective-C. I've tried to generate documentation for Swift SPM package, but got an error `find_spec_for_exe': can't find gem jazzy (>= 0.a) with executable jazzy (Gem::GemNotFoundException)`

Run this command in the root folder in my project. (project also has both swift and obj-c code)
```
$ jazzy \
  --module MRCalendar \
  --swift-build-tool spm \
  --build-tool-arguments -Xswiftc,-swift-version,-Xswiftc,5 \
  --sdk iphonesimulator  
```

P.S. I don't need to make documentation for Obj-C SPM, only for Swift SPM. 
Thanks!

**Comment by johnfairh** [comment]
The `find_spec_for_exe` thing looks like something to do with your Ruby env?  I don't know anything more about that, seem to be lots of hits on google.

Once you're past that, I would take out the `sdk` part, that is an ObjC argument.  And `swift build` cannot build for iOS/simulator as far as I know.

**Comment by johnfairh** [comment]
Closing, answered/inactive.
