### ISSUE TITLE
Include Images With Guide Documentation

### ISSUE THREAD

**Issue by dpfannenstiel** [realm/jazzy#1290]
I'm looking for way way to include image resources with guide documentation.  In previous version of Jazzy I think I was able to accomplish this with `--assets-directory` but that seems to have been deprecated.  Is there any way to specify additional resources to copy into the Jazzy output directory during build?  Or do I have to handled that as part of my build script.

**Comment by johnfairh** [comment]
There's no option to do this exactly.  You can do it manually during build script, but if you're relying on the Dash docset as well as the site then it's a bit painful (updating the .tgz too).

`--assets-directory` was removed long before my time, but your comment suggests another approach using its `--theme` replacement, either permanently or during your build script, that will sort out all the copies:
- Copy whichever theme you're using from inside the jazzy gem/checkout into your own place, call it `my_apple` for e.g;
- Copy your images etc. into the `my_apple/assets` tree;
- Point jazzy at that theme `--theme my_apple` and everything from the `assets` will be put into all the right places.

**Comment by johnfairh** [comment]
Closing, answered.
