### ISSUE TITLE
when I set different categories in one .h file, i get an error:jazzy-0.14.1/lib/jazzy/sourcekitten.rb:655:in `block in expand_extensions': undefined method `include?' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by UE900** [realm/jazzy#1292]
For example: i have a file named ClassA.h
```
@interface ClassA: NSObject 
/// doc1
@property (nonatomic, assign) BOOL isClassAOK;
@end
```
-----------------------------------------------------------

when i put this:
```
@interface ClassA (Test)
/// doc2
@property (nonatomic, assign) BOOL isClassACategoryOK;
@end 
```
into ClassA.h, using jazzy generate doc succeeded.

but when i put this:
```
@interface NSObject (Test)
/// doc3
@property (nonatomic, assign) BOOL isOtherCategoryOK;
@end 
```
into ClassA.h, i get an error:
```
jazzy-0.14.1/lib/jazzy/sourcekitten.rb:655:in `block in expand_extensions': undefined method `include?' for nil:NilClass (NoMethodError)
```
it's jazzy unsupport different categories in one file? or am i wrong?

**Comment by johnfairh** [comment]
You need `@import Foundation;` to get definitions for `BOOL` and `NSObject`.

Are you not getting compiler error messages?
```
/Users/johnf/project/ObjCTest/test.h:1:20: error: cannot find interface declaration for 'NSObject', superclass of 'ClassA'
/Users/johnf/project/ObjCTest/test.h:3:31: error: unknown type name 'BOOL'
/Users/johnf/project/ObjCTest/test.h:8:31: error: unknown type name 'BOOL'
/Users/johnf/project/ObjCTest/test.h:11:12: error: cannot find interface declaration for 'NSObject'
/Users/johnf/project/ObjCTest/test.h:13:31: error: unknown type name 'BOOL'
```
LibClang is producing some very weird output that is crashing jazzy.

**Comment by UE900** [comment]
Sorry, I didn't describe it clearly.
The entire case is:
![image](https://user-images.githubusercontent.com/4434384/142962356-99421981-9173-4c0f-bae4-bb411573b5a4.png)
The entire error message is:
![image](https://user-images.githubusercontent.com/4434384/142961937-069a4c95-c1fb-4bfc-9339-e9160e958c07.png)

--------------------------------------
cmd = 'sourcekitten doc --objc \
                    --single-file %s \
                    -- -x objective-c \
                    -isysroot $(xcrun --show-sdk-path) -I $(pwd) >> %s' % (single_header, single_doc_output)
os.system(cmd)
--------------------------------------
compose_doc_cmd = 'jazzy --clean \
                        --hide-documentation-coverage \
                        --disable-search \
                        --output %s \
                        --sourcekitten-sourcefile %s \
                        --readme %s \
                        --module %s \
                        --module-version %s \
                        --author %s \
                        --author_url %s' % (output_path, temp_doc_paths, readme_path, lib_name, lib_version, lib_author_name, lib_author_url)
os.system(compose_doc_cmd)

**Comment by johnfairh** [comment]
You still have compiler errors to fix:
```
/Users/johnf/project/ObjCTest/test.h:1:9: fatal error: 'UIKit/UIKit.h' file not found
```

The script is setting a macOS SDK which does not have UIKit.

Maybe try `$(xcrun --show-sdk-path --sdk iphonesimulator)`?

**Comment by johnfairh** [comment]
Closing, answered/inactive.
