### ISSUE TITLE
sparkle v2 autoDownloadUpdate, don't start auto downloading. 

### ISSUE THREAD

**Issue by kaiseren92** [realm/jazzy#1296]
have tried a lot of things but can't seem to see what I'm doing wrong. 
I can download if go to help->Check for updates it works that way by manually able to update the app that way through .

import Foundation
import Sparkle
import Cocoa
@main
class AppDelegate: NSObject, NSApplicationDelegate, SPUStandardUserDriverDelegate, SPUUpdaterDelegate {
    func applicationDidFinishLaunching(_ aNotification: Notification)
    { // Insert code here to initialize your application
 //   DispatchQueue.main.asyncAfter(deadline: DispatchTime.now()+1) {
//        SUUpdater.shared()?.checkForUpdatesInBackground()
 //   }
        
  SPUStandardUpdaterController(updaterDelegate: self, userDriverDelegate: self).updater.checkForUpdatesInBackground()
        var updateCheckInterval: TimeInterval { 10 }
        var automaticallyChecksForUpdates: Bool { true }
        var automaticallyDownloadsUpdates: Bool { true }
           
//        SUUpdater.shared()?.updateCheckInterval = 10
//        SUUpdater.shared()?.automaticallyChecksForUpdates = true
//        SUUpdater.shared()?.automaticallyDownloadsUpdates = true
    }
    func applicationWillTerminate(_ aNotification: Notification) {   
        // Insert code here to tear down your application    
    }
    func applicationShouldTerminateAfterLastWindowClosed(_ sender: NSApplication) -> Bool {    
        return true
    }
}

**Comment by johnfairh** [comment]
Wrong repo or confused bot?
