### ISSUE TITLE
Allowing for Themes

### ISSUE THREAD

**Issue by juangamnik** [realm/jazzy#130]
The generated HTML-code has a nice separation between content and style information via *jazzy.css* and *highlight.css*. In order to enable different themes it would be nice to have a command-line option for the use of someones own CSS-files (and perhaps offer some default themes, that the *community* can provide). 

On the one hand supporting this is very easy (its just copying different css files) and on the other hand you can just *delegate* issues like #82 (responsive web design) to themes. For this #95 (merging CSS files for README and body) would come in handy.

I have seen, that you are using jQuery in the generated files, this is most likely used for the accordion effect of declarations. This might be an issue for some themes as they do not want to use animations. But I think these accordions can be realized with CSS, too (CSS offers such animations) or the Javascript code controlling the jQuery animations would have to be part of the *theme-files* so that they can be omitted/replaced in other themes.

In this event the current CSS-files should be documented very good, so that a theme provider can adjust the styles easily.

**Comment by jpsim** [comment]
Done in #442
