### ISSUE TITLE
Getting PhaseScriptExecution on xcode 12.5.1 and macOS 11.5.2.

### ISSUE THREAD

**Issue by shezu** [realm/jazzy#1300]
jazzy version: 0.14.
getting this error when i run jazzy : 

Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild CODE_SIGN_IDENTITY= CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO

User defaults from command line:
    IDEPackageSupportUseBuiltinSCM = YES

Build settings from command line:
    CODE_SIGN_IDENTITY = 
    CODE_SIGNING_ALLOWED = NO
    CODE_SIGNING_REQUIRED = NO

note: Using new build system
note: Using codesigning identity override: 
note: Planning build
note: Analyzing workspace
note: Using build description from disk
note: Build preparation complete
warning: None of the architectures in ARCHS (arm64) are valid. Consider setting ARCHS to $(ARCHS_STANDARD) or updating it to include at least one value from VALID_ARCHS (arm64, arm64e, armv7, armv7s) which is not in EXCLUDED_ARCHS (arm64). (in target 'IConnectYou' from project 'IConnectYou')
PhaseScriptExecution [CP]\ Embed\ Pods\ Frameworks /Users/shahzaib.shamim/ICY_Re_Imagine_iOS/IConnectYou/build/IConnectYou.build/Release-iphoneos/IConnectYou.build/Script-20D6FB3FE675AAFC13266807.sh (in target 'IConnectYou' from project 'IConnectYou')
    cd /Users/shahzaib.shamim/ICY_Re_Imagine_iOS/IConnectYou
    /bin/sh -c /Users/shahzaib.shamim/ICY_Re_Imagine_iOS/IConnectYou/build/IConnectYou.build/Release-iphoneos/IConnectYou.build/Script-20D6FB3FE675AAFC13266807.sh
mkdir -p /Users/shahzaib.shamim/ICY_Re_Imagine_iOS/IConnectYou/build/Release-iphoneos/IConnectYou.app/Frameworks
/Users/shahzaib.shamim/ICY_Re_Imagine_iOS/IConnectYou/Pods/Target Support Files/Pods-IConnectYou/Pods-IConnectYou-frameworks.sh: line 42: source: unbound variable
Command PhaseScriptExecution failed with a nonzero exit code

** BUILD FAILED **

The following build commands failed:
	PhaseScriptExecution [CP]\ Embed\ Pods\ Frameworks /Users/shahzaib.shamim/ICY_Re_Imagine_iOS/IConnectYou/build/IConnectYou.build/Release-iphoneos/IConnectYou.build/Script-20D6FB3FE675AAFC13266807.sh
(1 failure)

**Comment by johnfairh** [comment]
That looks like the `xcodebuild` is failing -- the `Pods-IConnectYou-frameworks.sh` script is not part of jazzy.  You should probably figure out what environment it's missing and how to get `xcodebuild` to build your module properly.

**Comment by johnfairh** [comment]
Closing, answered/inactive.
