### ISSUE TITLE
Mixed Framework Swift & Obj-c documentation

### ISSUE THREAD

**Issue by atacand1920** [realm/jazzy#1304]
Using the sourcekitten command lines then Jazzy from the generated json files , how can we exclude some objective-c headers if we use sourcekitten command lines ?

**Comment by johnfairh** [comment]
The jazzy exclude & include flags are applied to the output of the sourcekitten phase so they should work normally.  You should be able to see what the tools think each file is called in the json.

**Comment by atacand1920** [comment]
tried like this but it doesn't exclude the files: 
jazzy --sourcekitten-sourcefile objcDoc.json,swiftDoc.json --exclude a.h,b.h (a and b are the files that i need to exclude from the documentation)

**Comment by johnfairh** [comment]
Check the readme for instructions on how to use `--exclude` -- if you do that & still have no luck then we'll need a full example.

**Comment by atacand1920** [comment]
Well, i used the :nodoc: keys and it worked like that, so we can not use --exclude after all. Thank you
