### ISSUE TITLE
Xcode 13.3 not reporting undocumented symbols

### ISSUE THREAD

**Issue by wajsic** [realm/jazzy#1306]
Hello - I've just upgraded my build tools to Xcode 13.3.

I use jazzy in combination with standalone sourcekitten. 

Versions:
- jazzy (0.14.2)
- sourcekitten (0.32.0)

First I run:
`sourcekitten doc -- -project project.xcodeproj -target targetname > kitty-docs.json`

Then I feed the sourcekitten doc to jazzy
`jazzy --config .jazzy-config.yaml --sourcekitten-sourcefile kitty-docs.json --output docs/mysdk`

So far it was working (until Xcode 13.3) good, and I was getting `undocumented.json` file with right data, but now no matter what documentation I remove I get 100% coverage. Any ideas what it could have changed? Looking at sourcekitten generated `kitty-docs.json` I can see that not all public symbols have `key.doc` defined, but jazzy is not detecting those. 

Thanks.

**Comment by johnfairh** [comment]
This might be the Swift 5.6 issue described in the release notes -- try setting `--module` in your `jazzy` command?

**Comment by wajsic** [comment]
Yep it works - thanks.
