### ISSUE TITLE
Unicode characters kill the parsing of all subsequent // MARK tags

### ISSUE THREAD

**Issue by brennon** [realm/jazzy#131]
Using `// MARK ...` is super useful in breaking up jazzy's outputted documentation. With code such as this:

```
/**
    Returns the location of one of the gesture's touches in the local
    coordinate system of a given node.    
*/
func locationOfTouch(touchIndex index: Int, inNode node: SKNode?) -> CGPoint {
    return trackingTouches[index].locationInNode(node)
}

// MARK: Getting the Recognizer’s State and Node
```

I get delicious output. However, if I change that to this:

```
/**
    Returns the location of one of the gesture’s touches in the local
    coordinate system of a given node.    
*/
func locationOfTouch(touchIndex index: Int, inNode node: SKNode?) -> CGPoint {
    return trackingTouches[index].locationInNode(node)
}

// MARK: Getting the Recognizer’s State and Node
```

That `// MARK` and every one that follows is not parsed. The difference between the two chunks of source is hard to spot--it's the single quotation mark/inverted comma: ’ vs. '

To be clear, every `// MARK` before the non-ASCII/Unicode character is parsed. In addition, all of my other documentation is parsed. The problem is exactly and only this: any `// MARK` preceded in the original source by a non-ASCII character is not produced in the outputted documentation.

**Comment by jpsim** [comment]
Thanks for reporting this! I just pushed a fix to sourcekitten, which will be included in the next release.

**Comment by segiddins** [comment]
@jpsim did you add a small test case for this?
