### ISSUE TITLE
Some Objective-C methods/variables are not documented without of direct #import

### ISSUE THREAD

**Issue by gerchicovy** [realm/jazzy#1310]
For example:
```
//SomeProtocol.h
@protocol SomeProcol <NSObject>
//...
@end
```

```
//SomeClass.h
@protocol SomeProcol;

@interface SomeClass
//...
@property (nonatomic, weak, nullable) id<SomeProtocol> delegate;
@end
```

The result is `SomeProcol` is documented, `SomeClass` is documented excluding `delegate`.

But in the same time `delegate` appears if I import `SomeProtocol.h` into `SomeClass.h`

**Comment by johnfairh** [comment]
This seems to be a swift/sourcekit issue, see jpsim/sourcekitten#731

**Comment by gerchicovy** [comment]
@johnfairh I agree that the example is duplicated but my case is slightly different.
In my case sometimes code requires direct import for `Foundation` or `UIKit` (for example `Foundation` is not imported directly but it is included in `UIKit` which is imported). But I didn't found the concrete example of this situation.

**Comment by johnfairh** [comment]
Going to close this one -- if you do come up with a concrete example that is not that sourcekitten issue then happy to take a look at it.
