### ISSUE TITLE
How to integrate jazzy with docusaurus?

### ISSUE THREAD

**Issue by monica-m-ps** [realm/jazzy#1316]
I have a whole bunch of documentation in docusaurus. Also added APIs generated with redocly. Now next I want to generate ios reference docs using docusaurus. Can someone please help?

I have generated the files locally. But how to add to the build?
I have looked everywhere but unable to find.

**Comment by johnfairh** [comment]
Jazzy generates static websites from Swift/ObjC modules and markdown using mustache templates.

You can edit the output html, customise the theme (mustache templates) or ask for help from those other tools about integrating static sites into their output.

**Comment by johnfairh** [comment]
Closing, answered/inactive.
