### ISSUE TITLE
0% documentation Coverage with 0 undocumented symbols #1174

### ISSUE THREAD

**Issue by inigoLlamosasConneqtech** [realm/jazzy#1318]
I know this is tackled on https://github.com/realm/jazzy/issues/1174, but it is closed so I am openning a new issue:

Hi, I am still getting this with the following setup:

  Xcode: 14.0 beta 2
  macOS: Monterrey (12.5.1)
  jazzy (0.14.2)

I am trying the following command:

sudo jazzy --podspec ../ctkit.podspec --min-acl fileprivate --module ctkit --output ../docs/website/docs/IT/ios/ios-docs/

The log gives me some messages like:
`Found conflicting type declarations....` or `myMethod() has no USR. First make sure all modules used in your project have been imported. If all used modules are imported, please report this problem by filing an issue at https://github.com/realm/jazzy/issues along with your Xcode project. If this token is declared in an `#if` block, please ignore this message.`

Any theories why I am all the time getting this error? I noticed the project doesn't build. However, running jazzy on this exact project did work about a year ago, getting 20% coverage.

I was thinking, might also have to do with the fact that I am running Xcode beta? I am looking at these changes: https://github.com/realm/jazzy/commit/3a590cda3f6413cfdeb13d616fb079337ef33946

Any help is much appreciated. Thanks

**Comment by johnfairh** [comment]
Jazzy doesn't support Xcode 14 yet - should be a release in the next few days.

**Comment by johnfairh** [comment]
Xcode 14 issue addressed in 0.14.3; please open a new issue if you still have problems with this version once your module is building correctly.
