### ISSUE TITLE
0% documentation Coverage with 0 undocumented symbols

### ISSUE THREAD

**Issue by inigoLlamosasConneqtech** [realm/jazzy#1321]
I know this is tackled on https://github.com/realm/jazzy/issues/1174, and was theoretically going to be fixed on https://github.com/realm/jazzy/issues/1318, but is still persisting on new 0.14.3 version:

Xcode: 14.0 beta 2
macOS: Monterrey (12.5.1)
jazzy (0.14.3)

I am trying the following command:

sudo jazzy --podspec ../ctkit.podspec --min-acl fileprivate --module ctkit --output ../docs/website/docs/IT/ios/ios-docs/

The log gives me some messages like:
`Found conflicting type declarations....` or `myMethod() has no USR. First make sure all modules used in your project have been imported. If all used modules are imported, please report this problem by filing an issue at https://github.com/realm/jazzy/issues along with your Xcode project. If this token is declared in an #if block, please ignore this message.`

Any theories why I am all the time getting this error? I noticed the project doesn't build. However, running jazzy on this exact project did work about a year ago, getting 20% coverage.

I was thinking, might also have to do with the fact that I am running Xcode beta? I am looking at these changes: https://github.com/realm/jazzy/commit/3a590cda3f6413cfdeb13d616fb079337ef33946

Any help is much appreciated. Thanks

**Comment by johnfairh** [comment]
As I wrote in your previous issue, you should get your module building before trying to run jazzy on it.

**Comment by inigoLlamosasConneqtech** [comment]
Correct, it does work
