### ISSUE TITLE
Xcode 14 Error | Could not parse compiler arguments from `xcodebuild` output.

### ISSUE THREAD

**Issue by iSgarb** [realm/jazzy#1323]
Using 'jazzy -c -x -workspace,aarqUtils.xcworkspace,-scheme,aarqUtils' in a Xcode 14 project I get this error:
```
{ platform:iOS Simulator, id:F55AB6C5-A45B-487E-83B0-897A1380E2A2, OS:12.4, name:iPhone Xʀ }

Running xcodebuild

Checking xcodebuild -showBuildSettings

Running xcodebuild

Could not parse compiler arguments from `xcodebuild` output.

Please confirm that `xcodebuild` is building a Swift module.

Saved `xcodebuild` log file: /var/folders/z6/lpx16sy52d183r2j8xzfmmpc0000gp/T/xcodebuild-CBD46787-1E4F-40E1-A918-D4BB12ADFCB4.log
```
Tech Stack:

Cocoapods 1.11.3
Xcode 14.0 (14A309)
Jazzy 0.14.3
macOs 12.6
Mac mini Intel i7 2014

The project does compile with no problem on all targets.

[xcodebuild-CBD46787-1E4F-40E1-A918-D4BB12ADFCB4.log](https://github.com/realm/jazzy/files/9654747/xcodebuild-CBD46787-1E4F-40E1-A918-D4BB12ADFCB4.log)

**Comment by johnfairh** [comment]
The error isn't about a compiler error, it's about not finding the right `swiftc` command in the log. It looks like the log has commands to build the modules {{projectDependencyName1}}, {{projectName}}, and {{projectName}}Tests.

You could try putting the actual module you want to document in the jazzy command with `-module` -- it may be that it's guessing a wrong module name from some environment thing (a podspec?) and then not matching that name in the log.

**Comment by iSgarb** [comment]
-m {{projectName}} solved my problem. Thank You.
