### ISSUE TITLE
Xcode 14 Error | no such module

### ISSUE THREAD

**Issue by iSgarb** [realm/jazzy#1324]
I'm trying to generate the documentation of a Xcode 14 project
First I used this command: **jazzy -c -x -workspace,aarqSecurity.xcworkspace,-scheme,aarqSecurity**
And it gave me this error:
```
Could not successfully run `xcodebuild`.

Please check the build arguments.

Saved `xcodebuild` log file: /var/folders/z6/lpx16sy52d183r2j8xzfmmpc0000gp/T/xcodebuild-65FE941B-8816-4EBF-94C4-B916A7954316.lo
```
[log_1.txt](https://github.com/realm/jazzy/files/9657014/log_1.txt)

Then I tried adding the module with: **jazzy -c -x -workspace,aarqSecurity.xcworkspace,-scheme,aarqSecurity -m aarqSecurity**
Which gave me this error:
```
Could not successfully run `xcodebuild`.

Please check the build arguments.

Saved `xcodebuild` log file: /var/folders/z6/lpx16sy52d183r2j8xzfmmpc0000gp/T/xcodebuild-C9B63E05-C00A-46D5-92B5-6FF1796D5E6E.log
```
[log_2.txt](https://github.com/realm/jazzy/files/9657016/log_2.txt)

In both logs it tells "no such module {{projectName}}".

**Tech Stack:**
Cocoapods 1.11.3
Xcode 14.0 (14A309)
Jazzy 0.14.3
macOs 12.6
Mac mini Intel i7 2014

The project does compile with no problem on all targets.

**Comment by johnfairh** [comment]
The logs are plain text and straight-forward to read.

`log_2.txt` shows (search for `swiftc`) that the only module being built is called `securityKeyChainAppTest`.

The Swift compiler error about an `import` statement not working is something you need to fix: you can see the `xcodebuild` command being run at the top of the file: it looks to me as though it matches your instructions.

**Comment by johnfairh** [comment]
Closing, answered/inactive
