### ISSUE TITLE
Exporting Documentation of our Pod (Library) failed

### ISSUE THREAD

**Issue by rashid-elgrocer** [realm/jazzy#1329]
when i run the jazzy command inside the root of library the build succeed but the documentation failed with below error in terminal.

jazzy
Using config file path of .jazzy.yaml file
WARNING: Unknown config file attribute "--min-acl"
Analyzing dependencies
Downloading dependencies
Installing el-grocer-shopper-sdk-iOS (0.1.3)
Generating Pods project
Skipping User Project Integration
Pod installation complete! There is 1 dependency from the Podfile and 1 total pod installed.
2022-10-13 21:09:14.407 xcodebuild[29891:350305] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionSentinelHostApplications for extension Xcode.DebuggerFoundation.AppExtensionHosts.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
2022-10-13 21:09:14.408 xcodebuild[29891:350305] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionPointIdentifierToBundleIdentifier for extension Xcode.DebuggerFoundation.AppExtensionToBundleIdentifierMap.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
Running xcodebuild
Checking xcodebuild -showBuildSettings
Running xcodebuild
Could not parse compiler arguments from `xcodebuild` output.
Please confirm that `xcodebuild` is building a Swift module.
Saved `xcodebuild` log file: /var/folders/h7/_8q5nbw94t5cy3vk2x7v7bqm0000gp/T/xcodebuild-6C82C928-9748-4344-BE30-DF40A47529D6.log
Error: Failed to generate documentation
/Library/Ruby/Gems/2.6.0/gems/jazzy-0.14.3/lib/jazzy/executable.rb:39:in `execute_command': /Library/Ruby/Gems/2.6.0/gems/jazzy-0.14.3/bin/sourcekitten ["doc", "--module-name", "el_grocer_shopper_sdk_iOS", "--", "-target", "el-grocer-shopper-sdk-iOS"] (RuntimeError)

2022-10-13 21:09:14.407 xcodebuild[29891:350305] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionSentinelHostApplications for extension Xcode.DebuggerFoundation.AppExtensionHosts.watchOS of plug-in com.apple.dt.IDEWatchSupportCore

2022-10-13 21:09:14.408 xcodebuild[29891:350305] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionPointIdentifierToBundleIdentifier for extension Xcode.DebuggerFoundation.AppExtensionToBundleIdentifierMap.watchOS of plug-in com.apple.dt.IDEWatchSupportCore

Running xcodebuild

Checking xcodebuild -showBuildSettings

Running xcodebuild

Could not parse compiler arguments from `xcodebuild` output.

Please confirm that `xcodebuild` is building a Swift module.

Saved `xcodebuild` log file: /var/folders/h7/_8q5nbw94t5cy3vk2x7v7bqm0000gp/T/xcodebuild-6C82C928-9748-4344-BE30-DF40A47529D6.log

Error: Failed to generate documentation
	from /Library/Ruby/Gems/2.6.0/gems/jazzy-0.14.3/lib/jazzy/sourcekitten.rb:269:in `run_sourcekitten'
	from /Library/Ruby/Gems/2.6.0/gems/jazzy-0.14.3/lib/jazzy/podspec_documenter.rb:32:in `block (3 levels) in sourcekitten_output'
	from /Library/Ruby/Gems/2.6.0/gems/jazzy-0.14.3/lib/jazzy/podspec_documenter.rb:30:in `map'
	from /Library/Ruby/Gems/2.6.0/gems/jazzy-0.14.3/lib/jazzy/podspec_documenter.rb:30:in `block (2 levels) in sourcekitten_output'
	from /Library/Ruby/Gems/2.6.0/gems/jazzy-0.14.3/lib/jazzy/podspec_documenter.rb:25:in `chdir'
	from /Library/Ruby/Gems/2.6.0/gems/jazzy-0.14.3/lib/jazzy/podspec_documenter.rb:25:in `block in sourcekitten_output'
	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/config.rb:41:in `with_changes'
	from /Library/Ruby/Gems/2.6.0/gems/jazzy-0.14.3/lib/jazzy/podspec_documenter.rb:20:in `sourcekitten_output'
	from /Library/Ruby/Gems/2.6.0/gems/jazzy-0.14.3/lib/jazzy/doc_builder.rb:76:in `build'
	from /Library/Ruby/Gems/2.6.0/gems/jazzy-0.14.3/bin/jazzy:16:in `<top (required)>'
	from /usr/local/bin/jazzy:23:in `load'
	from /usr/local/bin/jazzy:23:in `<main>'

My Pod folder structure:

<img width="969" alt="Screenshot 2022-10-13 at 9 10 37 PM" src="https://user-images.githubusercontent.com/111747507/195649541-1a12f558-b769-44eb-a1eb-02290afeeae9.png">

jazzy configuration file:

author: Library Teams
module: el-grocer-shopper-sdk-iOS
output: docs
theme: fullwidth
--min-acl: private
podspec: path to my podsepc file

xcodebuild_arguments:
 - -project
 - _Pods.xcodeproj
 - -scheme
 - my_scheme_name
 - CODE_SIGNING_ALLOWED = NO

**Comment by johnfairh** [comment]
The `xcodebuild_arguments` are ignored in podspec mode, you can delete them from your yaml file (or alternatively keep them and delete the `podspec` line.)

You'll need to read or post the Xcode error log mentioned: the tools are saying that the Swift module called `el_grocer_shopper_sdk_iOS` is not being built.  This module name is coming from the podspec, I think.

**Comment by rashid-elgrocer** [comment]
@johnfairh after removing deleting the xcodebuild_arguments didn't have any effect on it, below is the log of xcode build which is succeded.

2022-10-13 22:22:56.685 xcodebuild[30055:358355] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionSentinelHostApplications for extension Xcode.DebuggerFoundation.AppExtensionHosts.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
2022-10-13 22:22:56.685 xcodebuild[30055:358355] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionPointIdentifierToBundleIdentifier for extension Xcode.DebuggerFoundation.AppExtensionToBundleIdentifierMap.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -target el-grocer-shopper-sdk-iOS clean build CODE_SIGN_IDENTITY= CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO

User defaults from command line:
    IDEPackageSupportUseBuiltinSCM = YES

Build settings from command line:
    CODE_SIGN_IDENTITY = 
    CODE_SIGNING_ALLOWED = NO
    CODE_SIGNING_REQUIRED = NO

note: Using new build system
note: Using codesigning identity override: 
error: Could not delete `/var/folders/h7/_8q5nbw94t5cy3vk2x7v7bqm0000gp/T/jazzy20221013-30041-hm1qmuel-grocer-shopper-sdk-iOS/build` because it was not created by the build system.
note: Build preparation complete

** CLEAN FAILED **

note: Using new build system
note: Using codesigning identity override: 
note: Planning
Analyze workspace

Create build description
Build description signature: c07b70b483e6dc7a8b84341043058f90
Build description path: /var/folders/h7/_8q5nbw94t5cy3vk2x7v7bqm0000gp/T/jazzy20221013-30041-hm1qmuel-grocer-shopper-sdk-iOS/Pods/../build/XCBuildData/c07b70b483e6dc7a8b84341043058f90-desc.xcbuild

note: Build preparation complete
warning: Building targets in manual order is deprecated - check "Parallelize build for command-line builds" in the project editor, or set DISABLE_MANUAL_TARGET_ORDER_BUILD_WARNING in any of the targets in the current build to suppress this warning
CreateBuildDirectory /var/folders/h7/_8q5nbw94t5cy3vk2x7v7bqm0000gp/T/jazzy20221013-30041-hm1qmuel-grocer-shopper-sdk-iOS/build/Release-iphoneos/el-grocer-shopper-sdk-iOS
    cd /var/folders/h7/_8q5nbw94t5cy3vk2x7v7bqm0000gp/T/jazzy20221013-30041-hm1qmuel-grocer-shopper-sdk-iOS/Pods/Pods.xcodeproj
    builtin-create-build-directory /var/folders/h7/_8q5nbw94t5cy3vk2x7v7bqm0000gp/T/jazzy20221013-30041-hm1qmuel-grocer-shopper-sdk-iOS/build/Release-iphoneos/el-grocer-shopper-sdk-iOS

** BUILD SUCCEEDED **

**Comment by johnfairh** [comment]
You would need to work through the build files mentioned & figure out why nothing is being built -- might be that error mentioned during 'clean' or could be something is going wrong with your setup and the cocoapods stuff that jazzy uses.

You could try going the other way, delete the `podspec` parameter and use the Xcode build options.

**Comment by rashid-elgrocer** [comment]
> You would need to work through the build files mentioned & figure out why nothing is being built -- might be that error mentioned during 'clean' or could be something is going wrong with your setup and the cocoapods stuff that jazzy uses.
> 
> You could try going the other way, delete the `podspec` parameter and use the Xcode build options.

I already try it this way but its not working, gives with build failure, because external libraries not installing without podspec.

**Comment by johnfairh** [comment]
OK - if you've tried everything then not sure how we can help without a recreatable project to work on.

**Comment by johnfairh** [comment]
Closing, inactive
