### ISSUE TITLE
Migrate installation to homebrew

### ISSUE THREAD

**Issue by jpsim** [realm/jazzy#134]
And deprecate installation via rubygems. This will simplify building sourcekitten from source. Also, if _ever_ we want to port jazzy to Swift, we'll be able to keep installation path.

See https://github.com/thoughtbot/liftoff/issues/49 for other motivations. Any objections, @segiddins?

I think the biggest challenge in doing this will be bundling the other ruby dependencies.

**Comment by segiddins** [comment]
Yes, objections. Will write them up when I'm back in the office.

In summary, I think offering a homebrew installation path is great, but allowing installation as a gem maintains a lot of flexibility for other tools to hook into, especially things like CocoaDocs.

**Comment by orta** [comment]
FWIW, a lot of CD's dependencies are [in brew](https://github.com/CocoaPods/cocoadocs.org/blob/master/Rakefile#L9).

**Comment by jpsim** [comment]
Whatever we decide, I'd rather not have to support two different installation methods.

**Comment by segiddins** [comment]
Lets see how difficult supporting both is before making that decision? I have a feeling that it won't be that hard, and I'm willing to promise maintenance of the gem. 

-Samuel E. Giddins

On Jan 2, 2015, at 6:40 PM, JP Simard <notifications@github.com> wrote:

Whatever we decide, I'd rather not have to support two different installation methods.

**Comment by AliSoftware** [comment]
I am not the only one to prefer installing `jazzy` (and CP) with `gem`, the first reason being that I can install a gem even if I'm not a `sudoer` (generally the case on work computers due to some company policies, sadly)

BTW, even Homebrew suggests that gems should still be installed with `gem` and not `brew` :wink: 

> Homebrew complements OS X. Install your gems with gem, and their dependencies with brew.
_(Source: http://brew.sh)_

**Comment by orta** [comment]
Not to mention being able to do versioning.

**Comment by istx25** [comment]
Any progress on this?

**Comment by jpsim** [comment]
Let's not do this.

**Comment by istx25** [comment]
SGTM.
