### ISSUE TITLE
Latest Jazzy verson  is not generating the link to html file correctly 

### ISSUE THREAD

**Issue by mahavrani** [realm/jazzy#1348]
Below is the synax used in a .md file to linking local .html file 

`[Installation-using-CocoaPods]:./Introduction.html
`
Have called that in a text to link as below 

`[Installation using CocoaPods] [Installation-using-CocoaPods]
`
In Jazzy 0.14.3 the linking does not happen / did not work. But with same md file changes in jazzy 0.14.1 it works fine.

**Comment by johnfairh** [comment]
Can you say exactly how the linking "does not happen / did not work"?  A complete example would help.

For me, on 0.14.3, with a Guide.md containing just:
```markdown
[Installation using CocoaPods] [Installation-using-CocoaPods]
[Installation-using-CocoaPods]:./Introduction.html 
```
...I get this html:
```html
          <section class="section">

            <p><a href="./Introduction.html">Installation using CocoaPods</a> </p>

          </section>
```
...which I think is what I would expect?

I don't think jazzy itself has anything to do with generating this part -- check you're still using a good version of the redcarpet gem, which is what does the markdown->html conversion.

**Comment by johnfairh** [comment]
Closing, inactive.

**Comment by mahavrani** [comment]
Have updated latest gem as well.Only in jazzy 0.14.1  version it works fine.Let me know if you need any sample to trobleshoot

**Comment by johnfairh** [comment]
Please check my comment from Apr 25.
