### ISSUE TITLE
How does Jazzy keep track of what percent of documentation is completed?

### ISSUE THREAD

**Issue by YousufSSyed** [realm/jazzy#1359]
I noticed that docs for Sparkle has a percentage of documentation complete, and they use Jazzy.

**Comment by YousufSSyed** [comment]
@johnfairh Oh my god I accidentally posted this twice, can you delete the other one?!

**Comment by johnfairh** [comment]
Assumed it was your stalker :wink: it's closed, dw.

**Comment by johnfairh** [comment]
Closing, answered.
