### ISSUE TITLE
How does Jazzy keep track of what percent of documentation is completed?

### ISSUE THREAD

**Issue by Oneechan69** [realm/jazzy#1360]
I noticed that docs for Sparkle has a percentage of documentation complete, and they use Jazzy.
<img width="468" alt="Screenshot 2023-08-09 at 9 19 58 AM" src="https://github.com/realm/jazzy/assets/42646062/ab69f2ad-d3d5-44b6-9780-8c9cbfb2f9d4">

**Comment by johnfairh** [comment]
#1359
