### ISSUE TITLE
Jazzy chokes on target names containing '-'

### ISSUE THREAD

**Issue by dabrahams** [realm/jazzy#1364]
For whatever reason, the interface through which Jazzy consults SPM thinks the hyphens in target names are underscores, and [fails to find them](https://github.com/hylo-lang/hylo/actions/runs/6099354153/job/16551865836#step:11:112).  I had to make [this change](https://github.com/hylo-lang/hylo/commit/246c6529383401af08277f84cfd53af491217929) in my extraction procedure to work around it.

**Comment by johnfairh** [comment]
Jazzy and its stack deal with Swift module names, which cannot contain hyphens.

**Comment by johnfairh** [comment]
Closing, answered.
