### ISSUE TITLE
Can't exclude files generated during build.

### ISSUE THREAD

**Issue by clemens-unterkofler** [realm/jazzy#1377]
jazzy version: 0.14.4

Neither of the following works to exclude generated files:

```
exclude:
  - "**/DerivedData/**"
  - "**/DerivedSources/CoreMLGenerated/**"
  - "**/explicitFilename.swift"
```

Symbols are still added to documentation, coverage and undocumented.json.

**Comment by johnfairh** [comment]
There are instructions and examples on the syntax for include/exclude [here](https://github.com/realm/jazzy?tab=readme-ov-file#controlling-what-is-documented) -- if you still can't get it working then will need more info on how you're running jazzy and what your filesystem structure looks like.

**Comment by clemens-unterkofler** [comment]
ok changing to 
- "/*/DerivedData*"

in the .jazzy.yaml file seemed to work
