### ISSUE TITLE
Documenting wrong .xcodeproj file

### ISSUE THREAD

**Issue by ADaley121** [realm/jazzy#138]
Is there a way to specify which .xcodeproj file for jazzy to document? I have Alamofire imported into my xcode project, and when I run jazzy in the folder containing my .xcodeproj file that I want to document, jazzy decides to delve into my Alamofire folder instead and document the Alamofire.xcodeproj in there instead.

**Comment by beltex** [comment]
See `jazzy -h` for the list of options. I think the `-x` option is what your looking for:

```
-x arg1,arg2,…argN,              Arguments to forward to xcodebuild
```

**Comment by segiddins** [comment]
@ADaley121 yes, a scheme is something like `Release` or `Debug`.

**Comment by jpsim** [comment]
No, `Release`/`Debug` are typically build *configurations*, while a scheme would be a build process associated to a target (typically `MyApp` and `MyFramework`).

**Comment by ADaley121** [comment]
Thanks, I got it to work now.
