### ISSUE TITLE
Type alias link generation is not working properly in M1

### ISSUE THREAD

**Issue by mahavrani** [realm/jazzy#1382]
Type alias link generation is not working in M1.It is working in Intel Mac machine.

In Intel maching the type alias added is hidded properly.But in M1 mac its shown explicitly with local html file reference.PFA of sample.md and try generating it from M1 and Intel mac.

[Sample.md](https://github.com/realm/jazzy/files/14837848/Sample.md)

**Comment by johnfairh** [comment]
Please provide a project showing your issue and give the versions of swift/jazzy/macOS.

**Comment by johnfairh** [comment]
Closing, inactive
