### ISSUE TITLE
No parameters listed for `init` methods from symbolgraph.

### ISSUE THREAD

**Issue by thePsguy** [realm/jazzy#1383]
Attached simple symbol graph to reproduce issue.

For a symbol of type `swift.init` with a missing `functionSignature`: 
  - While DocC generates a parameter list:
    <img width="300" alt="image" src="https://github.com/realm/jazzy/assets/10270894/1a1dad53-ddd2-406e-a437-6f0694ee1246">
  - Jazzy does not:
    <img width="300" alt="image" src="https://github.com/realm/jazzy/assets/10270894/cc6a6c3b-9fc0-4732-b379-64447d77482b">

The symbol graph was generated with `swift symbolgraph-extract` like so:
```
swift symbolgraph-extract -target arm64-apple-ios17.4 -pretty-print -module-name TestSwiftModule -output-dir symbolgraphs -sdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS17.4.sdk -I .
```

And for some reason does not populate `functionSignature` for any `swift.init` symbols. (But does for swift func symbols of type `swift.method` with the exact same signature and doc comment.)

I ran DocC on the same symbol graph like so:
```
xcrun docc convert --additional-symbol-graph-dir ./ --output-dir ./docc_docs --hosting-base-path "/" --transform-for-static-hosting
```

And Jazzy like so:
```
jazzy --clean --module TestSwiftModule --swift-build-tool symbolgraph --symbolgraph-directory .
```

Hoping to understand either how I could get Jazzy to generate the parameters list for such a symbolgraph? Can Jazzy do that?
Or why `swift symbolgraph-extract` might not be including `functionSignature` for this module?

Attaching a stripped down simple symbol graph that reproduces this issue.
[TestSwiftModule.symbols.json](https://github.com/realm/jazzy/files/15001678/TestSwiftModule.symbols.json)

**Comment by johnfairh** [comment]
Thanks for reporting this.

Bad news: It's a Swift bug.

Good news: It's [fixed](https://github.com/apple/swift/pull/70207).

Bad news: you need a Swift 6 compiler (eg. swift.org nightly or wait for WWDC).

**Comment by thePsguy** [comment]
Haha, Great!
Thanks for the update! I'll go ahead and close this issue.
