### ISSUE TITLE
Cannot Execute Jazzy that's installed using Bundler on XCode 15.2

### ISSUE THREAD

**Issue by hilmyveradin** [realm/jazzy#1384]
I worked on OSS repo which using jazzy as it's documentation. However, the jazzy script is not recognizable as command and when I run bundle exec jazzy, it fails. Few things:

1. I'm using XCode 15.2
2. I'm using Ruby version 3.2.2
3. Jazzy already included in Gemfile.lock. It even already included in the vendor/bin/ruby file (see first image)
4. It appears there's error like the second image
5. When traced, it has something to do with "file exists but not in directory"

Any idea why?

![image](https://github.com/realm/jazzy/assets/74521244/baab22ed-07d7-4869-b3a3-f0adc62f0309)
![image](https://github.com/realm/jazzy/assets/74521244/411b1cf7-9c10-41d1-9227-1549466c4815)
![image](https://github.com/realm/jazzy/assets/74521244/cc05c1a9-67d5-48a0-83c4-7360888f4604)

**Comment by hilmyveradin** [comment]
I see. But it's expected for the project to be built in order to jazzy to generate documentation right? Or it's not?

I'm kind of confused on how to address this root cause, to be honest

**Comment by johnfairh** [comment]
Yes, jazzy runs `xcodebuild` as part of generating documentation.

You haven't said if you have found a possible `build` file in your project that is breaking things?

You can either rename that file or maybe look at changing `xcodebuild`'s build directory by passing it `-derivedDataDir` (see `man xcodebuild`).

**Comment by johnfairh** [comment]
Closing, answered.
