### ISSUE TITLE
Success or failure depending on compiler configuration

### ISSUE THREAD

**Issue by SimplyDanny** [realm/jazzy#1397]
For the code snippet

```swift
#if canImport(Glibc)
import Glibc
private let globFunction = Glibc.glob
#endif
```

Jazzy reports

```
file.swift:2:8: error: no such module 'Glibc'
import Glibc
       ^
0% documentation coverage with 0 undocumented symbols
```

Making `globFunction` public causes a `'globFunction' has no USR` error. So it seems like Jazzy tries to parse this declaration even though it's running on macOS without a `Glibc`.

On the one hand, all public declarations should be documented no matter on which platform they are active. But on the other hand, the compiler is just unable to report anything reasonable back depending on the scope the declaration is located in. What is the intended behavior in such cases?

**Comment by johnfairh** [comment]
It is a fairly recent SourceKit change to attempt to compile stuff that is `#ifdef`ed out which produces the `no such module` errors.  Unfortunately we cannot distinguish these from genuinely helpful compiler messages about relevant code.  (I think the intent of the change was to improve Xcode behaviour for such code.)

We never really finished making Jazzy support multiple compilation environments -- #750 is the notional tracker for what this ought to do (support compiling the same module multiple times and merging the results together with availability).

Right now what you see is what you get: if you have a docs-visible symbol that is `#ifdef`d out then there's no declaration but the doc comment is preserved where you can write about it (or :nodoc: to just hide it).

I don't know that DocC will do any better in this particular case but in the long term it's probably worth you guys moving in that direction -- the SourceKit interface will continue to gradually degrade!

**Comment by SimplyDanny** [comment]
Got that. Thank you for answering. 

I'll check out what DocC provides. For the time being, Jazzy works well though. The error it reports doesn't break doc generation. So that's acceptable.
