### ISSUE TITLE
Search in page

### ISSUE THREAD

**Issue by jpsim** [realm/jazzy#14]

**Comment by orta** [comment]
https://pspdfkit.com/blog/2016/adding-live-search-to-jazzy/

**Comment by jpsim** [comment]
Hopefully @esad can upstream those changes back in here 😄

**Comment by steipete** [comment]
Yes - still scheduled. We're a bit swamped by other things but will open a PR hopefully soon.

**Comment by narlei** [comment]
Search is very important to a documentation.
![screen shot 2016-07-19 at 08 14 44](https://cloud.githubusercontent.com/assets/8092922/16948531/a3c50b8e-4d8b-11e6-8bd5-9fcfc317fa3e.png)

**Comment by johnfairh** [comment]
Closing, #726 to track adding to the other themes.
