### ISSUE TITLE
Group global constants and functions by the file they're in?

### ISSUE THREAD

**Issue by thePsguy** [realm/jazzy#1400]
I see that specifying`custom_categories` can be used to achieve this, but for growing files, some that hold global constants and some that hold global functions, it is an additional maintenance overhead.

#1170 and #105 seem related, but having an option to group such symbols automatically by the file name / specifying a group at the file level would be amazing.

Is it possible to set up `custom_categories` using wildcards? i.e. maybe a pattern in the symbol names, or based on the file they're in?
If not, what would implementation for wildcards in `custom_categories` or file level grouping look like?

I believe since `custom_categories` is something that is already parsed and processed, adding support for wildcards or parsing files might be a smaller change?
Is it okay if I work on it?
Do we have access to the file name / source directory a symbol was in, in `def self.group_custom_categories(docs)`?
https://github.com/realm/jazzy/blob/4c0ee5dd0c67a566f025368b931547aab79f1cc9/lib/jazzy/sourcekitten.rb#L73-L88

Any pointers / tips would be appreciated.

eg:
```
"custom_categories": [{
        "name": "Global Utilities",
        "children": [
            "file:GlobalUtils.h",
            "regex:*CommonPattern*"
        ]
    }]
```

**Comment by johnfairh** [comment]
Yes it would be fine to add this kind of thing.

You want to be starting at [this method](https://github.com/realm/jazzy/blob/fd0b539c078690b3ed22950c32f44dbc90b33111/lib/jazzy/grouper.rb#L50) now.

At this point, `docs` is an array of top-level `SourceDeclaration`s, each a tree of source-code declarations.  And `doc_index` is all those `SourceDeclarations` processed into a search tree. [Here](https://gist.github.com/johnfairh/fe34ffce1352c8f1876ca879864b9cf6) is a quick implementation of `Enumerable` for `DocIndex` -- I think you probably want to iterate over that to find your candidates.

`SourceDeclaration` has all the metadata in it -- `name` is the local name like `myMethod(arg:)`; `fully_qualified_name` is the name within the declaration's module like `MyClass.myMethod(arg:)`; `fully_qualified_module_name` prepends the module name if you need that.

`SourceDeclaration#file` is whatever SourceKit provides for the source file -- usually the fully-qualified pathname.  If jazzy is in symbol graph mode though this is `nil` -- but your feature is still useful, just handle it gracefully & document.

For the `file` version I would recommend including a glob/wildcard/regexp there -- my experience is that one file is never enough for people!

You need to make sure that your output order is stable, ie. the order of the children generated is fixed for fixed input.
