### ISSUE TITLE
Swift enum cases out of order

### ISSUE THREAD

**Issue by thePsguy** [realm/jazzy#1406]
When generating with the `symbolgraph` build tool, enum cases are listed out of order. The wrong order is consistently the same:
<img src="https://github.com/user-attachments/assets/23172b53-6d42-4d80-a977-718b81c53e47" alt="screenshot" width="550"/>

The above is generated for something like:
```
/// The fields represent individual days of the week.
///
/// Matches NSDateComponents.weekday index.
/// Refer to https://developer.apple.com/documentation/foundation/nsdatecomponents/1410442-weekday
public enum DayOfWeek: UInt {

  case sunday = 1

  case monday = 2

  case tuesday = 3

  case wednesday = 4

  case thursday = 5

  case friday = 6

  case saturday = 7
}
```

The following command was used:
`jazzy --clean --sdk "iphoneos" --module GooglePlacesSwift --output jazzy_gen --swift-build-tool symbolgraph --build-tool-arguments -I,GooglePlacesSwift.xcframework/ios-arm64,-target,arm64-apple-ios17.4`

where the `ios-arm64` directory in the [xcframework](https://dl.google.com/geosdk/swiftpm/0.1.0/google_places_swift.xcframework.zip) contains a `.a` and a `.swiftmodule`

Any ideas where the problem might lie?
I'm open to investigating / creating a PR.

Thanks!

**Comment by johnfairh** [comment]
Symbolgraph sometimes does not give us source location info -- in that case jazzy has to fall back to some kind of default sort order.  I've never really looked into what causes this but I can make it happen artificially by deleting the `<mod>.swiftsourceinfo` file that accompanies the `.swiftmodule` when you do a straight `swiftc -emit-module`.

If I paste your code into a file & do that basic thing to build it, I get source declaration order but if I delete the `.swiftsourceinfo` I get your version.

**Comment by johnfairh** [comment]
Closing, answered
