### ISSUE TITLE
Library not loaded error when running

### ISSUE THREAD

**Issue by Isuru-Nanayakkara** [realm/jazzy#144]
After much trouble I finally installed Jazzy successfully. Then from the Terminal, I navigate inside an Swift Xcode project which I have documented according to the new [Swift documentation](http://nshipster.com/swift-documentation/) syntax and ran the command `jazzy`. But it outputs the following error.

**dyld: Library not loaded: @rpath/libclang.dylib
  Referenced from: /Library/Ruby/Gems/2.0.0/gems/jazzy-0.0.20/bin/sourcekitten
  Reason: image not found
Please pass in xcodebuild arguments using -x
If build arguments are correct, please file an issue on https://github.com/realm/jazzy/issues**

How do I resolve this?

**Comment by beltex** [comment]
Where do you have Xcode installed? It's expected to be under `/Applications/Xcode.app/...`

You can check by running `xcode-select -p`

**Comment by Isuru-Nanayakkara** [comment]
Yes. It returns this.
**/Applications/Xcode-Beta.app/Contents/Developer**

Its the correct path. I have the Xcode 6.2 beta installed.

**Comment by beltex** [comment]
Not quite. Your's is `Xcode-Beta.app`, while expected is `Xcode.app`. I ran into this before [myself](https://github.com/beltex/SMCKit/issues/3#issuecomment-66921109). Simple work around is to create a symlink to your `lib` dir.

```bash
mkdir -p /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr
ln -s /Applications/Xcode-Beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib

**Comment by Isuru-Nanayakkara** [comment]
I see. One question. When I eventualy install a stable Xcode version, do I have to remove the symlink or something?

**Comment by beltex** [comment]
No. When you install a GM version either manually (by placing it in the `/Applications/` dir) or via the App Store it will overwrite that whole directory path and thus the symlink.

Is it working for you now?

**Comment by Isuru-Nanayakkara** [comment]
Yep! That solved it. Works fine nwo. Thank you so much :+1:

**Comment by beltex** [comment]
Nice, np! :)
