### ISSUE TITLE
Markdown

### ISSUE THREAD

**Issue by khoogheem** [realm/jazzy#155]
Looks like although the renderer says space after header is false... it is not producing the correct output.

I have a README.md file that has...

~~~
Blah
==========

Blah is designed to create a base set of functions that will make development easier.  

## Installation

To install the framework copy the project into your existing project.  Under your Target/General add as a Framework.  


**Some of the Classes are Swift Only**, due to use of non portable features such as Strucs/Varidics and Tuples.. and will be noted as such.

##Supported OS

~~~

Whats is odd.. is that on Github the readme shows correctly.. but in the preview if I un block the code.. it shows up like jazzy is producing....

Also for the readme ...
if there is a code block using the <code>~~~</code> looks like it needs have a separated line between it to show up as code

**Comment by segiddins** [comment]
The markdown options have changed slightly on master since the last release.

**Comment by khoogheem** [comment]
Ok.. 
trying the master.. but get an error with source kitten..

~~~
Parsing UIImage+Extension.swift (18/30)
sourcekit: [1:connection-event-handler:9359: 0.0000] Connection interrupt
sourcekit: [1:pingService:9359: 0.0011] pinging service
sourcekit: [1:sourcekitd_send_request_sync:1299: 0.0017] request dropped while restoring service
/jazzy/lib/jazzy/sourcekitten.rb:51:in `run_sourcekitten': Running `/jazzy/lib/jazzy/sourcekitten/sourcekitten doc` failed:  (RuntimeError)
	from /jazzy/lib/jazzy/doc_builder.rb:55:in `build'
	from /jazzy/bin/jazzy:15:in `<main>'
~~~

probably something I did in building it ;)

**Comment by segiddins** [comment]
No, I just need to update the vendored sourcekitten binary :)

**Comment by khoogheem** [comment]
Ok... didn't notice it was using a vended version.. switched out my local one.. the Header stuff works..
But still looks like <code>~~~</code> needs to have a line separation for it to show up correctly as code.

Thanks
