### ISSUE TITLE
Comments after Function name showing up

### ISSUE THREAD

**Issue by khoogheem** [realm/jazzy#156]
Here is what is generated by jazzy:
~~~
public class func addSkipBackupAttributeToItemsAtPath(filePath: String) -> Bool {
		//Che
~~~
 
This is the code:

~~~
	public class func addSkipBackupAttributeToItemsAtPath(filePath: String) -> Bool {
		//Check if the file/path is even valid
		if !NSFileManager.defaultManager().fileExistsAtPath(filePath) {
			return false
		}
~~~

I would expect that any comments after the { should not be showing up...

**Comment by emaloney** [comment]
This looks related to an issue I found here: https://github.com/realm/jazzy/issues/145

**Comment by jpsim** [comment]
@emaloney is right that this is a duplicate of #145.
