### ISSUE TITLE
Functions in Enums that are Extensions ;)-

### ISSUE THREAD

**Issue by khoogheem** [realm/jazzy#157]
Lets say I have an Extension of GKColor (which is a typedef of either UIColor or NSColor) **which BTW always shows as UIColor in the document..  anyway to get typedefs to show up.. (ok not for this issue).

Here is what I have.

~~~
public extension GKColor {
    //MARK: NHL Colors

	//MARK: Anaheim Ducks
	/**
	Provides the Team Colors for the NHL Anaheim Ducks
	*/
	public enum AnaheimDucks {
		/** Color whose RGBA values are (r 0.0 g 0.0 b 0.0 a 1.0) */
		case black
		/** Color whose RGBA values are (r 0.569 g 0.463 b 0.294 a 1.0) */
		case gold
		/** Color whose RGBA values are (r 0.937 g 0.322 b 0.145 a 1.0) */
		case orange
		
		/**
		Provides the color object from the Team Color
		
		:returns: Returns The Color Object
		*/
		public func color() -> GKColor {
			switch self {
			case black:
				return GKColor.blackColor()
			case gold:
				return GKColor(hexString: "91764B")
			case orange:
				return GKColor(hexString: "EF5225")
			}
		}
	}
~~~

The document shows AnaheimDucks.. then
~~~
public enum ArizonaCoyotes
~~~
Which is ok.. however I would also expect it to show that the function color can be applied.

**Comment by jpsim** [comment]
Usually jazzy will show children under the "Show more" link. Is that not the case here?

**Comment by khoogheem** [comment]
Ok.. I didn't even see that ;)

yes.. it is showing when I hit the show more link
