### ISSUE TITLE
Create CocoaPods plugin to document libs

### ISSUE THREAD

**Issue by segiddins** [realm/jazzy#158]
`pod lib document` and `pod spec document`

**Comment by AliSoftware** [comment]
Isn't this feature already provided by simply running `jazzy --podspec Foo.podspec`?

**Comment by segiddins** [comment]
But those aren't CocoaPods commands :)

**Comment by AliSoftware** [comment]
So basically the CP plugin will just be an exact equivalent of the jazzy one, and the only purpose would be to bring that feature to the CP namespace/command for convenience, nothing much, right?

BTW if we were to do that plug-in, I'm not convinced the `document` subcommand name is appropriate; we should probably prefer `pod lib doc` or `pod lib jazzy` for example.

Or maybe instead we could add this feature to the already existing `cocoapods-appledoc` plugin (even if it will invoke `jazzy` there instead and not `appledoc`) or to the `cocoapods-docs` plugin (that only opens the documentation page of a pod for now, but we could talk to the author and add a subcommand for doc generation in there)

**Comment by segiddins** [comment]
Closing as unnecessary.
