### ISSUE TITLE
Library not loaded: @rpath/libswiftCore.dylib sourcekitten

### ISSUE THREAD

**Issue by maltzsama** [realm/jazzy#159]
I did uninstall of jazzy, updated gem, but nothing working
```
dyld: Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/jazzy-0.1.0/lib/jazzy/sourcekitten/sourcekitten
  Reason: image not found
/usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/jazzy-0.1.0/lib/jazzy/sourcekitten.rb:51:in `run_sourcekitten': Running `/usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/jazzy-0.1.0/lib/jazzy/sourcekitten/sourcekitten doc` failed:  (RuntimeError)
	from /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/jazzy-0.1.0/lib/jazzy/doc_builder.rb:55:in `build'
	from /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/jazzy-0.1.0/bin/jazzy:15:in `<top (required)>'
	from /usr/local/var/rbenv/versions/2.1.5/bin/jazzy:23:in `load'
	from /usr/local/var/rbenv/versions/2.1.5/bin/jazzy:23:in `<main>'
```

**Comment by segiddins** [comment]
@maltzsama do you have Xcode (>= 6.1.1) installed as `/Applications/Xcode.app`?

**Comment by ProjectDent** [comment]
I'm getting his same issue, and I have XCode 6.1.1 installed.

**Comment by beltex** [comment]
Seems that for some reason, RubyGems is not downloading the symlink `Current -> A` inside of `lib/jazzy/sourcekitten/SourceKittenFramework.framework`, which is why the `rpath` is failing (as it expects `../Versions/Current/Frameworks`). This may not have been noticed before if you have installed SourceKitten standalone, as it installs the needed `dylib`s at `/Library/Frameworks/SourceKittenFramework.framework/Versions/Current/Frameworks` which is another valid `rpath` (can check via `otool -l` on the SourceKitten binary). `0.0.20` works fine, this is new since SourceKittens Makefile and install structure has changed a bunch.

For those who need a quick work around in the meantime.

```sh
# This will tell you the path to your RubyGem install. For example: /Library/Ruby/Gems/2.0.0/
gem env

cd <RUBY_GEM_PATH>/gems/jazzy-0.1.0/lib/jazzy/sourcekitten/
sudo install_name_tool -add_rpath "@executable_path/SourceKittenFramework.framework/Versions/A/Frameworks" sourcekitten
```

**Comment by maltzsama** [comment]
This works fine :+1:

**Comment by naterhat** [comment]
worked for me too.

**Comment by AliSoftware** [comment]
This patch does not seem to be sufficient for me. Now it can't find `libclang` :/

I installed jazzy this weekend (during the workshop with @jpsim) with a simple `sudo gem install jazzy` so I got the latest version 0.1.0 right now. (and I never installed SourceKitten itself on that computer)

Before the patch I got this error with `libswiftCore.dylib` not being found like above, so I tried to apply the quick fix:
```
$ pwd
/Library/Ruby/Gems/2.0.0/gems/jazzy-0.1.0/lib/jazzy/sourcekitten
$ sudo install_name_tool -add_rpath "@executable_path/SourceKittenFramework.framework/Versions/A/Frameworks" sourcekitten
Password:
```
And tried to launch jazzy again.

The error changed… but now it can't find `libclang.dylib`:
```
dyld: Library not loaded: @rpath/libclang.dylib
  Referenced from: /Library/Ruby/Gems/2.0.0/gems/jazzy-0.1.0/lib/jazzy/sourcekitten/./SourceKittenFramework.framework/SourceKittenFramework
  Reason: image not found
/Library/Ruby/Gems/2.0.0/gems/jazzy-0.1.0/lib/jazzy/sourcekitten.rb:51:in `run_sourcekitten': Running `/Library/Ruby/Gems/2.0.0/gems/jazzy-0.1.0/lib/jazzy/sourcekitten/sourcekitten doc` failed:  (RuntimeError)
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.1.0/lib/jazzy/doc_builder.rb:55:in `build'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.1.0/bin/jazzy:15:in `<top (required)>'
	from /usr/bin/jazzy:23:in `load'
	from /usr/bin/jazzy:23:in `<main>'
```

**Comment by beltex** [comment]
@AliSoftware As I understand it, `libclang.dylib` is sourced from your Xcode install, and it's expected to be at `/Applications/Xcode.app/...` You can check yours via `xcode-select -p`

Here's the solution to that via [symlinks](https://github.com/realm/jazzy/issues/144#issuecomment-69210893) (preferred solution, as it will persist even if a new version of jazzy is installed). Or alternatively, you can add the `rpath` to your specific Xcode install to the binary as we did here previously, though this time its the `SourceKittenFramework` binary which is at `<RUBY_GEM_PATH>/gems/jazzy-0.1.0/lib/jazzy/sourcekitten/SourceKittenFramework.framework/`

So it be

```bash
sudo install_name_tool -add_rpath "<PATH_TO_XCODE>/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib" SourceKittenFramework
```

Hope that helps! :)

**Comment by AliSoftware** [comment]
@beltex I'm ashamed not to have seen that one.
I was quite sure my Xcode was named `Xcode.app` but that's only the case on my work computer; on my personal computer, it was called `Xcode6.app` instead and that's indeed the reason it failed.
Once renamed (and `xcode-select`-ed), `jazzy` worked fine.

Thanks for your insight! :saxophone:

**Comment by beltex** [comment]
np! :)

**Comment by rodriguise** [comment]
I get this error too, and my Xcode is in the usual place. After the "patch" above I still get:

Failed to generate documentation
/Library/Ruby/Gems/2.0.0/gems/jazzy-0.1.0/lib/jazzy/sourcekitten.rb:51:in `run_sourcekitten': Running `/Library/Ruby/Gems/2.0.0/gems/jazzy-0.1.0/lib/jazzy/sourcekitten/sourcekitten doc` failed:  (RuntimeError)
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.1.0/lib/jazzy/doc_builder.rb:55:in `build'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.1.0/bin/jazzy:15:in `<top (required)>'
	from /usr/bin/jazzy:23:in `load'
	from /usr/bin/jazzy:23:in `<main>'

**Comment by segiddins** [comment]
@rodriguise your error is unrelated -- SourceKitten is running for you, but it's encountering an error along the way.

**Comment by beltex** [comment]
Same error still :(

Symlinks are there now, but some are not quite correct.

```bash
# Should link to '-> Versions/Current/SourceKittenFramework'
$ pwd
/Library/Ruby/Gems/2.0.0/gems/jazzy-0.1.1/lib/jazzy/SourceKitten/SourceKittenFramework.framework
$ ls -l SourceKittenFramework.framework
lrwxr-xr-x  1 root  wheel  48 17 Feb 20:19 SourceKittenFramework.framework -> Versions/Current/SourceKittenFramework.framework

# Should link to '-> A'
$ cd Versions
$ ls -l Current
lrwxr-xr-x  1 root  wheel  10 17 Feb 20:19 Current -> Versions/A
```

**Comment by segiddins** [comment]
@beltex any chance you could submit a PR fixing this?

**Comment by jballands** [comment]
I'm still getting the same issue. Xcode 6.1.1, Jazzy 0.1.1:

<code>
dyld: Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: /usr/local/lib/ruby/gems/2.2.0/gems/jazzy-0.1.1/lib/jazzy/sourcekitten/sourcekitten
  Reason: image not found
/usr/local/lib/ruby/gems/2.2.0/gems/jazzy-0.1.1/lib/jazzy/sourcekitten.rb:51:in `run_sourcekitten': Running `/usr/local/lib/ruby/gems/2.2.0/gems/jazzy-0.1.1/lib/jazzy/sourcekitten/sourcekitten doc` failed:  (RuntimeError)
	from /usr/local/lib/ruby/gems/2.2.0/gems/jazzy-0.1.1/lib/jazzy/doc_builder.rb:55:in `build'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jazzy-0.1.1/bin/jazzy:15:in `<top (required)>'
	from /usr/local/bin/jazzy:23:in `load'
	from /usr/local/bin/jazzy:23:in `<main>'
/Users/ajballan/Documents/Work Stuff/Development/ReadyApp RT/docs/scripts
</code>

Post regarding the <code>install_name_tool</code> works, but latest version of Jazzy doesn't work out of the box.

**Comment by segiddins** [comment]
@jballands where do you have Xcode installed?

**Comment by jballands** [comment]
@segiddins <code>/Applications/Xcode.app</code>

**Comment by trishayy** [comment]
I can also confirm that this problem is still occuring.

**Comment by emaloney** [comment]
I was having this problem as well, and was able to resolve it by manually installing SourceKitten 0.3.1 directly from the .pkg file [downloadable here](https://github.com/jpsim/SourceKitten/releases/tag/0.3.1).

Hope this helps!

**Comment by 0xced** [comment]
No need to use `install_name_tool`, just fixing the frameworks structure should be enough. For some reason, the frameworks installed inside the sourcekitten directory have a symbolic link for `Current -> Versions/A` instead of `Current -> A`.

Here is how to fix it:
```
$ cd /Library/Ruby/Gems/2.0.0/gems/jazzy-0.1.1/lib/jazzy/sourcekitten
$ for framework in *.framework; do pushd "$framework/Versions" && sudo ln -fs A Current && popd; done
/Library/Ruby/Gems/2.0.0/gems/jazzy-0.1.1/lib/jazzy/sourcekitten/Commandant.framework/Versions /Library/Ruby/Gems/2.0.0/gems/jazzy-0.1.1/lib/jazzy/sourcekitten
/Library/Ruby/Gems/2.0.0/gems/jazzy-0.1.1/lib/jazzy/sourcekitten
/Library/Ruby/Gems/2.0.0/gems/jazzy-0.1.1/lib/jazzy/sourcekitten/LlamaKit.framework/Versions /Library/Ruby/Gems/2.0.0/gems/jazzy-0.1.1/lib/jazzy/sourcekitten
/Library/Ruby/Gems/2.0.0/gems/jazzy-0.1.1/lib/jazzy/sourcekitten
/Library/Ruby/Gems/2.0.0/gems/jazzy-0.1.1/lib/jazzy/sourcekitten/SourceKittenFramework.framework/Versions /Library/Ruby/Gems/2.0.0/gems/jazzy-0.1.1/lib/jazzy/sourcekitten
/Library/Ruby/Gems/2.0.0/gems/jazzy-0.1.1/lib/jazzy/sourcekitten
```

**Comment by beltex** [comment]
@segiddins Done! Let me know if it works for you.

And sorry about the late response, was held up with a few things.

**Comment by segiddins** [comment]
No worries :) I really appreciate the help.

**Comment by beltex** [comment]
Hi folks! The latest version of jazzy (`0.1.2`) should have this fixed. There still seems to be some issues nonetheless though - https://github.com/realm/jazzy/issues/170

If you can give it a shot and report back the result it would be most appreciated! :)

**Comment by trishayy** [comment]
I had a coworker run the latest version of jazzy and he said that he had no issues! 

Thanks for everything.

**Comment by beltex** [comment]
@trishayy Awesome, thanks!
