### ISSUE TITLE
ERROR: Failed to build gem native extension.

### ISSUE THREAD

**Issue by Codeido** [realm/jazzy#165]
Hello.

After entering the command
```
sudo gem install jazzy
```

i receive this error:

```
Building native extensions.  This could take a while...
ERROR:  Error installing jazzy:
	ERROR: Failed to build gem native extension.

    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby extconf.rb
checking if the C compiler accepts ... yes
checking if the C compiler accepts -Wno-error=unused-command-line-argument-hard-error-in-future... no
Building nokogiri using packaged libraries.
-----
The file "/usr/include/iconv.h" is missing in your build environment,
which means you haven't installed Xcode Command Line Tools properly.

To install Command Line Tools, try running `xcode-select --install` on
terminal and follow the instructions.  If it fails, open Xcode.app,
select from the menu "Xcode" - "Open Developer Tool" - "More Developer
Tools" to open the developer site, download the installer for your OS
version and run it.
-----
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
	--help
	--clean
	--use-system-libraries
	--enable-static
	--disable-static
	--with-zlib-dir
	--without-zlib-dir
	--with-zlib-include
	--without-zlib-include=${zlib-dir}/include
	--with-zlib-lib
	--without-zlib-lib=${zlib-dir}/lib
	--enable-cross-build
	--disable-cross-build


Gem files will remain installed in /Library/Ruby/Gems/2.0.0/gems/nokogiri-1.6.6.2 for inspection.
Results logged to /Library/Ruby/Gems/2.0.0/gems/nokogiri-1.6.6.2/ext/nokogiri/gem_make.out
```

What is the reason for this error?

**Comment by segiddins** [comment]
That's an issue with compiling that version of Nokogiri on OS X.

**Comment by beltex** [comment]
@Codeido I ran into this as well. The workaround mentioned [here](http://www.virtlab.cx/ruby-fix-error-install-nokogiri-yosemite/) fixed it, via this [comment](https://github.com/sparklemotion/nokogiri/issues/1231#issuecomment-75485561) from the Nokogiri issue thread.

**Comment by JorgenAndreasson** [comment]
Also having difficulty installing jazzy.
Here is the output I receive;

    Building native extensions.  This could take a while...
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby extconf.rb
    creating Makefile
    make "DESTDIR="
    make: *** No rule to make target `/Applications/Xcode-            beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/L    ibrary/Frameworks/Ruby.framework/Versions/2.0/usr/include/ruby-2.0.0/universal-        darwin14/ruby/config.h', needed by `autolink.o'.  Stop.
    ERROR:  Error installing jazzy:
	ERROR: Failed to build gem native extension.

    Building has failed. See above output for more information on the failure.

    Gem files will remain installed in /Library/Ruby/Gems/2.0.0/gems/redcarpet-3.3.2 for inspection.
    Results logged to /Library/Ruby/Gems/2.0.0/gems/redcarpet-3.3.2/ext/redcarpet/gem_make.out
    

Please excuse the formatting....

**Comment by izotx** [comment]
xcode-select --install
Let me move to the next warning-error which now says:
unable to convert "\xCF" from ASCII-8BIT to UTF-8 for lib/jazzy/SourceKitten/Frameworks/SourceKittenFramework.framework/SourceKittenFramework

**Comment by dim971** [comment]
Based on jsross comment https://github.com/vmg/redcarpet/issues/668#issuecomment-444283767, I disabled SIP to copy universal-darwin17 with cp -R universal-darwin17 universal-darwin18 and then gem install jazzy, it works for me.
