### ISSUE TITLE
Wrong parsing with unicode characters

### ISSUE THREAD

**Issue by parkboo** [realm/jazzy#169]
Thanks for great project!

Jazzy just works fine with english characters but I found that it has some problem when using unicode characters (like Korean, Chinese, etc.) in swift source code like below:

![2015-02-27 11 28 08](https://cloud.githubusercontent.com/assets/4056576/6406411/c7cbe186-be73-11e4-9e50-ed96b455e67d.png)

Text encoding of swift file is utf-8.
Any workaround?

**Comment by jpsim** [comment]
@parkboo sorry for taking so long to get back to you. This is now fixed as of 0.1.5. Could you please try again to confirm? Thanks!
