### ISSUE TITLE
Update to jazzy-0.1.2 with XCode 6.3 beta 1(6D520o)

### ISSUE THREAD

**Issue by juangamnik** [realm/jazzy#170]
I updated jazzy to v0.1.2 and my `xcode-select -p` set to:
```bash
/Applications/Xcode-Beta.app/Contents/Developer
```

When I start jazzy afterwards:

```bash
$ jazzy -c
 dyld: Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: /Library/Ruby/Gems/2.0.0/gems/jazzy-0.1.2/lib/jazzy/sourcekitten/sourcekitten
  Reason: image not found
/Library/Ruby/Gems/2.0.0/gems/jazzy-0.1.2/lib/jazzy/sourcekitten.rb:51:in `run_sourcekitten': Running `/Library/Ruby/Gems/2.0.0/gems/jazzy-0.1.2/lib/jazzy/sourcekitten/sourcekitten doc` failed:  (RuntimeError)
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.1.2/lib/jazzy/doc_builder.rb:55:in `build'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.1.2/bin/jazzy:15:in `<top (required)>'
	from /usr/local/bin/jazzy:24:in `load'
	from /usr/local/bin/jazzy:24:in `<main>'
```

And a window pops up that there is a problem with the installation of sourekitten.

My hypothesis is that during installation of sourcekitten the swift code couldn't be compiled as it is not swift 1.2 compatible. But what should I do now to get it running again? change xcode-select to XCode 6.1 and reinstall the gem?

**Comment by segiddins** [comment]
It should be enough to have 6.1 or 6.1 installed at or symlinked to /applications/xcode.app

**Comment by juangamnik** [comment]
Hmm, I have installed Xcode Version 6.1.1 (6A2006) and it is situated at `/Applications/Xcode.app`.

**Comment by beltex** [comment]
Hi @juangamnik! This seems to suggest that the symlink to `libswiftCore.dylib` is broken. Strange, as the latest release should have fixed this. Try running a `ls -l` (or even better `tree` if you have it installed; `brew install tree`) from inside of 

```
/Library/Ruby/Gems/2.0.0/gems/jazzy-0.1.2/lib/jazzy/sourcekitten/SourceKittenFramework.framework/
```

This is how it should be

```
$ tree
.
├── Modules -> Versions/Current/Modules
├── Resources -> Versions/Current/Resources
├── SourceKittenFramework -> Versions/Current/SourceKittenFramework
└── Versions
    ├── A
    │   ├── Frameworks
    │   │   ├── SwiftXPC.framework
    │   │   │   ├── SwiftXPC
    │   │   │   └── Versions
    │   │   │       └── A
    │   │   │           ├── Modules
    │   │   │           │   ├── SwiftXPC.swiftmodule
    │   │   │           │   │   ├── x86_64.swiftdoc
    │   │   │           │   │   └── x86_64.swiftmodule
    │   │   │           │   └── module.modulemap
    │   │   │           ├── Resources
    │   │   │           │   └── Info.plist
    │   │   │           └── SwiftXPC
    │   │   ├── libswiftCore.dylib
    │   │   ├── libswiftCoreGraphics.dylib
    │   │   ├── libswiftDarwin.dylib
    │   │   ├── libswiftDispatch.dylib
    │   │   ├── libswiftFoundation.dylib
    │   │   ├── libswiftObjectiveC.dylib
    │   │   └── libswiftSecurity.dylib
    │   ├── Modules
    │   │   ├── SourceKittenFramework.swiftmodule
    │   │   │   ├── x86_64.swiftdoc
    │   │   │   └── x86_64.swiftmodule
    │   │   └── module.modulemap
    │   ├── Resources
    │   │   └── Info.plist
    │   └── SourceKittenFramework
    └── Current -> A
```

If `libswiftCore.dylib` is not being found then this path is invalid for some reason

`../SourceKittenFramework.framework/Versions/Current/Frameworks/`

**Comment by juangamnik** [comment]
For me the result of tree is:

```bash
$ tree 
.
├── SourceKittenFramework
└── Versions
    └── A
        ├── Frameworks
        │   ├── SwiftXPC.framework
        │   │   ├── SwiftXPC
        │   │   └── Versions
        │   │       └── A
        │   │           ├── Modules
        │   │           │   ├── SwiftXPC.swiftmodule
        │   │           │   │   ├── x86_64.swiftdoc
        │   │           │   │   └── x86_64.swiftmodule
        │   │           │   └── module.modulemap
        │   │           ├── Resources
        │   │           │   └── Info.plist
        │   │           └── SwiftXPC
        │   ├── libswiftCore.dylib
        │   ├── libswiftCoreGraphics.dylib
        │   ├── libswiftDarwin.dylib
        │   ├── libswiftDispatch.dylib
        │   ├── libswiftFoundation.dylib
        │   ├── libswiftObjectiveC.dylib
        │   └── libswiftSecurity.dylib
        ├── Modules
        │   ├── SourceKittenFramework.swiftmodule
        │   │   ├── x86_64.swiftdoc
        │   │   └── x86_64.swiftmodule
        │   └── module.modulemap
        ├── Resources
        │   └── Info.plist
        └── SourceKittenFramework

12 directories, 19 files
```

**Comment by juangamnik** [comment]
`SourceKittenFramework` is no symbolic link but concrete file:

```bash
$ file SourceKittenFramework 
SourceKittenFramework: Mach-O 64-bit dynamically linked shared library x86_64
```

**Comment by juangamnik** [comment]
OK, I added by hand the symbolic link `Current -> A` and `SourceKittenFramework -> Versions/Current/SourceKittenFramework`. Now this issue is gone. Perhaps there is something wrong in the installation routine?

**Comment by beltex** [comment]
Yeah the symlinks are not being created for some reason, so the destination file is being put in its place. The `Rakefile` in `lib/jazzy/SourceKitten/` handles this. I'm not sure why its failing to do so. I just tried a fresh install of jazzy, and the symlinks are created as expected. @segiddins Are you seeing the same?

**Comment by segiddins** [comment]
It's working for me, so I'm afraid I can't be of much help. 

-Samuel E. Giddins

On Mar 1, 2015, at 10:07 AM, beltex <notifications@github.com> wrote:

Yeah the symlinks are not being created for some reason, so the destination file is being put in its place. The Rakefile in lib/jazzy/SourceKitten/ handles this. I'm not sure why its failing to do so. I just tried a fresh install of jazzy, and the symlinks are created as expected. @segiddins Are you seeing the same?

**Comment by beltex** [comment]
Cool, so its not just my machine then! :)

I'll check with the other thread that raised this issue previously.

**Comment by juangamnik** [comment]
I tried to reinstall jazzy and it didn't help. It works for me now. But if you guys need more information for fixing the underlying problem (or just telling me how I can hold it correctly ;) ) I am eager to help. So just ask.

**Comment by beltex** [comment]
Sounds good, will do! :)

**Comment by jeeftor** [comment]
Xcode 6.3 beta didn't work for me - but switching to 6.2 worked fine.

**Comment by juangamnik** [comment]
update to jazzy v0.2.0 (XCode 6.3 installed) works.
