### ISSUE TITLE
Erroneous multiline code block formatting

### ISSUE THREAD

**Issue by cvasilak** [realm/jazzy#172]
Hi,

came across an issue when the comments contain a multiline code block example. That is the following is rendered as single-line instead of multiline
>
/**
a test function
>
>Here is an example usage:
\`\`\`
var foobar = \[String\]\(\)
foobar.append("foo")
\`\`\`
public func test() {...}

Here is a [screenshot](http://tinyurl.com/lp2du5m) of the render

Note that the same occurs if using the four-space indentation instead of the ` character. It always defaults to single-line.

**Comment by jpsim** [comment]
This is fixed as of 0.1.5. Thanks for reporting!
