### ISSUE TITLE
Allow ignoring files

### ISSUE THREAD

**Issue by K4stor** [realm/jazzy#173]
Hi there,

is there a way to leave files out of the documentation ?
Like the appdelegate. I dont wanna document that one :D

And ofc, thanks for dat awesome tool

Regards

**Comment by jpsim** [comment]
@K4stor it's not currently possible, though it should be pretty easy to do.

**Comment by bryanbartow** [comment]
I second this request. It would be extremely helpful (for me at least).

**Comment by jessesquires** [comment]
Can't you use this?

````
/// :nodoc:
````

**Comment by bryanbartow** [comment]
@jessesquires That doesn't seem to have any effect for me.

**Comment by jessesquires** [comment]
@bryanbartow , [here's](https://github.com/jessesquires/JSQCoreDataKit/blob/develop/JSQCoreDataKit/JSQCoreDataKit/CoreDataModel.swift#L120-L127) a working example

**Comment by jpsim** [comment]
You can use `/// :nodoc:` to ignore explicit declarations, but not entire files.

Adding a feature to ignore files should be very easy: it's just a matter of adding an `--ignored-files` CLI argument in [config.rb](https://github.com/realm/jazzy/blob/master/lib/jazzy/config.rb) and then filter SourceKitten's output based on that list of files in [sourcekitten.rb](https://github.com/realm/jazzy/blob/master/lib/jazzy/sourcekitten.rb#L247).

**Comment by jpsim** [comment]
I've opened #219 as a possible implementation of this feature. Let me know what you think!
