### ISSUE TITLE
Intro-page

### ISSUE THREAD

**Issue by K4stor** [realm/jazzy#174]
Hi 

It would be nice,
if I could add an introduction page. I am documenting an SDK so a page 
as general overview would be nice !

Or is that actually possible ?

Regards

**Comment by segiddins** [comment]
Yup! That's exactly what the README option does :)

**Comment by jpsim** [comment]
> Yup! That's exactly what the README option does :)

It should be as simple as having a `README.md` or similar in the same directory where you run jazzy.
