### ISSUE TITLE
Code font too small?

### ISSUE THREAD

**Issue by jessesquires** [realm/jazzy#175]
Looks like jazzy is using `12px` Menlo. Maybe it should be bumped to `13px` ?

When comparing to docs generated by CocoaDocs (appledoc), jazzy feels/looks odd and is a bit harder to read.

**Comment by beltex** [comment]
Hi @jessesquires!

The font and size was [picked](https://github.com/realm/jazzy/issues/137) simply to gain parity with Apple’s own document style/theme, which jazzy attempts to duplicate. So it could certainly be changed. In addition, #130 will help with this as well, making styles easy to configure.

As a quick workaround, you can always modify the `jazzy.css.scss` file in your jazzy install, [line 3](https://github.com/realm/jazzy/blob/master/lib/jazzy/assets/css/jazzy.css.scss#L3) will do the trick! (Located inside your RubyGem install, can check via `gem env | grep INSTALLATION` - for example `/Library/Ruby/Gems/2.0.0/gems/jazzy-0.1.2/`)

**Comment by jessesquires** [comment]
Awesome! :+1: Thanks @beltex

**Comment by beltex** [comment]
np! :)
