### ISSUE TITLE
Second and subsequent lines of multi-line function declaration are omitted from docs

### ISSUE THREAD

**Issue by emaloney** [realm/jazzy#176]
I've created a multi-line function declaration broken up with carriage returns.

The code is formatted as follows:

![screen shot 2015-03-10 at 6 15 06 pm](https://cloud.githubusercontent.com/assets/3768925/6586690/f5ba5b68-c751-11e4-82ec-f7badec66a30.png)

Using `jazzy` version `0.1.2`, only the first line of the declaration appears in the documentation:

![screen shot 2015-03-10 at 6 15 29 pm](https://cloud.githubusercontent.com/assets/3768925/6586708/2013bb66-c752-11e4-8a86-7bd1c7f13e4a.png)

**Comment by jpsim** [comment]
This is fixed as of 0.1.5. Thanks for reporting!
