### ISSUE TITLE
Documentation coverage incorrect, issues with subscripts

### ISSUE THREAD

**Issue by jessesquires** [realm/jazzy#178]
Related to #63 and #69.

I have 100% coverage for [JSQDataSourcesKit](http://www.jessesquires.com/JSQDataSourcesKit/), but jazzy is reporting 89%.

If you look at the source, there are a few `public subscript`s that are *not* documented. However, when I attempt to add docs for these, jazzy reports 86%.

------------------------------------------

**Subscripts:**
I'm not sure how this may be improved, but I also wanted to mention it.

Currently, what jazzy generates for subscripts is a bit odd. It's hard to describe, so it would be best to look at an example. I'm using [VVDocumenter](https://github.com/onevcat/VVDocumenter-Xcode) to generate doc comments and what it generates makes sense (as in, I understand what it's *attempting* to do), but it treats subscripts like a normal function — thus, the odd docs/comments. Unfortunately, there's also no guidance from the Swift std lib on how to write docs for subscripts.

**Comment by jessesquires** [comment]
**Update:**

I just completed docs for [JSQCoreDataKit](http://www.jessesquires.com/JSQCoreDataKit). It also has 100% coverage, but jazzy is reporting 91%.

This framework is much simpler than the one I sited previously in the original issue comment. It has fairly simple classes and structs, no subscripts or generics.

------------------------------------------------

Both of these repos (`JSQDataSourcesKit` and `JSQCoreDataKit`) contain a `build_docs.sh` script. For testing/verifying this issue, you can run this after cloning either repo.

**Comment by jessesquires** [comment]
**Update:**

Docs hosted by CocoaDocs report incorrect coverage.
My GitHub pages: [JSQDataSourcesKit](http://www.jessesquires.com/JSQDataSourcesKit/) says 89%.
CocoaDocs: [JSQDataSourcesKit](http://cocoadocs.org/docsets/JSQDataSourcesKit/1.0.0/) says 29%.

**Comment by jpsim** [comment]
@jessesquires first of all, thanks for using jazzy in your projects and reporting these issues!

You bring up a few distinct problems in your comments.

**1. CocoaDocs**

CocoaDocs is running an outdated version of jazzy which considered private declarations in the documentation coverage statistics. I'll see if I can get that version updated.

**2. Initializers with parameters are incorrectly detected as undocumented**

> I have 100% coverage for JSQDataSourcesKit, but jazzy is reporting 89%.

I created #183 to track this and have a pending fix in #184. Thanks for reporting it.

**3. Subscripts**

> If you look at the source, there are a few public subscripts that are not documented. However, when I attempt to add docs for these, jazzy reports 86%.

Jazzy doesn't really support documenting subscripts just yet. This is being tracked in https://github.com/jpsim/SourceKitten/issues/27.

**Comment by segiddins** [comment]
@jpsim CocoaDocs is running with Jazzy 0.1.2, and I'm pretty sure it has the minimum ACL set to public?

**Comment by jessesquires** [comment]
@jpsim :+1: No problem! Thanks for the update/info and fixes! :smile:

**Comment by jessesquires** [comment]
Fixed in [v0.1.4](https://github.com/realm/jazzy/releases/tag/v0.1.4).

The following now correctly report 100% coverage. :tada: :tada: 

* http://www.jessesquires.com/JSQDataSourcesKit/
* http://www.jessesquires.com/JSQCoreDataKit/
* http://www.jessesquires.com/JSQNotificationObserverKit/

Thanks for the hard work @jpsim and @segiddins !
