### ISSUE TITLE
deinit methods are documented, but shouldn't be

### ISSUE THREAD

**Issue by jessesquires** [realm/jazzy#191]
Jazzy generates docs for `deinit` methods. Example here for [JSQNotificationObserverKit](http://www.jessesquires.com/JSQNotificationObserverKit/Classes/NotificationObserver.html).

Based on how jazzy works, it makes sense why this is happening. However, I think that `deinit` should be treated as a `private` method. Unfortunately, the `private` modifier cannot be applied to `deinit`.

**Comment by segiddins** [comment]
I'd just recommend using `:nodoc:` on their doc comments.

**Comment by jessesquires** [comment]
Hey @segiddins - can you clarify that? 

The following still generates docs for `deinit` with a description of "nodoc".

````swift
///  :nodoc:
deinit {
    // deinit code
}
````

**Comment by segiddins** [comment]
Are you using the latest version of jazzy (0.1.4)?

**Comment by jessesquires** [comment]
doh! Just updated and it's all good! :+1: 

Thanks @segiddins !
