### ISSUE TITLE
When using --source-directory, README is not parsed for index.html

### ISSUE THREAD

**Issue by jessesquires** [realm/jazzy#196]
The `--source-directory` option is now working, however the `README` must be in the specified directory.

As mentioned in #177, I have the following structure:
````
├── Example
│   ├── Example.xcodeproj
├── JSQDataSourcesKit
│   ├── JSQDataSourcesKit.xcodeproj
├── README.md
````

Because I specify a source directory of `JSQDataSourcesKit/` for the framework, the `README` at the root directory is not parsed. It makes sense why this would happen, but is this expected behavior?

I'm currently working around this by including a `README` in `JSQDataSourcesKit/`, but I'm not sure if there's a better way.

**Comment by jpsim** [comment]
> It makes sense why this would happen, but is this expected behavior?

Nope :grinning:! But Sam's PR just addressed this. Go Sam.

**Comment by jessesquires** [comment]
awesome!

![img](http://media.giphy.com/media/aVgaFxzKX9E64/giphy.gif)
