### ISSUE TITLE
Line breaks not obeyed consistently

### ISSUE THREAD

**Issue by emaloney** [realm/jazzy#199]
When documenting the member of a class, struct or enum, the line breaks in the description portion of the comment are ignored.

This source:

![screen shot 2015-03-26 at 5 01 53 pm](https://cloud.githubusercontent.com/assets/3768925/6857239/d5db365a-d3db-11e4-9c11-b027caca819e.png)

produces this documentation:

![screen shot 2015-03-26 at 5 01 41 pm](https://cloud.githubusercontent.com/assets/3768925/6857255/ee0274d2-d3db-11e4-970c-73c022db1dce.png)

Note that text following a line break is appended to the end of the previous line without a space. Adding a space at the end of the previous line works to separate the sentences, but some of us have been encouraged by our colleagues to set up Xcode to strip trailing spaces. ;)

Interestingly, the entity-level descriptions work slightly differently:

![screen shot 2015-03-26 at 5 18 03 pm](https://cloud.githubusercontent.com/assets/3768925/6857302/27bb711a-d3dc-11e4-9f90-97635df21da6.png)

The first line break is obeyed, but subsequent ones are ignored:

![screen shot 2015-03-26 at 5 18 17 pm](https://cloud.githubusercontent.com/assets/3768925/6857308/31e50318-d3dc-11e4-8eb0-1cd319db1453.png)

**Comment by segiddins** [comment]
This is a known issue that @jpsim is working on.

**Comment by jpsim** [comment]
Yes, I'm working on fixing this, and many other markdown rendering issues in the process. I'll update this issue when I have a PR ready with fixes.

**Comment by jpsim** [comment]
This is now fixed.
