### ISSUE TITLE
How do I change default (html) display to show body of documented items?

### ISSUE THREAD

**Issue by Mozahler** [realm/jazzy#201]
I don't know css, jquery and html coding, and have been trying to figure this out for quite some time. I display jazzy output in a webview on my 6+, and I'd like the right hand side of the screen to be fully expanded when it displays after selecting a class on the left side, rather than have to manually scroll down and click on every link on the page. I don't know where to look/what to update to make the default "fully expanded", but surely it is an easy thing to update (a JQuery file?)  when I copy the docs directory to the device... right?

**Comment by Mozahler** [comment]
I'm thinking it involves the JQuery show() command

**Comment by jpsim** [comment]
Add the following to the bottom of `lib/jazzy/assets/css/jazzy.css`:

```css
#reference {
  .height-container {
    display: block;
  }
}
```

and remove all the script tags in `lib/jazzy/doc.mustache` and everything will be expanded.

**Comment by Mozahler** [comment]
thank you, thank you.

**Comment by Mozahler** [comment]
Not quite there, yet. I added the #reference just inside the bottom/closing brace. 
I removed all script tags, as follows (Did I do this wrong? output looks the same as it used to - no expansion)  

here's a diff of the edited vs.  original doc.mustache file

>     <script type="text/javascript">
>     window.jazzy = {'docset': false}
>     if (typeof window.dash != 'undefined') {
>       document.documentElement.className += ' dash'
>       window.jazzy.docset = true
>     }
>     if (navigator.userAgent.match(/xcode/i)) {
>       document.documentElement.className += ' xcode'
>       window.jazzy.docset = true
>     }
>     </script>
>     <script src="{{path_to_root}}js/jquery.min.js" defer></script>
>     <script src="{{path_to_root}}js/jazzy.js" defer></script>

**Comment by jpsim** [comment]
> I added the #reference just inside the bottom/closing brace.

It has to be at the very bottom, not inside the bottom closing brace.

**Comment by Mozahler** [comment]
Wow that's fast!! thanks again!

**Comment by Mozahler** [comment]
![screen shot 2015-04-04 at 7 57 16 pm](https://cloud.githubusercontent.com/assets/9641531/6995170/fdc1b5e2-db04-11e4-91eb-0496584c9e10.png)

I moved it outside the closing brace, you can view the results. 
I was hoping the blue links on the right would be expanded.
