### ISSUE TITLE
Jazzy 0.1.6 claims to work only with Swift 1.1

### ISSUE THREAD

**Issue by emaloney** [realm/jazzy#211]
After updating to Jazzy 0.1.6, I am getting an error message when attempting to run Jazzy against a codebase with Swift 1.2 code.

I could've sworn I used the last Jazzy release with Swift 1.2 code, but perhaps I'm mistaken.

The error message I'm getting is:

```
$ jazzy
/Users/emaloney/.gem/ruby/2.0.0/gems/jazzy-0.1.6/lib/jazzy/sourcekitten.rb:75:in `assert_swift_version': Jazzy only works with Swift 1.1. (RuntimeError)
	from /Users/emaloney/.gem/ruby/2.0.0/gems/jazzy-0.1.6/lib/jazzy/sourcekitten.rb:81:in `run_sourcekitten'
	from /Users/emaloney/.gem/ruby/2.0.0/gems/jazzy-0.1.6/lib/jazzy/doc_builder.rb:53:in `block in build'
	from /Users/emaloney/.gem/ruby/2.0.0/gems/jazzy-0.1.6/lib/jazzy/doc_builder.rb:51:in `chdir'
	from /Users/emaloney/.gem/ruby/2.0.0/gems/jazzy-0.1.6/lib/jazzy/doc_builder.rb:51:in `build'
	from /Users/emaloney/.gem/ruby/2.0.0/gems/jazzy-0.1.6/bin/jazzy:15:in `<top (required)>'
	from /usr/bin/jazzy:23:in `load'
	from /usr/bin/jazzy:23:in `<main>'
```

I'm running the Xcode 6.3 GM (build 6D570). Also, if it helps:

```
$ xcode-select -p
/Applications/Xcode.app/Contents/Developer
```

and:

```
$ jazzy --version
jazzy version: 0.1.6
```

**Comment by segiddins** [comment]
That is correct, jazzy v0.1.6 only works with swift 1.1

**Comment by depl0y** [comment]
Weird, because I am only developing in Swift 1.2 (for weeks) and Jazzy has been able to build documentation up until now. Even with Xcode 6.3 betas.

**Comment by segiddins** [comment]
The fact that it worked would've been by pure coincidence. We're aiming to get a Swift 1.2 release out in the near future, though.

**Comment by emaloney** [comment]
Thanks a lot for your work on this. Jazzy is a great tool to have.
