### ISSUE TITLE
Support new Markdown format as per Xcode 6.3

### ISSUE THREAD

**Issue by jeeftor** [realm/jazzy#212]
It looks like the new Xcode release has support for inline markdown

![screen shot 2015-04-10 at 12 59 14 pm](https://cloud.githubusercontent.com/assets/6491743/7092684/e56f53ce-df81-11e4-8dbe-e24989ca4d20.png)

**Comment by segiddins** [comment]
and does Jazzy v0.1.6 not?

**Comment by jeeftor** [comment]
Well 0.1.6 only supports Swift v1.1 so ... I think not

**Comment by segiddins** [comment]
@jeeftor we do our own Markdown / ReST parsing inside jazzy and sourcekitten, so if things don't show up correctly, that's a bug :)
