### ISSUE TITLE
Frameworks, Cocoapods and jazzy

### ISSUE THREAD

**Issue by RabbitMC** [realm/jazzy#216]
Hi there,

I have strange behaviour. I have a Xcode workspace because I'm using cocoa pods. 
Also I have some own Frameworks added via ProjectSettingsPane -> Add a target -> CocoaTouchFramework to this workspace. I need this custom framework for IBDesignable and IBInspectable Views to be rendered in my storyboard.

When I ran `jazzy` it's only documenting one of my own Frameworks. Everything else is untouched.

Then I was trying to run this command `jazzy -x -workspace,NameOfMyProject.xcworkspace,-scheme,MyMainScheme -a It's me mario! :)` - jazzy now build documentation for this specific Scheme. 

My Question is how can I make it runnable for the hole workspace? So for all my custom Frameworks and! the Project files? 

I'm using Xcode 6.3, Swift 1.2, jazzy 0.2.0

**Comment by jpsim** [comment]
Jazzy can only document a single scheme at a time, so you'll have to run jazzy for each scheme you'd like to document.

**Comment by RabbitMC** [comment]
So there is no way to get a documentation of the hole workspace?

"Jazzy can only document a single scheme at a time, so you'll have to run jazzy for each scheme you'd like to document." -> Will jazzy concat the documentations of schemes?

**Comment by jpsim** [comment]
Jazzy is really meant to document logically independent modules (like an app, or a framework). Why does your project look like, which parts are you trying to document and why can't those modules be independently documented? I'm sincerely interested in what your use case is and see if that's something we want to support in jazzy.

**Comment by RabbitMC** [comment]
I have upload a simple example project: https://github.com/RabbitMC/JazzyExmaple-ios

Run `jazzy`, and you will see, only the framework will be documented

**Comment by jpsim** [comment]
So you have four targets in that sample project: JazzyExmaple (iOS app), SimpleFramework (cocoa touch framework) and test targets for both.

Although jazzy could technically document your test targets, I have yet to be shown a compelling reason to do so.

Your app target and framework targets are distinct modules and thus should be documented independently.

So jazzy is behaving as designed here.
