### ISSUE TITLE
fuzzy generates empty doc

### ISSUE THREAD

**Issue by W2N-git** [realm/jazzy#217]
Just tried on test application with

jazzy -o DOC -a John -m TestSwiftApp -x -project,TestSwiftApp.xcodeproj,-scheme,TestSwiftApp,-sdk,iphonesimulator8.3

what i've got 
![p1](https://cloud.githubusercontent.com/assets/7563525/7339716/ae11a604-ec81-11e4-9061-c49ea8b6f353.png)

![p2](https://cloud.githubusercontent.com/assets/7563525/7339717/b2c2fb3a-ec81-11e4-9c50-5160b6518d9c.png)

what am i doing wrong?

**Comment by segiddins** [comment]
Are any of your methods or classes public?

**Comment by W2N-git** [comment]
Should i set them public explicitly with "public" keyword?

**Comment by jessesquires** [comment]
@W2N-git - yes, you'll need to make anything you want documented `public`. 

jazzy does support documenting `internal` and `private` members, but I would consider this bad practice if you are building a framework. (Also, if making an actual Cocoa Touch `.framework`, you'll need to use `public` anyway.)

**Comment by W2N-git** [comment]
It works! 
jessesquires, I completely agree with you!
