### ISSUE TITLE
Auto-detect the language in code blocks with no language specified

### ISSUE THREAD

**Issue by jeeftor** [realm/jazzy#218]
Now that Swift can use markdown in the documentation it would be great if we could do code highlighting in the jazzydoc.  For example there is a picture.  It would be great if there was syntax highlighting coloring for swift in there.

![screen shot 2015-04-30 at 9 24 17 am](https://cloud.githubusercontent.com/assets/6491743/7413585/061cb0fa-ef1b-11e4-8681-f5991dc16d7e.png)

So it looks like there is basically an almost there thing for this:

```
<pre class="highlight plaintext"><code>func newAHRSMessageHandler(notif : NSNotification) {
 println(notif.asAHRSMessage!)
}
</code></pre>
```

I realize that maybe this would be problematic because inside of the swift documentation format the markdown can't really say whether it should be syntax highlighted or not so ... maybe there isn't really a way to get this working - although I would think that anytime you are adding a code block you are probably ALWAYS doing swift code...

**Comment by segiddins** [comment]
Just mark the code block as swift and it should be syntax highlighted

**Comment by jeeftor** [comment]
But doing so doesn't render correctly in Xcode

**Comment by jpsim** [comment]
> But doing so doesn't render correctly in Xcode

That's a good point! I've renamed the issue to be a feature request to automatically detect the language in code blocks with no language specified.

**Comment by johnfairh** [comment]
#930 added this to jazzy.  Xcode seems to tolerate marking code blocks with languages now too anyway.
