### ISSUE TITLE
Documenting embedded carthage frameworks

### ISSUE THREAD

**Issue by jeeftor** [realm/jazzy#222]
We've been working on an iOS application and decided to go the framework route and have been using carthage internally to build various frameworks.  In our "top level" application there are various sub frameworks i'd like to document.

My work around to handle this situation is I've created a HTML file that points to the various documentations for the embedded frameworks and then I have a "mega" script that generates all the documentation:

    say -v Zarvox "Generating Documentation ... please wait" &
    jazzy -o docs/otto/ -c -m "OTTO Digital Co-Pilot"
    jazzy -o docs/dataManager/ -c -m "DataManager" --source-directory Carthage/Checkouts/ios-data-manager/ --min-acl public
    jazzy -o docs/gdl90/ -c -m "GDL90 & AHRS Library" --source-directory Carthage/Checkouts/gdl90/ --min-acl public
    jazzy -o docs/aviation-measures/ -c -m "Aviation Measures Library" --source-directory Carthage/Checkouts/aviation-measures/ --min-acl public

So I'm wondering if there is a better way that jazzy could support my situation.  I realize its geared more towards single-project documentation so perhaps my situation is better handled some other way - but if anybody thinks this is a good idea.

I guess then my question would be could we support maybe:

* Support for multiple source directories
* support for multiple projects

**Comment by jpsim** [comment]
I'd stick with your approach. I think there's sufficient custom information that you're passing in for each module that automating it wouldn't help much (you'd still need to specify individual output directories and flags per-module).

Also, as a minor note, as of jazzy 0.2.0, `--min-acl` is `public` by default, so you don't need to pass that in :wink:.

**Comment by jeeftor** [comment]
Hi - just wondering if this - multi-jazzy approach now carries over to config files.  i.e. do i need a ton of different jazzy.yaml files?
