### ISSUE TITLE
Incomplete docs with "`Alamofire` has no USR." error

### ISSUE THREAD

**Issue by adly-holler** [realm/jazzy#223]
Installed latest jazzy, have Xcode 6.3 `xcode-select`ed and I'm importing a bunch of frameworks, including Alamofire, into my project using Carthage. The framework is embedded & imported in Xcode.

I get 

```
`Alamofire` has no USR. First make sure all modules used in your project have been imported.
If all used modules are imported, please report this by filing an issue at 
https://github.com/realm/jazzy/issues along with your Xcode project.
```

and the generated docs only have a small portion of the content they should have. Can anyone help? I can't post the code because it belongs to a client.

**Comment by jpsim** [comment]
Are you sure you're importing Alamofire (`import Alamofire`) in every file which uses its symbols? That's typically what the error implies.

**Comment by adly-holler** [comment]
Oh! I didn't know exactly what it meant by import. I've got about 250 swift files with Alamofire scattered around – there's no alternative is there?

**Comment by jpsim** [comment]
If I had access to the code I could troubleshoot to see what's causing the issue, otherwise my ability to help investigate is limited.

**Comment by adly-holler** [comment]
OK we good. I needed to specify `--module [Skynet]` so that it wouldn't try to document Alamofire and my other Carthage frameworks, whose source I didn't import.
