### ISSUE TITLE
Single-line computed property documentation renders source

### ISSUE THREAD

**Issue by stephencelis** [realm/jazzy#226]
I'm seeing some strange behavior with properties that are written on a single line. _E.g._, this:

https://github.com/stephencelis/SQLite.swift/blob/3a0435ebce11fd31e7a4176eacff5f3350e70782/SQLite/Database.swift#L33

Yields this:

![screen shot 2015-05-05 at 3 25 00 pm](https://cloud.githubusercontent.com/assets/658/7481016/05697ea8-f33b-11e4-910d-c364576f46b8.png)

**Comment by stephencelis** [comment]
Fixing #225 may automatically fix this one.

**Comment by jpsim** [comment]
Yes, #225 would fix this one, but I'll keep this issue open because we could fix this separately.
