### ISSUE TITLE
Running $jazzy seems to work but documented files are ignored

### ISSUE THREAD

**Issue by dlbuckley** [realm/jazzy#227]
I might just be having a totally stupid moment here, but I've just tried to run Jazzy against a new project with 1 new Swift file added (and documented) as a bit of a test but nothing seems to be generated for that file.

Here is what the project looks like:
![screen shot 2015-05-07 at 11 19 05](https://cloud.githubusercontent.com/assets/349373/7513294/f915acdc-f4aa-11e4-81b0-54427e22b104.png)

This is the output from the console:
![screen shot 2015-05-07 at 11 20 31](https://cloud.githubusercontent.com/assets/349373/7513309/21564850-f4ab-11e4-9a77-1600ffcd8a85.png)

And this is what the result looks like (I included a readme to test that also):
![screen shot 2015-05-07 at 11 22 01](https://cloud.githubusercontent.com/assets/349373/7513339/520c5c28-f4ab-11e4-9c2a-78c4f5c1e620.png)

Also here is my project directory for good measure:
![screen shot 2015-05-07 at 11 22 34](https://cloud.githubusercontent.com/assets/349373/7513356/714ba74c-f4ab-11e4-867a-4987e1a4ef33.png)

As you can see from the console output, it's reading the files and trying to generate docs from it, but nothing appears to be shown relating to those files in the documentation.

I've never used Jazzy before so this was a bit of a test to see it's results as I would quite like to use it. So back to the original question; am I just being stupid or am I missing something?

**Comment by jpsim** [comment]
Jazzy only documents Swift declarations with a `public` ACL by default, of which your project has none.

You can override jazzy's minimum ACL level by passing in the command line flag `--min-acl {private,internal,public}`. For documenting frameworks, you usually want `public`. For apps, usually `internal`.

**Comment by dlbuckley** [comment]
Brilliant! Hit the nail right on the head, it all works perfectly now, thanks.
