### ISSUE TITLE
Jazzy 0.2.0 renders documentation page for extension despite :nodoc:

### ISSUE THREAD

**Issue by emaloney** [realm/jazzy#229]
I have an extension to an `enum` in order to implement a specific protocol.

All members of the extension—as well as the extension itself—are marked with `:nodoc:` as follows:

![screen shot 2015-05-08 at 3 55 48 pm](https://cloud.githubusercontent.com/assets/3768925/7544402/bc59565e-f59a-11e4-8bc9-f61cafc27443.png)

Despite this, jazzy is still creating an entry in the *Extensions* section for this extension, as well as a stub index page:

![screen shot 2015-05-08 at 3 57 02 pm](https://cloud.githubusercontent.com/assets/3768925/7544422/f10b3250-f59a-11e4-99ef-a1dad4ea2bcb.png)

I would expect neither an entry in *Extensions* nor an index page given that there is nothing specified that should be documented.

**Comment by jpsim** [comment]
Thanks for reporting! Definitely a bug, it seems.

**Comment by jpsim** [comment]
I believe this was fixed a little while ago. Please open a new issue if this happens again, along with sample code that can reproduce the bug. Thanks!
