### ISSUE TITLE
Documented extension is displayed as undocumented

### ISSUE THREAD

**Issue by emaloney** [realm/jazzy#230]
At the top-level of an extension to a class, although I've provided a description for the extension, it shows as "Undocumented" when the documentation is generated.

The functions in the extension are also documented, and in that case, the documentation is being rendered as expected.

Here's my source:

![screen shot 2015-05-14 at 10 36 07 pm](https://cloud.githubusercontent.com/assets/3768925/7645876/ac0f438c-fa89-11e4-9687-97e39269d05f.png)

And here's a screenshot of the generated documentation, showing the extension itself as "Undocumented" while correctly showing documentation for the `sameDayWithHour(_:, minute:, second:, nanosecond:)` function:

![screen shot 2015-05-14 at 10 38 40 pm](https://cloud.githubusercontent.com/assets/3768925/7645909/ff9cb32c-fa89-11e4-8316-00aa07a7ef4c.png)

**Comment by segiddins** [comment]
Do you have an `import Foundation` or an `import Foundation.NSDate` above the extension?

**Comment by emaloney** [comment]
I did not. However, I just tried adding it (both ways) & regenerating the docs, and in both cases, the result was the same: still showing the top-level NSDate extension as "Undocumented".

**Comment by emaloney** [comment]
I should add this is version `0.2.0`.

**Comment by tadija** [comment]
I have the same problem in version 0.2.2.

**Comment by jpsim** [comment]
I believe this is addressed by https://github.com/jpsim/SourceKitten/pull/104.
