### ISSUE TITLE
Allow Copyright holder to be specified separately from Author

### ISSUE THREAD

**Issue by emaloney** [realm/jazzy#231]
**_Feature Request_** Currently, the value passed as the `--author` is used for both the *Authors* section of the default index page and for the Copyright tag at the bottom of each page. (Side note: it also seems strange that "Authors" would be plural when the field only seems to take one value.)

In the case of a group of open-source projects I'm working on, we'd like to list authors as the person, people or team working on the project, but the copyright holder as our employer.

Perhaps the entire copyright attribution should be specifiable from the command line (`--copyright`), because it is common for projects at my company to be copyrighted over a range of years, not just for the year that the documentation was generated.

**Comment by segiddins** [comment]
@emaloney we'd love a pull request implementing this!

**Comment by emaloney** [comment]
Ok, I'll take a look at what's involved. Any tips on where I should start looking to add something like that would be greatly appreciated. My Ruby knowledge is cursory and several years out-of-date.

**Comment by emaloney** [comment]
[Pull request submitted](https://github.com/realm/jazzy/pull/232).

Please let me know what you think.

**Comment by orta** [comment]
^ this can be closed, as it was merged.
