### ISSUE TITLE
Only extensions are listed in documentation index

### ISSUE THREAD

**Issue by christiancabarrocas** [realm/jazzy#234]
Working in Xcode 6.2 - When generating docs, only Extensions appear in the left menu, all well documented. No classes or enums appears. Tried with min-acl public, internal and private options. When generating the docs, jazzy shows Parsing classes messages...

Running xcodebuild
Parsing DeviceUtils.swift (1/9)  ---> Class, don't appear in docs
Parsing CircleNumberIndicator.swift (2/9)  ---> Class, don't appear in docs
Parsing ErrorCodes.swift (3/9)   ---> Class, don't appear in docs
Parsing NSStringUtils.swift (4/9)
Parsing NSNumberUtils.swift (5/9)
Parsing UIImageUtils.swift (6/9)
Parsing NSDateExtensions.swift (7/9)
Parsing NoMediaView.swift (8/9)   ---> Class, don't appear in docs
Parsing SearchUtils.swift (9/9)   ---> Class, don't appear in docs
building site
jam out ♪♫ to your fresh new docs in `Documentation/`

**Comment by jpsim** [comment]
This is probably because Xcode 6.3 is jazzy's minimum supported version. I've just noticed that the README states Xcode 6.1 instead, and just created #235 to make sure we update that asap.

Is it feasible for you to try with Xcode 6.3?

**Comment by Mozahler** [comment]
I'm seeing the same behavior with 6.3.2. Processed 39 classes (files), got one class, one enum, 5 extensions....

**Comment by depl0y** [comment]
Isn't this because classes etc must be marked public before Jazzy picks them up?

**Comment by robertmryan** [comment]
Or you can specify `--min-acl internal`. It defaults to `public`. Or you can use `private`.

**Comment by Mozahler** [comment]
Thank you both so much!  Yes, of course that was the reason.

**Comment by jpsim** [comment]
The README now has a [Troubleshooting](https://github.com/realm/jazzy#troubleshooting) section with guidance for when this happens.
