### ISSUE TITLE
Empty comment causes crash with invalid range

### ISSUE THREAD

**Issue by Mozahler** [realm/jazzy#236]
fatal error: Can't form Range with end < start
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.2.1/lib/jazzy/sourcekitten.rb:84:in `run_sourcekitten'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.2.1/lib/jazzy/doc_builder.rb:53:in `block in build'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.2.1/lib/jazzy/doc_builder.rb:51:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.2.1/lib/jazzy/doc_builder.rb:51:in `build'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.2.1/bin/jazzy:15:in `<top (required)>'
	from /usr/bin/jazzy:23:in `load'
	from /usr/bin/jazzy:23:in `<main>'

Turns out the cause was this line of code:
///

Apparently I deleted the comment, but left the slashes in.

**Comment by jpsim** [comment]
Thanks for filing this, @Mozahler. I just pushed a fix to SourceKitten which should land in the next release of jazzy: https://github.com/jpsim/SourceKitten/pull/50

**Comment by Mozahler** [comment]
Sure. Thank you for all your hard work!
