### ISSUE TITLE
Print the number of skipped declarations

### ISSUE THREAD

**Issue by jpsim** [realm/jazzy#238]
Output could look like this:

```
jam out ♪♫ to your fresh new docs in `docs`
Documented X public declarations
Skipped Y internal declarations and Z private declarations
```

This feature request was prompted by some confusion among new users who reported that none of their declarations were being documented (because none of them were marked `public` and `--min-acl` was set to `public`). See #237.

**Comment by istx25** [comment]
From what I can see, I believe this has been resolved? I won't close this one myself because I'm not actually 100% sure. Let me know what y'all think.

**Comment by jpsim** [comment]
No, this hasn't been resolved. The log output from the initial comment is still desirable I think.

**Comment by jpsim** [comment]
Done by the wonderful @johnfairh!
