### ISSUE TITLE
Documents subclasses with extensions as extensions only

### ISSUE THREAD

**Issue by jballands** [realm/jazzy#239]
For example:

```
class Corgi:Animal {
   ...
}

extension Corgi:DomesticAnimalDelegate {
   ...
}
```

`Corgi` will only be documented under the **Extensions** section, but not under the **Classes** section. Preferred behavior would be to put `Corgi` under the **Extensions** section and the **Classes** section.

**Comment by jpsim** [comment]
We've recently added a "Troubleshooting" section to our README which should provide some guidance in this scenario (see https://github.com/realm/jazzy#only-extensions-are-listed-in-the-documentation).

> By default, jazzy only documents public declarations. To generate documentation for declarations with a lower accessibility level (internal or private), please set the `--min-acl` flag to `internal` or `private`.

**Comment by jpsim** [comment]
So in other words, extensions in Swift are public by default (since there's no ACL modifier for `extension`), but `class`es aren't, so the extension is showing up, but not the class declaration.

**Comment by depl0y** [comment]
I know this is closed, but is this really also the Swift behaviour? In the example of @jballands he creates a class without the public declaration. So when trying to use this class from within a different project, the class isn't available (So neither are the extensions).

I would think extensions get the same accessibility level as their 'base'.

**Comment by jpsim** [comment]
> I know this is closed, but is this really also the Swift behaviour?

No, actually it isn't. But SourceKit doesn't expose the accessibility level of extensions, so to determine that properly we'd have to check the accessibility level of the type being extended, which is non-trivial.

Can you think of a way to determine that?
