### ISSUE TITLE
Two-space indented text is not styled as code block.

### ISSUE THREAD

**Issue by evgenyneu** [realm/jazzy#241]
## How to reproduce

Clone the Moa repository and generate the docs

```
git clone git@github.com:evgenyneu/moa.git
cd moa
jazzy
```

Open docs for Moa class in the browser:

```
open docs/Classes/Moa.html
```

## Expected behavior

The 2-space indented text in the comments to the Moa class is styled as code block.

## Actual behavior

The 2-space indented text is **not** styled as code block but shown as a single line of text with body text style.

## How it looks in jazzy docs

![jazzy_doc](https://cloud.githubusercontent.com/assets/880411/7895632/ba5fcb96-06dc-11e5-86e2-037c2e42a2bf.png)

## How it looks in Xcode 6.4 (6E23):

![help_in_xcode](https://cloud.githubusercontent.com/assets/880411/7895634/bfef3a4c-06dc-11e5-83ae-91f5a6bde766.png)

#### I am using 2-space tabs in my project settings.

![xcode_text_settings](https://cloud.githubusercontent.com/assets/880411/7895638/cad9efec-06dc-11e5-9fe2-ae4e8e68ea0f.png)

**Comment by jpsim** [comment]
Doesn't the markdown spec require indentation of 4 spaces for code blocks?

> To produce a code block in Markdown, simply indent every line of the block by at least 4 spaces or 1 tab.

From http://daringfireball.net/projects/markdown/syntax#precode

**Comment by jpsim** [comment]
In the spec, I'd expect "1 tab" to mean a single tab character (`\t`).

**Comment by evgenyneu** [comment]
@jpsim thanks for looking into it. The 2-space indented code block is recognised by Xcode. Either it is not using Markdown or it is a bug in Xcode.

![bfef3a4c-06dc-11e5-83ae-91f5a6bde766](https://cloud.githubusercontent.com/assets/880411/7899973/0e1edaae-077f-11e5-8fa3-263c88d088b4.png)

**Comment by kylef** [comment]
The code documentation is actually reStructuredText, Xcode parses it as reStructuredText, so I would assume this is a block quote as per the rST specification. I believe that is why indenting again `return image` results in a separate block quote within the outer block quote.

**Comment by jpsim** [comment]
@kylef is right, Xcode is parsing (almost) reStructuredText, while jazzy is parsing comments as Markdown. We made this decision because 1) Xcode isn't consistent, or spec-conforming, in its parsing of rST, 2) there are no generally ruby-friendly rST parsers, 3) users are typically familiar with Markdown and 4) rST is pretty close to markdown.

**Comment by evgenyneu** [comment]
Very cool, I will just indent the code block with 4 spaces then. Problem solved. Thanks.

**Comment by jpsim** [comment]
Ok, don't hesitate to share any further feedback you have!
