### ISSUE TITLE
Exclude option not working?!?

### ISSUE THREAD

**Issue by khoogheem** [realm/jazzy#243]
if I use -e Somefile+Exten.swift it still is picking up the documentation of that file.

**Comment by jpsim** [comment]
You have to pass in the absolute path of the file. You can see #219 which added this functionality for all the details of its implementation.

**Comment by khoogheem** [comment]
JP -

Thanks.. Sorry to be a pain.. but no one should have to read #219 to figure it out ;)

should make note of that in jazzy -h

**Comment by jpsim** [comment]
Or you could make a PR...
