### ISSUE TITLE
"View on GitHub" header link shouldn't be generated when no GitHub URL is specified

### ISSUE THREAD

**Issue by khoogheem** [realm/jazzy#244]
I recommend that the Link to GitHub is removed unless you specify the -g option.

OR Better yet.. I would like to actually see a option that we could specify any Project URL so if you host on GitHub or BitBucket, or want to point it back to your Company URL project page..

**Comment by jpsim** [comment]
You're right that the "View on GitHub" link in the upper right of the page still gets generated regardless of if a GitHub url is specified. We'll be sure to fix that.

**Comment by jpsim** [comment]
Fixed in #292.
