### ISSUE TITLE
Xcode Run Script Build Phase

### ISSUE THREAD

**Issue by akashvercetti** [realm/jazzy#248]
I would like to be able to generate docs as soon as i Build a target. I believe I need gems path before using the jazzy command in the script. I'm using Yosemite and Xcode 6.3. Can anyone guide me on this?

**Comment by jpsim** [comment]
You can find where jazzy is installed on your system by running `which jazzy`, and invoke jazzy by its absolute path in your Xcode build phase.

**Comment by akashvercetti** [comment]
Worked like a charm!
Thanks a bunch!
