### ISSUE TITLE
Swift: unwanted sentence in an extension documentation

### ISSUE THREAD

**Issue by groue** [realm/jazzy#249]
Hello,

In http://cocoadocs.org/docsets/GRMustache.swift/0.9.2/Extensions/Bool.html#/s:vE8MustacheSb11mustacheBoxCS_11MustacheBox, the sentence at the top of the page is irrelevant and unwanted:

> MustacheBox conforms to the MustacheBoxable protocol so that it can feed Mustache templates. Its mustacheBox property returns itself.

The code source that has been used to produce this incorrect documentation is (with highlighting of relevant sentences): https://github.com/groue/GRMustache.swift/blob/v0.9.2/Mustache/Rendering/Box.swift#L155-L188

(Originally posted on https://github.com/CocoaPods/cocoadocs.org/issues/353)

**Comment by jpsim** [comment]
Thanks for reporting this. I believe this will be addressed by https://github.com/jpsim/SourceKitten/pull/104.

**Comment by groue** [comment]
Thanks for bubbling this issue up!

**Comment by jpsim** [comment]
Should be fixed now.
