### ISSUE TITLE
Parse enum's

### ISSUE THREAD

**Issue by jpsim** [realm/jazzy#25]

**Comment by nicolas-miari** [comment]
I am having some issues trying to get the keywords properly interpreted in the comments of each `case`. SourceKit (or jazzy?) seems to be very sensitive to white space. I will post sample code once I have figured out the pattern of reproducibility...

**Comment by nicolas-miari** [comment]
OK, seems to have to do with japanese text somehow (however, the pattern isn't clear enough for me to create dummy code that reproduces the issue - I'll have to post my actual code). I'll open a new issue.
