### ISSUE TITLE
Swift 2 Support

### ISSUE THREAD

**Issue by segiddins** [realm/jazzy#251]

**Comment by jessesquires** [comment]
Hey @segiddins - what's the level of effort here?

Also, quick note/reminder, as of beta4:
>Swift documentation comments recognize a top-level list item `- Throws: ...` which should be used to document what errors can be thrown and why.

**Comment by segiddins** [comment]
@jpsim has a branch he's been promising to push up

**Comment by jpsim** [comment]
The required work is almost entirely contained in SourceKitten, which has a [`swift-2.0`](https://github.com/jpsim/SourceKitten/tree/swift-2.0) branch, but I haven't tried this with jazzy yet.

**Comment by stevestreza** [comment]
Running this against a Swift 2 codebase I'm working on with Xcode 7 beta 4, it seems that there are some elements that SourceKitten is not returning a `key.substructure` for. This is causing a crash in [lib/jazzy/sourcekitten.rb:182](https://github.com/realm/jazzy/blob/swift-2.0/lib/jazzy/sourcekitten.rb#L187). I worked around this for now by checking for nil in the preceding if check but I'm not sure if that's the right approach.

**Comment by jpsim** [comment]
@stevestreza are you using the `swift-2.0` branch of jazzy? You'll need Xcode 7 beta 4 installed under `/Applications/Xcode-beta.app` and have it selected under `xcode-select` for the time being, if you're using that branch. We'll have fewer hoops to jump through once we make an official release of it, I promise :wink:.

**Comment by stevestreza** [comment]
Yep, on the `swift-2.0` branch, with `xcode-select` pointing at the `/Applications/Xcode-beta.app`. Just wanted to bring up one issue I ran into in practical use. I understand the development-y state of things. :)

**Comment by jpsim** [comment]
Hmmm, that's odd then. I don't suppose you can share code that reproduces the issue?

The `swift-2.0` branch has some integration tests for `Alamofire` and `RealmSwift` at the moment and we're not seeing that particular issue. If you find a project that exhibits the same problem, please share it with us so we can troubleshoot further!

Thanks!

**Comment by jdraymon** [comment]
I see that the SourceKitten version has been bumped to 5.0 - is this fixed now?

**Comment by jpsim** [comment]
Indeed, jazzy officially supports Swift 2 now. Thanks for pointing this out.
