### ISSUE TITLE
SourceKit connection interrupt

### ISSUE THREAD

**Issue by jpsim** [realm/jazzy#253]
Taken from https://github.com/realm/jazzy/issues/242#issuecomment-116748774:

> For me, jazzy chokes on most extensions (pretty much all of the ones that I have). Is it just me or should I file this as an issue?

```
`Parsing AlamofireParameterEncodingExtensions.swift (106/168)`

sourcekit: [1:connection-event-handler:7943: 0.0000] Connection interrupt

sourcekit: [1:pingService:7943: 0.0007] pinging service

sourcekit: [1:sourcekitd_send_request_sync:1551: 0.0013] request dropped while restoring service
	from /Users/kosta/.rvm/gems/ruby-head/gems/jazzy-0.2.1/lib/jazzy/sourcekitten.rb:84:in `run_sourcekitten'
	from /Users/kosta/.rvm/gems/ruby-head/gems/jazzy-0.2.1/lib/jazzy/doc_builder.rb:53:in `block in build'
	from /Users/kosta/.rvm/gems/ruby-head/gems/jazzy-0.2.1/lib/jazzy/doc_builder.rb:51:in `chdir'
	from /Users/kosta/.rvm/gems/ruby-head/gems/jazzy-0.2.1/lib/jazzy/doc_builder.rb:51:in `build'
	from /Users/kosta/.rvm/gems/ruby-head/gems/jazzy-0.2.1/bin/jazzy:15:in `<top (required)>'
	from /Users/kosta/.rvm/gems/ruby-head/bin/jazzy:23:in `load'
	from /Users/kosta/.rvm/gems/ruby-head/bin/jazzy:23:in `<main>'
	from /Users/kosta/.rvm/gems/ruby-head/bin/ruby_executable_hooks:15:in `eval'
	from /Users/kosta/.rvm/gems/ruby-head/bin/ruby_executable_hooks:15:in `<main>'
```

> Thanks guys (please let me know if i need to transfer this to a new issue). I am using 6.3.2 and 6.4 beta and I am not noticing any difference in behavior with jazzy. I don't have xcode 7 installed. The code is in Swift 1.2. Here is one of the files that it chokes on (I had to redact some code, only method signatures are shown):

```swift
import Foundation
import Alamofire

extension Alamofire.Request {
    func responseIcnJson(queue: dispatch_queue_t? = nil, completionHandler: (NSURLRequest, NSHTTPURLResponse?, NSDictionary?, NSError?) -> Void) -> Self {
    }
    
    class func icnJsonserializer() -> Alamofire.Request.Serializer {
        return {
            request, response, data in 
		}
    }
```

/cc @tachtevrenidis

**Comment by Vaseltior** [comment]
I get the same results

**Comment by tachtevrenidis** [comment]
thanks @Vaseltior. @jpsim, are there any updates here?

**Comment by jpsim** [comment]
I think the situation has improved in Swift 2 Beta 4.

**Comment by isaacroldan** [comment]
This is happening to me in Beta4 and Beta5 :(

**Comment by jpsim** [comment]
note to all: whenever you see a "sourcekit connection interrupt" logged, that's Apple's SourceKit service itself crashing, and you should file a radar since this is something only Apple can fix. Here's one I just filed as an example: [rdar://22394418](http://www.openradar.me/22394418).

**Comment by damianesteban** [comment]
Has anyone gotten jazzy working with Xcode 7 Beta _ yet?  It has been over a month for me and still no luck.

**Comment by pcantrell** [comment]
@damianesteban: It’s working just great for me with Xcode 7, and successfully generating [docs for a Swift 2.0 project](http://bustoutsolutions.github.io/siesta/api/).

Things to check:

- Did you check out Jazzy’s `swift-2.0` branch? (And — sanity check — are you using that `jazzy` instead of accidentally picking up the distro version from the gem in your path?)
- Did you use `xcode-select` to point it at the right command line?
- Does your project build successfully with `xcodebuild`?

**Comment by jpsim** [comment]
I haven't seen SourceKit crash since Xcode 7.0 GM came out a little while ago, so I'm closing this.

**Comment by olivaresf** [comment]
Running into this issue on Xcode 7.2.1 (7C1002). What can I give you besides this error?

```sourcekit: [1:sourcekitd_send_request_sync:1547: 0.0019] request dropped while restoring service
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.5.0/lib/jazzy/sourcekitten.rb:140:in `run_sourcekitten'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.5.0/lib/jazzy/doc_builder.rb:57:in `block in build'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.5.0/lib/jazzy/doc_builder.rb:55:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.5.0/lib/jazzy/doc_builder.rb:55:in `build'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.5.0/bin/jazzy:15:in `<top (required)>'
	from /usr/local/bin/jazzy:23:in `load'
	from /usr/local/bin/jazzy:23:in `<main>'```

**Comment by damianesteban** [comment]
I haven't experienced this error in quite awhile and I never did quite figure out why it was happening in the first place.

**Comment by iwasrobbed** [comment]
Seems to happen quite frequently, even for simple structs. Using Xcode 7.3 / Swift 2.2

```
rob$ jazzy --swift-version 2.2
Running xcodebuild
Parsing UserLocalizations.swift (1/29)
sourcekit: [1:connection-event-handler:7939: 0.0000] Connection interrupt
sourcekit: [1:pingService:7939: 0.0008] pinging service
sourcekit: [1:sourcekitd_send_request_sync:1547: 0.0011] request dropped while restoring service
/Users/rob/.rvm/gems/ruby-2.2.0/gems/jazzy-0.5.0/lib/jazzy/executable.rb:36:in `execute_command': /Users/rob/.rvm/gems/ruby-2.2.0/gems/jazzy-0.5.0/lib/jazzy/SourceKitten/bin/sourcekitten ["doc"] (RuntimeError)

Running xcodebuild

Parsing UserLocalizations.swift (1/29)

sourcekit: [1:connection-event-handler:7939: 0.0000] Connection interrupt

sourcekit: [1:pingService:7939: 0.0008] pinging service

sourcekit: [1:sourcekitd_send_request_sync:1547: 0.0011] request dropped while restoring service
	from /Users/rob/.rvm/gems/ruby-2.2.0/gems/jazzy-0.5.0/lib/jazzy/sourcekitten.rb:140:in `run_sourcekitten'
	from /Users/rob/.rvm/gems/ruby-2.2.0/gems/jazzy-0.5.0/lib/jazzy/doc_builder.rb:57:in `block in build'
	from /Users/rob/.rvm/gems/ruby-2.2.0/gems/jazzy-0.5.0/lib/jazzy/doc_builder.rb:55:in `chdir'
	from /Users/rob/.rvm/gems/ruby-2.2.0/gems/jazzy-0.5.0/lib/jazzy/doc_builder.rb:55:in `build'
	from /Users/rob/.rvm/gems/ruby-2.2.0/gems/jazzy-0.5.0/bin/jazzy:15:in `<top (required)>'
	from /Users/rob/.rvm/gems/ruby-2.2.0/bin/jazzy:23:in `load'
	from /Users/rob/.rvm/gems/ruby-2.2.0/bin/jazzy:23:in `<main>'
	from /Users/rob/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/rob/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'
```

The file it bails on is:

```
import Foundation

struct UserLocalizations {
    static let menuFAQ = NSLocalizedString("FAQ", comment: "")
    static let menuFAQSubtitle = NSLocalizedString("Frequently asked questions", comment: "")
}
```

Commenting out the struct at least lets it get to the next file and then it bails again. The second file is an extension with a class method inside and actually has function docs on it.

**Comment by jpsim** [comment]
@iwasrobbed have you filed a radar or a Swift bug?

**Comment by jpsim** [comment]
These are SourceKit bugs and for Apple to fix them, they need to be aware of them. Please file a radar at https://bugreport.apple.com and a Swift bug at https://bugs.swift.org
