### ISSUE TITLE
Failing with incomplete comments

### ISSUE THREAD

**Issue by Vaseltior** [realm/jazzy#254]
If, in Swift, I put the following comments before a function or property :

```
///
///
///
func theGivenMethod() {
}
``` 
or this

```
///
var theGivenProperty: AnyObject? = nil
``` 

respectively, instead of

```
///
/// Some comment
///
func theGivenMethod() {
}
``` 

and

```
/// Useless property
var theGivenProperty: AnyObject? = nil
``` 

I get this

```
fatal error: Can't form Range with end < start
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.2.1/lib/jazzy/sourcekitten.rb:84:in `run_sourcekitten'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.2.1/lib/jazzy/doc_builder.rb:53:in `block in build'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.2.1/lib/jazzy/doc_builder.rb:51:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.2.1/lib/jazzy/doc_builder.rb:51:in `build'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.2.1/bin/jazzy:15:in `<top (required)>'
	from /usr/bin/jazzy:23:in `load'
	from /usr/bin/jazzy:23:in `<main>'
```

**Comment by jpsim** [comment]
Well that's unfortunate! Sorry you're having this much trouble :grimacing:. I'll look into this asap and report back.

**Comment by Vaseltior** [comment]
Ok thx, byt the way do you know why some of my other files that are parsed, are not present in the documentation? Event if I put comments on them? I think I'm doing it wrong somewhere. Let me reformulate. What is needed in Swift for a file being present in the documentation? Thx

**Comment by jpsim** [comment]
The html files are only built once the parsing successfully completes, which isn't the case here.

**Comment by Vaseltior** [comment]
No, I did it using a cleaned version, removing every parasite in my code that could cause jazzy stopping.

**Comment by jpsim** [comment]
could it be that you're documenting code with an ACL that's lower than `--min-acl`? It defaults to `public`.

**Comment by Vaseltior** [comment]
For instance

```
Running xcodebuild
Parsing ROGameProtocol.swift (1/6)
Parsing SwellAll.swift (2/6)
Parsing GameScene.swift (3/6)
Parsing KeychainWrapper.swift (4/6)
Parsing GameViewController.swift (5/6)
Parsing AppDelegate.swift (6/6)
building site
jam out ♪♫ to your fresh new docs in `docs`
```

![capture d ecran 2015-06-30 a 21 01 01](https://cloud.githubusercontent.com/assets/915156/8439274/411e3658-1f6b-11e5-95d1-910cc7a1540f.png)

**Comment by Vaseltior** [comment]
I added `--min-acl` after reading documentation. ??? here is the file content

````
/**
This is what defines a game
*/
protocol ROGameProtocol {
  /// Tell if the game is sarted or not
  var isStarted: Bool {get}
  
  /// Tell if the game is over or not
  var gameOver: Bool {get}
}
```

**Comment by Vaseltior** [comment]
Command line is:

```
MacBook-Pro:Rotala vaseltior$ jazzy --min-acl
Running xcodebuild
Parsing ROGameProtocol.swift (1/6)
Parsing SwellAll.swift (2/6)
Parsing GameScene.swift (3/6)
Parsing KeychainWrapper.swift (4/6)
Parsing GameViewController.swift (5/6)
Parsing AppDelegate.swift (6/6)
building site
jam out ♪♫ to your fresh new docs in `docs`
```

**Comment by jpsim** [comment]
Usage for `--min-acl` is `--min-acl [private | internal | public]`, so you're missing a parameter value there.

**Comment by Vaseltior** [comment]
Oh great, thank you.

**Comment by jpsim** [comment]
Glad we worked this out.
