### ISSUE TITLE
Is supported in japanese chracters?

### ISSUE THREAD

**Issue by ryujik** [realm/jazzy#256]
Hi, I have a project documented in japanese characters. But, I when execute in jazzy command show me falta error:
```
fatal error: unexpectedly found nil while unwrapping an Optional value
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.2.1/lib/jazzy/sourcekitten.rb:84:in `run_sourcekitten'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.2.1/lib/jazzy/doc_builder.rb:53:in `block in build'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.2.1/lib/jazzy/doc_builder.rb:51:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.2.1/lib/jazzy/doc_builder.rb:51:in `build'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.2.1/bin/jazzy:15:in `<top (required)>'
	from /usr/bin/jazzy:23:in `load'
	from /usr/bin/jazzy:23:in `<main>'
```
Is there problem using the Japanese characters in use jazzy?

**Comment by jpsim** [comment]
Jazzy is built on SourceKitten, and it has tests for multi-byte characters (see https://github.com/jpsim/SourceKitten/blob/master/Source/SourceKittenFrameworkTests/StringTests.swift).

Perhaps those tests aren't extensive? If you could share an Xcode project that reproduces this issue with me, I'd be able to investigate further.

**Comment by ryujik** [comment]
Sorry I can't show the code directly because it's a commercial project. But, I check when that bug reproduces and report in this issue. Thanks.

**Comment by jpsim** [comment]
Or you could add a test to https://github.com/jpsim/SourceKitten/blob/master/Source/SourceKittenFrameworkTests/StringTests.swift

**Comment by jpsim** [comment]
Could you please try your project again with jazzy 0.4.0? If this is still an issue, I'd appreciate if you could share a sample project that reproduces the problem.

Thanks!

**Comment by ryujik** [comment]
Good job!!! Now it works. Thanks!
