### ISSUE TITLE
Improve support for symlinked files

### ISSUE THREAD

**Issue by jpsim** [realm/jazzy#263]
For example, Realm Swift now symlinks `RealmSwift-swift1.2` or `RealmSwift-swift2.0` into `RealmSwift` depending on which Xcode is building the project.

This means that links that point to say `https://github.com/realm/realm-cocoa/tree/v0.94.0/RealmSwift/Realm.swift#L143-L145` won't resolve, since git will actually store the file in `https://github.com/realm/realm-cocoa/tree/v0.94.0/RealmSwift-swift1.2/Realm.swift#L143-L145`.

Fixing this issue probably just requires calling `realpath` in a bunch of places. /cc @segiddins

**Comment by segiddins** [comment]
We already seem to do this at https://github.com/realm/jazzy/blob/86917a69e238eedb781d7e4ae87aa7c37c39816b/lib/jazzy/doc_builder.rb#L227

**Comment by jpsim** [comment]
Yeah, I don't have a repro case handy and this may very well have been fixed since the last time I had noticed the issue, so I'll close this.
