### ISSUE TITLE
What are Swift extensions?

### ISSUE THREAD

**Issue by groue** [realm/jazzy#267]
What are extensions? I want to question the way to document them in a separate page.

Today, it is a tool for the developper. Everybody copies the way the Swift standard lib is written, and everybody writes tiny extensions which have *no purpose for the end user*, since it's only the current trend in swift coding.

Unfortunately coding a library is not the same task as using this library, and particularly using the jazzy-generated documentation as a reference tool.

**1st problem**

For the end user, the way jazzy isolates extensions gives pages without any context like the following: http://cocoadocs.org/docsets/GRDB.swift/0.7.0/Extensions/Database.html. You don't get what this page is about? That is pretty normal, nobody could. Good luck figuring out why those functions are put on the side, and how they are grouped. The answer "because they are in an extension" is not a relevant answer, because the library user still does't know why they are in an extension, and is forced to wild guesses.

In this specific case, those extensions should have been merged in the main class, http://cocoadocs.org/docsets/GRDB.swift/0.7.0/Classes/Database.html, with proper section titles (from the docstring of extensions as in https://github.com/groue/GRDB.swift/blob/v0.7.0/GRDB/RowModel.swift#L679-L682)

**Second problem**

Border between type definition and its extensions are sometimes fuzzy. If the coder decides to move a function from the type definition to an extension, or the opposite, the function moves in the documentation generated by jazzy. Without any real purpose. And for the confusion of the end user. With broken links in search engines. Etc. For example, is there any purpose generating different documentations for those two classes ?

```swift
/// The class C1 ...
class C1 { }
extension C1: CustomStringConvertible {
    /// A textual representation of `self`.
    public var description: String { return ... }
}

/// The class C2 ...
class C2 : CustomStringConvertible {
    /// A textual representation of `self`.
    public var description: String { return ... }
}
```

Thanks for listening!

**Comment by pcantrell** [comment]
#278 fixes this.

**Comment by jpsim** [comment]
Thanks for posting this thought-out description of why jazzy should improve its extension support. I agree with @pcantrell that #278 goes a long way towards addressing this and that #242 sufficiently tracks this feature request, so I'm closing this as a duplicate.
