### ISSUE TITLE
sourcekit - Connection interrupt

### ISSUE THREAD

**Issue by damianesteban** [realm/jazzy#272]
I've been using Jazzy for several months and have never had any issues with it.  I'm wrapping up a project and went to generate some documentation last night and I got the following error:

    sourcekit: [1:connection-event-handler:7943: 0.0000] Connection interrupt
    sourcekit: [1:pingService:7943: 0.0007] pinging service
    sourcekit: [1:sourcekitd_send_request_sync:1551: 0.0012] request dropped while       
    restoring service

Has anyone else experienced this issue?  

Thank you.

**Comment by beltex** [comment]
Hi @damianesteban!

See #215 & #253.

**Comment by jpsim** [comment]
The best thing we can get to help troubleshoot in these cases is a project that reproduces the issue. Would it be possible for you to share that with us?

**Comment by damianesteban** [comment]
Unfortunately I can't share the project, but I will look at the above issues and give you a more detailed log.

**Comment by jpsim** [comment]
I find it useful to use [SourceKitten](https://github.com/jpsim/SourceKitten) via Xcode when debugging these sorts of issues. If you "Build & Run" the "sourcekitten" target, setting `doc` as an executable argument and the working directory to your project's root in the scheme's build setting, you should have all the power of LLDB at your fingertips.

**Comment by brownleej** [comment]
I ran into this issue in one of my projects (https://github.com/brownleej/tailor/). Through trial and error, I traced the problem down to the documentation for a generic equality operator:

    public func ==<T: Persistable>(lhs: T, rhs: T) -> Bool

Once I removed the comments from this method, it was able to generate the documentation.

I ran this inside of SourceKitten, it was crashing in SwiftXPC.fromXPC. From there, it was calling xpc_dictionary_apply, which was causing _xpc_api_misuse. I don't know enough about SourceKit or XPC to know where to take it from there, but I hope this helps.

**Comment by jpsim** [comment]
Cross-posting from #253 (and closing this as a duplicate):

> note to all: whenever you see a "sourcekit connection interrupt" logged, that's Apple's SourceKit service itself crashing, and you should file a radar since this is something only Apple can fix. Here's one I just filed as an example: [rdar://22394418](http://www.openradar.me/22394418).

**Comment by damianesteban** [comment]
I should have added to this discussion before, I apologize.  As soon as I uninstalled Xcode 7 Beta all was well.
