### ISSUE TITLE
deduplicate_declarations merges distinct methods that should not be merged

### ISSUE THREAD

**Issue by pcantrell** [realm/jazzy#277]
It’s unclear when and why it happens — I’m unable to reproduce it in a small test case, so it may be a SourceKit bug — but sometimes, multiple variants of a method end up with the same USR. For example, in [Siesta](https://github.com/bustoutsolutions/siesta), [these methods](https://github.com/bustoutsolutions/siesta/blob/master/Source/Resource.swift#L283-L408):

    request(_:requestMutation:)
    request(_:data:mimeType:requestMutation:)
    request(_:text:mimeType:encoding:requestMutation:)
    request(_:json:mimeType:requestMutation:)
    request(_:urlEncoded:requestMutation:)

…all end up with the USR `s:FC6Siesta8Resource7requestERR`. When this happens, `deduplicate_declarations` incorrectly merges them, and only one of them gets documented.

The original intent of `deduplicate_declarations` was to merge multiple extensions of the same entity. (See 777ba4dac97ba0dd57f1b737f2a294ccd4baae27.) It probably shouldn’t touch methods at all.

**Comment by segiddins** [comment]
@pcantrell it actually is supposed to touch methods -- it's needed to play nice with documenting podspecs. The issue there is the `ERR` at the end of the USR -- that indicates generating a USR actually failed

**Comment by pcantrell** [comment]
Ah, somebody else is up too late too. :)

What does the podspec case look like? As you see, I have a fix coming in a larger PR, and can account for the podspec if I know what I'm looking for.

**Comment by segiddins** [comment]
The same module is documented potentially many times. I'm fairly confident that the current `deduplicate_declarations` is correct, and it's the inability to properly generate the USR that's the real issue here.

**Comment by pcantrell** [comment]
In the cases where [USR, type] fails to be globally unique as Jazzy expects, [USR, type, name] works. Would that break the podspec case?

**Comment by segiddins** [comment]
No it wouldn't break the podspec case, but again, this feels like a bandaide versus figuring out why you're getting error types when running SourceKitten at all.

**Comment by pcantrell** [comment]
Does the `ERR` suffix come from Sourcekitten? I thought it was a SourceKit thing.

If it’s from Sourcekitten, then yes, it’s a band-aid and I’ll track down the underlying bug.

If it comes from SourceKit, then there’s an underlying Apple bug, but that doesn’t change the fact that Jazzy’s assumption of the global uniqueness of USRs is incorrect.

**Comment by segiddins** [comment]
It does come from SourceKit, but it means the xcodebuild arguments passed are incorrect, or theres a missing `import` statement somewhere -- valid programs never actually contain error types, regardless of what SourceKit occasionally says.

**Comment by pcantrell** [comment]
Indeed, you’re right — a seemingly unrelated compile error elsewhere in the project (a `.h` file, not even in Swift!) triggered the problem. Sorry for the noise!

**Comment by segiddins** [comment]
No worries whatsoever!
