### ISSUE TITLE
Use declaration name in URL rather than USR if there's no collision

### ISSUE THREAD

**Issue by jpsim** [realm/jazzy#287]
Jazzy uses USRs for URLs because Swift allows overloading declarations with the same name, but with different type signatures. However, since overloading is the minority case, we could use the name instead of the USR if there's no collision which would look a lot nicer:

```
Before:
Classes/Realm.html#/s:FC10RealmSwift5Realm6createFS0_U__FTMQ_5valuePSs9AnyObject_6updateSb_Q_

After:
Classes/Realm.html#/create(_:value:update:)
```

Ideally, we'd have `id` tags for both name and USR, which would help with auto-linking. For example, if you reference `Realm.create(_:value:update:)` from a documentation comment, jazzy could automatically hyperlink the reference.

**Comment by istx25** [comment]
Any progress on this?

**Comment by jpsim** [comment]
No progress on this to report.

**Comment by johnfairh** [comment]
Realistically not going to change the URL scheme at this point.  DocC does almost exactly this!
