### ISSUE TITLE
Can't Hide Percentage Documented?

### ISSUE THREAD

**Issue by xsahoo** [realm/jazzy#297]
Is there no way to hide the "(X% documented)" that appears at the top left of the page? It seems more intuitive that this would be hidden by default and only displayed when an option is specified. 
![screen shot 2015-09-10 at 5 02 52 pm](https://cloud.githubusercontent.com/assets/7671705/9804019/d2badc60-57dd-11e5-9963-42351854714b.png)

**Comment by mbogh** [comment]
We could add an option:
`--[no-]hide-documentation-coverage    Hide (X% documented) from the generated document`

**Comment by jpsim** [comment]
@mbogh that sounds fine to me. @xsahoo another way to do this is to use custom templates

**Comment by mbogh** [comment]
Cool, I'll submit a PR.

Should a new integration spec be made or should one of the existing be modified (e.g. `misc_jazzy_features`)?
