### ISSUE TITLE
Example of categories JSON or YAML file with custom groupings

### ISSUE THREAD

**Issue by aure** [realm/jazzy#299]
From jazzy --help:
   --categories file            JSON or YAML file with custom groupings
  
Can someone give me a hint what the categories file can/should look like?

Thanks

**Comment by pcantrell** [comment]
It's something of a work in progress, with the categories file to be replaced by a more generic `.jazzy.yaml` config file.

For the current usage, though, here is a [sample config file](https://github.com/bustoutsolutions/siesta/blob/gh-pages/_templates/api-categories.yaml) and [its output](http://bustoutsolutions.github.io/siesta/api/).

You can follow discussion on the feature on #281. Note that the nice results linked above also depend on #289, yet to be merged.

**Comment by aure** [comment]
Gorgeous!

**Comment by plummer** [comment]
Just pointing out the sample config file linked is dead.

**Comment by pcantrell** [comment]
@plummer Thanks. Link fixed in post above.
