### ISSUE TITLE
Allow to specify documentation header title

### ISSUE THREAD

**Issue by nickygerritsen** [realm/jazzy#300]
Now that @jpsim merged #298 you use the module name both for getting the module out of XCode and for the name of the documentation pages (shown in the header).

Although this is now overridable by specifying both `-m X` and `-x '--module-name,Y`, I think it would be better if we could set the title to something different, for example by passing `--title=X` or similar.

What are your thoughts on this?

**Comment by jpsim** [comment]
Thanks for sharing this use case. My first inclination would be to recommend that you use custom templates (#257). I'm open to making this a feature, but I'm under the impression that the case in which the title is different than the module name is actually fairly rare in practice.

**Comment by istx25** [comment]
Any progress on this?

**Comment by jpsim** [comment]
No progress on this to report.

**Comment by johnfairh** [comment]
Covered in #411.
