### ISSUE TITLE
Can't debug Xcode 7 build - how do I view build progress?

### ISSUE THREAD

**Issue by Mozahler** [realm/jazzy#309]
<img width="784" alt="screen shot 2015-09-26 at 9 45 47 am" src="https://cloud.githubusercontent.com/assets/9641531/10117851/d3957354-6433-11e5-9cd9-79e4bcd3d56a.png">

The above picture shows activity approximately 10 minutes after starting a jazzy build.
I don't see a cmdline verbose option to running jazzy, but need to understand why my project fails to build. Is there an intermediate file I can view to see what problems are being encountered?
Before Swift 2.0, I could get a jazzy build. Xcode can compile the project of just over 100 swift files.
I don't know which files are causing a problem. I see I can exclude files, can I include instead? Do I have to write a script [not my forte, but I will relearn enough ruby to do it if I have to] to gather all file names and exclude all but one, one by one until I find all offending files? 
I am using this command:
jazzy --skip-undocumented --swift-version 2.0 --min-acl internal
and the command "jazzy -v" results in: jazzy version: 0.3.1
As always, I appreciate your dedication to this project.

**Comment by Mozahler** [comment]
The build I documented above finished after I opened the issue (it ran for 45+ minutes on a 13" retina MacBookPro on OS X 10.10.5, freshly rebooted before I started). Instead of an expect 108 or so classes/protocols/extensions, I got 3. I have no idea why. jazzyCmd.sh is the command line mentioned above. (jazzy --skip-undocumented --swift-version 2.0 --min-acl internal)
$ ./jazzyCmd.sh 
Running xcodebuild
Parsing NSCalendarExtensions.swift (1/3)
Parsing Utilities.swift (2/3)
Parsing EventStoreExtensions.swift (3/3)
building site
jam out ♪♫ to your fresh new docs in `docs`

**Comment by segiddins** [comment]
Perhaps it would help if you specified xcodebuild arguments in your invocation of jazzy?

**Comment by Mozahler** [comment]
I don't understand 😕

**Comment by segiddins** [comment]
```
    -x arg1,arg2,…argN,              Arguments to forward to xcodebuild
        --xcodebuild-arguments
```

**Comment by Mozahler** [comment]
Which ones are need beyond those I documented above?

**Comment by Mozahler** [comment]
I see. I need to understand how to use xcodebuild. Fair enough. Thanks.

**Comment by Mozahler** [comment]
💃🏾👯🎉🐢💨🎉👯🎉💃

**Comment by jpsim** [comment]
hahaha, I'm glad you figured it out @Mozahler!
