### ISSUE TITLE
Xcode 7.1

### ISSUE THREAD

**Issue by gsapienza** [realm/jazzy#311]
Is there support for Xcode 7.1 yet? Can't get anything documented, maybe I am missing something.

This is what I am seeing. Im sure my comments are formatted correctly

![No documentation](https://s3.amazonaws.com/f.cl.ly/items/0H081G2m3F2r3M422T44/Screen%20Shot%202015-10-02%20at%202.41.46%20PM.png)

**Comment by jpsim** [comment]
Sure, Xcode 7.1 works, what command did you run to generate these empty docs? What project is this running on? Is the framework you're documenting empty?

**Comment by gsapienza** [comment]
Just used the plain 'jazzy' command. It is running on a project that contains cocoa pods. I'm not sure if that makes a difference. Which framework would you be referring to?

**Comment by segiddins** [comment]
try running `jazzy --swift-version 2.1`?

**Comment by gsapienza** [comment]
this is what that returns

/Library/Ruby/Gems/2.0.0/gems/jazzy-0.3.1/lib/jazzy/sourcekitten.rb:116:in `run_sourcekitten': undefined method `as_env' for nil:NilClass (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.3.1/lib/jazzy/doc_builder.rb:56:in `block in build'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.3.1/lib/jazzy/doc_builder.rb:54:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.3.1/lib/jazzy/doc_builder.rb:54:in `build'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.3.1/bin/jazzy:15:in `<top (required)>'
	from /usr/local/bin/jazzy:23:in `load'
	from /usr/local/bin/jazzy:23:in `<main>'

**Comment by jpsim** [comment]
Looks like jazzy can't find Xcode 7.1 on your machine. Are you sure you have that version installed?

Sorry for the stack trace there, we should really be catching that error more elegantly.

**Comment by jpsim** [comment]
Actually that error message should be improved as of #303, which still needs work before we can merge it.

**Comment by gsapienza** [comment]
Yep here is a screenshot of the version
![Xcode](https://s3.amazonaws.com/f.cl.ly/items/0v1j0e2o3k3o1u1s2v2R/Screen%20Shot%202015-10-02%20at%205.03.23%20PM.png)

Is there a way to point jazzy to the correct version of Xcode?

**Comment by jpsim** [comment]
> Is there a way to point jazzy to the correct version of Xcode?

Yes, specifying `--swift-version 2.1`. Jazzy uses Spotlight to find an Xcode with an appropriate Swift version, so maybe check that Spotlight is turned on and has indexed this Xcode installation?

**Comment by gsapienza** [comment]
Yep its there in spotlight :(

**Comment by jpsim** [comment]
Then I don't know why Jazzy can't find it. But that's orthogonal to your initial issue though, which is your docs being empty.

> Just used the plain 'jazzy' command. It is running on a project that contains cocoa pods. I'm not sure if that makes a difference. Which framework would you be referring to?

So are you using jazzy to document an iOS app rather than a framework? Please keep in mind that Jazzy's minimum ACL to document is `public` by default, so if your app only has `internal` or `private` declarations, jazzy won't pick up anything. You can pass `--min-acl internal` to see what that does.

**Comment by gsapienza** [comment]
Ok I did that and interestingly it only documented my watch extension.

**Comment by jpsim** [comment]
> Ok I did that and interestingly it only documented my watch extension.

So that must be the default scheme that's built when you run `xcodebuild` in your project's root too, then?

You can specify which module to document by passing in the `--module` parameter.

**Comment by gsapienza** [comment]
Ok where can I find the exact name of each module?

**Comment by jpsim** [comment]
In Swift, when you write `import ****` that's the module name. So for your app, it's the app's name.

**Comment by gsapienza** [comment]
didn't work :/ tried jazzy --module APP_NAME

**Comment by jpsim** [comment]
To be able to help you further, could you please post the exact steps we can take to reproduce your situation?

**Comment by gsapienza** [comment]
Sure, so I have an iOS project running swift 2.1, with a watch app and cocoa pods installed. I installed jazzy and documented a few non private methods to test it. I then ran the 'jazzy' command in the apps directory. From there I opened the docs in the project to find them empty. However, like I said earlier, it seems to be only documenting the files in my watch extension

**Comment by jpsim** [comment]
Here's what I think is happening:

1. When Xcode adds a watch extension target, it uses the naming scheme `$app_name WatchKit Extension` and `$app_name WatchKit App`.
2. When Jazzy is passed the `-m $app_name` argument, it will not only match `$app_name` but also the watch targets because of how SourceKitten extracts the compiler arguments for the given module: https://github.com/jpsim/SourceKitten/blob/0.5.1/Source/SourceKittenFramework/Xcode.swift#L128

If this is the case, you can tell Xcode to build just the app module by passing in `xcodebuild` arguments to jazzy: `jazzy -x '-scheme,$app_name'` (no space after the comma).

The proper way to fix this in jazzy will be to find a better way to extract compiler arguments, either by using an entirely different way than parsing `xcodebuild` output (which has always been fragile and hacky), or by at least strengthening the regular expression used to detect which one is for the given module name.

**Comment by gsapienza** [comment]
Ok that is almost there! It parses the correct files, but unfortunately throws me this and doesn't make the docs

 
building site
/Library/Ruby/Gems/2.0.0/gems/jazzy-0.3.1/lib/jazzy/sourcekitten.rb:233:in `make_source_declarations': undefined method `each' for nil:NilClass (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.3.1/lib/jazzy/sourcekitten.rb:235:in `block in make_source_declarations'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.3.1/lib/jazzy/sourcekitten.rb:233:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.3.1/lib/jazzy/sourcekitten.rb:233:in `make_source_declarations'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.3.1/lib/jazzy/sourcekitten.rb:305:in `parse'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.3.1/lib/jazzy/doc_builder.rb:109:in `build_docs_for_sourcekitten_output'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.3.1/lib/jazzy/doc_builder.rb:67:in `build'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.3.1/bin/jazzy:15:in `<top (required)>'
	from /usr/local/bin/jazzy:23:in `load'
	from /usr/local/bin/jazzy:23:in `<main>'

**Comment by jpsim** [comment]
@gsapienza please show me some code that reproduces that. I don't have much to go on at the moment.

**Comment by gsapienza** [comment]
Anything particular that would help? unfortunately, I'm not allowed to share the project that I am trying to integrate jazzy with

**Comment by jpsim** [comment]
> Anything particular that would help?

Whatever it would take for someone without access to your project to trigger the same issue you're getting.

**Comment by C4Framework** [comment]
`--swift-version 2.1` worked for me
