### ISSUE TITLE
How to update the integration tests to accept a new file.

### ISSUE THREAD

**Issue by jeeftor** [realm/jazzy#316]
Hi,

I have a pull request #315 that is currently failing because I've added new file to the template `bb.png` which is a bitbucket icon.  The problem is i'm not a ruby developer and I'm having trouble tracking down which file i need to update to get the integration tests to pass.  I believe somewhere I need to tell "something" that its ok for this file to exist in the `after` directory.

Any suggestions where to look??

**Comment by jpsim** [comment]
You're right that this should be documented!

There's a rake task to regenerate the integration fixtures: `bundle exec rake rebuild_integration_fixtures` (make sure you've run `bundle install` at least once before).

Once the integration specs have been rebuilt, you can make a PR at https://github.com/realm/jazzy-integration-specs and update the git submodule in this repo to point to the new commit.

**Comment by jeeftor** [comment]
So I forked the integration-specs repo - and I guess I will update my pull request to point to my version of the integration repo - then re-run the integration tests ... if they pass I will re-point to your repo, and submit a pull request on the integration repo - and then once that is updated my pull request should pass?

Is this the best way to do this?

**Comment by jpsim** [comment]
I think so. It's certainly messy, but still better than having that huge repo combined in jazzy proper.

**Comment by jpsim** [comment]
I added more details around this in #396. Thanks for encouraging us to do this!
