### ISSUE TITLE
Support all Swift 2 doc keywords

### ISSUE THREAD

**Issue by mkieselmann** [realm/jazzy#317]
Hi,
is there any possibility to treat the `throws` keyword in Swift 2 as a special case for methods; just like `returns` or the parameters.
For example:
```
/**
Description

  - throws: Error
  - returns: the list of log files
*/
public static func getLogFiles() throws -> [String] 
```
The returns description is styled in a special way just as the parameters, which are formatted with a table. It would be great to have a special style for the throws keyworks that is applied automatically for any `- throws: description`declarations.

Best regards and keep up the great work on jazzy.

**Comment by jpsim** [comment]
We should totally support this, along with all the other keywords described here: http://ericasadun.com/2015/06/14/swift-header-documentation-in-xcode-7/

**Comment by jpsim** [comment]
@mkieselmann and @jessesquires, you may be interested in #323, which provides support for this.
