### ISSUE TITLE
Jazzy `run_sourcekitten': undefined method `as_env' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by shashankdekate81** [realm/jazzy#320]
Hi 
I have install jazzy for swift html documentation. when i run jazzy command it alway show me

/Library/Ruby/Gems/2.0.0/gems/jazzy-0.3.1/lib/jazzy/sourcekitten.rb:116:in `run_sourcekitten': undefined method `as_env' for nil:NilClass (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.3.1/lib/jazzy/doc_builder.rb:56:in `block in build'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.3.1/lib/jazzy/doc_builder.rb:54:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.3.1/lib/jazzy/doc_builder.rb:54:in `build'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.3.1/bin/jazzy:15:in `<top (required)>'
	from /usr/bin/jazzy:23:in `load'
	from /usr/bin/jazzy:23:in `<main>'

I am using Xcode 6.3.2

**Comment by segiddins** [comment]
This has a better error message on master.

**Comment by jpsim** [comment]
...and that error message would say that jazzy couldn't find an Xcode that could build the requested Swift version.
