### ISSUE TITLE
Support -throws:, -note:, and -warning:

### ISSUE THREAD

**Issue by jessesquires** [realm/jazzy#322]
Currently, it looks like the latest version of jazzy does not parse/render `-throws:`, `-note:`, `-warning:`.

**Comment by jpsim** [comment]
Absolutely. I really haven't had much time to dedicated to jazzy lately, but this is high on my list, and already being tracked in #317.

**Comment by jessesquires** [comment]
Thanks @jpsim ! Sorry for the dupe! :blush:

**Comment by jpsim** [comment]
No worries at all, the previous one wasn't very descriptively named, so I just renamed it :stuck_out_tongue:
