### ISSUE TITLE
Runtime Error when parsing Swift file.

### ISSUE THREAD

**Issue by devxoul** [realm/jazzy#331]
**Environment**

- Jazzy 0.3.2
- OS X 10.11.1
- Ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin15]
- Xcode 7.1 (7B91b)
- Swift 2.1
- Building iOS 7.0 target project

**Command**

```bash
$ jazzy\
    --xcodebuild-arguments -workspace,StyleShare.xcworkspace,-scheme,StyleShare\
    --min-acl private\
    --swift-version 2.1

```

**Output**

```console
Running xcodebuild
Parsing A.swift (1/200)
Parsing B.swift (2/200)
Parsing C.swift (3/200)
...repeated...
Parsing X.swift (106/200)
Parsing StyleFullViewController.swift (107/200)
/usr/local/lib/ruby/gems/2.2.0/gems/jazzy-0.3.2/lib/jazzy/executable.rb:35:in `execute_command': /usr/local/lib/ruby/gems/2.2.0/gems/jazzy-0.3.2/lib/jazzy/SourceKitten/bin/sourcekitten ["doc", "-workspace", "StyleShare.xcworkspace", "-scheme", "StyleShare"] (RuntimeError)

Parsing A.swift (1/200)

Parsing B.swift (2/200)

Parsing C.swift (3/200)

...repeated...

Parsing X.swift (106/200)

Parsing StyleFullViewController.swift (107/200)
	from /usr/local/lib/ruby/gems/2.2.0/gems/jazzy-0.3.2/lib/jazzy/sourcekitten.rb:128:in `run_sourcekitten'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jazzy-0.3.2/lib/jazzy/doc_builder.rb:56:in `block in build'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jazzy-0.3.2/lib/jazzy/doc_builder.rb:54:in `chdir'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jazzy-0.3.2/lib/jazzy/doc_builder.rb:54:in `build'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jazzy-0.3.2/bin/jazzy:15:in `<top (required)>'
	from /usr/local/bin/jazzy:23:in `load'
	from /usr/local/bin/jazzy:23:in `<main>'
```

Am I doing wrong?
Thanks!

**Comment by segiddins** [comment]
Looks to me like source kitten choked at some point?

**Comment by jpsim** [comment]
@devxoul could you please share the contents of the Swift file that crashes jazzy? That should help us troubleshoot. Thanks!

**Comment by devxoul** [comment]
@jpsim, I think it has been fixed in https://github.com/jpsim/SourceKitten/issues/75 and shipped with 0.5.2 release. Running `$ sourcekitten` with 0.5.2 works properly.

How can I use jazzy with SourceKitten 0.5.2? It seems that submodule is pointing the latest commit of SourceKitten, but I don't think the latest release of jazzy uses it. Should I have to build and run manually?

Thanks!

**Comment by segiddins** [comment]
@devxoul for now you'll need to run jazzy from master, but I can imagine we'll be putting out a new release sometime soon.

**Comment by jpsim** [comment]
Closing as this is fixed on master. I intend to cut a jazzy release as soon as possible.

**Comment by devxoul** [comment]
:+1:
