### ISSUE TITLE
Fails to create documentation

### ISSUE THREAD

**Issue by AfricanSwift** [realm/jazzy#332]
After parsing all the swift files it ends with the following message:

parsing ....

/Library/Ruby/Gems/2.0.0/gems/jazzy-0.3.2/lib/jazzy/executable.rb:35:in `execute_command': /Library/Ruby/Gems/2.0.0/gems/jazzy-0.3.2/lib/jazzy/SourceKitten/bin/sourcekitten "doc"] (RuntimeError)

parsing... 

from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.3.2/lib/jazzy/sourcekitten.rb:128:in `run_sourcekitten'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.3.2/lib/jazzy/doc_builder.rb:56:in `block in build'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.3.2/lib/jazzy/doc_builder.rb:54:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.3.2/lib/jazzy/doc_builder.rb:54:in `build'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.3.2/bin/jazzy:15:in `<top (required)>'
	from /usr/bin/jazzy:23:in `load'
	from /usr/bin/jazzy:23:in `<main>'

Is there a more detailed log that will explain why it's crashing?

FYI:
Xcode Version 7.0 (7A220), stored as xcode.app in /Applications

**Comment by AfricanSwift** [comment]
Additional error, occurs first, followed by the rest.

/Library/Ruby/Gems/2.0.0/gems/jazzy-0.3.2/lib/jazzy/executable.rb:35:in `execute_command': /Library/Ruby/Gems/2.0.0/gems/jazzy-0.3.2/lib/jazzy/SourceKitten/bin/sourcekitten ["doc"] (RuntimeError)

**Comment by AfricanSwift** [comment]
First error, followed by the above.

/Library/Ruby/Gems/2.0.0/gems/jazzy-0.3.2/lib/jazzy/executable.rb:35:in `execute_command': /Library/Ruby/Gems/2.0.0/gems/jazzy-0.3.2/lib/jazzy/SourceKitten/bin/sourcekitten ["doc"] (RuntimeError)

**Comment by AfricanSwift** [comment]
This seems to be part of the same issue as [Illegal instruction: 4] (https://github.com/jpsim/SourceKitten/issues/75)

**Comment by AfricanSwift** [comment]
This is a small rendition is what caused the SourceKitten crash.

extension NSColor {
    public var red: CGFloat {
        /// crash scenario -  This line crashes source kitten.
        let multiplier: CGFloat = 255.0
        return self.redComponent * multiplier
    }
}

**Comment by jpsim** [comment]
This was fixed in https://github.com/jpsim/SourceKitten/pull/79 and will be included in the next release of jazzy.

Thanks for taking the time to share details on what wasn't working for you!
