### ISSUE TITLE
Members added to extension of nested type show up in the parent

### ISSUE THREAD

**Issue by pcantrell** [realm/jazzy#333]
Realm adds a `description` extension to the nested type `Realm.Configuration`:

https://github.com/realm/realm-cocoa/blob/master/RealmSwift-swift2.0/RealmConfiguration.swift#L168-L173

…but Jazzy puts it on `Realm:`

https://github.com/realm/jazzy-integration-specs/blob/c14d4041795d0ab886977729e81afd92372b4e6b/document_realm_swift/after/docs/Extensions/Realm.html#L235-L264

**Comment by istx25** [comment]
Completed with #343.

**Comment by jpsim** [comment]
This is still very much a bug: https://realm.io/docs/swift/latest/api/Classes/Realm.html#/s:vVC10RealmSwift5Realm13Configuration11descriptionSS

![image](https://cloud.githubusercontent.com/assets/474794/20637305/d1f27880-b338-11e6-8cc0-89039ac510e5.png)

**Comment by istx25** [comment]
I see, sorry about that!

**Comment by johnfairh** [comment]
Was hoping this would be fixed by latest sourcekitten - is not, problem seems to be that SourceKit is pretty sure that the extension is of Realm rather than Realm.Configuration.  More digging.

**Comment by maximkhatskevich** [comment]
The problem persists for me as well, see this repo:
https://github.com/XCEssentials/State/tree/2.6.2

In particular, type `State` has nested type `Pending`, which is declared in extension of `State`, but member function `onUpdate` that belongs to `Pending` appears in `State` members list, not in `Pending`.
