### ISSUE TITLE
Sourcekitten does not return extension declarations

### ISSUE THREAD

**Issue by pcantrell** [realm/jazzy#334]
For an extension of `A`, sourcekitten gives the original declaration of `A` instead of the extension declaration:

      {
        "key.kind" : "source.lang.swift.decl.extension",
        ...
        "key.annotated_decl" : "<Declaration>public final class List&lt;T : <Type usr=\"s:C10RealmSwift6Object\">Object<\/Type>&gt; : <Type usr=\"s:C10RealmSwift8ListBase\">ListBase<\/Type><\/Declaration>",
        ...

As far as I can tell, this prevents Jazzy from being able to show type constraints on extensions.

**Comment by jpsim** [comment]
Fixed in #441.
