### ISSUE TITLE
Docs not being generated with Xcode 7.1 and Swift 2.1

### ISSUE THREAD

**Issue by mattgabor** [realm/jazzy#336]
Has anyone been able to successfully run Jazzy with Xcode 7.1 and Swift 2.1? 

I run` jazzy --swift-version 2.1 --min-acl --module MyProject`
and jazzy runs properly, but my docs are still empty.

This is the documentation style I am using in my code:
```
   /**
    Searches the file system for a given directory
    - author: Matt Gabor
    - parameter atPath: The path you want to retrieve files from
    - returns: An array of the path URLs located in atPath
    */
```

**Comment by segiddins** [comment]
You have to actually specify a minimum acl, as in `--min-acl internal`

**Comment by mattgabor** [comment]
Sorry about that, thanks for the help.
