### ISSUE TITLE
Can't select iOS SDK

### ISSUE THREAD

**Issue by jverkoey** [realm/jazzy#345]
When I run the following:

    jazzy --objc --framework-root . --umbrella-header NimbusCore.h --module NimbusCore --output docs

This error is logged: `fatal error: 'UIKit/UIKit.h' file not found`

I'm not sure how to change the default SDK path, which appears to be the OSX SDK.

    > xcrun --show-sdk-path
    /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk

I was able to fix this last night by changing `sourcekitten.rb:120` from `xcrun --show-sdk-path` to

    /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.1.sdk

But I figure there's a better way to do this?

**Comment by jpsim** [comment]
For the time being, you can specify the full clang arguments yourself like so:

```
jazzy --objc -x --objc,NimbusCore.h,-x,objective-c,-isysroot,`xcrun --show-sdk-path --sdk iphoneos`,-I,`pwd` --module NimbusCore --output docs
```

But this is something I'll want to simplify soon.

**Comment by jverkoey** [comment]
Ah hah, `xcrun --show-sdk-path --sdk iphoneos` is what I was looking for :) Those args worked, thanks!
