### ISSUE TITLE
Is indirect documentation possible?

### ISSUE THREAD

**Issue by jverkoey** [realm/jazzy#346]
This may be impossible, but in doxygen-land you can write documentation for an API that lives separate from the declaration of the API. For example:

```
@interface SomeClass : NSObject

/** Summary summary. */
- (void)someMethod;

@end

/**
 Additional long-form documentation explaining technical considerations for the API.
 @fn SomeClass::someMethod
 */
```

I realize that jazzy uses Clang, so any features are limited by what Clang is able to do. I'm asking this more as a "is this even possible?" rather than a feature request :)

Assuming it's impossible at the Clang level (which I'm expecting), is there a way at the jazzy level to provide auxiliary documentation for APIs? Perhaps it would be possible to extend jazzy in this manner given that you have the AST already. Could have a directory of auxiliary .md files that are associated with given APIs...

**Comment by jpsim** [comment]
It'd be possible to do this, but I'm not sure I'd want to. I'm not convinced that adding in the necessary complexity to make this happen would be worthwhile, to be honest.

**Comment by jverkoey** [comment]
Cool, good to know. Thanks for the feedback!
