### ISSUE TITLE
Does jazzy support method or property link?

### ISSUE THREAD

**Issue by Zingoer** [realm/jazzy#359]
I'm trying to write some comments that reference some other class's methods and properties. Would some one tell me how to do it in markdown with Jazzy? I do know that jazzy can link class automatically if use `MyClass`.

**Comment by jpsim** [comment]
Currently jazzy only autolinks top-level declarations (the tokens you see in the left sidebar: classes, structs, functions, enums, globals, etc.). But @pcantrell is working on making it possible to reference sub-declarations in #355 which is all sorts of awesome :).

**Comment by segiddins** [comment]
It should work of you fully qualify the method or property.

**Comment by Zingoer** [comment]
@jpsim Awesome. Thank you for your fast reply! I really love this project. Hope #355 can be finished soon ;p

**Comment by pcantrell** [comment]
Soon as the busy redhead gets a few free minutes! (I’m eager for it too. Which is why I wrote it, I guess.)

**Comment by jpsim** [comment]
The busy redhead wrapped this up in an awesome PR of autolinking improvements in #355. Thanks @pcantrell
