### ISSUE TITLE
Jazzy produces filenames with unsupported characters on Windows for Swift Operators

### ISSUE THREAD

**Issue by RndmTsk** [realm/jazzy#361]
Operators such as "public func +=<K, V> (inout left: [K:V], right: [K:V]) { ... }" produce file names that include unsupported characters on Windows machines (i.e. an IIS server).

Example filename: +=(_:_:).html

**Comment by RndmTsk** [comment]
Here is a list of unsupported characters: https://support.microsoft.com/en-us/kb/177506

**Comment by istx25** [comment]
#558 needs to be reviewed but this issue is a little irrelevant/out of date now. Closing and will continue the conversation in that PR.

**Comment by SDGGiesbrecht** [comment]
The configuration option `use_safe_filenames` and the corresponding flag `--use-safe-filenames` are now available. Until 0.7.4 is released, you can build and run from source (in your project directory):
```
git clone https://github.com/realm/jazzy
cd jazzy
bundle install
cd ..
jazzy/bin/jazzy --use-safe-filenames
rm -rf jazzy
```
Any other flags you normally use (such as `--clean`) can be added to the second last line.
