### ISSUE TITLE
Support bracket syntax for Objective-C autolinks

### ISSUE THREAD

**Issue by pcantrell** [realm/jazzy#362]
Autolinking should support:
- `[RLMRealm defaultRealm]`
- `+[RLMRealm defaultRealm]`
- `-[RLMRealm writeCopyToPath:encryptionKey:error:]`

Notes:
- Ensure that `RLMRealm.configuration` still works after this change.
- Not necessary at this time to prevent dot-separated references from working, even if they’re not valid Obj-C.

**Comment by jpsim** [comment]
> Not necessary at this time to prevent dot-separated references from working, even if they’re not valid Obj-C.

`RLMRealm.configuration` isn't valid ObjC but is certainly a lot nicer to write than `-[RLMRealm configuration]`, and the former to me implies a property, while the latter is more of an instance method, which has *some* semantic difference.

**Comment by istx25** [comment]
Any progress on this?

**Comment by jpsim** [comment]
None to report.

**Comment by 1ec5** [comment]
#707 implements the `+[RLMRealm defaultRealm]` and `-[RLMRealm writeCopyToPath:encryptionKey:error:]` syntaxes without regressing the `RLMRealm.configuration` syntax.

**Comment by 1ec5** [comment]
More syntaxes we should autolink:

* [ ] `+defaultRealm`
* [ ] `-writeCopyToPath:encryptionKey:error:`
