### ISSUE TITLE
README clarification

### ISSUE THREAD

**Issue by jverkoey** [realm/jazzy#365]
What does "installed in a location indexed by Spotlight" mean as far as being a requirement?

**Comment by segiddins** [comment]
It means that `mdfind "kMDItemCFBundleIdentifier == 'com.apple.t.Xcode'` has to include that Xcode

**Comment by jpsim** [comment]
Spotlight doesn't index all locations on your system (system, temp, cache directories, etc.), so as long as Spotlight is enabled on your system and has indexed the location where you've installed the Xcode version you need to build your documentation, jazzy will find it.

Jazzy uses [xcinvoke](https://github.com/segiddins/xcinvoke) to do this. Here's where we integrate this: https://github.com/realm/jazzy/blob/41e3a8825b4194322b0d15483f9071573a59027f/lib/jazzy/sourcekitten.rb#L136-L142
