### ISSUE TITLE
Broken link in config.rb

### ISSUE THREAD

**Issue by lumaxis** [realm/jazzy#379]
The link [`http://git.io/vcTZm`](http://git.io/vcTZm) [here](https://github.com/realm/jazzy/blob/b3bd5bce8203081fc747561020bd70cf99c18f08/lib/jazzy/config.rb#L238) ends in a 404

**Comment by pcantrell** [comment]
Oh, that's my fault! Updated Siesta forgetting that the jazzy docs referred to that file.
