### ISSUE TITLE
Not sure how to format config file... Perhaps provide a sample?

### ISSUE THREAD

**Issue by nicolas-miari** [realm/jazzy#401]
I am getting errors when trying to use a config file (as opposed to passing arguments through the command line); perhaps a sample `.yaml` file in the README would help?

These are the contents of my config file (`.jazzy.yaml`):

    author:myname@maydomain.com
    min_acl:internal

And this is the Terminal output:

    $ jazzy
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin15/rbconfig.rb:213: warning: Insecure world writable dir /usr in PATH, mode 040777
    Using config file /Users/[myUserName]/Projects/[Project Folder Name]/Production/Code/.jazzy.yaml
    /Library/Ruby/Gems/2.0.0/gems/jazzy-0.4.0/lib/jazzy/config.rb:319:in `block in parse_config_file': undefined method `key?' for "author:myname@maydomain.com min_acl:internal":String (NoMethodError)
    	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.4.0/lib/jazzy/config.rb:317:in `each'
	    from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.4.0/lib/jazzy/config.rb:317:in `parse_config_file'
	    from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.4.0/lib/jazzy/config.rb:265:in `parse!'
	    from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.4.0/bin/jazzy:15:in `<top (required)>'
	    from /usr/local/bin/jazzy:23:in `load'
	    from /usr/local/bin/jazzy:23:in `<main>'
    $ _`

**Comment by segiddins** [comment]
You need a space after the `:`

**Comment by nicolas-miari** [comment]
Oh, thanks. I'm dead serious I was using a space at first, and then collapsed it to see if it would work, but must be my imagination.

**Comment by DanBurkhardt** [comment]
Ok, but also, can we get a sample yaml file that just shows all of the possible options?
