### ISSUE TITLE
Keywords rendered "as-is" unless separated by blank new line

### ISSUE THREAD

**Issue by nicolas-miari** [realm/jazzy#402]
I have these two methods, with comments as shown:

    /**
     A simple method to illustrate documentation comments.
     - parameter string: The sample string.
     - returns: The compond string.
     - since: 1.0
     - author: Nicolás Miari.
     */
    func firstMethod(withString string:String) -> String
    {
        return "First Method called with string: \(string)"
    }
    
    /**
     Another simple method to illustrate documentation comments.
    
     - parameter string: The sample string.
    
     - returns: The compond string.
    
     - since: 1.0
    
     - author: Nicolás Miari.
    */
    func secondMethod(withString string:String) -> String
    {
        return "Second Method called with string: \(string)"
    }

(Notice how keywords are separated by extra empty lines in the second method).

**Note: Both comment blocks' keywords are parsed properly by Xcode:** they are drawn in the color specified by `Documentation Markup Keywords` in Xcode's `Preferences > Fonts & Colors` (as opposed to the -different-  `Documentation Markup` color).

When I run jazzy, I get this for the first method:

<img width="764" alt="first 2x" src="https://cloud.githubusercontent.com/assets/1000912/11434436/dd36f1f0-950f-11e5-9be7-fad8bb335270.png">

(I have highlighted the keyword content, being wrongly appended "as-is" to the method description).

...whereas for the second method (with blank lines between keywords), I get the expected result:

<img width="759" alt="second 2x" src="https://cloud.githubusercontent.com/assets/1000912/11434448/0c321c0a-9510-11e5-80d3-2c203b63dc22.png">

**Comment by nicolas-miari** [comment]
Notice that `parameter` and `returns` are properly interpreted as method parameters and return value respectively, **in addition** to being inlined in the method description. In contrast, `since` and `author` are ignored. I haven't tested other keywords.

**Comment by jpsim** [comment]
Jazzy uses Markdown to parse documentation comments. This text does not create a valid Markdown list:

```md
A simple method to illustrate documentation comments.
- parameter string: The sample string.
- returns: The compond string.
- since: 1.0
- author: Nicolás Miari.
```

Whereas this does:

```md
Another simple method to illustrate documentation comments.

- parameter string: The sample string.

- returns: The compond string.

- since: 1.0

- author: Nicolás Miari.
```

So Xcode is not following Markdown convention here. You can see that how jazzy generates its Markdown is correct, based on this: http://daringfireball.net/projects/markdown/dingus

The parameters and return are being parsed regardless because jazzy relies on Xcode's parser for those, but we intend to move away from this soon towards to pure Mardown parsing instead.

**Comment by nicolas-miari** [comment]
Great, thanks for the detailed explanation. I'm all for not perverting markdown, too.

It is a bummer, though, given how many more blank lines are needed to write the same documentation, but I guess I'll have to live with that.

**Comment by jpsim** [comment]
> It is a bummer, though, given how many more blank lines are needed to write the same documentation, but I guess I'll have to live with that.

I should've clarified that you don't need blank lines between each item. This is fine:

```md
Another simple method to illustrate documentation comments.

- parameter string: The sample string.
- returns: The compond string.
- since: 1.0
- author: Nicolás Miari.
```

So you just need a blank line before the list, otherwise it's not a list according to Markdown.

**Comment by nicolas-miari** [comment]
Oh, great. Thanks again!

**Comment by thislooksfun** [comment]
This is still an issue when using `Parameters` instead of individual `parameter` definitions

Working example:
```Swift
/// Some basic description
///
/// - parameter name: description
/// - parameter otherName: something else
```

Not working (adds a nested list to the output):
```Swift
/// Some basic description
///
/// - Parameters:
///   - name: description
///   - otherName: something else
```

**Comment by jpsim** [comment]
@thislooksfun see #388.

**Comment by thislooksfun** [comment]
Whoops, my bad. Didn't see that one.
