### ISSUE TITLE
Japanese Text When Commenting Enums - Hell Breaks Loose.

### ISSUE THREAD

**Issue by nicolas-miari** [realm/jazzy#403]
This is my code (actual code):

    /**
     メモ書きの線の太さを表す定数群。

     - since: 1.0
     */
    enum StrokeWidth: Int
    {
    
        /**
         一番細い線の幅（ 2 ポイント相当）。
     
         - since: 0.1
         */
        case Thin = 0
    
    
        /**
         二番目に細い線の幅（ 4 ポイント相当）。
     
         - since: 1.0
         */
        case MediumThin
    
        /**
         中間の線の幅（ 6 ポイント相当）。
     
         - since: 1.0
         */
        case Medium
    
        /**
         二番目に太い線の幅（ 8 ポイント相当）。
     
         - since: 1.0
         */
        case MediumThick
    
        /**
         一番太い線の幅（ 10 ポイント相当）。
     
         - since: 1.0
         */
        case Thick
    }

**Notice that the comments for each `case` have the exact same structure, including white space.**

_(I have removed some methods in the enum which presence or absence doesn't seem to alter the effects of the issue)_

The enum's description and `since:` keyword are rendered as expected.

<img width="750" alt="top 2x" src="https://cloud.githubusercontent.com/assets/1000912/11438642/8b2421b0-9539-11e5-9d76-279ae316d5ec.png">

Cases `.MediumThin`, `.MediumThick`, and `.Tick`, too, render as expected:

<img width="757" alt="mediumthin 2x" src="https://cloud.githubusercontent.com/assets/1000912/11438652/93fac79e-9539-11e5-9cf8-d792d69f63b6.png">

...but for the first case `.Thin`, the `since:` keyword is rendered as a code block:

<img width="753" alt="thin 2x" src="https://cloud.githubusercontent.com/assets/1000912/11438661/a6ce50b6-9539-11e5-8886-0ae154f1f4cc.png">

...and for the  third case `.Medium`, the description and `since:` content are missing, and only the declaration is rendered:

<img width="753" alt="medium 2x" src="https://cloud.githubusercontent.com/assets/1000912/11438665/aa9a094c-9539-11e5-8e42-7795b8ef21ee.png">

After looking for what could be causing it (and comparing this actual code with other simpler enums that I created for testing), **I realized that the japanese description of the enum had something to do:** If I replace it by text in roman characters (or remove it altogether), the issue disappears (all cases render as expected).

**However,** it is not that simple: If instead, I reduce the whole enum description to the single, first character "メ", the issue disappears too.

A quick binary search revealed that the maximum allowed portion of the original description text is: 

> メモ書きの線の...

Any further japanese characters trigger the issue, but appending roman characters seems to have no ill effect.

Perhaps this is an issue with SourceKit, and hence completely out of your reach. But if not, perhaps it's worth a look...

**Comment by nicolas-miari** [comment]
**ADDENDUM:**

I also tried progressively trimming the description text from the start, and only when I got as short as:

> ...を表す定数群。

...did the issue disappear.

The two central, consecutive characters that are missing on both cases are:

 > ...太さ...

Removing these and leaving the rest of the description intact does not solve the issue, however.

**Comment by segiddins** [comment]
What version of jazzy are you using?

**Comment by nicolas-miari** [comment]
I'm not sure how to check the version of jazzy, but I installed it not long a go (couple of weeks?).

`which jazzy`

gives:

`/usr/local/bin/jazzy`

And right command-I on the executable doesn't give much info.

**Comment by segiddins** [comment]
`jazzy --version` ?

**Comment by nicolas-miari** [comment]
Oops! missed that in the `jazzy -h` output (near the bottom)!

It is `0.4.0`.

**Comment by nicolas-miari** [comment]
Updated to 0.4.1, seems to be working now; thanks.

**Comment by nicolas-miari** [comment]
Wait, silly me... I had removed the japanese text in the description and forgot to add it back. 
The issue is still happening as of 0.4.1.

**Comment by nicolas-miari** [comment]
**Additional info:**
I have added a (lazily) computed property and a method to my `enum`:

    /**
     全定数の個数を返す。
     
     - returns: 全定数（幅）の個数。
     
     - since: 1.0
     */
    static let count: Int = {
        var max: Int = 0
        while let _ = StrokeWidth(rawValue: ++max) {}
        return max
    }()
    
    /**
     各定数の実際の幅の値（浮動小数点数）。
     
     - returns: 実際の幅の値（浮動小数点数）。
     
     - since: 1.0
     */
    func floatValue() -> CGFloat
    {
        switch self {
        case .Thin:
            return 2.0
            
        case .MediumThin:
            return 4.0
        
        case .Medium:
            return 6.0
            
        case .MediumThick:
            return 8.0
            
        case .Thick:
            return 10.0
            
        default:
            return 0.0
        }
    }


I noticed that, when the japanese description text that causes the issue is present, these two render as expected. **However**, if I remove the description text altogether:

    /**
     
 
     - since: 1.0
     */

...or replace it with this:

    /**
     Description text in English, for testing purposes.
 
     - since: 1.0
     */

...then the `since:` keyword for **both** property **and** method seem to be ignored by jazzy, and are **absent** from the output:

<img width="766" alt="countandfloatvalue" src="https://cloud.githubusercontent.com/assets/1000912/11462865/5159597a-975d-11e5-9e14-cbd53327c5a7.png">

**Comment by nicolas-miari** [comment]
I have created a sample, minimal project that demonstrates the general issue: When the description text of a type (class, enum,etc.) contains Japanese text, jazzy's output for the documentation of its properties breaks. 

I'll update it with more variations (e.g., /***/-type comments vs. ///-type, etc.)

https://github.com/nicolas-miari/Jazzy-Test-Bed

**Comment by jpsim** [comment]
I believe this is fixed in #441.

**Comment by nicolas-miari** [comment]
Thanks; Will update jazzy and check as soon as I can.

**Comment by nicolas-miari** [comment]
Indeed, fixed as of 0.5.0. Thanks a lot!
