### ISSUE TITLE
Can't run jazzy commands - GEM Load Error

### ISSUE THREAD

**Issue by macromania** [realm/jazzy#407]
I've no idea about these Ruby errors but I get followings when I just run any jazzy commands. I guess, a step in installation could be missing in Readme. Any quick fix appreciated.

```
jazzy
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1995:in `raise_if_conflicts': can't activate activesupport-3.2.19, already activated activesupport-4.2.4 (Gem::LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1176:in `activate'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:96:in `block in require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:95:in `each'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:95:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.4.1/lib/jazzy/source_declaration/type.rb:1:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.4.1/lib/jazzy/source_declaration.rb:2:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.4.1/lib/jazzy/doc_builder.rb:13:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.4.1/lib/jazzy.rb:2:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.4.1/bin/jazzy:13:in `<top (required)>'
	from /usr/local/bin/jazzy:23:in `load'
	from /usr/local/bin/jazzy:23:in `<main>'
```

**Comment by isair** [comment]
If you try uninstalling activesupport-4.2.4, does it tell you that cocoapods is using it and you shouldn't proceed?

**Comment by jpsim** [comment]
Installing ruby gems is extremely dependent on your system configuration. Since this is a very old issue, I'm closing this but if you still have trouble installing jazzy, please open a new issue and I'll do my best to troubleshoot the process with you.

**Comment by tumatauenga** [comment]
I'm having this issue as well, looks to be a conflict with the version of activesupport that cocoapods 1.0.0 and 1.0.1 requires.

`
13:06:47$ jazzy -h
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1995:in `raise_if_conflicts': can't activate activesupport-3.2.18, already activated activesupport-4.2.4 (Gem::LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1176:in `activate'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:96:in `block in require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:95:in `each'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:95:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.7.0/lib/jazzy/source_declaration/type.rb:1:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.7.0/lib/jazzy/source_declaration.rb:2:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.7.0/lib/jazzy/doc_builder.rb:14:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.7.0/lib/jazzy.rb:2:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.7.0/bin/jazzy:13:in `<top (required)>'
	from /usr/local/bin/jazzy:23:in `load'
	from /usr/local/bin/jazzy:23:in `<main>'
13:09:57$ gem uninstall activesupport 4.2.4

Select gem to uninstall:
 1. activesupport-3.2.18
 2. activesupport-4.2.4
 3. All versions
> 2

You have requested to uninstall the gem:
	activesupport-4.2.4

cocoapods-1.0.1 depends on activesupport (>= 4.0.2)
cocoapods-1.0.0 depends on activesupport (>= 4.0.2)
cocoapods-core-1.0.1 depends on activesupport (>= 4.0.2)
cocoapods-core-1.0.0 depends on activesupport (>= 4.0.2)
If you remove this gem, these dependencies will not be met.
Continue with Uninstall? [yN]  N
ERROR:  While executing gem ... (Gem::DependencyRemovalException)
    Uninstallation aborted due to dependent gem(s)
`

**Comment by sh-a-n** [comment]
same error. Please fix this issuer.

**Comment by ericleich** [comment]
I ran into the same issue, and then uninstalling activesupport-3.2.18 fixed it for me.

I can't explain why jazzy wouldn't try to use activesupport-4.2.4 in the first place though.
