### ISSUE TITLE
Empty Description in Class Triggers Weird Layout Bug 

### ISSUE THREAD

**Issue by nicolas-miari** [realm/jazzy#408]
This source code:

    import Foundation

    /**
     - since: 0.1
     - author: Nicolás Miari.
     - todo: If the **description** text is a blank line or no line at all (i.e, all
     subsequent keywords start from the first line of the comment block) **and** all 
     the keyword lines start with a single space (i.e., first character is 
     horizontally aligned to coincide with the first asterisk of the block comment 
     opening -see source code of this comment if it isn't clear), then: the keywords 
     from the second on appear as if "nested" inside the first keyword (that is, as
     if indented "one level deeper"), and there is a residual closing "div" tag is 
     rendered as-is (uninterepreted) inside a code block at the end.
     Japanese text in the description doesn't seem to cause any problems.
    */
    class EmptyDescription
    {
    
    }

...causes this output:

<img width="757" alt="emptydescription 2x" src="https://cloud.githubusercontent.com/assets/1000912/11468347/140d295e-9792-11e5-89a8-c97e9c3bf47a.png">

As mentioned in the TODO above (the only option to keep the description empty, and trigger the issue!), the issue will not surface if either of the following is true:

1. The description (i.e., text before any keywords) is not **empty**. 
2. All the lines inside the block have zero trailing white space (see code below).

Example of number 2 above:

    /**
    - since: 0.1
    - author: Nicolás Miari.
    - todo: Empty description, yet all lines' first characters are horizontally aligned to the 
    opening "/" (no left margin).
    */

I have added this test class (as well as others) to my test-bed project where I trial-and-error different patterns to see what works and what doesn't:

https://github.com/nicolas-miari/Jazzy-Test-Bed

(It is much faster than experimenting in my 100+ source file production code, given how many times I run jazzy after minor changes).

**Comment by jpsim** [comment]
Sorry for not looking at this for a while, but going through old issues, this appears to be fixed now:

```swift
/**
 - since: 0.1
 - author: N/A.
*/
class EmptyDescription
{

}
```

![image](https://cloud.githubusercontent.com/assets/474794/14308336/54dd7fe0-fb8a-11e5-8447-511097226db7.png)
