### ISSUE TITLE
Can not install Jazzy on Mac

### ISSUE THREAD

**Issue by sauvikatinnofied** [realm/jazzy#409]
I am currently using **OS X Yosemite 10.10.5** and my *gem* version is *2.4.8*. While installing Jazzy using terminal command `$ [sudo] gem install jazzy` `terminal` is showing me error

```ternimal
Sauviks-Mac-mini:~ SauvikDolui$ sudo gem install jazzy
Building native extensions.  This could take a while...
ERROR:  Error installing jazzy:
	ERROR: Failed to build gem native extension.

    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -r ./siteconf20151130-16864-13be8fm.rb extconf.rb
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
make: *** No rule to make target `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/include/ruby-2.0.0/universal-darwin14/ruby/config.h', needed by `autolink.o'.  Stop.

make failed, exit code 2

Gem files will remain installed in /Library/Ruby/Gems/2.0.0/gems/redcarpet-3.3.3 for inspection.
Results logged to /Library/Ruby/Gems/2.0.0/extensions/universal-darwin-14/2.0.0/redcarpet-3.3.3/gem_make.out
```

**Comment by segiddins** [comment]
So that's actually failing to build redcarpet 's native extension, not an issue installing jazzy per se.

**Comment by jpsim** [comment]
@sauvikatinnofied I suggest you try `gem install redcarpet` and file an issue at https://github.com/vmg/redcarpet if anything goes wrong. If that installation succeeds, you should be able to `gem install jazzy` too.

**Comment by ewanmellor** [comment]
I had this same problem.  In my case it was because the Redcarpet build is trying to use Xcode's Ruby package, but these are configured for El Capitan (darwin15) and I was running on Yosemite (darwin14).

I fixed this with

    cd /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/include/ruby-2.0.0/
    sudo ln -s universal-darwin15 universal-darwin14

**Comment by GuoZhiQiang** [comment]
@ewanmellor  Do you have redcarpet installed in the path of `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/include/ruby-2.0.0/ `   ?

**Comment by ewanmellor** [comment]
@GuoZhiQiang No.  I have `/Library/Ruby/Gems/2.0.0/gems/redcarpet-3.3.4`, `/usr/local/bin/redcarpet`, `/Library/Ruby/Gems/2.0.0/extensions/universal-darwin-15/2.0.0/redcarpet-3.3.4`

**Comment by GuoZhiQiang** [comment]
is this what you have done : `cd /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/include/ruby-2.0.0/
sudo ln -s universal-darwin15 universal-darwin14`，

and run `sudo gem install redcarpet` ? I have an error when i install jazzy, but i don't know how to fix it https://github.com/realm/jazzy/issues/593

**Comment by GuoZhiQiang** [comment]
@segiddins @jpsim I suggest you install two versions of Xcode, then install jazzy later

**Comment by clarisoftro** [comment]
I was able to install both `redcarpet` and `jazzy` by running `xcode-select --install` to update XCode Command Line Tools to latest version.
