### ISSUE TITLE
Can't install `jazzy` gem from master.

### ISSUE THREAD

**Issue by nlutsenko** [realm/jazzy#410]
Gemfile:
```
gem 'jazzy', :git => 'git@github.com:realm/jazzy.git'
```

Running `bundle install` and all I get is:
```
Using jazzy 0.4.1 from git@github.com:realm/jazzy.git (at master)
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

 ($$omitted huge path for sanity reasons$$)

rake aborted!
Errno::EEXIST: File exists - (A, Versions/Current)
```

The Rakefile [here](https://github.com/realm/jazzy/blob/master/lib/jazzy/SourceKitten/Rakefile) looks shady. Not sure on what were the intentions there, but looks like `rubygems` actually doesn't omit symlinks when installing from master of the repo.
Probably the fix is as simple as just adding `unless File(...).exist` in those.

P.S. Can't contribute just yet for reasons outside of my control, but can point out issues.

**Comment by segiddins** [comment]
Ah do you have RubyGems 2.5? If so, I think I know how to fix it.

**Comment by nlutsenko** [comment]
Actually am running `2.4.6`...

**Comment by segiddins** [comment]
Interesting. @jpsim what RubyGems were you running when you released 0.4.1?

**Comment by jpsim** [comment]
```
$ ruby --version
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin15]
$ gem --version
2.4.5.1
```

**Comment by nlutsenko** [comment]
```
$ ruby --version
ruby 2.0.0p643 (2015-02-25 revision 49749) [x86_64-darwin14.1.0]
$ gem --version
2.4.6
```
;)

**Comment by segiddins** [comment]
Hm then it isn't what I think. But I think just `rm_rf`ing the symlink targets should be done anyways

**Comment by jpsim** [comment]
Since we continue to test installing jazzy from source on CI, and through several release tests, I'll close this as a ruby environment issue. If you're still having issues installing jazzy, please open a new issue and I'll be happy to help you troubleshoot the process.
