### ISSUE TITLE
Method Abstract Rendered as Code Block

### ISSUE THREAD

**Issue by nicolas-miari** [realm/jazzy#415]
Possibly related to #408, but not sure.

I have a huge `UIViewController` subclass with many many properties, outlets, actions and methods.
For some methods (but not all), the abstract will render as a code block. There are no spaces or other markup that could trigger that. 

Example:

    /**
     (See superclass documentation)
     
     - since: 0.1
     */
    override func viewDidAppear(animated: Bool)

**Note:** No empty space after the opening `/**` (only newline). 

<img width="762" alt="viewdidappear 2x" src="https://cloud.githubusercontent.com/assets/1000912/11737683/2622fffc-a01f-11e5-97f2-13df6ffada7b.png">

 
Because of how long it takes to build the whole documentation (my project has 100+ source files), I have tried transplanting the method an comments to another class in a smaller test project; however, the issue does not occur.

Looks like some of these bugs aren't "local": i.e., they seem to be triggered by something in the comments of a separate (earlier?) property/method.

**Comment by jpsim** [comment]
Sorry for not looking at this for a while, but going through old issues, this appears to be fixed now:

```swift
/**
 (See superclass documentation)

 - since: 0.1
 */
override func viewDidAppear(animated: Bool)
```

![image](https://cloud.githubusercontent.com/assets/474794/14308403/c6524386-fb8a-11e5-895d-577b89d29b44.png)
