### ISSUE TITLE
Bundle ID / Bundle Name not getting passed through the Podspec?

### ISSUE THREAD

**Issue by orta** [realm/jazzy#418]
I've got an issue from https://github.com/CocoaPods/cocoadocs.org/issues/411 which comes from this [Config instance](https://github.com/CocoaPods/cocoadocs.org/blob/master/cocoadocs.rb#L426). With this [Podspec](https://github.com/CocoaPods/Specs/blob/master/Specs/SwiftDate/2.0.2/SwiftDate.podspec.json) 

 I took a look through CD and it looks like it's happening on all [swift](http://cocoadocs.org/docsets/SoundCloudSwift/0.0.1/) libraries since I updated to 0.4.1. Any ideas where this could become unhooked? Your integration tests look correct WRT these bits of metadata in the plist.

**Comment by jpsim** [comment]
I'm not sure why this is happening. @segiddins ideas?

**Comment by segiddins** [comment]
I'd have to try debugging to know, but maybe it's related to how values are set when a new config instance is created, since that was refactored after I wrote the original jazzy support in cocoadocs?

**Comment by jpsim** [comment]
The following works for me with jazzy 0.5.0 and https://github.com/malcommac/SwiftDate/commit/ceae3c28c0ec7a53532a089660b842235d32fe24:

```
$ git clone https://github.com/malcommac/SwiftDate.git
$ cd SwiftDate
$ jazzy --podspec SwiftDate.podspec
...builds docs...
$ cat docs/docsets/SwiftDate.docset/Contents/Info.plist | grep com.jazzy
<string>com.jazzy.swiftdate</string>
```

Also works with jazzy at 0.4.1 (although I had to comment out `tvos` from the podspec and run `jazzy --podspec SwiftDate.podspec --swift-version 2.1.1`).

So all I can say for sure is that the problem isn't with the podspec documenter in jazzy, it is "elsewhere". I'll need to spend more time looking into how cocoadocs integrates jazzy to see where the problem lies.

**Comment by segiddins** [comment]
@jpsim try when the podspec isn't in the current working directory

**Comment by jpsim** [comment]
> @jpsim try when the podspec isn't in the current working directory

Still works:

```
$ cd ..
$ jazzy --podspec SwiftDate/SwiftDate.podspec
$ cat docs/docsets/SwiftDate.docset/Contents/Info.plist | grep com.jazzy
<string>com.jazzy.swiftdate</string>
```

**Comment by orta** [comment]
Hrm, you should be able to run:
```
git clone https://github.com/CocoaPods/cocoadocs.org
bundle install
bundle exec rake install_tools
```

then do: `bundle exec ./cocoadocs.rb preview [pod]` - I think `SidebarOverlay` should exhibit the problem, note, I added a workaround to CocoaDocs that adds the plist manually. But it shouldn't build for this.

**Comment by segiddins** [comment]
```diff
diff --git a/cocoadocs.rb b/cocoadocs.rb
index bf02792..75b18c2 100755
--- a/cocoadocs.rb
+++ b/cocoadocs.rb
@@ -430,7 +430,7 @@ class CocoaDocs < Object
           c.config_file = Pathname(jazzy_config) if jazzy_config
           c.parse_config_file
 
-          c.podspec = Pathname(download_spec_path)
+          c.podspec = Pod::Specification.from_file(download_spec_path)
           c.output = Pathname(docset_location)
           c.min_acl = Jazzy::SourceDeclaration::AccessControlLevel.public
           c.docset_icon = Pathname(__FILE__).parent + 'resources/docset_icon.png'
```

Might fix it

**Comment by jpsim** [comment]
@segiddins's patch looks right to me

**Comment by orta** [comment]
Not to look a gift-horse in the mouth, so this parser only gets ran from the command line? https://github.com/realm/jazzy/blob/master/lib/jazzy/config.rb#L185

**Comment by segiddins** [comment]
Yeah, the `parse` proc only gets called when setting from the attribute, and not via the setter on the config

**Comment by orta** [comment]
ace

**Comment by orta** [comment]
thanks for your time @jpsim @segiddins

**Comment by jpsim** [comment]
> Yeah, the parse proc only gets called when setting from the attribute, and not via the setter on the config

That seems correct to me actually. The config property is `podspec` not `podspec_path` after all. This is more flexible in the case that you want to programmatically make a `Pod::Specification`.
