### ISSUE TITLE
Architecture and missing type errors when building Obj-C framework

### ISSUE THREAD

**Issue by mightyleader** [realm/jazzy#420]
Hey,
I'm getting some errors when I build my Obj-C framework that seem to stem from the contents of the Umbrella Header file. 
Removing the entry for this in the jazzy command makes the errors go away (but then there's no docs). 
It doesn't appear to affect the code build.

Here's the output from the build:
`/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.2.sdk/usr/include/sys/cdefs.h:707:2: error: Unsupported architecture
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.2.sdk/usr/include/machine/types.h:37:2: error: architecture not supported
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.2.sdk/usr/include/machine/_types.h:34:2: error: architecture not supported
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.2.sdk/usr/include/sys/_types.h:55:9: error: unknown type name '__int64_t'
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.2.sdk/usr/include/sys/_types.h:56:9: error: unknown type name '__int32_t'
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.2.sdk/usr/include/sys/_types.h:57:9: error: unknown type name '__int32_t'
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.2.sdk/usr/include/sys/_types.h:60:9: error: unknown type name '__uint32_t'
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.2.sdk/usr/include/sys/_types.h:61:9: error: unknown type name '__uint32_t'
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.2.sdk/usr/include/sys/_types.h:62:9: error: unknown type name '__uint64_t'
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.2.sdk/usr/include/sys/_types.h:68:9: error: unknown type name '__darwin_natural_t'
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.2.sdk/usr/include/sys/_types.h:70:9: error: unknown type name '__uint16_t'
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.2.sdk/usr/include/sys/_types.h:71:9: error: unknown type name '__int64_t'
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.2.sdk/usr/include/sys/_types.h:72:9: error: unknown type name '__int32_t'
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.2.sdk/usr/include/sys/_types.h:73:9: error: unknown type name '__uint32_t'
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.2.sdk/usr/include/sys/_types.h:74:9: error: unknown type name '__int32_t'
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.2.sdk/usr/include/sys/_types.h:75:9: error: unknown type name '__uint32_t'
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.2.sdk/usr/include/sys/_types.h:76:9: error: unknown type name '__uint32_t'
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.2.sdk/usr/include/machine/endian.h:37:2: error: architecture not supported
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.2.sdk/usr/include/sys/types.h:95:9: error: unknown type name 'u_int64_t'
fatal error: too many errors emitted, stopping now [-ferror-limit=]
building site
jam out ♪♫ to your fresh new docs in`docs/objc_output`
Command /bin/sh emitted errors but did not return a nonzero exit code to indicate failure
`

Here's the Jazzy command I am running in a build phase Run Script entry:
`jazzy \
--objc \
--swift-version 2.1.1 \
--clean \
--author "name" \
--author_url https:\/\/website.com \
--module-version 1.0 \
--umbrella-header Thing/Thing.h \
--framework-root . \
--module InclusiveToolkit \
--root-url http:\/\/website.com/docs/objc/1.0/api/ \
--output docs/objc_output \
--skip-undocumented \
--min-acl private`

Any input much appreciated.

**Comment by jpsim** [comment]
That looks like [rdar://22993940](http://www.openradar.me/22993940) to me.

Try the following:

```shell
jazzy \
  --objc \
  --swift-version 2.1.1 \
  --clean \
  --author "name" \
  --author_url https://website.com \
  --module-version 1.0 \
  --umbrella-header Thing/Thing.h \
  --framework-root . \
  --module InclusiveToolkit \
  --root-url http://website.com/docs/objc/1.0/api/ \
  --output docs/objc_output \
  --skip-undocumented \
  --xcodebuild-arguments -destination,id=$(xcrun simctl list devices | grep -v unavailable | grep -m 1 -o '[0-9A-F\-]\{36\}')
```

Note that I haven't tried that myself yet.

**Comment by mightyleader** [comment]
Thanks, will give it a go later and report

**Comment by khoogheem** [comment]
Ran into this same problem...
tried the above with no luck.

Also changes the --xcodebuild-arguments to use the -schema

here is the error
~~~
Running xcodebuild
Could not parse compiler arguments from `xcodebuild` output.
Please confirm that `xcodebuild` is building a Swift module.
Saved `xcodebuild` log file: /var/folders/15/0qmncw69585bglb0ld8j4fph0000gn/T/xcodebuild-5DFFABC5-75A4-4799-B00A-93129909BDDB.log
Failed to generate documentation
/Library/Ruby/Gems/2.0.0/gems/jazzy-0.5.0/lib/jazzy/executable.rb:36:in `execute_command': /Library/Ruby/Gems/2.0.0/gems/jazzy-0.5.0/lib/jazzy/SourceKitten/bin/sourcekitten ["doc", "-scheme", "iOSDynamic"] (RuntimeError)


Running xcodebuild

Could not parse compiler arguments from `xcodebuild` output.

Please confirm that `xcodebuild` is building a Swift module.
~~~

looks like it thinks it is building a swift module

**Comment by jpsim** [comment]
@khoogheem please share more information, like the full jazzy command you're using, which version of jazzy, what you're documenting (e.g. Objective-C dynamic framework for iOS?), if the project you're documenting is available publicly, what is it?

**Comment by khoogheem** [comment]
No problems

Version is 0.5.0
Testing on Objective-C Project
Project has targets for iOS (old style Frameworks, iOSDynamic, Mac, tv), however was testing trying to use the Dynamic iOS Schema
Project is not public.. sorry


~~~
Kevinh01:gatewaykit kevinh$ jazzy --objc --clean --umbrella-header GatewayiOS/Gateway.h --framework-root . --module Gateway --sdk iphoneos --xcodebuild-arguments -scheme, GatewayDynamic --output Customer/jaz
Running xcodebuild
Could not parse compiler arguments from `xcodebuild` output.
Please confirm that `xcodebuild` is building a Swift module.
Saved `xcodebuild` log file: /var/folders/15/0qmncw69585bglb0ld8j4fph0000gn/T/xcodebuild-8C6EE6EB-A915-471D-AEEA-1D4A3AA8A8DE.log
Failed to generate documentation
/Library/Ruby/Gems/2.0.0/gems/jazzy-0.5.0/lib/jazzy/executable.rb:36:in `execute_command': /Library/Ruby/Gems/2.0.0/gems/jazzy-0.5.0/lib/jazzy/SourceKitten/bin/sourcekitten ["doc", "-scheme", "GatewayDynamic"] (RuntimeError)
~~~~

**Comment by jpsim** [comment]
Because you're overriding `--xcodebuild-arguments`, the `--objc` flag isn't being passed to SourceKitten, so you'll have to specify the full arguments to SourceKitten yourself:

```
jazzy --objc --clean --umbrella-header GatewayiOS/Gateway.h --framework-root . --module Gateway --sdk iphoneos --xcodebuild-arguments --objc,GatewayiOS/Gateway.h,-x,objective-c,-isysroot,$(xcrun --show-sdk-path --sdk iphoneos),-I,$(pwd),-scheme,GatewayDynamic --output Customer/jaz
```

**Comment by cezarywojcik** [comment]
I am running into a similar issue when trying to generate docs for a static Objective-C library.

Command:
```
jazzy \
   --objc \
   --clean \
   --author "Cezary Wojcik" \
   --umbrella-header Thing/Thing.h \
   --framework-root . \
   --sdk iphoneos
```

I get a bunch of

```
error: architecture not supported
...
error: unknown type name '__uint32_t'
...
```

**Comment by ChanMQ** [comment]
I have the same problem but with em++. Have you solved the problem? I have no idea what could do

**Comment by johnfairh** [comment]
I'm going to close this issue because it is very old and covers several different things.  My guess at the Jan2016 issue is that it should say "iphonesimulator" instead of "iphoneos".  @ChanMQ if that helps you then great, otherwise please open a new issue describing the problem (jazzy version, jazzy command, errors produced, project for the framework you're trying to document if possible).
