### ISSUE TITLE
set dash keyword to module name

### ISSUE THREAD

**Issue by breathe** [realm/jazzy#423]
Is it possible to customize the keyword of generated dash docsets?  I'm able to build a dash docset with jazzy (great -- thanks!!) and I am hosting a dash feed url.  Via the dash feed url I'm able download/install the dash bundle as expected.  But the default keyword for docset search of my docset is set to 'jazzy:' -- is it possible to customize this when building the docset?

**Comment by jpsim** [comment]
There's no way to do that today via jazzy's public interface. I'm actually not familiar with this feature of Dash, is there some documentation in Dash for the "keyword" feature you're referring to so I can learn more about it?

What does this do? What value should this be set to in normal usage? Thanks!

**Comment by breathe** [comment]
I looked through the Dash docs but haven't been able to find anything that I could identify as related to this ...  For clarity -- here's an image showing the keyword name for some of the various datasets I have loaded -- dash allows the end user to customize the keyword<->dataset mappings if they want -- however the dataset provider seems to also be able to provide a default value -- in this screenshot you can see sensible keyword values for the various dataset bundles I have loaded (and I have not customized any of the dataset names shown)...  Any docset I load which is built with jazzy provides the keyword name "jazzy" ...

![screen shot 2015-12-17 at 2 36 20 pm](https://cloud.githubusercontent.com/assets/434034/11884056/e6e56076-a4cb-11e5-8ba7-cc53ee1be7ea.png)

**Comment by jpsim** [comment]
Seems like we should be setting this value to the module name then.

**Comment by jpsim** [comment]
Thanks for this information, @breathe!

**Comment by jpsim** [comment]
alright this is finally fixed! Thanks for your patience @breathe!
