### ISSUE TITLE
Unable to find Xcode with swift version

### ISSUE THREAD

**Issue by lostatseajoshua** [realm/jazzy#425]
I keep receiving this error:
`run_sourcekitten : Unable to find an Xcode with swift version 2.1. (RuntimeError) whenever I run the command`  
The command I used was: 
`jazzy`

This is my first time using jazzy and I installed it only 10 mins ago so it should be on the latest version. Is there something I am suppose to do first to make it run? Or do I have to be in a certain dir? Thanks!

edit: Also I am on Xcode Version 7.2 (7C68)

**Comment by sanguish** [comment]
Yeah, so apparently Xcode 7.2 lacks the Swift toolchain in xcodebuild (according to Latner on Twitter).

I downgraded to 7.1.1

How 7.2 got released like that is a very bad indication of testing on Apple's part.

**Comment by segiddins** [comment]
try `jazzy --swift-version=2.1.1`

**Comment by lostatseajoshua** [comment]
@sanguish that worked! Thanks. Now the problem is that it did not read my documentation. It was really inaccurate. :( but either way thanks I really appreciate the work and the help.
