### ISSUE TITLE
Error:  "Unable to find an Xcode with swift version 2.1"

### ISSUE THREAD

**Issue by ghoetker** [realm/jazzy#426]
Trying to run Jazzy version: 0.4.1. Using XCode 7.2, Apple Swift version 2.1.1 (swiftlang-700.1.101.15 clang-700.1.81). I receive the following set of errors when running jazzy with no additional options.

/Library/Ruby/Gems/2.0.0/gems/jazzy-0.4.1/lib/jazzy/sourcekitten.rb:137:in `run_sourcekitten': Unable to find an Xcode with swift version 2.1. (RuntimeError)
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.4.1/lib/jazzy/doc_builder.rb:57:in `block in build'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.4.1/lib/jazzy/doc_builder.rb:55:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.4.1/lib/jazzy/doc_builder.rb:55:in `build'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.4.1/bin/jazzy:15:in `<top (required)>'
	from /usr/local/bin/jazzy:23:in `load'
	from /usr/local/bin/jazzy:23:in `<main>'

**Comment by jpsim** [comment]
You have to specify `--swift-version=2.1.1` unless you're building jazzy from source. I know this isn't clear behavior, so I've opened #427 to improve this situation.

**Comment by ghoetker** [comment]
Thanks very much for the quick and helpful answer.

Glenn

Glenn Hoetker

Arizona State University | W. P. Carey School of Business
Professor & Dean's Council Distinguished Scholar
Affiliate Professor   Sandra Day O'Conner College of Law
Senior Sustainability Scholar   Julie Ann Wrigley Global Institute of Sustainability
Faculty Fellow   Center for Science, Law & Innovation
Glenn.Hoetker@asu.edu<mailto:Glenn.Hoetker@asu.edu>  | http://hoetker.faculty.asu.edu<http://hoetker.faculty.asu.edu/> | 480-965-4566


[cid:68ABE575-A016-4BB8-BBC5-81519DC9D377@ph.cox.net]

On Dec 17, 2015, at 9:31 PM, JP Simard <notifications@github.com<mailto:notifications@github.com>> wrote:


You have to specify --swift-version=2.1.1 unless you're building jazzy from source. I know this isn't clear behavior, so I've opened #427<https://github.com/realm/jazzy/issues/427> to improve this situation.
