### ISSUE TITLE
Methods description doesn't get parsed well, extra "Parameter" section in html

### ISSUE THREAD

**Issue by Sega-Zero** [realm/jazzy#431]
This code:

``` swift
import Foundation

/// Sample proto.
public protocol ExampleProto {
    /**
     Sample method 1

     - Parameter sampleParam: just another string parameter
     */
    func sampleMethod1(sample sampleParam: String)
}
```

produces this tooltip rendering in xcode:
![xcode rendering](https://cloud.githubusercontent.com/assets/2203199/11944244/c22bfc62-a855-11e5-8311-55aff83ad482.jpg)
and this is what I see in html:
![html bad render](https://cloud.githubusercontent.com/assets/2203199/11944270/ef3b3880-a855-11e5-9cf9-f36b4c0bbfec.jpg)

Another example may be found in #430. 

---

Or with that code:

``` swift
/**
 Sample method 1

 - Parameter sampleParam: just another string parameter
 - Important: important info
 - Note: and a note
*/
func sampleMethod1(sample sampleParam: String)
```

I get this output:
![Important tag swallowed](https://cloud.githubusercontent.com/assets/2203199/11944635/9c014cb0-a858-11e5-8a87-a212014ae9fe.jpg) (see `Important` and `Note` sections missing)

Having this kind of issues on some of my protocols, and in some cases I have a really terrible outputs, like this: 
![sample output](https://cloud.githubusercontent.com/assets/2203199/11944400/2139f780-a857-11e5-96be-b05572ac2563.jpg) (sorry for pixelating), but I couldn't reproduce this on a separate swift file yet.

jazzy 0.4.1, swift 2.1.1, building with `jazzy --source-directory . --swift-version 2.1.1 --clean`

**Comment by nicolas-miari** [comment]
Looks related to #408 and #415, opened by myself.

**Comment by jpsim** [comment]
Sorry for the lack of activity here @Sega-Zero! It looks like the situation has improved *somewhat* since you filed this, but it's still not quite fixed:

![image](https://cloud.githubusercontent.com/assets/474794/14308628/2057071c-fb8c-11e5-83ae-90b1a862cffe.png)

**Comment by PaulBernhardt** [comment]
I am seeing this as well. I'd be happy with a workaround if anyone can figure out what is actually triggering the duplication in the Jazzy docs.

**Comment by jpsim** [comment]
What's triggering this is the uppercase `Parameter`. The workaround is simple: use a lowercase `- parameter name: Description...`

**Comment by PaulBernhardt** [comment]
Thank you, changing to lowercase solved the issue for me

**Comment by lloydsargent** [comment]
Okay, this is still a mess. If I have the following:

    /**
        Initializes a basic window.
     
        - parameter:
            - contentRect: Rectangle defining the location of the winow.
            - styleMask: Int
            - backing: backing buffer type
            - defer: we seldom defer
     
    */

The ONLY thing I get is this:

![__docerror1](https://cloud.githubusercontent.com/assets/1956960/14477136/ac277a20-00d1-11e6-8bb3-07c4291bbf49.png)

If I replace **parameter** with **parameters** then I get the erroneous output as mentioned above (I’ve highlighted the erroneous part in pink)

![__docerror2](https://cloud.githubusercontent.com/assets/1956960/14477292/82bbccb2-00d2-11e6-8ad5-9550e08ff21e.png)

The only thing that seems to get me the correct documentation is the following:

    /**
        Initializes a basic window.
     
        - parameter contentRect: Rectangle defining the location of the winow.
        - parameter styleMask: Int
        - parameter backing: backing buffer type
        - parameter defer: we seldom defer
     
    */

It’s messier than using **parameters**, but until this bug is fixed, this is the only workaround I’ve discovered.

**Comment by jpsim** [comment]
@lloydsargent your workaround is appropriate, that's the only syntax jazzy supports at the moment.

**Comment by storix** [comment]
Having the same issue. I think, there should be some note in the `README` file that it's not appropriate to use `parameters` keyword with jazzy.

**Comment by istx25** [comment]
Any decisions with this? I think the best (temporary solution [or not]) is to just add the note into the README or somewhere that people will read.

**Comment by jpsim** [comment]
We should definitely list grouped parameters as an unsupported format. Fixing case sensitivity should be super simple for someone motivated to do so.

**Comment by SDGGiesbrecht** [comment]
Parameters are now supported both uppercase and lowercase, both grouped and separate. Build from source (see [here](https://github.com/realm/jazzy/issues/637#issuecomment-267476495)) or wait for the next release.

**Comment by fjcaetano** [comment]
Parameter parsing works fine for me when the list comes before the description. Using your example:
```/**
    - parameter contentRect: Rectangle defining the location of the winow.
    - parameter styleMask: Int
    - parameter backing: backing buffer type
    - parameter defer: we seldom defer

    Initializes a basic window.
*/
```

It works either way, with a `- parameter` for each item or grouping them in `- parameters`
