### ISSUE TITLE
`run_sourcekitten': Unable to find an Xcode with swift version 2.1. (RuntimeError)

### ISSUE THREAD

**Issue by vnramachandra** [realm/jazzy#432]
I recently installed XCode 7.2 and upon running jazzy command including swift version [jazzy --swift-version 2.1.1] I am getting following error.
/Library/Ruby/Gems/2.0.0/gems/jazzy-0.4.1/lib/jazzy/sourcekitten.rb:137:in `run_sourcekitten': Unable to find an Xcode with swift version 2.1. (RuntimeError)
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.4.1/lib/jazzy/doc_builder.rb:57:in `block in build'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.4.1/lib/jazzy/doc_builder.rb:55:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.4.1/lib/jazzy/doc_builder.rb:55:in `build'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.4.1/bin/jazzy:15:in `<top (required)>'
	from /usr/local/bin/jazzy:23:in `load'
	from /usr/local/bin/jazzy:23:in `<main>'

Could you please help to resolve this?

Thanks in advance,
Ramachandra V N.

**Comment by vnramachandra** [comment]
Even if we are using jazzy to document Objective-C source we need to add --swift-version 2.1.1.

**Comment by jpsim** [comment]
Yes, sorry for the confusing behavior. I hope #427 can address that.

**Comment by vnramachandra** [comment]
Thank you for the quick update.
