### ISSUE TITLE
Jazzy having trouble parsing methods which have the same name, but different parameters

### ISSUE THREAD

**Issue by theddnc** [realm/jazzy#433]
I have a project that I've uploaded to CocoaPods, but the docs have not been generated yet. I've started googling and decided to run jazzy on my own machine. Here's where Jazzy fails:

```
Found conflicting type declarations with the same name, which may indicate a build issue or a bug in Jazzy: instance method retrieve(_:), instance method retrieve(), instance method retrieve(_:)
```

I've installed jazzy today, so I should have the latest version: 0.4.1

My class provides three ```retrieve``` methods:
```swift
public func retrieve(path: String) -> Promise<ResponseBundle>
public func retrieve() -> Promise<ResponseBundle>
public func retrieve(filter: [String: String]) -> Promise<ResponseBundle>
```

The code does compile without any problems, so i guess that this is an issue with jazzy. I've looked through the open issues here and hadn't found anything related to my problem, so I'm creating my own issue.

...aaand Merry Christmas / Happy holidays to all :)

**Comment by pcantrell** [comment]
I take it those are global functions, i.e. not nested inside a type?

**Comment by theddnc** [comment]
> My class provides three retrieve methods

These are defined in a ```Service```:

```swift
class Service {
    //...
    public func retrieve(path: String) -> Promise<ResponseBundle>
    public func retrieve() -> Promise<ResponseBundle>
    public func retrieve(filter: [String: String]) -> Promise<ResponseBundle>
    //...
}
```

You can find the full class [here](https://github.com/theddnc/iService/blob/master/iService/Service.swift)

**Comment by jpsim** [comment]
Sorry for the lack of activity here, @theddnc! Whatever the issue was, it seems to be resolved now:

```
$ git clone git@github.com:theddnc/iService.git
$ jazzy --podspec iService.podspec 
Updating local specs repositories

CocoaPods 1.0.0.beta.6 is available.
To update use: `sudo gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

Analyzing dependencies
Fetching podspec for `iService` from `/Users/jp/Projects/iService`
Downloading dependencies
Installing iPromise (1.1.2)
Installing iService (0.0.3)
Generating Pods project
Pod installation complete! There is 1 dependency from the Podfile and 2 total pods installed.
Running xcodebuild
Parsing Response.swift (1/3)
Parsing Service.swift (2/3)
Parsing ServiceRealm.swift (3/3)
building site
jam out ♪♫ to your fresh new docs in `docs`
```

Output: http://static.realm.io/jazzy_demo/iService/index.html

**Comment by theddnc** [comment]
Awesome, my cocoadocs are working now and also looking quite pretty. Thanks!
