### ISSUE TITLE
Copy missing documentation from protocol

### ISSUE THREAD

**Issue by Sega-Zero** [realm/jazzy#434]
It would be nice if there will be no need in documenting protocols implementations, if the protocol itself has a documentation. Right now i have to copy the docs from the protocol to the implementation to have 100% documented output, which is not quite comfortable. An example of this may be found in [swiftlint issue 284](https://github.com/realm/SwiftLint/issues/284#issuecomment-167226023)

**Comment by jpsim** [comment]
We're already tracking this as an issue in jazzy. I'm on my phone right now so I can't find it though. Closing as a duplicate.

**Comment by pcantrell** [comment]
@Sega-Zero, Jazzy already provides some help with this:

If you are providing a **default implementation in a protocol extension**, then Jazzy will merge the extension docs into the protocol docs. You can thus [document protocol methods](https://github.com/bustoutsolutions/siesta/blob/master/Source/ResourceObserver.swift#L36-L40) with the protocol’s general contract, and [document the extension](https://github.com/bustoutsolutions/siesta/blob/master/Source/ResourceObserver.swift#L51-L52) to describe only what the default implementation does. Jazzy will merge them into [one nice method description](https://bustoutsolutions.github.io/siesta/api/Protocols/ResourceObserver.html#/s:FP6Siesta16ResourceObserver22isEquivalentToObserveruRq_S0__Fq_FPS0__Sb) with a “Default Implementation” section.

If you are **implementing a protocol method on a concrete type** and do not want to provide additional docs for a method, you can use `/// :nodoc:` to signal that the method is intentionally undocumented. Here, for example, [this struct’s docs](https://github.com/bustoutsolutions/siesta/blob/master/Source/ResponseTransformer.swift#L130-L135) adequately describe what it does, and documenting [this method](https://github.com/bustoutsolutions/siesta/blob/master/Source/ResponseTransformer.swift#L130-L135) would add no useful information, so it is marked `:nodoc:`.

**Comment by Sega-Zero** [comment]
None of this fits my needs. I need all documentation to be copied from the protocol's docs to the implementation, or/and to have a reference to the protocol. So, the `SampleStruct` struct from the link above could have it's own page in the documentation.

**Comment by pcantrell** [comment]
What good would copying the docs do?

**Comment by Sega-Zero** [comment]
1. No need to follow to protocol's documentation
2. There may be several protocols that are implementing in that particular type
3. It's always better to have one source of truth, copying is the path to errors and mistakes

**Comment by pcantrell** [comment]
Right, agreed to all that, so I’m wondering why you’d want Jazzy to copy the docs? I picture myself reading an API, and having to read text from `SampleStruct` in order to figure out that it duplicates information I already read in the protocol description just seems annoying.

I do think it would be nice if Jazzy provided more cross-type linking for supertypes, implemented protocols, subclasses, implementing types, etc. A link from a method to the protocol it implements seems sensible. Copying text does not, but I’m wondering if maybe I don’t see the case for that….

**Comment by Sega-Zero** [comment]
Well, a link to the source is pretty enough to understand the purpose of a particular method/property. But I think it would be much better to have a description text too, so the reader could save the context of the struct, if there are more methods/properties on it. IMHO, a raw method text is not that informative.

Maybe a better way would be cutting the methods out of the struct's documentation and keep a link to the protocol, but I'm not sure if this is better than text copying.

**Comment by Sega-Zero** [comment]
The case from #190 mentioned extensions, but the problem is the same.

**Comment by pcantrell** [comment]
Well, @jpsim might disagree, but I’d want a just link to the protocol method in that situation too.

**Comment by Sega-Zero** [comment]
An option for this will be acceptable for both camps =)
