### ISSUE TITLE
fatal error: 'UIKit/UIKit.h' file

### ISSUE THREAD

**Issue by khoogheem** [realm/jazzy#445]
When running an Objc Project that has an 
~~~
#import <UIKit/UIKIt.h>
~~~
 statement.. it complains with fatal error: fatal error: 'UIKit/UIKit.h' file not found
However it successfully skips over Foundation.h import.

**Comment by jpsim** [comment]
You should specify `--sdk [iphone|watch|appletv][os|simulator]|macosx` if you're documenting something for a platform other than OS X, which is the default.

**Comment by FelixSFD** [comment]
`--sdk` does not work for me.

I start jazzy with:
`jazzy --objc --clean --umbrella-header myapp/myapp-bridging-header.h --framework-root /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.1.sdk --author "author name" --sdk iphoneos`

This ist the error-message:
```
/Library/Ruby/Gems/2.0.0/gems/jazzy-0.4.1/lib/jazzy/config.rb:312:in `parse_command_line': invalid option: --sdk (OptionParser::InvalidOption)
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.4.1/lib/jazzy/config.rb:270:in `parse!'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.4.1/bin/jazzy:15:in `<top (required)>'
	from /usr/local/bin/jazzy:23:in `load'
	from /usr/local/bin/jazzy:23:in `<main>'
```

The same message appears, when I use `--sdk macosx` manually

**Comment by khoogheem** [comment]
I get the same using --sdk and pick  an option.

however if I don't use --sdk.. I am seeing this
~~~
fatal error: Unsupported CXCursorKind: UnexposedDecl: file /Users/jp/Projects/jazzy/SourceKitten/Source/SourceKittenFramework/ObjCDeclarationKind.swift, line 64

/Library/Ruby/Gems/2.0.0/gems/jazzy-0.4.1/lib/jazzy/executable.rb:36:in `execute_command': 
/Library/Ruby/Gems/2.0.0/gems/jazzy-0.4.1/lib/jazzy/SourceKitten/bin/sourcekitten ["doc", "--objc", 
"/Users/path/header.h", "-x", "objective-c", "-isysroot", "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk", "-I", "/Users/path"] (RuntimeError)
~~~

**Comment by jpsim** [comment]
I was wrong, `--sdk` wasn't included in an official release. So I just cut [0.5.0](https://github.com/realm/jazzy/releases/tag/v0.5.0), which includes the `--sdk` option along with a bunch of other features & bug fixes.
