### ISSUE TITLE
--author only supports first Word

### ISSUE THREAD

**Issue by khoogheem** [realm/jazzy#446]
if have author with anything but one word.. it will only parse and use that first word.

Example
~~~
--author Realm Database
~~~
Will show up as © 2016 Realm in the docs.

Even if you use
~~~
--author "Realm Database"
-or- 
--author 'Realm Database'
~~~

**Comment by jpsim** [comment]
`--author 'Two Words'` works for me:

```html
<p>&copy; YYYY <a class="link" href="https://example.com" target="_blank" rel="external">Two Words</a>. All rights reserved. (Last updated: YYYY-MM-DD)</p>
```

Are you sure quoting doesn't help? What shell are you using?

**Comment by khoogheem** [comment]
Odd.. must not have cleaned up the docs from a prior run where it failed mid way through.

I will consider it a mistake on my part ;)

**Comment by JorgenAndreasson** [comment]
I have the same problem as khoogheem.
I only get the first word after --author. In this case it shows up as 'Clockwork

jazzy --clean --min-acl private --module PiPlayer --author ‘Clockwork Concepts’ --output Documentation
