### ISSUE TITLE
Objective C documentation for cocoapod lib create structure

### ISSUE THREAD

**Issue by niklasdstrom** [realm/jazzy#455]
I have an objc pod created using the [cocoapod lib create tool](https://guides.cocoapods.org/making/using-pod-lib-create.html), and I am now trying to use jazzy to generate documentation for that pod.

The Classes folder also contains many subfolders so the tree looks more like this:
```
  MyLib
  ├── .travis.yml
  ├── _Pods.xcproject
  ├── Example
  │   ├── MyLib
  │   ├── MyLib.xcodeproj
  │   ├── MyLib.xcworkspace
  │   ├── Podfile
  │   ├── Podfile.lock
  │   ├── Pods
  │   └── Tests
  ├── LICENSE
  ├── MyLib.podspec
  ├── Pod
  │   ├── Assets
  │   └── Classes
  │     └── Models
  │        └── model.h
  │        └── model.m
  │     └── Views
  │        └── view.h
  │        └── view.m
  └── README.
```

When I tried creating proper umbrella headers (Where not necessarily all header files are public), I ran into trouble with files not being found properly.

How would you design a umbrella header in a case like this, and how would the jazzy command look like? I feel like I´ve tried a thousand different combination, and I don't know if the problems im running into are because of the umbrella header, the jazzy objc syntax or something completely different.

I also tried running the jazzy --podspec command, but as far as I could understand, that is swift only unfortunately.

Appreciate any help.

**Comment by segiddins** [comment]
What jazzy command are you running?

**Comment by jpsim** [comment]
Sorry @niklasdstrom, we never heard back from you after @segiddins's question! So I'm closing this issue. Please open a new issue if you're still having problems with the latest version of jazzy (0.6.0). Thanks!
