### ISSUE TITLE
`run_sourcekitten': Unable to find an Xcode with swift version 2.1.1. (RuntimeError)

### ISSUE THREAD

**Issue by caohrong** [realm/jazzy#461]
I use jazzy --swift-version 2.1.1 to built my document, But It's still show the error message.
/Library/Ruby/Gems/2.0.0/gems/jazzy-0.5.0/lib/jazzy/sourcekitten.rb:137:in `run_sourcekitten': Unable to find an Xcode with swift version 2.1.1. (RuntimeError)
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.5.0/lib/jazzy/doc_builder.rb:57:in `block in build'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.5.0/lib/jazzy/doc_builder.rb:55:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.5.0/lib/jazzy/doc_builder.rb:55:in `build'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.5.0/bin/jazzy:15:in `<top (required)>'
	from /usr/local/bin/jazzy:23:in `load'
	from /usr/local/bin/jazzy:23:in `<main>'

I  used cocoapod in my project, so the jazzy can't find the real project? Can you help me？ Thanks

XcodeVersion: 7.1.1(7B1005)
Project Language: Swift

**Comment by caohrong** [comment]
Because swift version is 2.1   add --swift-version 2.1 to built , It's Working!

**Comment by hatjs880328** [comment]
Wow

**Comment by hatjs880328** [comment]
--swift-version 2.0

**Comment by doozMen** [comment]
With the update to Xcode today to swift 2.2 you have to type `jazzy --swift-version 2.2`

**Comment by jkyin** [comment]
@doozMen Could I config swift-version in YAML file? Example: `swift-version: 2.2`

**Comment by pcantrell** [comment]
@jkyin https://github.com/bustoutsolutions/siesta/blob/master/.jazzy.yaml#L9

**Comment by jkyin** [comment]
@pcantrell Thanks ❤️

**Comment by doozMen** [comment]
@jkyin yes you could. Just try it out I would say. Good luck

**Comment by yeelan0319** [comment]
Hi @jpsim 
I recently upgrade to Jazzy 0.6.0, which seems by default using swift 2.2. My swift version is 2.1.1, so it throw me similar bugs as above. 
So our solution is instead of passing ```--swift-version 2.1.1```, we pass something like ```--swift-version $(swift --version | head -n1 | awk '{print $4}')```, since everyone may have a slight different version of swift. Could you see if this might cause any harm? And may I know why jazzy need to specify exactly which version of swift we are using when generating reference documentations? 

Much thanks!

**Comment by jpsim** [comment]
> And may I know why jazzy need to specify exactly which version of swift we are using when generating reference documentations?

To know which version of Xcode to link against SourceKitten. We're tracking improving this in #427
