### ISSUE TITLE
Support new doc comment fields for Swift [Xcode 7.3b2, Swift 2.2]

### ISSUE THREAD

**Issue by jessesquires** [realm/jazzy#465]
:tada: From the release notes:

> Three new doc comment fields, namely `- keyword:`, `- recommended:` and `- recommendedover:`, allow Swift users to cooperate with code completion engine to deliver more effective code completion results. The `- keyword:` field specifies concepts that are not fully manifested in declaration names. `- recommended:` indicates other declarations are preferred to the one decorated; to the contrary, `- recommendedover:` indicates the decorated declaration is preferred to those declarations whose names are specified. (23101030)

**Comment by istx25** [comment]
Any progress on this?

**Comment by jpsim** [comment]
These terms just need to be added to this list: https://github.com/realm/jazzy/blob/v0.7.2/lib/jazzy/jazzy_markdown.rb#L22-L45

**Comment by SDGGiesbrecht** [comment]
All current callouts are now supported. (2016‐12‐16)

**Comment by jessesquires** [comment]
cc @rnystrom
