### ISSUE TITLE
Get an error when running build

### ISSUE THREAD

**Issue by jiglesiasf** [realm/jazzy#467]
It happens to my three times so far, I install the gem, everything works fine,  but after 3,4, 5 times exporting I get the following error: 
Running xcodebuild
Could not parse compiler arguments from `xcodebuild` output.
Please confirm that `xcodebuild` is building a Swift module.
Saved `xcodebuild` log file: /var/folders/_2/nt04pyd12yq9m1p0797b9b480000gn/T/xcodebuild-A3651668-15B4-4F23-976E-924A584F5559.log
Failed to generate documentation
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.5.0/lib/jazzy/sourcekitten.rb:140:in `run_sourcekitten'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.5.0/lib/jazzy/doc_builder.rb:57:in `block in build'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.5.0/lib/jazzy/doc_builder.rb:55:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.5.0/lib/jazzy/doc_builder.rb:55:in `build'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.5.0/bin/jazzy:15:in `<top (required)>'
	from /usr/local/bin/jazzy:23:in `load'
	from /usr/local/bin/jazzy:23:in `<main>'

I do not if there is a bug, or it is something I am doing wrong. 

thanks!

**Comment by jiglesiasf** [comment]
Resolved. 

I was trying to run jazzy out of the project folder.

**Comment by jpsim** [comment]
Glad you got this to work @jiglesiasf!
