### ISSUE TITLE
Missing Descriptions

### ISSUE THREAD

**Issue by nkirby** [realm/jazzy#469]
Hi Jazzy Team.

I'm having an issue generating docs. 

Descriptions generated between `/**` and `*/` don't show up in the generated HTML. It seems attributes like `returns` works.

Descriptions generated with `///` work.

--

__Example__:
```
/**
Just a test object.
*/

public final class Test: NSObject {

    /**
    Does a very important task and returns a string
     
    - returns: "String"
    */
    
    public func doThingAndReturnString() -> String {
        return "String"
    }
}
```

Generates:

![screen shot 2016-02-03 at 3 29 37 pm](https://cloud.githubusercontent.com/assets/5007840/12796056/f83ee09c-ca8a-11e5-882e-17439d05ff4f.png)

--

__Whereas__:

```
///Just a test object.

public final class Test: NSObject {

    /// Does a very important task and returns a string
    ///- returns: "String"
    
    public func doThingAndReturnString() -> String {
        return "String"
    }
}
```

Generates:

![screen shot 2016-02-03 at 3 30 45 pm](https://cloud.githubusercontent.com/assets/5007840/12796097/2484b12c-ca8b-11e5-8d5a-97a416aa2d84.png)

--

This was validated by creating a brand new iOS application and built using the standard `jazzy` command with no options. 

The project can be supplied if necessary. 

Thanks for the great work you've done so far!

--

Using:
Xcode Version 7.2 (7C68)
Jazzy Version 0.5.0
OS X Version 10.11.3 (15D21)

**Comment by segiddins** [comment]
What happens if you get rid of the extra newline between your docs and the declaration?

**Comment by nkirby** [comment]
@segiddins That works. Strangely the extra newline doesn't seem to matter for Xcode's in-app documentation viewing (option clicking, or force clicking). Thanks!

**Comment by jpsim** [comment]
#496 should fix this. Could you try running it from source from that branch?

**Comment by jpsim** [comment]
@nkirby sorry for the trouble here, could you please try again using jazzy 0.6.0 which was just pushed to rubygems earlier today? Thanks!

**Comment by nkirby** [comment]
Hey @jpsim sorry I missed the first notification, it must have come in when I was on vacation. My apologies.

Yes, everything works great. Thank you!
