### ISSUE TITLE
Jazzy not creating docs from comments

### ISSUE THREAD

**Issue by akhilsuri** [realm/jazzy#472]
![screenshot](https://cloud.githubusercontent.com/assets/7919804/12806336/1ebdfcf8-cb2b-11e5-808f-d6ea984e08e9.png)
I have documented code as per new Swift keywords. When I run jazzy, following output comes:

```
/usr/local/Cellar/ruby/2.2.1/lib/ruby/2.2.0/open3.rb:193: warning: Insecure world writable dir /Users/User in PATH, mode 040777
Running xcodebuild
```
and then it parses all my swift code files one by one, with following end line.
```
building site
jam out ♪♫ to your fresh new docs in `docs`
```
But when I open my index.html under Safari, I get blank Reference page. Attached the screenshot. Please let me know what is happening here.
![screenshot](https://cloud.githubusercontent.com/assets/7919804/12806318/f8ca1306-cb2a-11e5-84a7-fdda469ae2ea.png)

**Comment by segiddins** [comment]
Are you sure you have public declarations in your swift module?

**Comment by akhilsuri** [comment]
Yes, it has public declarations.

**Comment by leed90** [comment]
i've got the same problem. 
And i can't fix it :(

**Comment by segiddins** [comment]
Can you share a project that reproduces the issue?

**Comment by akhilsuri02** [comment]
Please run the following command 
jazzy --min-acl internal
or make all your methods public

This will solve the problem.

**Comment by jpsim** [comment]
It's very difficult to tell what's happening in this ticket, the images aren't resolving:

![image](https://cloud.githubusercontent.com/assets/474794/14308910/05d43156-fb8e-11e5-9790-e2bba2fc74d3.png)

and there's no comment after the proposed solution from @akhilsuri02 above, so I'm closing this issue. If you're still having issues with jazzy, please open a new issue with more information so we can help troubleshoot with you. Thanks!
