### ISSUE TITLE
Empty "Other structs" group

### ISSUE THREAD

**Issue by esad** [realm/jazzy#475]
If all structs found in project are assigned to custom groups, jazzy still emits an empty "Other Structs" group.

Minimal test case:

https://gist.github.com/esad/3c809178eed53736ca33

Resulting output attached.
![screen shot 2016-02-04 at 17 42 46](https://cloud.githubusercontent.com/assets/11807/12822114/be9415e2-cb66-11e5-9bc3-cc1b8ac2e5d8.png)

**Comment by jpsim** [comment]
Yeah, this is a bug. We should filter out empty groups.
