### ISSUE TITLE
Can not process overloaded methods

### ISSUE THREAD

**Issue by bibhas2** [realm/jazzy#477]
If a Swift class has multiple overloaded methods with same name I get ``Found conflicting type declarations with the same name`` error. And it drops all such methods from output except for one.

**Comment by pcantrell** [comment]
It shouldn't. Can you post the type signatures of those declarations?

**Comment by bibhas2** [comment]
This problems seems to be happening in a very specific case. This is happening only when the method returns a ``Promise<T>`` where ``Promise`` is from the ``PromiseKit`` API. As a result it will take a bit of work to reproduce the problem.

1) Create a Xcode project and add PromiseKit cocoa pod as dependency. Example:

```
platform :ios, '9.0'
use_frameworks!

target 'MyProject' do
    pod 'PromiseKit', '~> 3.0'
end
```

2) Create a class like this:

```swift
import Foundation
import PromiseKit
/**
 This class deposits payments and voids past payments.
*/
public class PaymentManager {
    /**
     Post a payment to the currently logged in user.
     
     - returns: A promise indicating the status
    */
    public func post() -> Promise<Int> {
        return Promise(1)
    }
    /**
     Post a payment to a specific account.
     
     - parameters accountId: The account ID to post the charge.
     - returns: A promise indicating the status
    */
    public func post(accountId: String) -> Promise<Int> {
        return Promise(1)
    }
}
```

Now when you run jazzy you get:

```
Found conflicting type declarations with the same name, which may indicate a build issue or a bug in Jazzy: instance method post(), instance method post(_:)
A compile error prevented PaymentManager.post() from receiving a unique USR. Documentation may be incomplete. Please check for compile errors by running `xcodebuild `.
```

**Comment by pcantrell** [comment]
When I run your example, I get this Jazzy output:

    Running xcodebuild
    Parsing ViewController.swift (1/2)
    Parsing AppDelegate.swift (2/2)
    building site
    Found conflicting type declarations with the same name, which may indicate a build issue or a bug in Jazzy: instance method post(), instance method post(_:)
    Found conflicting type declarations with the same name, which may indicate a build issue or a bug in Jazzy: class PaymentManager, class PaymentManager
    Found conflicting type declarations with the same name, which may indicate a build issue or a bug in Jazzy: instance method post(), instance method post(_:)
    A compile error prevented PaymentManager.post() from receiving a unique USR. Documentation may be incomplete. Please check for compile errors by running `xcodebuild `.
    A compile error prevented post() from receiving a unique USR. Documentation may be incomplete. Please check for compile errors by running `xcodebuild `.
    jam out ♪♫ to your fresh new docs in `docs`

Aha! A smoking gun!

    A compile error prevented PaymentManager.post() from receiving a unique USR.

And then this recommendation:

    Please check for compile errors by running `xcodebuild `.

So I run `xcodebuild`, and voila:

    error: no such module 'PromiseKit'
    import PromiseKit

The problem is that `xcodebuild` builds the project, not the workspace, and thus can't find any of the dependency pods. But it works when I point it at the workspace:

    xcodebuild -workspace MyProject.xcworkspace -scheme MyProject

…so I pass those xcodebuild args when running Jazzy:

    jazzy -x -workspace,MyProject.xcworkspace,-scheme,MyProject

…and that works.

**Comment by bibhas2** [comment]
OK, that worked. It will be cool if Jazzy could detect a workspace and run the build like this automatically. Cocoapod is very popular out there and many projects will need this work around at this point.

**Comment by Sega-Zero** [comment]
Had the same `unique USR` error. Tried to specify workspace and jazzy fails:

> $ jazzy  -x -workspace,Project.xcworkspace,-scheme,Release
Running xcodebuild
Could not parse compiler arguments from `xcodebuild` output.
Please confirm that `xcodebuild` is building a Swift module.
Saved `xcodebuild` log file: /var/folders/kh/9rw5rwln3_74r_g69jn93t8h0000gn/T/xcodebuild-675CAA1D-7FAE-4EFE-A035-E6DC5C3670E6.log
Failed to generate documentation
/Library/Ruby/Gems/2.0.0/gems/jazzy-0.5.0/lib/jazzy/executable.rb:36:in `execute_command': /Library/Ruby/Gems/2.0.0/gems/jazzy-0.5.0/lib/jazzy/SourceKitten/bin/sourcekitten ["doc", "-workspace", "Project.xcworkspace", "-scheme", "Release"] (RuntimeError)

> Running xcodebuild

> Could not parse compiler arguments from `xcodebuild` output.

> Please confirm that `xcodebuild` is building a Swift module.

> Saved `xcodebuild` log file: /var/folders/kh/9rw5rwln3_74r_g69jn93t8h0000gn/T/xcodebuild-675CAA1D-7FAE-4EFE-A035-E6DC5C3670E6.log

> Failed to generate documentation
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.5.0/lib/jazzy/sourcekitten.rb:140:in `run_sourcekitten'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.5.0/lib/jazzy/doc_builder.rb:57:in `block in build'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.5.0/lib/jazzy/doc_builder.rb:55:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.5.0/lib/jazzy/doc_builder.rb:55:in `build'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.5.0/bin/jazzy:15:in `<top (required)>'
	from /usr/local/bin/jazzy:23:in `load'
	from /usr/local/bin/jazzy:23:in `<main>'

The log file shows no errors and ends with 
> ** BUILD SUCCEEDED **
