### ISSUE TITLE
Upgrade to SourceKitten 0.10

### ISSUE THREAD

**Issue by esad** [realm/jazzy#482]
See https://github.com/realm/jazzy/issues/451 - this should be fixed in newest SourceKitten release.

I tried upgrading by simpling updating the submodule and rebuilding, but it seems that syntax has changed somewhat since 0.7.3 and 0.10.

**Comment by jpsim** [comment]
See #496

**Comment by jpsim** [comment]
Just updated SourceKitten to a little past 0.11.0.
