### ISSUE TITLE
Support autolinking return and parameters types in the method signature

### ISSUE THREAD

**Issue by esad** [realm/jazzy#483]
It would be nice if recognized top level declarations would be autolinked in the method signature. For example, in Realm docs, the following would be become hyperlinks:

<img width="745" alt="screen shot 2016-02-14 at 14 01 19" src="https://cloud.githubusercontent.com/assets/11807/13033791/9fa5503c-d323-11e5-9a0a-1ce3f3bcd2bc.png">

**Comment by esad** [comment]
Perhaps we could just simply apply autolinking to all declarations?

Easy fix idea: as declarations are passed through the highlighter, we could reuse the highlighter tokenization and simply match-and-replace recognized top level declarations inside various <span>s emmited by the highlighter?

**Comment by istx25** [comment]
Merged in with https://github.com/realm/jazzy/pull/588. Closing.
