### ISSUE TITLE
Allow overriding Xcode derivedDataPath

### ISSUE THREAD

**Issue by breathe** [realm/jazzy#484]
jazzy creates a directory called build/ relative to the Xcode project being built which has contents with structure very much like the contents that go into Xcode derivedDataPath.  Would be nice to have an option to control the path for this directory to make it easier to keep this build artifact out of the source tree.

**Comment by jpsim** [comment]
You can specify arguments to `xcodebuild` using the `-x` argument to jazzy, so you can override the derived data location using that approach. I don't think we'll be adding a different way to do this in jazzy any time soon, so I'm closing this issue.
