### ISSUE TITLE
Missing word in --author

### ISSUE THREAD

**Issue by JorgenAndreasson** [realm/jazzy#485]
This is the same issue as #446, but since it's closed I'll ask it again.
I end up with the same problem as in the other issue with only one of the words showing.

jazzy --clean --min-acl private --module PiPlayer --author ‘Clockwork Concepts’ --output Documentation

Only 'Clockwork shows in the document. I deleted the whole folder, as I thought the problem was the same as reported in 446, but no joy.
Has anyone an idea what I could be doing wrong?

**Comment by JorgenAndreasson** [comment]
My bad.
I had my command line in notes to edit. Then copied and paste to Terminal.
However, the ' or " had some formatting that I didn't see. Once I typed it directly in Terminal, or used Sublime Text it came out OK.

**Comment by jpsim** [comment]
yup, this should serve as a reminder that it's important to escape spaces when using bash.
