### ISSUE TITLE
jazzy fail to compile xcworkspace, but xcodebuild works fine

### ISSUE THREAD

**Issue by Sega-Zero** [realm/jazzy#488]
having this output:

> $ jazzy --no-clean -x -workspace,Project.xcworkspace,-scheme,Debug
> Running xcodebuild
> Could not parse compiler arguments from `xcodebuild` output.
> Please confirm that `xcodebuild` is building a Swift module.
> Saved `xcodebuild` log file: /var/folders/kh/9rw5rwln3_74r_g69jn93t8h0000gn/T/xcodebuild-805C10FF-CBA6-4642-B43D-80517E610778.log
> Failed to generate documentation
> /Library/Ruby/Gems/2.0.0/gems/jazzy-0.5.0/lib/jazzy/executable.rb:36:in `execute_command': /Library/Ruby/Gems/2.0.0/gems/jazzy-0.5.0/lib/jazzy/SourceKitten/bin/sourcekitten ["doc", "-workspace", "Project.xcworkspace", "-scheme", "Debug"](RuntimeError)
> 
> Running xcodebuild
> 
> Could not parse compiler arguments from `xcodebuild` output.
> 
> Please confirm that `xcodebuild` is building a Swift module.
> 
> Saved `xcodebuild` log file: /var/folders/kh/9rw5rwln3_74r_g69jn93t8h0000gn/T/xcodebuild-805C10FF-CBA6-4642-B43D-80517E610778.log
> 
> Failed to generate documentation
>     from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.5.0/lib/jazzy/sourcekitten.rb:140:in `run_sourcekitten'
>     from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.5.0/lib/jazzy/doc_builder.rb:57:in`block in build'
>     from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.5.0/lib/jazzy/doc_builder.rb:55:in `chdir'
>     from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.5.0/lib/jazzy/doc_builder.rb:55:in`build'
>     from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.5.0/bin/jazzy:15:in `<top (required)>'
>     from /usr/local/bin/jazzy:23:in`load'
>     from /usr/local/bin/jazzy:23:in `<main>'

meanwhile, xcodebuild log shows `** BUILD SUCCEEDED **` at the end.
are there any hidden verbose options, so I could detect the reason?

**Comment by Screon** [comment]
Have the same issue. Is there any solution?

**Comment by Screon** [comment]
Very funny. I renamed tagret from gis-demo to GisDemo and make new scheme named GisDemo without character "-". And it works...

**Comment by jpsim** [comment]
> Very funny. I renamed tagret from gis-demo to GisDemo and make new scheme named GisDemo without character "-". And it works...

Please note that jazzy expects the module name to be the clang module name, not whatever your scheme is called in Xcode.

@Sega-Zero are you still having trouble building docs for your project? If so, could you share steps for me to reproduce the issues you're seeing? Thanks!

**Comment by Screon** [comment]
@jpsim Thanks for explanation! No issue with old module name.

**Comment by Sega-Zero** [comment]
Still having that issue. Will try to find the steps to reproduce this

**Comment by jpsim** [comment]
> Will try to find the steps to reproduce this

That would help, yes.

**Comment by bhargavigostu** [comment]
Facing same issue.. Is there any update on this issue?

**Comment by istx25** [comment]
Please provide more information and repro steps for @jpsim and I. It would also be awesome if you could include a minimal project that reproduces the issue. Will close for inactivity in 2 weeks if there are no new responses.

**Comment by Sega-Zero** [comment]
Cannot reproduce this on a test project. Hard to locate the real issue cause.

**Comment by istx25** [comment]
If it's reproducible on a certain function or place in your code on a real project, try to refactor that out to another project that you can share. We need some concrete data.

**Comment by Sega-Zero** [comment]
I got thousands of documented places in my project, so I will need a lot of attempts, since I don't really know what function exactly causes this. I don't have that much time, sorry. If jazzy could have some extra verbosity, I could probably locate the problem piece of code and share it with you.

**Comment by istx25** [comment]
I understand. I didn't mean to come off as snippy. I know this is a difficult issue to reproduce concretely but it's imperative in resolving this problem for good. If that's you or I or both of us or everyone, someone, preferably multiple people need to reproduce this issue in multiple (and varied) minimal test projects.

**Comment by Sega-Zero** [comment]
Not having that kind of trouble on version 0.7.3 👍

**Comment by dsuvorov** [comment]
Just faced with the same issue. After a couple of hours googling I found almost nothing :).
The solution was to use "_" symbols instead of "-" in module name. 
I.e. if your project/workspace and target name is "test-module-one" you should use: ```-m "test_module_one"```
