### ISSUE TITLE
Rendering issue (i think)

### ISSUE THREAD

**Issue by jeeftor** [realm/jazzy#489]
I'm getting a random `</div>` showing up.

*INPUT*
<img width="560" alt="screen shot 2016-02-24 at 11 26 59 am" src="https://cloud.githubusercontent.com/assets/6491743/13292403/99da9ba8-dae9-11e5-95e6-3c577d6daff9.png">

*OUTPUT*
<img width="730" alt="screen shot 2016-02-24 at 11 27 08 am" src="https://cloud.githubusercontent.com/assets/6491743/13292404/99e4fc24-dae9-11e5-96e0-83912ff1aec6.png">

**Comment by jpsim** [comment]
@jeeftor could you please try again using jazzy 0.6.0? It includes some bug fixes which may be related to this issue. Thanks!

**Comment by jpsim** [comment]
assuming this is fixed since we never heard back from @jeeftor on this
