### ISSUE TITLE
'Could not parse compiler arguments' when documenting Obj-C Framework

### ISSUE THREAD

**Issue by gbernady** [realm/jazzy#492]
I have a project consisting of a bunch of Obj-C Frameworks (soon to include Swift code) and an app, all residing in a single workspace. When I run jazzy to document one of the Frameworks, I get the `Could not parse compiler arguments from 'xcodebuild' output.` error.

Here's a [sample project](https://github.com/realm/jazzy/files/148437/Foo.zip) reproducing the issue.

And logs:
> /D/Foo ❯❯❯ ./doc.sh                                                                                                                                                                            + jazzy --objc --author foo --module-version 1.0.0 --umbrella-header Libraries/Bar/Bar/Bar.h --framework-root Libraries/Bar --module Bar --sdk iphoneos -x -workspace,Foo.xcworkspace,-scheme,Bar
> Running xcodebuild
> Could not parse compiler arguments from `xcodebuild` output.
> Please confirm that `xcodebuild` is building a Swift module.
> Saved `xcodebuild` log file: /var/folders/qd/23r2s42j5xs78mqsm3_pss_926b9jc/T/xcodebuild-8B4A01F2-2459-4942-A533-DC660E86521F.log
> Failed to generate documentation
> /Library/Ruby/Gems/2.0.0/gems/jazzy-0.5.0/lib/jazzy/executable.rb:36:in `execute_command': /Library/Ruby/Gems/2.0.0/gems/jazzy-0.5.0/lib/jazzy/SourceKitten/bin/sourcekitten > ["doc", "-workspace", "Foo.xcworkspace", "-scheme", "Bar"] (RuntimeError)
> 
> Running xcodebuild
> 
> Could not parse compiler arguments from `xcodebuild` output.
> 
> Please confirm that `xcodebuild` is building a Swift module.
> 
> Saved `xcodebuild` log file: /var/folders/qd/23r2s42j5xs78mqsm3_pss_926b9jc/T/xcodebuild-8B4A01F2-2459-4942-A533-DC660E86521F.log
> 
> Failed to generate documentation
> 	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.5.0/lib/jazzy/sourcekitten.rb:140:in `run_sourcekitten'
> 	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.5.0/lib/jazzy/doc_builder.rb:57:in `block in build'
> 	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.5.0/lib/jazzy/doc_builder.rb:55:in `chdir'
> 	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.5.0/lib/jazzy/doc_builder.rb:55:in `build'
> 	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.5.0/bin/jazzy:15:in `<top (required)>'
> 	from /usr/local/bin/jazzy:23:in `load'
> 	from /usr/local/bin/jazzy:23:in `<main>'

What's interesting, if I add a Swift class to my Framework, the error disappears. However only the one Swift class is documented.

Am I missing something? I'm using jazzy 0.5.0 and Xcode 7.2.1. I would really appreciate some help in diagnosing the issue.

**Comment by rastersize** [comment]
AFAIK if you override the parameters passed to `xcodebuild` (i.e. via the `-x` flag) you must also send all options. E.g. see how Realm does it in https://github.com/realm/realm-cocoa/blob/master/build.sh#L239

That is in your case I guess something like `--xcodebuild-arguments --objc,Libraries/Bar/Bar/Bar.h,-x,objective-c,-isysroot,$(xcrun --show-sdk-path),-I,Libraries/Bar`.

**Comment by jpsim** [comment]
@rastersize is correct, that `-x` arguments will override any arguments to be sent to SourceKitten/Xcode that would otherwise be set by jazzy, which includes `--objc`, which is why the error disappears when you have a single Swift class, because jazzy then tries to document your "Swift" project. So just prepend `--objc` to your `-x` arguments.

**Comment by gbernady** [comment]
Thanks! I tried adding just the `--obj` to `-x` and... clang crashed. Then I started rewriting the jazzy invocation command as suggested by @rastersize, every time encountering the same crash.

In the end I got to something like

    xcode_args="--objc,Libraries/Bar/Bar/Bar.h,-x,objective-c,-isysroot,$(xcrun --sdk iphoneos --show-sdk-path),-I,$(pwd),-workspace,Foo.xcworkspace,-scheme,Bar"
    jazzy \
      --objc \
      --clean \
      --author foo \
      --module-version 1.0.0 \
      --module Bar \
      --xcodebuild-arguments $xcode_args

With the crash every time looking like this

    libclang: crash detected during parsing: {
      'source_filename' : 'Libraries/Bar/Bar/Bar.h'
      'command_line_args' : ['-x', 'objective-c', '-isysroot', '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.3.sdk', '-I', '/Users/berng/Downloads/Foo', '-workspace', 'Foo.xcworkspace', '-scheme', 'Bar'],
      'unsaved_files' : [],
      'options' : 1,
    }

Is there a way to pass the workspace and scheme to jazzy other than xcodebuild arguments?

**Comment by jpsim** [comment]
If you share a project that reproduces the issue I'll be able to troubleshoot this with you... otherwise it'll be challenging.

> Is there a way to pass the workspace and scheme to jazzy other than xcodebuild arguments?

Not for Objective-C just yet, but we are tracking that as jpsim/SourceKitten#88

**Comment by gbernady** [comment]
Here's a sample project - [Foo.zip](https://github.com/realm/jazzy/files/207119/Foo.zip)

I just ran it on my second machine, and:
* jazzy 0.5.0 does not report any crashes or errors, but the docs are empty.
* jazzy 0.6.0 fails with the following error

```
    Unrecognized arguments: -x, -soiryt, -I, -awrpcosek, -semch
    /Users/gregor/.gem/ruby/2.3.0/gems/jazzy-0.6.0/lib/jazzy/executable.rb:36:in `execute_command': /Users/gregor/.gem/ruby/2.3.0/gems/jazzy-0.6.0/lib/jazzy/SourceKitten/bin/sourcekitten ["doc", "--objc", "Libraries/Bar/Bar/Bar.h", "-x", "objective-c", "-isysroot", "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.3.sdk", "-I", "/Users/gregor/Downloads/Foo", "-workspace", "Foo.xcworkspace", "-scheme", "Bar"] (RuntimeError)

    Unrecognized arguments: -x, -soiryt, -I, -awrpcosek, -semch
        from /Users/gregor/.gem/ruby/2.3.0/gems/jazzy-0.6.0/lib/jazzy/sourcekitten.rb:142:in `run_sourcekitten'
        from /Users/gregor/.gem/ruby/2.3.0/gems/jazzy-0.6.0/lib/jazzy/doc_builder.rb:56:in `block in build'
        from /Users/gregor/.gem/ruby/2.3.0/gems/jazzy-0.6.0/lib/jazzy/doc_builder.rb:54:in `chdir'
        from /Users/gregor/.gem/ruby/2.3.0/gems/jazzy-0.6.0/lib/jazzy/doc_builder.rb:54:in `build'
        from /Users/gregor/.gem/ruby/2.3.0/gems/jazzy-0.6.0/bin/jazzy:15:in `<top (required)>'
        from /Users/gregor/.gem/ruby/2.3.0/bin/jazzy:23:in `load'
        from /Users/gregor/.gem/ruby/2.3.0/bin/jazzy:23:in `<main>'
```
I did not encounter the libclang crash however, so it may have something to do with my main machine's configuration. I will look into it tomorrow. I saw a similar problem with libclang also reported in #479.

**Comment by jpsim** [comment]
Here's what your `doc.sh` should look like:

```sh
jazzy \
  --objc \
  --swift-version 2.2 \
  --clean \
  --sdk iphonesimulator \
  --umbrella-header Libraries/Bar/Bar/Bar.h \
  --framework-root Libraries/Bar \
  --author foo \
  --module-version 1.0.0 \
  --module Bar
```

That works fine for me with Jazzy 0.6.0.

You'll also need to use Objective-C style documentation comments for them to be picked up by jazzy. In other words, replacing `/*!` with `/**`:

```objc
/**
 * Sample class description.
 */
@interface Baz : NSObject

/// A property.
@property (nonatomic) NSString *baz;

/**
 * Does something.
 *
 * @return YES if it did something, no otherwise.
 */
- (BOOL)doSomething;

@end
```

If I make those changes, the following documentation is generated: http://static.realm.io/jazzy_demo/GH492/index.html

===

Finally, if you want to still provide xcodebuild arguments directly, for now you'll need to prepend them with `--`.

**Comment by gbernady** [comment]
Thanks a lot! It works. I'm actually glad I don't have to use the xcodebuild arguments.

As for the `/*!` comment blocks, I just assumed they are supported, because HeaderDoc, Xcode and Doxygen all recognize them.

**Comment by jpsim** [comment]
Ah, I wasn't familiar with that syntax. I just created a ticket to track supporting that: #517.

I'm glad we got all this worked out!

**Comment by gbernady** [comment]
Me too! Thanks again.
