### ISSUE TITLE
Issue Finding xcrun?

### ISSUE THREAD

**Issue by ort11** [realm/jazzy#493]
XCODE 7.2.1, OSX 10.11.3, have checked the command line tools, etc.  Getting the following, any help would be appreciated.

    jazzy \
    --clean \
    --author Realm \
    --author_url https://realm.io \
    --github_url https://github.com/realm/realm-cocoa \
    --github-file-prefix https://github.com/realm/realm-cocoa/tree/v0.96.2 \
    --module-version 0.96.2 \
    --xcodebuild-arguments -scheme,RealmSwift \
    --module RealmSwift \
    --root-url https://realm.io/docs/swift/0.96.2/api/ \
    --output docs/swift_output \
    --theme docs/themesJeffs-MBP-2:smallSDKSwift jefforthober$ jazzy \
    >   --clean \
    >   --author Realm \
    >   --author_url https://realm.io \
    >   --github_url https://github.com/realm/realm-cocoa \
    >   --github-file-prefix https://github.com/realm/realm-cocoa/tree/v0.96.2 \
    >   --module-version 0.96.2 \
    >   --xcodebuild-arguments -scheme,RealmSwift \
    >   --module RealmSwift \
    >   --root-url https://realm.io/docs/swift/0.96.2/api/ \
    >   --output docs/swift_output \
    >   --theme docs/themes
    xcrun: error: unable to find utility "xcrun", not a developer tool or in PATH
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open3.rb:211:in `spawn': No such file or directory -  (Errno::ENOENT)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open3.rb:211:in `popen_run'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open3.rb:99:in `popen3'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open3.rb:279:in `capture3'
	from /Library/Ruby/Gems/2.0.0/gems/xcinvoke-0.2.1/lib/xcinvoke/xcode.rb:86:in `xcrun'
	from /Library/Ruby/Gems/2.0.0/gems/xcinvoke-0.2.1/lib/xcinvoke/xcode.rb:119:in `swift_info'
	from /Library/Ruby/Gems/2.0.0/gems/xcinvoke-0.2.1/lib/xcinvoke/xcode.rb:57:in `swift_version'
	from /Library/Ruby/Gems/2.0.0/gems/xcinvoke-0.2.1/lib/xcinvoke/xcode.rb:53:in `block in find_swift_version'
	from /Library/Ruby/Gems/2.0.0/gems/xcinvoke-0.2.1/lib/xcinvoke/xcode.rb:44:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/xcinvoke-0.2.1/lib/xcinvoke/xcode.rb:44:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/xcinvoke-0.2.1/lib/xcinvoke/xcode.rb:53:in `select'
	from /Library/Ruby/Gems/2.0.0/gems/xcinvoke-0.2.1/lib/xcinvoke/xcode.rb:53:in `find_swift_version'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.5.0/lib/jazzy/sourcekitten.rb:136:in `run_sourcekitten'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.5.0/lib/jazzy/doc_builder.rb:57:in `block in build'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.5.0/lib/jazzy/doc_builder.rb:55:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.5.0/lib/jazzy/doc_builder.rb:55:in `build'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.5.0/bin/jazzy:15:in `<top (required)>'
	from /usr/local/bin/jazzy:23:in `load'
	from /usr/local/bin/jazzy:23:in `<main>'

**Comment by ort11** [comment]
FYI

$ echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
$ whereis xcrun
/usr/bin/xcrun

**Comment by segiddins** [comment]
What Xcode versions do you have installed?

**Comment by ort11** [comment]
Had to fix this by doing XCODE / PREFERENCES / LOCATIONS / Command Line Tools / Select Proper One

The problem was that there were > 1 XCODE versions installed and this was blank

thanks for the quick reply.
