### ISSUE TITLE
Unable to generate documentation for a specified target

### ISSUE THREAD

**Issue by oscarmk1** [realm/jazzy#494]
I am using jazzy version 0.5 to generate documentation for my test target, but I am unable to do so. I am trying something like this from terminal:

jazzy --min-acl internal --xcodebuild-arguments -target,MyTestTarget

The output from the console is:

Running xcodebuild

Could not parse compiler arguments from `xcodebuild` output.

Please confirm that `xcodebuild` is building a Swift module.

I am not sure if jazzy can be used to generate documentation for a test target, I wasn't able to find documentation on what type of targets it can generate documentation for.

The reason why I would like to generate documentation for my test cases is for purposes of ATDD compliance, to make it easier for non-technical people to look at all the test cases in a BDD format, that I have as markdown comments.

If this is not supported, is there any other tool that will allow me to generate html from markdown for a test target?.

Thanks.

**Comment by jpsim** [comment]
I think you'll find the conversation in #504 very relevant to your problem.
