### ISSUE TITLE
Jazzy output what's missing 

### ISSUE THREAD

**Issue by ScottYelich** [realm/jazzy#497]
Maybe this can be done already, but searching the docs (and jazzy -h), google and issues... I can't seem to find out how.

Jazzy has this as part of the HTML results:  Docs (95% documented)

But I have no idea what's missing in the 5%.  I've clicked on everything that I can see in the HTML and it all seems to have documentation... and it's tedious to have to click on everything looking for what's missing.

Is there any way to do this now?

**Comment by jpsim** [comment]
What's undocumented is written to `docs/undocumented.txt`. This has been changed to `docs/undocumented.json` recently (#392).

**Comment by ScottYelich** [comment]
I found it:  public extension UIDevice {

Jazzy wants me to document UIDevice!
not sure what to do.

**Comment by jpsim** [comment]
> Jazzy wants me to document UIDevice!

lol, no. Jazzy wants you to document your extension to UIDevice!

**Comment by ScottYelich** [comment]
I thought I had... I have documentation on everything in the extension... I'll verify again now just to be sure.  More than likely I am missing something, somewhere... just have to find it.  :-/

**Comment by ScottYelich** [comment]
///   This struct contains values to use when enabling analytics services such as:
    ///   - Flurry
    ///   - Adobe (Omniture)
    ///   - Google Analytics
    ///
    ///   Usage:
    ///
    ///     AnalyticsManager.setupWithAnalytics([
    ///       AnalyticsManager.Constants.AnalyticsService.Flurry : "FLURRY_KEY_TEXTVALUE"
    ///     ])
    /// 
    public struct Constants {
        public struct AnalyticsService {
            public static let Flurry = "ARFlurry";
        }
    }

Ok, so I needed to add documentation to the "public struct AnalyticsService" as well as "public statis let Flurry" line.  That gave me 100% coverage... and UIDevice is still coming up as "undocumented" ... which I guess I can live with.

**Comment by ScottYelich** [comment]
Thank you for the amazingly quick responses!

I personally consider this question closed/resolved with your first response about the output file.  Perhaps this could be called out in the documentation, as I did not notice the file in the docs directory and it's really helpful.

**Comment by jpsim** [comment]
@ScottYelich could you please try again with jazzy built from source on the `jp-sourcekitten-0.11.0` branch? That fixes a few issues, so may help with your undocumented UIDevice.

**Comment by ScottYelich** [comment]
I'm building this branch now to test:

Scotts-MacBook-Pro-2 [151]> xx --version

jazzy version: 0.5.0

Scotts-MacBook-Pro-2 [152]> /NOBACKUP/jazzy/bin/jazzy --clean

Running xcodebuild

Parsing DeviceInfo.swift (1/4)

Parsing Device.swift (2/4)

Parsing GlobalConstants.swift (3/4)

Parsing Analytics.swift (4/4)

building site

jam out ♪♫ to your fresh new docs in `docs`

Scotts-MacBook-Pro-2 [153]> cd /NOBACKUP/jazzy/

Scotts-MacBook-Pro-2 [154]> git branch

* jp-sourcekitten-0-11.0

  master

  origin/jp-sourcekitten-0-11.0



I still get 100% coverage -- but UIDevice is "undocumented" ... am I
running Jazzy correctly?

**Comment by ScottYelich** [comment]
I responded to the email w/ an image attached, the image didn't seem to come through.

<img width="823" alt="screen shot 2016-03-18 at 2 18 26 pm" src="https://cloud.githubusercontent.com/assets/58249/13887945/f41b5f7a-ed14-11e5-9192-89e59afbf699.png">

**Comment by jpsim** [comment]
ok, and what does your `UIDevice` extension documentation look like? Is it something like this?

```swift
/// My super awesome UIDevice extension
extension UIDevice {
  // Get the model identifier for the current UIDevice...
  public var modelIdentifier: String {
    return "oh hai!"
  }
}
```

**Comment by ScottYelich** [comment]
// MARK: - UIDevice extentions

///  uidevice extension jazz doc test
public extension UIDevice {
    
    ///  Get the model identifier for the current UIDevice.
    ///
    ///  Usage:
    ///
    ///    let modelName = UIDevice.currentDevice().modelIdentifier
    
    public var modelIdentifier: String {

**Comment by ScottYelich** [comment]
I get the same result "undocumented" if I have the /// before the public extension line.... or if there is no /// prior to that line.

**Comment by jpsim** [comment]
That's a bug. I think I've fixed it in SourceKitten here jpsim/SourceKitten#188

**Comment by jpsim** [comment]
We're actually tracking that bug as #454. Since this is the only thing we're now discussing in this ticket, I'll close this one as a duplicate. Thanks for your help!

**Comment by ScottYelich** [comment]
Yes, #454 looks like the same issue.  I'll test with the updates ASAP.

Thank you very much for your quick attention to this.  I was not expecting that.
