### ISSUE TITLE
Documentation coverage wrong if files outside project

### ISSUE THREAD

**Issue by arn00s** [realm/jazzy#498]
Hi there,
I tried to jazzy a project containing external files (not inside the project directory), but linked into the xCode project.
With this solution, code coverage is always 100% for external files.
Since I copy the same file inside the directory, then he founds some undocumented methods...

**Comment by jpsim** [comment]
That shouldn't be the case. Can you please share a project that exhibits this behavior so we can investigate?

**Comment by jpsim** [comment]
@arn00s I never heard back from you since my last comment. It's a bit difficult for me to make any progress on this until then. Thanks!

**Comment by arn00s** [comment]
I'm sorry @jpsim , forgot about that one. I'll share the project with you later today.

**Comment by arn00s** [comment]
Hi @jpsim , please check this repo, and try 'jazzy' on each different commit, then check the documentation coverage.  https://github.com/arn00s/jazzy-documentation-bug

**Comment by istx25** [comment]
Thanks @arn00s. We'll review this asap and see what needs to be done (if something still does).
