### ISSUE TITLE
--exclude file1,file2,…fileN does not work

### ISSUE THREAD

**Issue by jasonwuconcur** [realm/jazzy#500]
Hi,
I was running jazzy to generate docs using Xcode 7.2.1 and jazzy 0.5.0. I got the below error message. After I dug more, I found if file RealmDataProvider.swift includes code like  let realm = try! Realm() or let objectType = T.self, the below error will show up. if it does not, it could generate the docs. I was trying to use -e to exclude the file. However it did not work. Any help is welcome. Thanks

Jason

Parsing RealmDataProvider.swift (11/14)

sourcekit: [1:connection-event-handler:9891: 0.0000] Connection interrupt

sourcekit: [1:pingService:9891: 0.0005] pinging service

sourcekit: [1:sourcekitd_send_request_sync:1551: 0.0008] request dropped while restoring service
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.5.0/lib/jazzy/sourcekitten.rb:140:in `run_sourcekitten'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.5.0/lib/jazzy/doc_builder.rb:57:in `block in build'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.5.0/lib/jazzy/doc_builder.rb:55:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.5.0/lib/jazzy/doc_builder.rb:55:in `build'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.5.0/bin/jazzy:15:in `<top (required)>'
	from /usr/bin/jazzy:23:in `load'
	from /usr/bin/jazzy:23:in `<main>'

**Comment by jpsim** [comment]
It looks like SourceKit is crashing. Have you filed a bug at https://bugs.swift.org? That's probably the best way to make Apple aware of bugs in SourceKit.
