### ISSUE TITLE
Support for excluded directories

### ISSUE THREAD

**Issue by JackoPlane** [realm/jazzy#503]
In the same way [SwiftLint](https://github.com/realm/SwiftLint) supports whole directories to be excluded, the ability to exclude specific directories would allow for increased support for excluding things like `Vendor/`

**Comment by jpsim** [comment]
@JackoPlane since Jazzy just generates documentation for modules, building your `Vendor/` code as separate frameworks would have the same effect, and would work with jazzy today. I'm fine keeping this open as a feature request, but don't see ourselves implementing this any time soon.
