### ISSUE TITLE
Functions tagged with an attribute

### ISSUE THREAD

**Issue by couchdeveloper** [realm/jazzy#505]
The documentation for functions with an attribute _followed by a new line_ will not be properly generated.

For example, the function marked with the attribute  `@warn_unused_result` followed by a new line followed by the function declaration:

    /**
     The body.

     - parameter f: The maping function.
     - returns: A `Try<U>`.
     */
    @warn_unused_result
    public func map<U>(@noescape f: T throws -> U) -> Try<U> {
        ...
    }

For the above source code, jazzy will not generate documentation including the "body" of the comment. Parameters and the return tag will be included in the documentation, though.

If there's no new line after the attribute, the documentation will be correct:

    /**
     The body.

     - parameter f: The maping function.
     - returns: A `Try<U>`.
     */
    @warn_unused_result public func map<U>(@noescape f: T throws -> U) -> Try<U> {
        ...
    }

**Comment by jpsim** [comment]
This should be fixed on the `master` branch. Could you please build jazzy from source to confirm that this has been addressed in your case?

**Comment by couchdeveloper** [comment]
You are right, it's fixed in HEAD master.  Great! ;)
