### ISSUE TITLE
Support compiling multiple scss files into one

### ISSUE THREAD

**Issue by meleyal** [realm/jazzy#507]
e.g. we have the following directory structure:

``` sh
jazzy-docs/theme/assets/css
├── components
│   ├── _code.css
│   ├── _grid.css
│   ├── _icons.css
│   ├── _main-content.css
│   ├── _navbar.css
│   ├── _scaffolding.css
│   └── _sidebar.css
├── highlight.css.scss
└── jazzy.css.scss
```

Where `jazzy.css.scss` is a 'manifest' including the component files using `@import`:

``` scss
@import '../vendor/bootstrap/css/bootstrap.css';
@import './components/_scaffolding.css';
@import './components/_grid.css';
@import './components/_navbar.css';
@import './components/_main-content.css';
@import './components/_sidebar.css';
@import './components/_code.css';
@import './components/_icons.css';
```

Currently jazzy just passes `.scss` files one by one through Sass, but it would be great if you could just pass the manifest through sass and let it resolve the dependencies. This way (afaik) you could share variables, mixins, etc. and get a single `.css` file as output.

**Comment by jpsim** [comment]
Sounds like a great idea! Is this functionality you'd be interested in adding to jazzy yourself?

**Comment by istx25** [comment]
Hey @meleyal, wanted to bring attention back to this. As @jpsim asked, are you interested in implementing this yourself? Would love to see a PR. :)

**Comment by johnfairh** [comment]
At this point not going to change the sass 'architecture'.
