### ISSUE TITLE
Installation problem - (OSX version - 10.11.3 (15D21) , Xcode Version - 7.3 (7D175))

### ISSUE THREAD

**Issue by ArunPrasanth-R** [realm/jazzy#509]
I have just run the command : " sudo gem install jazzy " .... As mentioned in the documentation. It throws me the below mentioned error.

Building native extensions. This could take a while...
ERROR: Error installing jazzy:
ERROR: Failed to build gem native extension.
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby extconf.rb
creating Makefile

make "DESTDIR="
make: *** No rule to make target "/Applications/Xcode', needed byautolink.o'. Stop.

Gem files will remain installed in /Library/Ruby/Gems/2.0.0/gems/redcarpet-3.3.4 for inspection.
Results logged to /Library/Ruby/Gems/2.0.0/gems/redcarpet-3.3.4/ext/redcarpet/gem_make.out

**Comment by segiddins** [comment]
Are you sure you have Xcode installed as `/Application/Xcode.app`?

**Comment by ArunPrasanth-R** [comment]
I have installed Xcode. It is /Applications/Xcode\ 7.3.app

On Tue, Apr 5, 2016 at 7:49 PM, Samuel Giddins <notifications@github.com>
wrote:

> Are you sure you have Xcode installed as /Application/Xcode.app?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/realm/jazzy/issues/509#issuecomment-205830514>
>



-- 
Regards,
[image: --]
ArunPrasanth R
[image: https://]about.me/arunprasanth
<https://about.me/arunprasanth?promo=email_sig&utm_source=email_sig&utm_medium=email_sig&utm_campaign=external_links>
* iOS  Application *
*Developer*
*Payoda Technologies Private Limited <http://www.payoda.com/>*

**Comment by jpsim** [comment]
This is probably an issue with your Ruby configuration. What happens when you try to install the redcarpet gem? `sudo gem install redcarpet`.

**Comment by ArunPrasanth-R** [comment]
I'm getting this error while executing sudo gem install red carpet.



ptpldm014:~ user$ sudo gem install redcarpet

Password:

Building native extensions.  This could take a while...

ERROR:  Error installing redcarpet:

ERROR: Failed to build gem native extension.


    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
extconf.rb

creating Makefile


make "DESTDIR="

make: *** No rule to make target `"/Applications/Xcode', needed by
`autolink.o'.  Stop.



Gem files will remain installed in
/Library/Ruby/Gems/2.0.0/gems/redcarpet-3.3.4 for inspection.

Results logged to
/Library/Ruby/Gems/2.0.0/gems/redcarpet-3.3.4/ext/redcarpet/gem_make.out

ptpldm014:~ user$

On Wed, Apr 6, 2016 at 1:47 PM, JP Simard <notifications@github.com> wrote:

> This is probably an issue with your Ruby configuration. What happens when
> you try to install the redcarpet gem? sudo gem install redcarpet.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/realm/jazzy/issues/509#issuecomment-206210879>
>



-- 
Regards,
[image: --]
ArunPrasanth R
[image: https://]about.me/arunprasanth
<https://about.me/arunprasanth?promo=email_sig&utm_source=email_sig&utm_medium=email_sig&utm_campaign=external_links>
* iOS  Application *
*Developer*
*Payoda Technologies Private Limited <http://www.payoda.com/>*

**Comment by jpsim** [comment]
I suggest you bring this up with the redcarpet folks by filing an issue with them: https://github.com/vmg/redcarpet/issues/new

**Comment by segiddins** [comment]
The issue is that that extension is expecting Xcode to exist at `/Applications/Xcode.app`

**Comment by jpsim** [comment]
That sounds like a reasonable cause. @ArunPrasanth-R you could try symlinking Xcode to the location expected by redcarpet and trying again: `ln -s /Applications/Xcode-7.3.app /Applications/Xcode.app`

**Comment by ArunPrasanth-R** [comment]
I thought that would be the issue and changed */Applications/Xcode.app*.
Unfortunately the issue exists.

While executing sudo gem install redcarpet, I faced the below mentioned
error

ptpldm014:~ user$ *sudo gem install redcarpet*

Password:

Building native extensions.  This could take a while...

ERROR:  Error installing redcarpet:

ERROR: Failed to build gem native extension.


    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
extconf.rb

mkmf.rb can't find header files for ruby at
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/include/ruby.h



Gem files will remain installed in
/Library/Ruby/Gems/2.0.0/gems/redcarpet-3.3.4 for inspection.

Results logged to
/Library/Ruby/Gems/2.0.0/gems/redcarpet-3.3.4/ext/redcarpet/gem_make.out

On Thu, Apr 7, 2016 at 12:23 AM, JP Simard <notifications@github.com> wrote:

> That sounds like a reasonable cause. @ArunPrasanth-R
> <https://github.com/ArunPrasanth-R> you could try symlinking Xcode to the
> location expected by redcarpet and trying again: ln -s
> /Applications/Xcode-7.3.app /Applications/Xcode.app
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/realm/jazzy/issues/509#issuecomment-206512270>
>



-- 
Regards,
[image: --]
ArunPrasanth R
[image: https://]about.me/arunprasanth
<https://about.me/arunprasanth?promo=email_sig&utm_source=email_sig&utm_medium=email_sig&utm_campaign=external_links>
* iOS  Application *
*Developer*
*Payoda Technologies Private Limited <http://www.payoda.com/>*

**Comment by jpsim** [comment]
So did you file an issue with redcarpet?

**Comment by ArunPrasanth-R** [comment]
No.

On Thu, Apr 7, 2016 at 11:23 AM, JP Simard <notifications@github.com> wrote:

> So did you file an issue with redcarpet?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/realm/jazzy/issues/509#issuecomment-206707291>
>



-- 
Regards,
[image: --]
ArunPrasanth R
[image: https://]about.me/arunprasanth
<https://about.me/arunprasanth?promo=email_sig&utm_source=email_sig&utm_medium=email_sig&utm_campaign=external_links>
* iOS  Application *
*Developer*
*Payoda Technologies Private Limited <http://www.payoda.com/>*

**Comment by jpsim** [comment]
That would be a good start

**Comment by ArunPrasanth-R** [comment]
I have updated the ruby ,which resolved my issue. Now, i could able to
install and run Jazzy without any issue.

Thanks for the support.


On Thu, Apr 7, 2016 at 10:57 PM, JP Simard <notifications@github.com> wrote:

> That would be a good start
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/realm/jazzy/issues/509#issuecomment-207012596>
>



-- 
Regards,
[image: --]
ArunPrasanth R
[image: https://]about.me/arunprasanth
<https://about.me/arunprasanth?promo=email_sig&utm_source=email_sig&utm_medium=email_sig&utm_campaign=external_links>
* iOS  Application *
*Developer*
*Payoda Technologies Private Limited <http://www.payoda.com/>*

**Comment by jpsim** [comment]
Glad to hear it.
