### ISSUE TITLE
[bug] Extensions incorrectly show "Undocumented" text

### ISSUE THREAD

**Issue by jessesquires** [realm/jazzy#519]
At the top-level where class descriptions are usually displayed, extensions show `"Undocumented"`. See screenshot:

![screen shot 2016-04-07 at 8 01 29 pm](https://cloud.githubusercontent.com/assets/2301114/14373107/9f643fdc-fcfb-11e5-82d1-90217610a03b.png)

I think the preferred behavior here should be to display nothing.

**Comment by jessesquires** [comment]
Oh forgot, here's the project:

https://github.com/jessesquires/PresenterKit

**Comment by jpsim** [comment]
Duplicate of #454?

**Comment by jessesquires** [comment]
Oops! :blush: Yep.
