### ISSUE TITLE
Header slugs incompatible with GitHub-Flavored Markdown

### ISSUE THREAD

**Issue by zwaldowski** [realm/jazzy#524]
GitHub-Flavored Markdown slugs headers using dashes (`-`), not underscores (`_`), rendering anchor links for READMEs invalid in Jazzy when they are valid online, i.e., when generated with [doctoc](https://github.com/thlorenz/doctoc).

* [Example](https://bucket.waldowski.me/BNRDeferred-20160413/index.html) of Jazzy-generated doc with broken anchors.
* [Code in Jazzy](https://github.com/realm/jazzy/blob/master/lib/jazzy/jazzy_markdown.rb#L11) implementing the behavior.
* [Code in DocToc](https://github.com/thlorenz/anchor-markdown-header/blob/master/anchor-markdown-header.js#L18) showing the behavior.
* [Code in a GFM-compatible renderer](https://github.com/chjj/marked/blob/master/lib/marked.js#L795) showing the behavior.

I'd PR to fix it myself, but I'm not sure what breakages would occur and/or why the dash was chosen.

Cheers!

**Comment by jpsim** [comment]
@segiddins wrote that code in #84 when we migrated to redcarpet for Markdown rendering. Sam, do you remember why you went with underscores here?

It seems to me that updating this to use dashes would be fine given the predominance of GitHub-hosted projects. I have no clue how many people use one over the other in the wild either.

**Comment by segiddins** [comment]
I think it was just arbitrary

**Comment by jpsim** [comment]
Cool, not a bad choice initially, but in light of @zwaldowski's evidence, I vote we change the `_` for a `-`. @zwaldowski care to do this?

**Comment by zwaldowski** [comment]
*/me rolls for an Intelligence check*
