### ISSUE TITLE
Following the FAE ruleset, jazzy HTML output produces several accessibility errors.

### ISSUE THREAD

**Issue by r-flynn** [realm/jazzy#525]
Following the FAE ruleset, jazzy HTML output produces several accessibility errors.
## List of Accessibility Issues Summary

| FAE Rule | Violations | Message | Class |
| --- | --- | --- | --- |
| Warn | 1 | The words contained in each h1 element should match a subset of the words contained in the title element. Words (%1) in h1 elements should also be in the title element. | Title |
| Fail | 1 | Heading elements that follow the last h1 should be properly nested. | Headings |
| Note | 1 | No alt text provided, but alternate text was found on the title attribute. | Images |
| Warn | 1 | Every img element that is less than 8 pixels high or 8 pixels wide OR has an empty alt attribute value should be removed and CSS techniques should be used for styling content. | Images |
| Warn | 1 | The character encoding was not specified. | W3C Specifications |
| Warn | 4 | Ensure that links that point to the same HREF use the same link text. | Links |
| Warn | 5 | Each map, ul or ol element that precedes the last h1 element and appears to be a navigation bar should be immediately preceded by a heading element, preferably an h2. | Menu and Navigation Bars |

**Comment by jpsim** [comment]
Thanks for reporting these as areas for improvement, @r-flynn! Is this something you think you could help address? I'm really not that familiar with either FAE or front-end web development in general!

**Comment by istx25** [comment]
Hey @r-flynn! Wanted to bring attention to @jpsim's comment. Would you be interested in helping us address this problem and improve it?

**Comment by johnfairh** [comment]
Tidied up the actual errors in jazzy 0.14.1.
