### ISSUE TITLE
Help: How to provide default implementation of Protocols

### ISSUE THREAD

**Issue by RahulKatariya** [realm/jazzy#531]
How to document the default implementation in protocols.

[![Restofire][1]][1]

  [1]: http://i.stack.imgur.com/By4aw.png

**Comment by jpsim** [comment]
You can document default implementations in protocols by documenting the default implementation in protocols.

Example: [docs](https://bustoutsolutions.github.io/siesta/api/Protocols/ResourceObserver.html#/s:FP6Siesta16ResourceObserver23resourceRequestProgressuRq_S0__Fq_FTCS_8Resource8progressSd_T_) & [source](https://github.com/bustoutsolutions/siesta/blob/d41e12dec2eb3c239f5d6738c6eaf86458c4f209/Source/ResourceObserver.swift#L46-L47)

```swift
/// Requestable protocol.
public protocol Requestable {
  /// The base URL. `configuration.BaseURL` by default.
  public var baseURL: String { get }
}

public extension Requestable {
  /// Insert default implementation documentation here.
  public var baseURL: String {
    return configuration.BaseURL
  }
}
```

**Comment by RahulKatariya** [comment]
👍🏼
