### ISSUE TITLE
Question: How to link to a section within index.html ?

### ISSUE THREAD

**Issue by wittedhaddock** [realm/jazzy#534]
With the nice GH-like markdown generation inside a project's README.mb, I'm wondering how to produce the same effect as a section-link. 

This: https://gist.github.com/asabaylus/3071099

This may be myself being blind... where is the documentation that describes what Markdown is and is not supported? 

Thank you

**Comment by jpsim** [comment]
We recently made a change to match the slug generation used by jazzy to match GitHub's (#526). So anchor links should now work just like GitHub.
