### ISSUE TITLE
Problem with generating Swift declarations from Objective-C

### ISSUE THREAD

**Issue by jonlansdell** [realm/jazzy#536]
I'm running the latest version incorporating the latest (really excellent) changes from https://github.com/realm/jazzy/pull/530. The Swift interfaces are all generated correctly from the Objective-C project, with one exception:

An Objective-C interface such as:

`-(void)enumerateObjectsUsingBlock:(void (^)(NSObject *obj, NSInteger idx, BOOL *stop))block;`

Produces the following Swift:

`func enumerateObjectsUsingBlock(block: ((NSObject!, Int, UnsafeMutablePointer`

(it doesn't process the BOOL *stop)

whereas it should generate something like:

`func enumerateObjectsUsingBlock(block: (NSObject!, Int, UnsafeMutablePointer<ObjCBool>) -> Void)`

Thanks.

Jon

**Comment by jpsim** [comment]
Thanks for reporting this Jon, and yes I also noticed that.

Jazzy uses SourceKit to generate those, so any improvements should probably be done there, upstream. The SourceKit project is available on GitHub here: https://github.com/apple/swift/tree/master/tools/SourceKit

**Comment by istx25** [comment]
Since this is not an issue specific to Jazzy, I'm going to close the issue. Feel free to re-open if you disagree.
