### ISSUE TITLE
Unable to get Jazzy to work with -(hypens) in project name

### ISSUE THREAD

**Issue by Raja413** [realm/jazzy#537]
I get this error when i try to get jazzy docs on a project which has "-" in the name of the project.

Running xcodebuild

Could not parse compiler arguments from `xcodebuild` output.

Please confirm that `xcodebuild` is building a Swift module

the name of my project is login-switcher-handler-ios

**Comment by jpsim** [comment]
Clang modules are C99 identifiers, so your module name isn't `login-switcher-handler-ios`, it's probably `login_switcher_handler_ios`.

**Comment by Raja413** [comment]
I don't have "_" in the name of my project. I only have "-". My root folder also has "-". Shouldn't my root folder   have "-".

**Comment by emoleumassi** [comment]
Something new?

**Comment by Raja413** [comment]
No, Its still the same. Looks like it doesn't work with "-".

**Comment by jpsim** [comment]
Clang modules don't have hyphens. If you share exact steps to reproduce, I could tell you more about why it's not working.

**Comment by Raja413** [comment]
Steps to reproduce

1:My root folder is

/Users/rajareddyporeddy/Library/Developer/SharedLibs/aa-environmentswitcher-cleint-iOS/environment-switcher-client-ios

2: i have installed jazzy through terminal ([sudo] gem install jazzy)

3: go to root of the project
4: run jazzy

it throws an error 

Running xcodebuild

Could not parse compiler arguments from xcodebuild output.


when i tried to run jazzy with removing "-" in my project, it worked fine

**Comment by istx25** [comment]
I'll try to get around to reviewing these repro steps soon. Sorry for the wait times, @Raja413!

**Comment by mootpointer** [comment]
I think I've run into a similar issue, I can help with repro if that's useful.

**Comment by jpsim** [comment]
Hi @mootpointer, yes a repro case would be helpful

**Comment by johnfairh** [comment]
Latest everything all works fine provided you either omit `--module` or give the correct module name (Xcode Build Settings -> Product Module Name).
