### ISSUE TITLE
Jazzy doesn't escape ? in URLs

### ISSUE THREAD

**Issue by kballard** [realm/jazzy#547]
If I have a documented implementation of the `??` operator, Jazzy creates a file `Functions/??(_:_:).html`, but it doesn't escape the `?` in hyperlinks to this function. This includes the hyperlink in the sidebar as well as the "See more" hyperlink when looking at the Functions page. The hyperlinks end up looking something like `<a href="Functions/??(_:_:).html">See more</a>`, and clicking on this hyperlink ends up showing the Functions folder in the Finder (as the `?` is interpreted as the beginning of a query string).

jazzy version: 0.6.0

**Comment by jpsim** [comment]
Thanks for filing this! We really should improve our URL generation sanitization in general.

**Comment by istx25** [comment]
I see that #558 needs to be reviewed and merged.

**Comment by SDGGiesbrecht** [comment]
The configuration option `use_safe_filenames` and the corresponding flag `--use-safe-filenames` are now available. Until 0.7.4 is released, you can build and run from source (in your project directory):
```
git clone https://github.com/realm/jazzy
cd jazzy
bundle install
cd ..
jazzy/bin/jazzy --use-safe-filenames
rm -rf jazzy
```
Any other flags you normally use (such as `--clean`) can be added to the second last line.
