### ISSUE TITLE
run failed

### ISSUE THREAD

**Issue by neng18** [realm/jazzy#553]
error info : Failed to generate documentation
    from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.6.0/lib/jazzy/sourcekitten.rb:142:in `run_sourcekitten'
    from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.6.0/lib/jazzy/doc_builder.rb:56:in`block in build'
    from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.6.0/lib/jazzy/doc_builder.rb:54:in `chdir'
    from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.6.0/lib/jazzy/doc_builder.rb:54:in`build'
    from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.6.0/bin/jazzy:15:in `<top (required)>'
    from /usr/local/bin/jazzy:23:in`load'
    from /usr/local/bin/jazzy:23:in `<main>'

**Comment by istx25** [comment]
Hi @neng18. Thanks for reaching out. Would you be able to elaborate more on the issue and where specifically you need assistance? I'll be closing this issue in two weeks if there is no further activity.
