### ISSUE TITLE
Accommodating Improper Usage for Documenting Objective-C

### ISSUE THREAD

**Issue by Mozahler** [realm/jazzy#554]
I love jazzy, but I struggle with the Objective C Documentation process. If I download a trending project from GitHub, often many of the classes are documented well in the .m files but not the .h files. If I put the .m file names in the umbrella header, jazzy blows up. Besides copying the comments to the .h files, is there a less manually intensive way of getting needed results? 

jazzy
Using config file /Users/Alex/Downloads/DateTools-master/.jazzy.yaml
fatal error: Unsupported CXCursorKind: ObjCImplementationDecl: file /Users/jp/Projects/jazzy/SourceKitten/Source/SourceKittenFramework/ObjCDeclarationKind.swift, line 71
/Library/Ruby/Gems/2.0.0/gems/jazzy-0.6.0/lib/jazzy/executable.rb:36:in `execute_command': /Library/Ruby/Gems/2.0.0/gems/jazzy-0.6.0/lib/jazzy/SourceKitten/bin/sourcekitten ["doc", "--objc", "/Users/Alex/Downloads/DateTools-master/DateTools/Umbrella.h", "--", "-x", "objective-c", "-isysroot", "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk", "-I", "/Users/Alex/Downloads/DateTools-master/DateTools"] (RuntimeError)

fatal error: Unsupported CXCursorKind: ObjCImplementationDecl: file /Users/jp/Projects/jazzy/SourceKitten/Source/SourceKittenFramework/ObjCDeclarationKind.swift, line 71
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.6.0/lib/jazzy/sourcekitten.rb:142:in `run_sourcekitten'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.6.0/lib/jazzy/doc_builder.rb:56:in `block in build'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.6.0/lib/jazzy/doc_builder.rb:54:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.6.0/lib/jazzy/doc_builder.rb:54:in `build'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.6.0/bin/jazzy:15:in `<top (required)>'
	from /usr/local/bin/jazzy:23:in `load'
	from /usr/local/bin/jazzy:23:in `<main>'

**Comment by jpsim** [comment]
The Objective-C interface is extremely unforgiving. We're tracking making improvements to this in #399 and jpsim/SourceKitten#88
