### ISSUE TITLE
Empty "Unexposeds" group

### ISSUE THREAD

**Issue by jonlansdell** [realm/jazzy#573]
When using Jazzy 0.61 and later, I'm getting an empty 'Unexposeds' Group as shown. Any suggestions as to how to fix this would be appreciated. The project is an Objective-C framework.

Thanks. 

![unexposed](https://cloud.githubusercontent.com/assets/10199979/15831700/c0d882c8-2c16-11e6-9b1d-61396204cbe9.png)

**Comment by jpsim** [comment]
This looks like fallout from #562. Which unexposed declarations do you have in your interface?

Here's how clang defines unexposed declarations: http://clang.llvm.org/doxygen/group__CINDEX.html#ggaaccc432245b4cd9f2d470913f9ef0013ab6c248d25235d6188a1c56ecba85efaf

> A declaration whose specific kind is not exposed via this interface.
> 
> Unexposed declarations have the same operations as any other kind of declaration; one can extract their location information, spelling, find their definitions, etc. However, the specific kind of the declaration is not reported.

Regardless, based on this definition I think we should explicitly ignore these types of declarations as they seem to be useful for compilers but not readers of API documentation.

**Comment by fluidjax** [comment]
I can replicate this error by having just a semicolon on its own line in a header file, I think its outside of a class or interface definition, but if you put a semicolon as the first line it seems to do it.

**Comment by jonlansdell** [comment]
I can confirm that removing the rogue semi-colon fixes the problem. Thanks for your help.

**Comment by esad** [comment]
Probably related/same bug: https://github.com/realm/jazzy/issues/475

**Comment by jpsim** [comment]
I think this is a separate bug actually.
