### ISSUE TITLE
Feature request: stable urls when a type changes realm

### ISSUE THREAD

**Issue by groue** [realm/jazzy#584]
As it evolves, a library may decide that a struct should be refactored as a protocol, or a class, or the opposite, etc.

Since the URL generated by Jazzy contains "Structs", "Protocols", etc, maintaining links to documentation is more difficult than it could be, because it's not only a matter of replacing version numbers:
- http://cocoadocs.org/docsets/GRDB.swift/0.64.0/Structs/FetchRequest.html
- http://cocoadocs.org/docsets/GRDB.swift/0.72.0/Protocols/FetchRequest.html

Since Swift identifiers can not be reused (unlike Obj-C which accepts both a protocol and a class with the same name, as NSObject), don't you think we could just get rid of the "Structs", "Protocols", "Classes" in the URL generated by jazzy?

**Comment by jpsim** [comment]
good points, I can't think of any reason not to do this, but I'm also concerned there might be reasons not to do this that neither of us have thought of. Let's keep this one open for sure.

**Comment by johnfairh** [comment]
Realistically at this point not going to change the URL scheme.  I think DocC does do this though.
