### ISSUE TITLE
Is it possible to disable creation of docset files?

### ISSUE THREAD

**Issue by valery-bashkatov** [realm/jazzy#592]
Hi. Is it possible to disable creation of docset files via Jazzy parameters?

**Comment by jpsim** [comment]
Why?

**Comment by jpsim** [comment]
Hi @valery-bashkatov, sorry for my curt response before. I'd love to know why you'd like to disable the creation of docsets when running jazzy. That part of the build process should be very fast comparatively, so disabling this wouldn't make jazzy run noticeably faster.
