### ISSUE TITLE
Duplicate generation of clases @objc

### ISSUE THREAD

**Issue by javialgaba** [realm/jazzy#594]
I have a class written in Swift that I want to bridge to Objective-C. But when I use **jazzy** I get only one class definition (SwifItem) instead of two.

```
@objc(OBJCItem) public final class SwifItem: NSObject
```
It is possible to have two definitions (OBJCItem AND SwiftItem) generated by jazzy?

**Comment by jpsim** [comment]
It's just one declaration. What I suspect you really want is #136.

**Comment by javialgaba** [comment]
Exactly. I just found that right now it works from ObjC to Swift, not the other way around https://github.com/realm/jazzy/issues/136#issuecomment-225059909. 
Anyway thank you very much for your fast response! This project is **awesome**!

**Comment by jpsim** [comment]
cool, then let's close this keep the conversation in #136 😄
