### ISSUE TITLE
There are both Objective-C and Swift refrence in my document.

### ISSUE THREAD

**Issue by YinChangDao** [realm/jazzy#597]
I used jazyy 0.7.0 to genrate my Objective-C SDK document,but I found there are both Objective-C and swift refrences. I just want to create Objective-C API refrence, what should I do? I also in a puzzle about that all the Structs in my documents are empty.Could you tell why? Thank you in advance.

**Comment by agentk** [comment]
Hi @YinChangDao if the documentation you are generating for an open source library? Or are you able to put together the smallest possible demo test case?

**Comment by YinChangDao** [comment]
Hi @agentk I'd like to generate a documentation for my open source library. After I used jazzy, there are both Objective-C and swift API references in the index.html file. But I hope there is Objective-C API reference alone. Do you know what should I do?

**Comment by agentk** [comment]
I don't have any idea without seeing what's going on in your case.

I haven't dealt with a library generating both objc and swift personally, but having an example project of the issue or your specific library would be REALLY helpful to see more about what's going on.

**Comment by YinChangDao** [comment]
Thanks for your reply, for I didn't have that case in my hand, tomorrow I will post the screenshot of the index.html file. @agentk

**Comment by YinChangDao** [comment]
Hi @agentk I just wrote a test demo. Here I post the result screenshot in which the problem can be shown.
![Uploading IMG_2470.PNG…]()
![Uploading IMG_2467.PNG…]()
![Uploading IMG_2468.PNG…]()
![Uploading IMG_2469.PNG…]()

**Comment by YinChangDao** [comment]
Hi @agentk I just wrote a test demo. The problem occurs, but I can't post the result screenshot, it always remind me that the server can't process my picture file. Here is my code.
 `@interface Header : NSObject

/**
 *  Signal quality.
 */
typedef struct
{
    /**
     *  Signal quality range [0, 100].
     */
    uint8_t quality;
} SignalQualit;

/**
 *  The connectivity status of the device.
 */
@property (assign, nonatomic, readonly, getter=isConnected) BOOL connected;

/**
 *  Get the device firmware version.
 */
- (void)getFirmwareVersionWithCompletion:(void (^) (NSString *version, NSError *error))block;

@end`

**Comment by YinChangDao** [comment]
Hi @agentk I just wrote a test demo. The problem occurs, but I cannot upload the result picture, the server always remind me that it cannot process my picture file. Here is my code in header file.
@interface Header : NSObject

/**
 *  Signal quality.
 */
typedef struct
{
    /**
     *  Signal quality range [0, 100].
     */
    uint8_t quality;
} SignalQualit;

/**
 *  The connectivity status of the device.
 */
@property (assign, nonatomic, readonly, getter=isConnected) BOOL connected;

/**
 *  Get the device firmware version.
 */
- (void)getFirmwareVersionWithCompletion:(void (^) (NSString *version, NSError *error))block;

@end

My jazzy command: 
jazzy --objc --clean --umbrella-header Header/Header.h --framework-root . --output jazzy/doc

**Comment by YinChangDao** [comment]
Hi @agentk I just wrote a test demo. The problem occurs, but I cannot upload the result picture, the server always remind me that it cannot process my picture file. 
``
@interface Header : NSObject

/**
 *  Signal quality.
 */
typedef struct
{
    /**
     *  Signal quality range [0, 100].
     */
    uint8_t quality;
} SignalQualit;

/**
 *  The connectivity status of the device.
 */
@property (assign, nonatomic, readonly, getter=isConnected) BOOL connected;

/**
 *  Get the device firmware version.
 */
- (void)getFirmwareVersionWithCompletion:(void (^) (NSString *version, NSError *error))block;

@end
```
My jazzy command: 
jazzy --objc --clean --umbrella-header Header/Header.h --framework-root . --output jazzy/doc

**Comment by YinChangDao** [comment]
Hi @agentk I just wrote a test demo. The problem occurs, but I cannot upload the result picture, the server always remind me that it cannot process my picture file. 
```@interface Header : NSObject

/**
 *  Signal quality.
 */
typedef struct
{
    /**
     *  Signal quality range [0, 100].
     */
    uint8_t quality;
} SignalQualit;

/**
 *  The connectivity status of the device.
 */
@property (assign, nonatomic, readonly, getter=isConnected) BOOL connected;

/**
 *  Get the device firmware version.
 */
- (void)getFirmwareVersionWithCompletion:(void (^) (NSString *version, NSError *error))block;

@end```
My jazzy command: 
jazzy --objc --clean --umbrella-header Header/Header.h --framework-root . --output jazzy/doc

**Comment by YinChangDao** [comment]
Hi @agentk I just wrote a test demo. The problem occurs, but I cannot upload the result picture, the server always remind me that it cannot process my picture file. 
```
@interface Header : NSObject

/**
 *  Signal quality.
 */
typedef struct
{
    /**
     *  Signal quality range [0, 100].
     */
    uint8_t quality;
} SignalQualit;

/**
 *  The connectivity status of the device.
 */
@property (assign, nonatomic, readonly, getter=isConnected) BOOL connected;

/**
 *  Get the device firmware version.
 */
- (void)getFirmwareVersionWithCompletion:(void (^) (NSString *version, NSError *error))block;

@end
```
My jazzy command: 
jazzy --objc --clean --umbrella-header Header/Header.h --framework-root . --output jazzy/doc

**Comment by chenny408** [comment]
I'm having the same issue, is there a solution for this?

**Comment by XLE22** [comment]
Have you found out a solution because I'm in this situation as well, please ?

**Comment by steven-t-h** [comment]
@XLE22, @YinChangDao - I'm having this issue as well (working with @chenny408 ) have you found a solution or any suggestions?

**Comment by YinChangDao** [comment]
Sorry, I have no idea for this problem. I used [appledoc](https://github.com/tomaz/appledoc) instead.

**Comment by steven-t-h** [comment]
@YinChangDao thanks. I just built a custom theme and was able to remove the Swift references.

**Comment by YinChangDao** [comment]
@steven-t-h sounds great!

**Comment by vsanthanam** [comment]
Newer versions of jazzy support `--hide-declarations swift`
