### ISSUE TITLE
Group generated classes to be categorized 

### ISSUE THREAD

**Issue by hossamghareeb** [realm/jazzy#599]
After generating the documentation, under Classes I see a huge list of classes for my MVC. Is it possible to group them?, for example Model classes, View Controllers classes, .... etc. I already have groups for Enums and Extensions and don't know if its possible to add custom ones.

**Comment by orta** [comment]
You can use custom_categories in your `.jazzy.yml` file to move types in to thier own categories: e.g https://github.com/ReSwift/ReSwift/blob/master/.jazzy.json#L15

**Comment by agentk** [comment]
@hossamghareeb Have you had any progress trying custom categories?
For documentation maintenance, Jazzy provides good command line output to indicate when a class has changed and is missing from the .jazzy.json file.

**Comment by hossamghareeb** [comment]
@agentk I used custom_categories inside `.jazzy.yml` and I got the job done. It was pretty easy

**Comment by agentk** [comment]
I'm happy you found a solution. I'll close this for now. Feel free to reopen if it's still an issue. 👍
