### ISSUE TITLE
Using --abstract completely overwrites the existing abstract for non-custom categories.

### ISSUE THREAD

**Issue by thibaudrobelain** [realm/jazzy#600]
The README states "Using the --abstract options, extra markdown can be included after the heading of section overview pages. Think of it as a template include." 

Currently, it works fine if you're providing .md files for entirely new sections, but if you provide say "MyClass.md", it will overwrite the existing abstract for MyClass with the .md one instead of simply appending it at the end.

I'm assuming opening a PR to fix this doesn't change much because existing functionality for new sections isn't changed, it will just extend that functionality to auto-generated docs for classes, enums etc.
I'll open one in a bit!

**Comment by agentk** [comment]
That's a good catch @thibaudrobelain, I had only ever thought of it as a fix for custom sections not having an abstract. I think appending the existing content should be the correct behaviour. I don't see much point in adding an option to choose between behaviours.

I would be interested to see what anybody else using the --abstract option has run into too.

**Comment by johnfairh** [comment]
This was fixed a while ago by PR starting with the one linked above.
