### ISSUE TITLE
Failed to build Swift documentation even though build finished successfully

### ISSUE THREAD

**Issue by arikis** [realm/jazzy#606]
Software versions:

```
Xcode 7.3.1 (7D1014)
Jazzy 0.7.0
```

I'm building documentation for a Swift framework with following xcodebuild arguments in `.jazzy.yaml`:

``` yaml
xcodebuild_arguments: 
    - "-project"
    - "Overdrive/Overdrive.xcodeproj"
    - "-scheme"
    - "Overdrive macOS"
```

I also pass `--swift-version 2.2` and `--clean` arguments to `jazzy`. However, process fails and outputs following:

```
Using config file /Users/said/Developer/Overdrive/.jazzy.yaml
Running xcodebuild
Could not parse compiler arguments from `xcodebuild` output.
Please confirm that `xcodebuild` is building a Swift module.
Saved `xcodebuild` log file: /var/folders/b1/0yzf21m93fn6h7q6pwgx_xfh0000gn/T/xcodebuild-AD674B96-0257-4E9C-BCE4-883273D6F87F.log
Failed to generate documentation
/Library/Ruby/Gems/2.0.0/gems/jazzy-0.7.0/lib/jazzy/executable.rb:36:in `execute_command': /Library/Ruby/Gems/2.0.0/gems/jazzy-0.7.0/lib/jazzy/SourceKitten/bin/sourcekitten ["doc", "--", "-project", "Overdrive/Overdrive.xcodeproj", "-scheme", "Overdrive\\ macOS"] (RuntimeError)

Running xcodebuild

Could not parse compiler arguments from `xcodebuild` output.

Please confirm that `xcodebuild` is building a Swift module.
```

What is strange is that build finishes successfully, judging by the `.log` file from the `xcodebuild` output. 
[Link to the Gist](https://gist.github.com/arikis/75a59b506e94837987664d064124d79a).

But, if I run `jazzy` inside framework root folder without `xcodebuild_arguments`, documentation is generated successfully.
## Steps to reproduce:
1. Create empty dynamic iOS framework (`AnyFramework`)
2. Change default scheme name to `AnyFramework iOS` (with space)
3. Write `.jazzy.yaml`:

``` yaml
xcodebuild_arguments: 
    - "-project"
    - "AnyFramework/AnyFramework.xcodeproj"
    - "-scheme"
    - "AnyFramework iOS"
```
1. Run `jazzy` without any arguments.

**Comment by agentk** [comment]
It looks like sourcekitten is being run from the directory jazzy is run from. Which would be the correct behaviour. How is sourcekitten supposed to know that you are not in the folder with the xcodeproj?

The way I've been handling it with ReSwift (and my preferred way of building docs) is just with a build script that changes to the folder containing xcodeproj first, then popping at the end.

Ie,
```bash
pushd AnyFramework
jazzy
popd
```
