### ISSUE TITLE
Feature request: Support Swift Markdown documentation syntax with Objective-C and C++ code

### ISSUE THREAD

**Issue by marioarbras** [realm/jazzy#611]
It would be interesting if we could use Swift Markdown documentation syntax with Objective-C and C++ code, assuming that the code can be compiled with Clang.

**Comment by istx25** [comment]
Hi @marioarbras. We don't currently have the bandwidth to implement this ourselves. We'd be happy to review a PR if you're open to submitting one. Cheers!

**Comment by johnfairh** [comment]
Old issue cleanup: this works for ObjC, C++ #1255.
