### ISSUE TITLE
Multiple markdowns support

### ISSUE THREAD

**Issue by vnramachandra** [realm/jazzy#613]
Hi Jazzy Team,

Could you please brief me about how to use multiple markdown files while creating docs?

I have multiple markdown .md files and I would want jazzy to generate seperate HTML files for each markdown. In current project we are using below option,

```
  --documentation ../Markdown/*.md
```

If we keep two markdown files under folder, it picks up the only one file instead of both.

   is this possible and available? Please do let me know. I also looked into issue #523 and #556 , but it's not helping my case.

Thanks,
Ramachandra V N.

**Comment by vnramachandra** [comment]
Hi Jazzy team,

Any update on this?

Thanks,
Ramachandra V N.

**Comment by vnramachandra** [comment]
For your reference, I am here by attaching sample for further details. Please do let me know If I could do anything to troubleshoot this issue and also let me know about how to read multiple markdown files support.
[TestApplication.zip](https://github.com/realm/jazzy/files/406901/TestApplication.zip)

**Comment by vnramachandra** [comment]
Any progress on this? I have provided sample code as well. Thank you.

**Comment by istx25** [comment]
Hi @vnramachandra! Thanks for submitting this issue and providing a test project. My apologies that no one has responded to you until now. I'll read over everything you've provided and respond as soon as I can with more information and assistance.

**Comment by vnramachandra** [comment]
@istx25 Thank you. Will be looking forward to hear from you.

**Comment by shahdhiren** [comment]
Any update on this? I am also looking to include multiple MD files in particular order. Is there a support in jazzy?

**Comment by johnfairh** [comment]
Closing: OP needed to quote the CLI to avoid shell glob expansion; use `custom_categories` to customise doc order.
