### ISSUE TITLE
How to document the parameters like response: Response<AnyObject, NSError> etc?

### ISSUE THREAD

**Issue by riksof-arqam** [realm/jazzy#615]
How to document the parameters of the following functions?

1.
 /// - Parameter response: Response<AnyObject, NSError>
func myFunction(response: Response<AnyObject, NSError>) {
       // function body
}

2.
func search(searchTerm: String, searchCategory: String, callback: (Response<AnyObject, NSError>) -> Void ) {
        Alamofire.request(.GET, Constants.apiSearchUrl, parameters: ["searchTerm": searchTerm, "searchCategory": searchCategory])
            .validate()
            .responseJSON { response in
                callback(response)
        }
    }

**Comment by istx25** [comment]
Hi @riksof-arqam! Thanks for reaching out. My apologies that no one responded to your support request until now. I've added your request to our backlog queue and I'll respond very soon with some more information. Please feel free to close the issue if help is no longer required or necessary.
