### ISSUE TITLE
How to fix "type_body_length" and "file_length"?

### ISSUE THREAD

**Issue by riksof-arqam** [realm/jazzy#616]
Warnings are as follows:

warning: Type Body Length Violation: Type body should span 200 lines or less excluding comments and whitespace: currently spans 203 lines (type_body_length)

 warning: File Line Length Violation: File should contain 400 lines or less: currently contains 420 (file_length)

**Comment by jpsim** [comment]
Pretty sure you meant to file this on the SwiftLint repo, no jazzy.
