### ISSUE TITLE
Separating UIViewControllers into its own group

### ISSUE THREAD

**Issue by ilandbt** [realm/jazzy#618]
Hi,
I creating an internal documentation for a team.
So i want them to be able to see the UIViewControllers in a separate group (like enums, classes, ect')
Is there a way to do this?

Thanks

**Comment by jpsim** [comment]
`custom_categories`

**Comment by ilandbt** [comment]
Thanks, 
Where can i find more information about custom_categories?

**Comment by jpsim** [comment]
There's some minimal documentation in the README: https://github.com/realm/jazzy/blob/master/README.md

The integration tests contains a project that uses custom categories: https://github.com/realm/jazzy-integration-specs/blob/master/misc_jazzy_features/before/.jazzy.yaml

And a GitHub search for `custom_categories filename:.jazzy.yaml` reveals many projects using jazzy with custom categories: https://github.com/search?utf8=%E2%9C%93&q=custom_categories+filename%3A.jazzy.yaml&type=Code&ref=searchresults

**Comment by liuxuan30** [comment]
@jpsim one more question, it seems like custom_categories does not support reg expression?
Let's say I have many classes with some prefix: some starts with Line, some starts with Bar.
I want to group them into Line Type and Bar Type,
```
custom_categories:
  name: Bar Type
     children:
     - Bar*
  name: Line Type
     children:
     - Line*
```
It won't have any effect. Instead, I have manually list all the classes. Am I wrong?

**Comment by istx25** [comment]
Hi @liuxuan30. We'd be happy to help you with this but to respect separation of concerns, would you be able to file a new issue for this specific question (since it's quite different). Closing this one since @jpsim answered @ilandbt's original question.

**Comment by liuxuan30** [comment]
OK, will do.

**Comment by istx25** [comment]
@liuxuan30, replied on there. from my limited understanding, but maybe @jpsim will have more to say.

**Comment by jpsim** [comment]
I don't think `custom_categories` supports globbing or wildcard expansion, or anything like that, but I could be wrong and I'm too lazy to look up the implementation, and apparently so's everyone else since no one's replied.

**Comment by medcad-dev** [comment]
Hi,
Is there a tutorial or a process on how to add custom categories. I keep seeing .jazzy.yaml files in sample projects everywhere on GitHub, however I do not know how to generate that file.. additionally, once the file is made, do you just save the file in your Xcode project directory and jazzy will take care of the rest or do I have to run a special command in terminal?

Thanks!
