### ISSUE TITLE
some extensions render as undocumented

### ISSUE THREAD

**Issue by aramikg** [realm/jazzy#620]
I have a few extension that are being generated just fine but then also some that are being generated as undocumented.

Undocumented extensions:
- UIBarItem
- UIBarButtonItem
- UIViewController

sourcekitten 0.13 and 0.7 version of jazzy

**Comment by seanoshea** [comment]
I'm running into this exact same issue with http://cocoadocs.org/docsets/FuzzyMatchingSwift/0.1.0/Extensions/_ArrayType.html. Source code is available at https://github.com/seanoshea/FuzzyMatchingSwift/blob/develop/FuzzyMatchingSwift/Classes/FuzzyMatching.swift#L37 using the `0.7.0` version of `jazzy`

**Comment by istx25** [comment]
Hi @aramikg and @seanoshea. Thanks for submitting this issue (and adding some additional context, @seanoshea). I'll review all of this and see what we can do.

**Comment by jpsim** [comment]
Fixed in #819
