### ISSUE TITLE
Is there any guide that can take jazzy docs into Dash docset easily?

### ISSUE THREAD

**Issue by liuxuan30** [realm/jazzy#621]
Hi there,
Great project. Now I generated the docs using jazzy, and want to put it in Dash docset, so other people can download it via dash. However I don't see a clear steps doing so. 

I just want to follow what Realm did for the dash here:https://realm.io/docs/swift/latest/api/

How can I do it like that? 

To be more specific, I am stucking at 

```
12.4. Create the SQLite Index
12.5. Populate the SQLite Index, expecially "You need to create a script (or application or whatever) "
```

and further from Docset Generation Guide
Does jazzy support create and populate the SQLite index?

**Comment by segiddins** [comment]
jazzy already should be creating a dash docket for you

**Comment by liuxuan30** [comment]
@segiddins I don't see it under docs, where is it? Or what parameter should I use?

**Comment by jpsim** [comment]
it's generated in `docs/docsets`, for example: https://github.com/realm/jazzy-integration-specs/tree/master/misc_jazzy_features/after/docs/docsets

**Comment by liuxuan30** [comment]
where.. I do see the docsets folder, but it's empty

**Comment by jpsim** [comment]
That's not normal. Please share steps to reproduce your issue and we'll look into it to determine why the docset isn't generated.

**Comment by liuxuan30** [comment]
simply download https://github.com/danielgindi/Charts, go to ChartsRealm folder and type jazzy.

I do see some warnings, like:
```
A compile error prevented RealmRadarData.init(results:xValueField:dataSets:) from receiving a unique USR. Documentation may be incomplete. Please check for compile errors by running `xcodebuild `.
building site
jam out ♪♫ to your fresh new docs in `docs`
```
But I was able to see the html files

**Comment by agentk** [comment]
@liuxuan30 It may not be able to infer the target URL for the docset.

Are you specifying the `--root-url`, `--dash_url` and `--module` when calling `jazzy`?

**Comment by liuxuan30** [comment]
@agentk I don't specify anything, do I need to specify --dash_url?

**Comment by agentk** [comment]
`dash_url` is mandatory. If you have a look at the templates, they don't output a dash link unless `dash_url` is passed to the template.
https://github.com/realm/jazzy/blob/master/lib/jazzy/themes/apple/templates/header.mustache#L7-L9

**Comment by liuxuan30** [comment]
I just did a quick test, if I specify dash_url with some random url, the docset folder is still empty.

**Comment by ds1239** [comment]
I'm having this issue too.

**Comment by MrAlek** [comment]
Struggling a bit here too. I'm running `jazzy` without any params in a Swift 2.3 framework project and get HTML docs but the docset folder is empty.

**Comment by jpsim** [comment]
Hi all, without full steps to reproduce the issues you're running into, it's difficult for us to say what you may be missing in order to produce Dash docsets.

Short of having those details, I can point you to the integration specs that generate the docs for a variety of projects: https://github.com/realm/jazzy/blob/master/spec/integration_spec.rb

To pick one example, the [misc_jazzy_features spec](https://github.com/realm/jazzy/blob/master/spec/integration_spec.rb#L208) is the simplest case, which builds the [MiscJazzyFeatures Xcode project](https://github.com/realm/jazzy-integration-specs/tree/master/misc_jazzy_features/before) and generates the docset at under the [docs/docsets](https://github.com/realm/jazzy-integration-specs/tree/master/misc_jazzy_features/after/docs/docsets) directory.

**Comment by MrAlek** [comment]
Our issue is solved at least. It magically started working as we added more stuff into our framework. Haven't had a single problem since.

**Comment by liuxuan30** [comment]
@jpsim As I said earlier:
```


simply download https://github.com/danielgindi/Charts, go to ChartsRealm folder and type jazzy.

I do see some warnings, like:

A compile error prevented RealmRadarData.init(results:xValueField:dataSets:) from receiving a unique USR. Documentation may be incomplete. Please check for compile errors by running `xcodebuild `.
building site
jam out ♪♫ to your fresh new docs in `docs`

But I was able to see the html files

I just did a quick test, if I specify dash_url with some random url, the docset folder is still empty.
@agentk maybe you misunderstood my issue, it is said the jazzy can help produce a .docset, however the folder is empty.
```

**Comment by jpsim** [comment]
Thanks, I had missed that. Although there's no `ChartsRealm` folder.

Trying to adapt the steps to generate docs, the docset was properly generated.

Here are the steps I've taken to try to reproduce this:

```shell
$ jazzy --version
jazzy version: 0.7.3
$ git clone git@github.com:danielgindi/Charts.git
$ cd Charts
$ jazzy
[doc generation output]
$ ls docs/docsets
Charts.docset Charts.tgz
```

**Comment by hollanderbart** [comment]
I also experience this issue with several internal projects. The folders stays empty and am using the default build instruction. Can I get insight in some jazzy logging? `xcodebuild` runs fine and HTML looks fine

**Comment by johnfairh** [comment]
Closing in favour of #921.  Cause was probably lack of `--module`.
