### ISSUE TITLE
Can't generate docs given a project file

### ISSUE THREAD

**Issue by liuxuan30** [realm/jazzy#622]
I want to create docs for https://github.com/liuxuan30/Charts/tree/APIDocs/

The structure looks like:
root
____|ChartsRealm/ChartsRealm.xcodeproj
____|Charts/Charts.xcodeproj

I was able to go to the sub ChartsRealm folder and run jazzy, it produces docs perfectly;

However, if I run jazzy at root folder, with below command:
`jazzy --xcodebuild-arguments -project,ChartsRealm/ChartsRealm.xcodeproj`
It failed, saying 

```
Could not parse compiler arguments from `xcodebuild` output.

Please confirm that `xcodebuild` is building a Swift module.

Saved `xcodebuild` log file: /var/folders/8v/6dg7d6mx2850sv1gp8ts9thm0000gn/T/xcodebuild-4D7FE747-3169-471B-82CB-C2708B18406E.log
```

Then I take look at the log, it shows:

```
/Users/xuanliu/Development/GitHub/ios-charts/ChartsRealm/Classes/Data/RealmLineRadarDataSet.swift:18:8: error: no such module 'Charts'
 85 import Charts
 86        ^
 87 
 88 ** BUILD FAILED **
 89 
 90 
 91 The following build commands failed:
 92     CompileSwift normal arm64 /Users/xuanliu/Development/GitHub/ios-charts/ChartsRealm/Classes/Data/RealmLineRadarDataSet.swift
 93     CompileSwift normal arm64 /Users/xuanliu/Development/GitHub/ios-charts/ChartsRealm/Classes/Data/RealmPieDataSet.swift
 94     CompileSwift normal arm64 /Users/xuanliu/Development/GitHub/ios-charts/ChartsRealm/Classes/Data/RealmLineDataSet.swift
 95     CompileSwift normal arm64 /Users/xuanliu/Development/GitHub/ios-charts/ChartsRealm/Classes/Utils/RealmChartUtils.swift
 96     CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
 97 (5 failures)                                            
```

I am not sure why it failed? How could I fix it? Thanks

**Comment by jpsim** [comment]
I haven't had the chance to look into this, or to confirm the bug, but labelled it as such so I can reprioritize when I have some time.

**Comment by istx25** [comment]
Hi @liuxuan30! Thanks for filing this issue. I'll look into the problem more and see what we can do.

**Comment by johnfairh** [comment]
Closing, old: some kind of $PWD-relative search path.   jazzy's `--source-directory` solves this.

**Comment by atif-khan** [comment]
Hi, I am having the same issue. If someone has found the solution then please share.

**Comment by johnfairh** [comment]
@atif-khan please open a new issue with details of your problem and the versions of the software you are using.
