### ISSUE TITLE
Support for generating docs that contains several projects?

### ISSUE THREAD

**Issue by liuxuan30** [realm/jazzy#623]
Please take a look at https://github.com/danielgindi/Charts which I am trying to add docs
This project contains several folders like Charts, ChartsDemo, ChartsRealm, and each sub folder contains a Xcode project.

The exception is, ChartsDemo Xcode project will include Charts and ChartsRealm Xcode project.

I tried to generate jazzy doc under ChartsDemo, which I guess could include both Charts and ChartsRealm docs. However, it just has Charts doc. I don't know why ChartsRealm is missing.

So.. 
1. Why ChartsRealm is missing? Is there anything I missed? Or it's a bug? Not supported?
2. is it possible to generate a single jazzy doc for some of the sub folders/Xcode project? e.g. I want to generate a jazzy doc for Charts and ChartsRealm, excluding ChartsDemo.

**Comment by istx25** [comment]
Hi @liuxuan30. Thank you for submitting your question. My apologies that no one has responded to your support request until now. I'm not quite sure why ChartsRealm is missing but from my understanding, multi-Xcode project docs are currently unsupported. I'll do some more digging through.

**Comment by liuxuan30** [comment]
Thanks!

**Comment by jpsim** [comment]
It doesn't look like the `ChartsRealm` directory exists. Perhaps it was removed? Could you update this thread with the latest information? Thanks!

**Comment by jpsim** [comment]
Also see my comment in https://github.com/realm/jazzy/issues/621#issuecomment-265557247 for some related details.

**Comment by liuxuan30** [comment]
@jpsim it's there:
<img width="412" alt="image" src="https://cloud.githubusercontent.com/assets/4375169/20995197/645e0bac-bd30-11e6-8f34-748145d7af11.png">

**Comment by jpsim** [comment]
No, it doesn't appear to be there: https://github.com/danielgindi/Charts

![image](https://cloud.githubusercontent.com/assets/474794/20996371/03339fdc-bcb2-11e6-994c-68f4bbaa122b.png)

Is there a previous release I should be checking out?

**Comment by liuxuan30** [comment]
Sorry, it seems like it has been a while after I ask this and the structure changed.
However, please use ChartsDemo or ChartsDemo-OSX as example.

The idea is the same, Charts is one project along with two other projects like ChartsDemo-OSX, and we want to generate doc for all of them, not just Charts.

**Comment by jpsim** [comment]
Reading back the initial comment in this thread, you're asking for functionality that doesn't exist in Jazzy currently.

Today, jazzy only builds docs for a single module at a time. However, you can run `sourcekitten doc` multiple times and merge their output json, and pass that result to `jazzy --sourcekitten-sourcefile` to do this yourself. See https://github.com/realm/jazzy/issues/564#issuecomment-265289632

**Comment by liuxuan30** [comment]
OK, thanks!
