### ISSUE TITLE
Problem generating docs for App and Watch Extension

### ISSUE THREAD

**Issue by csauvage** [realm/jazzy#625]
Hi everybody & maintainers. 

I'm stuck in a problem while generating docs for my project : 

Here is the project structure : 
- **Project**
  - _AppConseiller_
- **Targets**
  - _AppConseiller_
  - _AppConseillerTest_
  - _AppConseillerUITest_
  - _AppWatchConseiller_
  - _AppWatchConseiller Extension_

I'm trying to generating docs for the apps but when I'm running `$ jazzy`
It runs successfully but it generate only the _AppWatchConseiller Extension_ docs, and I want both _AppWatchConseiller Extension_ **AND**  _AppConseiller_. 

But when I try `$ jazzy -x '--module-name,AppConseiller,-project,AppConseiller.xcodeproj’`
(following what I see on #504) I get an error

```
Could not parse compiler arguments from 'xcodebuild' output.
Please confirm that 'xcodebuild' is building a Swift module.
```

Thanks for your help.

**Comment by istx25** [comment]
Hi @csauvage. Thanks for reaching out. My apologies that no one has responded to your support request until now. I'll do some digging and come back to you with what I've found. In the meantime, I'd appreciate it if you could share any more info or reproduction steps (and since it's been a while), what you did in the meantime as a workaround.

**Comment by istx25** [comment]
Please feel free to comment as well if help is no longer needed or necessary. We'll assume that it is.

**Comment by csauvage** [comment]
Didn’t find any right know

**Comment by csauvage** [comment]
At the beginning it was for one of my client, the project is finished now (without the docs) nevertheless I'd love to find a solution currently working on a similar project (multiple targets, need to create docs)

**Comment by rlaguilar** [comment]
Hi @istx25. I'm having the same issue here. When I try to generate the docs for [this project](https://github.com/rlaguilar/doc-test), it doesn't generate the docs for the iOS app. I'm using the command:

`jazzy --min-acl internal`

**Comment by johnfairh** [comment]
Closing, inactive -- see #564, #862 for combining multiple modules (eg. app + extension).
