### ISSUE TITLE
xcodebuild successful, but no docs

### ISSUE THREAD

**Issue by preraksola** [realm/jazzy#627]
When I run the command `jazzy` from my project's root directory, I get the error `Could not parse compiler arguments from`xcodebuild`output.` in the console. But in the log file, I could see that xcodebuild command was executed sucessfully.

I am using following config in my `.jazzy.yaml` file:

```
clean: true
sdk: iphone
swift_version: 2.2
min_acl: internal
skip_undocumented: true
author: 'Prerak Sola'
copyright: 'Copyright © 2016 xxx. All rights reserved.'
theme: fullwidth
xcodebuild_arguments: [-workspace,'xxx yyy.xcworkspace',-scheme,'xxx yyy']
hide_documentation_coverage: true
head: '<h1><center> xxx - iOS Application</center> </h1>'
module_version: '1.0'
```

[xcodebuild-4AB3D10E-97C4-48B0-A4E0-E61FEEC9E73A copy.txt](https://github.com/realm/jazzy/files/394136/xcodebuild-4AB3D10E-97C4-48B0-A4E0-E61FEEC9E73A.copy.txt)

**Comment by istx25** [comment]
Hi @preraksola! Thanks for reaching out. My apologies that no one has responded to your support request until now. I will review what you've shared and come up with any follow-ups.

**Comment by johnfairh** [comment]
Closing, old, missing --module causing confusion.
