### ISSUE TITLE
Swift documentation can not contain bold code

### ISSUE THREAD

**Issue by blochberger** [realm/jazzy#631]
I try to use the following markdown in a Swift documentation comment:

```
The value is **`nil`** if …
```

Which will render as:

> The value is if …

I would expect it to be rendered as:

> The value is **`nil`** if …

So there is no way to render a text bold and monospaced at the same time.

This works in a `README.md` used as abstract.

**Comment by jpsim** [comment]
That's pretty odd... Maybe [redcarpet](https://github.com/vmg/redcarpet) is to blame here too? Not sure.

**Comment by johnfairh** [comment]
I bet this was in a returns: callout -- which swallows attempts at bold text.  Same as #476 really.

**Comment by blochberger** [comment]
I just tried it in the general description of the method as well as in a `returns` callout and it renders as expected. So it might have been fixed already. I used version 0.8.1.

**Comment by johnfairh** [comment]
Yes thanks for checking - was fixed in 0.8.1 via #795.
