### ISSUE TITLE
Jazzy won't parse symbols that have the @available attribute.

### ISSUE THREAD

**Issue by AndyIbanez** [realm/jazzy#633]
It looks like Jazzy cannot currently parse symbols that have the @available attribute.

I currently have something like this:

``` Swift
/// This is some epically
/// long documentation
@available(*, introduced: 1.0) public class Anilist {}
```

Jazzy will treat it as an error and not process it. Removing the @available attribute will let it generate the documentation fine.

**Comment by istx25** [comment]
We'll look into this. Thanks for filing this issue, @AndyIbanez.

**Comment by jpsim** [comment]
This was fixed in SourceKitten (at some point). I don't know if the version currently used by jazzy includes the fix or not.

**Comment by istx25** [comment]
So we should be able to close this once https://github.com/realm/jazzy/pull/679 is merged in.

**Comment by istx25** [comment]
Just to be safe.

**Comment by jpsim** [comment]
As long as we can confirm it resolves @AndyIbanez's case, yes.

**Comment by johnfairh** [comment]
This works in latest.
