### ISSUE TITLE
Can jazzy generate all files include alamofire,chart and myproject.xcodeproj into one display html?

### ISSUE THREAD

**Issue by kh4iri** [realm/jazzy#634]
Hello,
I have a problem. I try using jazzy to generate html of all files that include alamofire, chart and myproject into one html display. I try using code `jazzy`--min-acl-internal` but display on html show about alamofire and other files and other project do not show in html. How can i generate all files into one html display output like doxygen?

Sorry My English Is Bad.

**Comment by istx25** [comment]
Your English is great. Don't sweat it. 😸 

Thanks for reaching out, @kh4iri. My apologies that no one has responded to your support request until now. Regarding your question, Jazzy currently does not support the functionality you're after. It's something we hope to be able to do in the future but you're out of luck as of right now! 😕
