### ISSUE TITLE
Docs for methods include parameters and returns asides in the abstract, and once again after that

### ISSUE THREAD

**Issue by samsonjs** [realm/jazzy#637]
version 0.7.0

A screenshot probably describes this best:
![example output](https://samhuri.net/f/jazzy.png)

You can see that the docs for `a()` says: "Does stuff - x: foo - y: bar - Returns: something" ... if I have an empty line in between it's formatted as a nice aside, but still duplicated. It looks like there were some changes around this code last summer: https://github.com/realm/jazzy/commit/34796f3d0ea83bfb846a8d1933308c730b57aa74 and https://github.com/realm/jazzy/issues/282

It seems like maybe SourceKitten should have a nicer format for this instead of massaging the abstract in jazzy itself, but I'm not really sure what the intent in SourceKitten is there. I'm happy to try and help with this one if anyone can help point me in the right direction for how you think it should be fixed.

**Comment by istx25** [comment]
Hi @samsonjs. Thanks for filing this issue. My apologies that no one has responded to your support request until now. Unfortunately the image you uploaded before won't load for me. Would you be able to repost it? I will be closing in 2 weeks if there's no further activity.

**Comment by jpsim** [comment]
This is a duplicate of (several?) other issues tracking adding support for non-standard Markdown.

**Comment by istx25** [comment]
Since you have a little more familiarity with the issues, do you mind linking to some of those duplicates and then we can close this issue? No point keeping several open. We should consolidate the info and feature requests and use one as a tracker, imo.

**Comment by jpsim** [comment]
Sorry I haven't found the time to dig around for this yet. It's still on my todo list.

**Comment by samsonjs** [comment]
Sorry for the dead image link up there. Just for reference [here's what I'm talking about](http://static.samhuri.net/jazzy.png). The special Markdown sections are duplicated in the body text so you end up with the same info repeated for each method, like parameters, return value, complexity, etc.

**Comment by SDGGiesbrecht** [comment]
@samsonjs, a similar issue involving parameters and returns has now been fixed. However, I’m not sure what you mean by “complexity, etc.” being duplicated. (I only see complexity once in your image).

Please run the development version of Jazzy to see if there are any problems left. To do so, simply run the following commands inside the same folder where you would normally run `jazzy`.

```
git clone https://github.com/realm/jazzy
cd jazzy
bundle install
cd ..
jazzy/bin/jazzy
rm -rf jazzy

```

If you normally pass in arguments (e.g. `jazzy --clean`), those arguments can be added to the end of the second last line.

Note: The above script cleans up after itself.

**Comment by samsonjs** [comment]
@SDGGiesbrecht Correct you are are about complexity not being duplicated, my mistake. And the current development version is behaving as expected for returns and params. Thanks!
