### ISSUE TITLE
Should using a podspec automatically call 'install'?

### ISSUE THREAD

**Issue by seivan** [realm/jazzy#638]
I'd like to use the podspec for share content like licence, git_url and etc. Not necessarily cloning and trying to generate a documentation for it.

Is there a way to disable that, if not, would that be interesting to have?

**Comment by segiddins** [comment]
It should just pull metadata from the podspec if the podspec is in the current directory and you don't specify the `--podspec` option

**Comment by seivan** [comment]
@segiddins What if it isn't in the current directory? It's the json format, not ruby. 
I can move things around, so this issue could be closed but why is installing the default behaviour, it wasn't expected on my end.

**Comment by segiddins** [comment]
Installing is only done when using the `--podspec` option

**Comment by seivan** [comment]
@segiddins specifying the podspec path is also using ```--podspec```
