### ISSUE TITLE
Jazzy should ignore properties annotated with NS_UNAVAILABLE

### ISSUE THREAD

**Issue by skyline75489** [realm/jazzy#639]
Sometimes we don't want to expose certains methods and using `NS_UNAVAILABLE` like this:

``` objective-c
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)new NS_UNAVAILABLE;
```

It's clear that we don't want these methods to be available to users. Yet jazzy still marks these as `Undocumented`.

**Comment by istx25** [comment]
We've added this issue to our backlog queue. Feel free to submit a PR with the fix.

**Comment by jpsim** [comment]
This would be a great feature. Until that's supported, you can document with `/// :nodoc:` to omit the docs.

**Comment by johnfairh** [comment]
Latest jazzy clearly calls out unsupported methods as such in the docs -- I think this is the right behavior, users may want to know/authors may want to document what happened to them.  Using `:nodoc:` to suppress entirely is also viable.

**Comment by scosman** [comment]
Note for others finding their way here: `:nodoc:` hides the nice treatment of "clearly calls out unsupported methods". Better to put a short comment explaining why it's `NS_UNAVAILABLE` if it's a method the user expects (init, etc).
