### ISSUE TITLE
Display full hierarchy in side navigation

### ISSUE THREAD

**Issue by jpsim** [realm/jazzy#64]
Only top-level tokens are displayed in the side navigation. Nested tokens are only accessible in its parent's HTML file.

**Comment by jpsim** [comment]
@yoshyosh do you think you could help out with the front-end web portion of this? My skills are definitely lacking in that area, and you're a pro!

**Comment by jpsim** [comment]
This is now done, but just up to one level of nesting.

**Comment by istx25** [comment]
I think it's fair to close this issue. We can re-open if necessary though.
