### ISSUE TITLE
Jazzy overgrabs for headers

### ISSUE THREAD

**Issue by colincornaby** [realm/jazzy#641]
In my project Jazzy is using pragma marks and comments for previous sections for decorating headers in the class page. You can see the issue with some Realm's documentation here.
https://realm.io/docs/swift/latest/api/Classes.html

Is there a workaround for this issue?

**Comment by istx25** [comment]
Hi @colincornaby. Thank you for filing this issue. My apologies that no one responded to this support request until now. I will do some digging and come back with what I find. I would appreciate it if you'd be willing to share any workarounds you found (since this issue has aged a bit).

**Comment by johnfairh** [comment]
The 'FIXME' heading was a bug, fixed in master via #947.  The other headings look to be as-designed; #857 is to provide some kind of option to drop some/all of these headings.
