### ISSUE TITLE
links to referenced objects

### ISSUE THREAD

**Issue by poborin** [realm/jazzy#642]
Is it possible to reference objects from external frameworks in Objective-C?

Lets say I have a framework **A**, that depends on framework **B**. Dependency management leveraged by [Carthage](https://github.com/Carthage/Carthage). My class **Foo** from framework **A** inherits protocol **Bar** from framework **B**. e.g.

```ObjectiveC
/**
*  Foo implements Bar
*/
@interface Foo : NSObject <Bar>
```

The generated doc contains **Foo** description only without a link to the **Bar** framework docs.
> @interface Foo

```
Foo implements Bar
```

**Comment by poborin** [comment]
It actually referencing every object. My problem was I haven't passed correct xcodebuild arguments, thus jazzy could not find referenced objects

**Comment by JanC** [comment]
@poborin how do you pass "the correct xcodebuild arguments" ? I have the same issue

**Comment by pkrmf** [comment]
@poborin would you mind adding the arguments that help you with linking to objects referenced in another framework?
