### ISSUE TITLE
using jazzy when podpsec includes dependencies from a private spec repo

### ISSUE THREAD

**Issue by aliak00** [realm/jazzy#650]
I'm having trouble figuring out how to tell jazzy where the pods are. Is there a config option I'm not seeing somewhere? I get this error when I run jazzy:

```
Using config file /Users/aliak/spt/rashomon/ios-sdk/.jazzy.yaml
Analyzing dependencies
Fetching podspec for `Rashomon` from `/Users/aliak/spt/rashomon/ios-sdk`
/Users/aliak/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/resolver.rb:442:in `handle_resolver_error': [!] Unable to find a specification for `sch-event-sdk-ios (~> 3.6.5)` depended upon by `Rashomon` (Pod::Informative)
    from /Users/aliak/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/resolver.rb:65:in `rescue in resolve'
    from /Users/aliak/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/resolver.rb:57:in `resolve'
    from /Users/aliak/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/analyzer.rb:563:in `block in resolve_dependencies'
    from /Users/aliak/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/user_interface.rb:63:in `section'
    from /Users/aliak/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/analyzer.rb:561:in `resolve_dependencies'
    from /Users/aliak/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/analyzer.rb:76:in `analyze'
    from /Users/aliak/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:227:in `analyze'
    from /Users/aliak/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:151:in `block in resolve_dependencies'
    from /Users/aliak/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/user_interface.rb:63:in `section'
    from /Users/aliak/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:150:in `resolve_dependencies'
    from /Users/aliak/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:114:in `install!'
    from /Users/aliak/.rvm/gems/ruby-2.3.0/gems/jazzy-0.7.0/lib/jazzy/podspec_documenter.rb:18:in `block in sourcekitten_output'
    from /Users/aliak/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/config.rb:41:in `with_changes'
    from /Users/aliak/.rvm/gems/ruby-2.3.0/gems/jazzy-0.7.0/lib/jazzy/podspec_documenter.rb:15:in `sourcekitten_output'
    from /Users/aliak/.rvm/gems/ruby-2.3.0/gems/jazzy-0.7.0/lib/jazzy/doc_builder.rb:60:in `build'
    from /Users/aliak/.rvm/gems/ruby-2.3.0/gems/jazzy-0.7.0/bin/jazzy:15:in `<top (required)>'
    from /Users/aliak/.rvm/gems/ruby-2.3.0/bin/jazzy:23:in `load'
    from /Users/aliak/.rvm/gems/ruby-2.3.0/bin/jazzy:23:in `<main>'
    from /Users/aliak/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
    from /Users/aliak/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by Palleas** [comment]
I just ran into this exact issue. Is this something I can help with? I would only need a small nudge toward the right direction in the source code 😁

**Comment by istx25** [comment]
Hi there @aliak00 and @Palleas. Is this something you're experiencing on the new version as well?

**Comment by aliak00** [comment]
Hey @istx25 Yeah, updated to 0.7.2 and tried again. Same thing. Cannot find private specs. Which does make sense because there's no way to tell cocoa pods (through jazzy) where the specs are located. When you run pod repo lint you can specify those private spec with the `--sources` option. But I haven't figured out how to set them through jazzy yet. Or maybe there's a config file for cocoa pods way, but I haven't found that either.

**Comment by istx25** [comment]
Hi @aliak00! Thanks for double checking. I'll do some investigation and come back with what I find.

**Comment by sealz** [comment]
Having the same (similar?) issue here. I've got a cocoapod that is in a private repo that has a dependency on yet another cocoapod in the same private repo. When I try and reference the podspec using the `--podspec` flag it complains that it cannot find the specification for the private repo dependency.

Something along the lines of the `--sources` flag that @aliak00 mentioned in a previous comment would work and maintain some consistency with the rest of the tooling (e.g. Cocoapods.)

**Comment by dougdoe** [comment]
I also just found this thread and am having the same issue.

@aliak00, were you able to workaround this problem? If so, can you share your solution?

**Comment by sealz** [comment]
My workaround was to not use the `--podspec` argument and instead use the `--xcodebuild-arguments` flag with the same arguments I would use to get the project to build when using `xcodebuild`. I'm not exactly sure what the tradeoff here is, but it seems to build and generate the documentation as expected.

My `.jazzy.yaml` looks like this:

```
---
min_acl: public
github_url: https://github.com/example/example.git
readme: docs/README.md
author: Author
clean:
output: docs/source
module: MyLibrary
xcodebuild_arguments: ["-workspace","MyLibrary.xcworkspace","-scheme","MyLibrary","-sdk","iphonesimulator"]
```

**Comment by mgrebenets** [comment]
Is the `--podspec FILEPATH` used purely for building or also changes the way documentation is generated?

We commit our `Pods` directory with the project, so running `pod install` is not an issue for us.

I'm still curious though if I get some cool documentation features if `jazzy` is able to follow the URLs to dependency pods.

**Comment by jpsim** [comment]
Specifying a podspec will automatically populate some of the other values (e.g. author) and it'll also generate docs for all supported platforms of the podspec, merging them together.

But it won't create links to external docs, or document modules other than the one you're documenting. We're tracking linking to external docs in #13.

**Comment by bonebox** [comment]
Has any progress been made toward a solution for private CocoaPod repos?  Noticed today that this problem still exists.

**Comment by ForelaxX** [comment]
I met the same issue, I want to use jazzy inside my company, but all the pod is private, so I can't use podspec option. @jpsim will you make some fix to this issue?

**Comment by johnfairh** [comment]
First thing is to check if you can avoid `--podspec` -- see sealz's workaround above.

**Comment by ForelaxX** [comment]
I found out that `--podspec` can only use for swift project, so for now I can't use this option. >.<

**Comment by suxinde2009** [comment]
@sealz dude, your apporach works good, thanks for sharing your workaround

**Comment by jgongo** [comment]
No progress two years later? 😢

**Comment by jpsim** [comment]
Correct, no one has built support for generating Objective-C docs for a podspec. @jgongo sounds like you might be interested in building this?

**Comment by ptraca** [comment]
Another vote for this one.

**Comment by Jon889** [comment]
Another vote here too :)

**Comment by EugeneNaloiko** [comment]
One more vote!

**Comment by robertofrontado** [comment]
Another vote!

**Comment by johnfairh** [comment]
I wrote this in one of the linked issues, to repeat it here: if someone wants to implement this then one way would be to allow the user to provide some lines in the jazzy config file for inclusion in the `Podfile` that gets generated internally - eg. `source wherever`.  Can offer some tips on how to get started but you will need to be up for poking around the cocoapods Ruby api.
