### ISSUE TITLE
Comma in Xcode Build Arguments is treated as a delimeter

### ISSUE THREAD

**Issue by bearclough** [realm/jazzy#651]
When using Jazzy with the following xcodebuild-arguments 

`jazzy -x -scheme,TestScheme,-configuration,TestSim,-destination,'platform=iOS Simulator,name=iPhone 6,OS=10.0'`

The issue is that the -destination flag is parsed as 'platform:iOS Simulator' and the rest of the destination string is passed as an xcodebuild-arguement.

I'de be happy to fix if you could point me in the right direction or I can go digging :).  Or if there's an escape character that can be used that I missed.

**Comment by istx25** [comment]
Hi @bearclough. Thanks for reaching out. I'm not sure where to start with this issue. I'll start digging but I'd love it if you could as well. I'll come back with whatever I find in a couple weeks!

**Comment by Utsira** [comment]
I've also hit this issue. I tried escaping the comma (eg `\,` `\\,`) but to no avail. There needs to be a way to escape the comma, or perhaps what is inside the single quotes should be treated as a literal.

**Comment by Utsira** [comment]
Wondering whether I can use the jazzy config file instead of the command line to work round this

**Comment by johnfairh** [comment]
Using the config file is the right workaround: the CLI-parsing library jazzy uses does not have an escape for its comma handling.

**Comment by hmlongco** [comment]
This still seems to be an issue.

```
jazzy -x -project,RxSwiftWidgets.xcodeproj,-scheme,RxSwiftWidgets-Package,-destination,"platform=iOS Simulator,name=iPhone Xr 13"
```

Attempting the above from the command line fails as the comma before name causes that parameter to be broken out separately.

```
theme: jekyll-theme-architect
xcodebuild_arguments: -project,RxSwiftWidgets.xcodeproj,-scheme,RxSwiftWidgets-Package,-destination,'platform=iOS Simulator,name=iPhone Xr 13'
```
Using the configuration file changes nothing. The comma before name is removed and name is treated as a second argument which breaks the xcode build. Tried single quotes, double quotes, backslash-comma, comma-comma, all to no avail.

**Comment by johnfairh** [comment]
I think the config file would go something like:
```yaml
xcodebuild_arguments:
    - "-project"
    - "RxSwiftWidgets.xcodeproj"
    - "-scheme"
    - "RxSwiftWidgets-Package"
    - "-destination"
    - "platform=iOS Simulator,name=iPhone Xr 13"
```

**Comment by smrfeld** [comment]
I still ran into this 2 years later. The arguments in the config file that work for me are:
```
swift_build_tool: "xcodebuild"

build_tool_arguments:
  - "-scheme"
  - "MyScheme"
  - "-destination"
  - "platform=iOS Simulator,name=iPhone 12 Pro"
  - "-sdk"
  - "iphonesimulator"
 ```

**Comment by renetik** [comment]
I **"fixed"** it by removing platform part

```
jazzy \
    --clean \
    --author Renetik \
    --author_url https://renetik.github.io \
    --source-host github \
    --source-host-url https://github.com/renetik/renetik-ios-layout \
    --module RenetikLayout \
    --swift-build-tool xcodebuild --build-tool-arguments -scheme,RenetikLayout,-sdk,iphonesimulator,-destination,"name=iPhone 12"
```
