### ISSUE TITLE
Swift 3.0, Xcode 8: jazzy generates empty docs

### ISSUE THREAD

**Issue by agordeev** [realm/jazzy#657]
jazzy version: **0.7.1**
Config file:

```
clean: true
sdk: iphone
#swift_version: 3.0
author: Andrey Gordeev
author_url: https://andreygordeev.com
module: DCKit
module_version: 1.0.6
copyright: "2014-present © Andrey Gordeev. See LICENSE for more details."
github_url: https://github.com/andrew8712/DCKit/
xcodebuild_arguments: [clean,build,-project,DCKitSample.xcodeproj,-scheme,DCKit]
```

I run `jazzy`, it outputs the following:

```
Using config file /Users/..../DCKit/.jazzy.yaml
Running xcodebuild
Parsing DCBaseButton.swift (1/18)
Parsing DCCircleView.swift (2/18)
Parsing DCPlaceholderTextView.swift (3/18)
Parsing DCBaseView.swift (4/18)
Parsing DCBorderedTextView.swift (5/18)
Parsing DCMandatoryEmailTextField.swift (6/18)
Parsing DCPickerTextField.swift (7/18)
Parsing DCHairlineView.swift (8/18)
Parsing DCBorderedView.swift (9/18)
Parsing DCBorderedButton.swift (10/18)
Parsing DCBaseTextField.swift (11/18)
Parsing DCBaseLabel.swift (12/18)
Parsing DCRoundedButton.swift (13/18)
Parsing DCDashedBorderedView.swift (14/18)
Parsing DCBaseTextView.swift (15/18)
Parsing DCMandatoryNumberTextField.swift (16/18)
Parsing DCMandatoryTextField.swift (17/18)
Parsing DCBorderedTextField.swift (18/18)
building site
jam out ♪♫ to your fresh new docs in `docs`
```

However, the documentation contains only README.
Here's how classes look like:

```
/// Base text field class.
@IBDesignable open class DCBaseTextField: UITextField {

    /// Placeholder text color.
    @IBInspectable open var placeholderColor: UIColor = UIColor(white: 0.7, alpha: 1.0) {
        didSet {
            if let placeholder = placeholder {
                attributedPlaceholder = NSAttributedString(string: placeholder, attributes: [NSForegroundColorAttributeName: placeholderColor, NSFontAttributeName: font!])
            }
        }
    }

    /// A blinking cursor color.
    /// For some reasons setting tintColor from IB doesn't work, so we have to add a property for that.
    @IBInspectable open var cursorColor: UIColor = UIColor(red: 0.0, green: 122.0/255.0, blue: 1.0, alpha: 1.0) {
        didSet {
            tintColor = cursorColor
        }
    }
....
```

Am I missing something?

**Comment by sauvikatinnofied** [comment]
Is there any update on that issue?

**Comment by andrew8712** [comment]
@sauvikatinnofied Are you experiencing that too? I didn't check with the latest `jazzy` version. Did you?

**Comment by ScottYelich** [comment]
I am experiencing this... have you managed to get it to work for you?  jazzy v0.7.2 here.

**Comment by JoshHrach** [comment]
I just encountered this with Jazzy 0.7.2, running Xcode 8.1 with a Swift 3 project on macOS Sierra 10.12.1.

**Comment by CalebeNP** [comment]
Any update?

**Comment by orta** [comment]
There have been [no releases](https://github.com/realm/jazzy/releases) of Jazzy since this issue was opened, please don't just add "+1"s 

You should take it as something you could potentially fix

**Comment by istx25** [comment]
In agreement with @orta. Would anyone like to tackle this?

**Comment by dirtyhenry** [comment]
#664 seems to be a duplicate.

I have the same issue. One complementary information: only classes generated at compile-time by Xcode from my Core Data model appears in jazzy output. If I get it out of my target, the documentation is empty again.

**Comment by JesseBlack82** [comment]
I have verified that the problem doesn't exist with jazzy 0.7.3

```
git clone git@github.com:andrew8712/DCKit.git
cd DCKit
jazzy
```

The output is the same as the first comment in the issue, but does have documentation for more than just the README.md.

**Comment by dirtyhenry** [comment]
The problem still exists with my project: https://github.com/Bootstragram/Piggy.
I just get the README.md documented even it I get a very similar output to the one in the 1st comment, and a very similar `.jazzy.yaml` as well.

**Comment by JesseBlack82** [comment]
@dirtyhenry I don't see many documentation comments in that repo.  Does adding `min_acl: private` to your `.jazzy.yaml` get you all the documentation you are looking for?

**Comment by dirtyhenry** [comment]
Adding `min_acl: private` fixed my problem. Even undocumented, I was still expecting getting the list of classes, protocols, structs, etc. I hadn't considered this parameter. Thanks @JesseBlack82 for your help.

**Comment by JesseBlack82** [comment]
@dirtyhenry No problem.  Everything is `internal` by default, and isn't getting added to the documentation.  If you would like to exclude private types, functions and methods, you can use `min_acl: internal`.

**Comment by jpsim** [comment]
I think #238 would help a lot in improvement the user experience when the ACLs are too private for what Jazzy is documenting.

Is there anything tracked in this issue that wouldn't be covered by that? I think this issue may have been overloaded a bit with more than just one problem. @dirtyhenry's issue seems to have been due to not having any public ACLs (or too high of a min ACL, depending on how you look at it).

Is this the problem you were running into @andrew8712 @sauvikatinnofied @JoshHrach @CalebeNP ?

**Comment by Mozahler** [comment]
I was having this issue with version 0.7.3.  I specify min_acl: private in my .yaml, yet entire classes were missing.
The missing content appeared after adding to the jazzy command line:
--clean

**Comment by rameezhandel** [comment]
I was trying to generate document using jazzy with Xcode8.2 & swift 3.0, its always generating the document only for 3 files which is in 3 different targets. And when i try to run the command: "jazzy -x -workspace,MyProject.xcworkspace,-scheme,MyProject" it just hangs for a long time & no response.

**Comment by sauvikatinnofied** [comment]
Sorry for coming back after a long break. Issue was fixed using `min_acl: private` in my `.jazzy.yaml`.
