### ISSUE TITLE
Find a way to name extensions

### ISSUE THREAD

**Issue by jpsim** [realm/jazzy#66]
Swift extensions aren't named/labeled, but it'd be nice to find a better way to present them:

![image](https://cloud.githubusercontent.com/assets/474794/4870672/2463abb0-617a-11e4-80a2-cf3810446a43.png)

Maybe by using the MARK-style comment directly above it?

**Comment by khoogheem** [comment]
The other is with Extensions is not only are there multiple of the same name.. all of the links go to the same extension..  It builds all of the single files in the UIColor extension folder. but the uicolor.html is only showing what looks like the first extension of UIcolor it found

Doesn't Sourcekitten provide the filename in its output.. why not use that as part of the

**Comment by jpsim** [comment]
@khoogheem actually @segiddins just fixed that! See https://github.com/realm/jazzy/blob/master/CHANGELOG.md#bug-fixes

**Comment by khoogheem** [comment]
Ok.. I just saw that when using the master branch..

Here is my only problem now with Extensions )-

When I look at UIColor from the left tab bar it puts them all into one single long list of extensions.. (not sure if that is good or bad...)

Say I have NBA Colors in one file
NHL  Colors in another.
it lists them all  in the order of the way the file was read.

What is interesting is that i have //MARK: team name so I can better track it in Xcode.. which jazzy picks up and uses.

So you might get something like:
Atlanta Hawks
---hawsTeamcolors()
Chicago Bulls
-bullsTeamcolors()
Anaheim Ducks
-duckksTeamColors

If the file only has one //Mark:  it shows what you would expect
NBA Team Colors
-teamcolor()
-otherteamcolor()

NFL Team Colors
-teamcolor()
-otherteamcolor()

Would be nice if you could use the first Mark as the Main Header..

So your file might look like:
~~~
/**
	iOS & OSX Extensions of GKColor for Colors of NBA Teams

	**Swift Only**

	To get the red color of the Atlanta Hawks... AtlantaHawks.red.color()
*/
public extension GKColor {
    //MARK: NBA Colors

	//MARK: Atlanta Hawks
	/**
	Provides the Team Colors for the NBA Atlanta Hawks
	*/
	public enum AtlantaHawks {
		/** Color whose RGBA values are (r 0.0 g 0.0 b 0.502 a 1.0) */
		case blue
		/** Color whose RGBA values are (r 1.0 g 0.0 b 0.0 a 1.0) */
		case red
		/** Color whose RGBA values are (r 0.753 g 0.753 b 0.753 a 1.0) */
		case gray
~~~~

**Comment by khoogheem** [comment]
The other oddity is that if you have multiple extension files..I get undocumented...  guess it doesn't know which file to pick up the comment from.

**Comment by jpsim** [comment]
This isn't really necessary anymore because extensions are merged into their parent type and grouped under `// MARK`s. Closing.
