### ISSUE TITLE
Exclude documentation in source files, not entire files

### ISSUE THREAD

**Issue by gngrwzrd-intel** [realm/jazzy#665]
I haven't been able to find if this is available, but I'd love to be able to mark something in the source file as ignore or exclude. I know you have a command line option --exclude. But that only ignores entire files. It'd be great if there was something in the doc markup to exclude something. Maybe "!exclude" or something?

I think this would be used a lot. For me personally, I would like to be able to leave out docs of overrides of public functions in apple's frameworks - like drawRect, or layoutSubviews, those kinds of methods that really don't need documentation if they're overridden for something simple.

**Comment by pcantrell** [comment]
You are looking for `nodoc`, I think:

    /// :nodoc:
    public func foo() -> Bar
