### ISSUE TITLE
Module version is not available in templates

### ISSUE THREAD

**Issue by rlepinski** [realm/jazzy#666]
The module version is unavailable in templates:

```
{{module_version}}
```

Doesn't look like its set when generating the doc.

**Comment by istx25** [comment]
What version?

**Comment by istx25** [comment]
Please share a minimal test project that reproduces the issue.

**Comment by istx25** [comment]
Closing in 2 weeks if there's no further activity.

**Comment by jpsim** [comment]
None of the templates have `{{module_version}}`. @rlepinski is this a feature request? Would you like jazzy to make the module version available to Mustache templates?

**Comment by rlepinski** [comment]
@istx25 version 0.7.2.

@jpsim yes feature request. None of the templates use it but the command line options accept the module version so it would be nice to expose it for moustache templates.  Sorry for not providing more information when I originally created the ticket.

**Comment by jpsim** [comment]
Sure, that's easily exposable. Let's just add it to [doc.rb](https://github.com/realm/jazzy/blob/master/lib/jazzy/doc.rb) much like `language` is currently exposed.

**Comment by johnfairh** [comment]
Fixed in master.
