### ISSUE TITLE
ObjC Import file not found when using SPM directory structure

### ISSUE THREAD

**Issue by rnystrom** [realm/jazzy#667]
We're putting the finishing touches on an Objective-C framework and are trying to prepare for the eventual (maybe?) launch of the Swift Package Manager using the following dir structure:
- IGListKit.xcodeproj
- /Source
  - IGListKit.h
  - PublicFile.h
  - PublicFile.m
  - /Internal
    - PrivateFile.h
    - PrivateFile.m
- /Tests
- /Example
- /docs

Our script setup looks like

```
jazzy \
    --objc \
    --clean \
    --author 'Instagram' \
    --author_url 'https://twitter.com/fbOpenSource' \
    --github_url 'https://github.com/Instagram/IGListKit' \
    --sdk iphonesimulator \
    --module 'IGListKit' \
    --framework-root . \
    --umbrella-header Source/IGListKit.h \
    --readme README.md \
    --output docs/ \
```

Our umbrella header (and almost all the framework's `#import`s) look like:

```
#import <IGListKit/PublicFile.h>
#import <IGListKit/AnotherPublicFile.h>
#import <IGListKit/OneMorePublicFile.h>
```

When I run the script I get a "file not found" error like:

```
Source/IGListKit.h:1:9: fatal error: 'IGListKit/PublicFile.h' file not found
```

If I mv the `Source` dir to `IGListKit` all of the docs gen just fine. It seems like there should be a way to s/Source/IGListKit when searching for file paths, right? I hope I'm missing something obvious?

cc @jessesquires who's running into this w/ me

**Comment by rnystrom** [comment]
ping @jpsim on this. We have to hack around this bug to gen docs for [IGListKit](https://github.com/Instagram/IGListKit).

**Comment by mhuusko5** [comment]
I'm also running into this issue with a project with multiple/nested directories containing relevant headers, vs. just `ProjectName/ProjectName`. Temporarily creating `ProjectName/ProjectName`, and copying all headers in there resolves this issue, but then `run_sourceKitten` ends up failing (guessing because mismatch between file location and .xcodeproj?).

**Comment by istx25** [comment]
Hi @rnystrom and @mhuusko5. Thanks for reaching out. My apologies that no one responded to your support request until now. Did you ever find a functional workaround? Is the problem present in the latest version? Please let me know. I'll do my own digging in the meantime.

**Comment by rnystrom** [comment]
@istx25 yup we added a workaround for the time being https://github.com/Instagram/IGListKit/pull/93/files

But it's not a very robust solution

**Comment by istx25** [comment]
I'll look into this further. Thanks @rnystrom!

**Comment by jessesquires** [comment]
Is this the same issue as #518 ?

**Comment by johnfairh** [comment]
Added explanation and workaround options to docs.
