### ISSUE TITLE
If Xcode is named something else, make command exits.

### ISSUE THREAD

**Issue by JacobKingDev** [realm/jazzy#668]
My Xcode is called 'Xcode 8' instead of the default 'Xcode' (as I have multiple versions installed). When installing the installer exits on the make command complaining that it can't find '/Applications/Xcode'.

**Comment by istx25** [comment]
Symlink the current Xcode version you use to Xcode.app to avoid this issue. A tool like https://github.com/KrauseFx/xcode-install may be able to help you in this situation.

**Comment by jpsim** [comment]
Sorry for this being closed. Jazzy shouldn't require Xcode to be installed at `/Application/Xcode.app`, so I'm not sure why this happened to you.

Could you please elaborate on how this happened?

> When installing the installer exits on the make command complaining that it can't find '/Applications/Xcode'.

By "the installer", do you mean rubygems? Are you installing jazzy by running `gem install jazzy`? If that's what's failing, could you please share the full log output? Thanks!

**Comment by istx25** [comment]
My apologies @jpsim @xKINGYx - will do better in the future.

**Comment by johnfairh** [comment]
Dup of #994.
