### ISSUE TITLE
Allow ignoring certain tokens

### ISSUE THREAD

**Issue by jpsim** [realm/jazzy#67]
Best way I can think of to do this is to use a flag in the ReST comment. Maybe `:jazzy_ignore:`?

**Comment by lukaskubanek** [comment]
This would be a great feature! It would be especially handy for the overridden methods and properties in subclasses of framework classes, because their access level must not be restricted.

@jpsim May I ask whether there is any progress on this feature?

**Comment by segiddins** [comment]
@lukaskubanek not yet, but feel free to submit a pull request implementing the feature!

**Comment by WCByrne** [comment]
Before I look into the source, any progress on this? I have internal variables & functions in my SDK that shouldn't appear in the docs.

**Comment by segiddins** [comment]
@WCByrne for your use case, you might just be able to use the `--min-acl` option

**Comment by WCByrne** [comment]
@segiddins Awesome, exactly what I needed. Thank you!

**Comment by jpsim** [comment]
This feature was added in #180.
