### ISSUE TITLE
error handling xcodebuild parameters in objc

### ISSUE THREAD

**Issue by jeremiegirault** [realm/jazzy#672]
I cannot develop in ruby but I noticed that there is a logic problem by using jazzy and got to the source :
https://github.com/realm/jazzy/blob/master/lib/jazzy/sourcekitten.rb#L122

When xcodebuild_arguments are provided in objc mode, they are not appened to this array:

```
arguments += ['--objc', options.umbrella_header.to_s, '--', '-x',
                        'objective-c', '-isysroot',
                        `xcrun --show-sdk-path --sdk #{options.sdk}`.chomp,
                        '-I', options.framework_root.to_s]
```

but only to this one:

```
arguments = ['doc']
```

This means that I had to pass all arguments (`--objc <header> -- <all_clang_args>`) in the arguments as a workaround.

I don't think that this is the intended behavior (because we lose all other options passed to jazzy).

**Comment by istx25** [comment]
Hi @jeremiegirault. Thanks for submitting this issue. We'll look into this.

**Comment by iamamused** [comment]
Having a similar issue trying to pass the workspace and schema:

```
jazzy \
→   --clean \
→   --module-version 1.0.0 \
→   --xcodebuild-arguments -workspace Example.xcworkspace -scheme Example \
→   --module ice \
→   --objc \
→   --output docs/objc
/usr/local/lib/ruby/gems/2.3.0/gems/jazzy-0.7.3/lib/jazzy/doc_builder.rb:57:in `read': No such file or directory @ rb_sysopen - /Users/jsambells/Documents/Projects/git/Example/cheme (Errno::ENOENT)
	from /usr/local/lib/ruby/gems/2.3.0/gems/jazzy-0.7.3/lib/jazzy/doc_builder.rb:57:in `read'
	from /usr/local/lib/ruby/gems/2.3.0/gems/jazzy-0.7.3/lib/jazzy/doc_builder.rb:57:in `build'
	from /usr/local/lib/ruby/gems/2.3.0/gems/jazzy-0.7.3/bin/jazzy:15:in `<top (required)>'
	from /usr/local/bin/jazzy:22:in `load'
	from /usr/local/bin/jazzy:22:in `<main>'
```

**Comment by jpsim** [comment]
What happens when you run `xcodebuild -workspace Example.xcworkspace -scheme Example`?

**Comment by johnfairh** [comment]
Closing, old: code mentioned by OP is correct as-is.
