### ISSUE TITLE
Should the latest version of SourceKitten be used?

### ISSUE THREAD

**Issue by mhuusko5** [realm/jazzy#677]
It *seems* that jazzy is currently targeting SourceKitten from about 6 months ago. Would it make sense to upgrade/could it potentially fix issues with jazzy/SourceKit crashes (I haven't been able to run it on my proj for months, without crashing)?

**Comment by orta** [comment]
Makes sense, wanna give it a shot?

**Comment by mhuusko5** [comment]
Although I appreciate the offer/support, I'm hesitant as I understand the workings of the project so little to the point of not being able to use it/figure out why (old SourceKitten is a total guess; I also think I have the issue of having a non flat source structure that some other issues have mentioned).

That said, I may have some waste time this week to fiddle around with it... @jpsim as a maintainer of both projects, is there anything I would look out for integration wise/any obvious incompatibilities?

**Comment by istx25** [comment]
This issue has been completed. #679 just needs to be reviewed. Closing.

**Comment by jpsim** [comment]
@istx25 I prefer not to close issues until a fix lands in `master`. That way, others looking for similar issues will find it. So let's keep this open.

**Comment by johnfairh** [comment]
Latest SK now in master.
