### ISSUE TITLE
Issue and Pull Request Clean Up

### ISSUE THREAD

**Issue by istx25** [realm/jazzy#680]
- [x] Attach all closed issues and PRs to the **[Before](https://github.com/realm/jazzy/milestone/1)** milestone.
- [x] Ensure all PRs have been labeled and assigned _to someone_.
- [x] Create Project for backlog, PRs that need review, etc.
- [x] Ensure all issues have been assigned _to someone_.
- [x] Ensure all issues have been labeled.

**Comment by jpsim** [comment]
Thanks for doing this, @istx25! Must have been tedious!

**Comment by istx25** [comment]
No worries, @jpsim! Definitely took a while but I think it was an overall good use of my time. I think at times I got in automation mode since there was >500 PRs and issues to review. My apologies for any that were incorrectly closed or assumptions wrongly made. Will improve for the future.
