### ISSUE TITLE
Superclass in Objective-C class declaration is unlinked

### ISSUE THREAD

**Issue by 1ec5** [realm/jazzy#706]
The declaration for an Objective-C class has any protocols autolinked, but the superclass is never autolinked. For example, [this declaration](https://www.mapbox.com/ios-sdk/api/3.4.0-beta.5/Classes/MGLPolygon.html) reads:

```objc
@interface MGLPolygon : MGLMultiPoint <MGLOverlay>
```

“MGLMultiPoint” should link to the MGLMultiPoint class reference, but it remains unlinked. By contrast, “MGLOverlay” does link to the MGLOverlay protocol reference.

The cause appears to be that the `<span>` around “MGLMultiPoint” has a class of `nc` rather than `n` ([example of the latter](https://github.com/realm/jazzy-integration-specs/blob/a07dad280bdb94fa71efb33800d41d433967561d/document_realm_objc/after/docs/Classes/RLMResults.html#L169)).

/cc @friedbunny

**Comment by jpsim** [comment]
Thanks for reporting and fixing this promptly @1ec5!

**Comment by 1ec5** [comment]
Fixed in #713. 🎉
