### ISSUE TITLE
Cross-references to other methods?

### ISSUE THREAD

**Issue by sfyz** [realm/jazzy#709]
I can't find a way to cross-reference other methods within the documentation. Is this possible in Swift or Objective-C?

I'm currently trying to document an Objective-C codebase and I can't find a way to ref other methods (though I think properties work). It appears that you can reference another class either implicitly (` 'MyOtherClass' `) or explicitly (`<MyOtherClass>`) and the xref works fine, but I can't reference a *method* within another (or even the same) class. In appledoc, you can do this using the standard obj-c notation (` '[MyOtherClass myMethod]' `).

Anyway, I'd love to make this a feature request if this functionality isn't currently available.

Thanks!

**Comment by jpsim** [comment]
This is in the process of being added in #707, originally tracked in #362. So I'll be closing this as a duplicate. But thanks for the suggestion!

**Comment by sfyz** [comment]
Oh wow. I missed that when I filed the issue, but great to hear the news! thx.
