### ISSUE TITLE
Create documentation for entire Xcode project

### ISSUE THREAD

**Issue by lukaskollmer** [realm/jazzy#716]
Hi,

I'd like to use jazzy to create documentation for my entire Xcode project, not just an framework.
Is that possible?

Thanks!

**Comment by huguesbr** [comment]
@lukaskollmer I don't think it's an issue. I'm using it to document my app.

from Jazzy docs:

```
Swift

Only extensions are listed in the documentation?

By default, jazzy only documents public declarations. To generate documentation for declarations with a lower accessibility level (internal or private), please set the --min-acl flag to internal or private.
```

By default `Jazzy` will document `public` API as it's mainly used for framework documentation. But you can change the level of the ACL to `private` or `internal` to fit your needs.

You can also set this variable in a `.jazzy.yaml` to avoid typing it each time
Here is my `.jazzy.yaml`:

```
clean: true
sdk: iPhone
author: Hugues BERNET-ROLLANDE
author_url: http://www.xdev.fr
copyright: "2016-present © Hugues Bernet-Rollande"
min_acl: private
```

**Comment by jpsim** [comment]
Looks like @lukaskollmer is asking for a way to document multiple modules (whether frameworks, apps, test bundles, etc.). Jazzy fundamentally builds docs on a per-module basis.

Although it's not too hard to get it to document multiple modules at once. You basically need to combine the json output from multiple `sourcekitten doc` commands and feed it to `jazzy --sourcekitten-sourcefile` much like is done in [`podspec_documenter.rb`](https://github.com/realm/jazzy/blob/v0.7.4/lib/jazzy/podspec_documenter.rb#L12-L35) to combine docs from all platforms supported by a podspec.

**Comment by jpsim** [comment]
Hopefully that answers your question @lukaskollmer
