### ISSUE TITLE
Generate Badges for Documentation

### ISSUE THREAD

**Issue by harlanhaskins** [realm/jazzy#723]
I'd love to be able to generate a badge I can link to in my README.
I'd be willing to implement it if y'all think it'd be a welcome addition. 👍

**Comment by 1ec5** [comment]
It would be cool if the badge could indicate the documentation coverage as a percentage, like the default theme's navigation bar does.

**Comment by jpsim** [comment]
Great idea!

**Comment by harlanhaskins** [comment]
Alright, then I'll get started on this. Is there any issue with downloading badges from http://shields.io?

**Comment by jpsim** [comment]
I don't think so.

**Comment by harlanhaskins** [comment]
Great, so the flow I'm looking for is:

- Determine documentation percentage (which is displayed on the main site)
- Make a request to `https://img.shields.io/badge/documentation-<percentage>-<color-depending-on-percent>.svg`
- Store that in the `docs/` folder in a consistent place, and allow the user to point to that svg file with a link to wherever they host their docs?

**Comment by harlanhaskins** [comment]
I'm thinking:

| Percentage | Color |
|------------|-------|
| 100% | brightgreen |
| 85% < x < 100% | green |
| 60% < x < 85% | yellowgreen |
| 30% < x < 60% | yellow |
| 10% < x < 30% | orange |
| < 10% | red |

Works?

**Comment by harlanhaskins** [comment]
Should this be dependent on `options.hide_documentation_coverage`? What should we do if that's set?

**Comment by jpsim** [comment]
That's a good point. Let's not generate this if `hide_documentation_coverage` is set, because this feature requires Internet access, so it'd be nice to have some sort of way to disable it if you're offline and need to generate docs.

**Comment by harlanhaskins** [comment]
Right, is there a way to check that? I'm using `Open::URI` for it.

**Comment by harlanhaskins** [comment]
Actually, `open()` will return `nil` if the user isn't connected. Then we can just not serialize an image.

**Comment by jpsim** [comment]
IMO we should fail if we can't generate the badge, since once we have this, some may rely on it being available when building their docs.

**Comment by harlanhaskins** [comment]
Is there an existing way to handle failures and clean up? I have the base feature implemented.

**Comment by harlanhaskins** [comment]
Also, I can't seem to get it building -- I have sqlite3 installed from brew, but I still get 

```
Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.

    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby extconf.rb
checking for sqlite3.h... yes
checking for pthread_create() in -lpthread... yes
checking for sqlite3_libversion_number() in -lsqlite3... no
sqlite3 is missing. Try 'brew install sqlite3',
'yum install sqlite-devel' or 'apt-get install libsqlite3-dev'
and check your shared library search path (the
location where your sqlite3 shared library is located).
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
	--with-sqlite3-config
	--without-sqlite3-config
	--with-pkg-config
	--without-pkg-config
	--with-sqlite3-dir
	--without-sqlite3-dir
	--with-sqlite3-include
	--without-sqlite3-include=${sqlite3-dir}/include
	--with-sqlite3-lib
	--without-sqlite3-lib=${sqlite3-dir}/
	--with-pthreadlib
	--without-pthreadlib
	--with-sqlite3lib
	--without-sqlite3lib


Gem files will remain installed in
/var/folders/g8/wpsgg5t551d111sgx__7m5qc0000gq/T/bundler20170110-22421-1pb2jr7sqlite3-1.3.13/gems/sqlite3-1.3.13 for inspection.
Results logged to
/var/folders/g8/wpsgg5t551d111sgx__7m5qc0000gq/T/bundler20170110-22421-1pb2jr7sqlite3-1.3.13/gems/sqlite3-1.3.13/ext/sqlite3/gem_make.out

An error occurred while installing sqlite3 (1.3.13), and Bundler cannot continue.
Make sure that `gem install sqlite3 -v '1.3.13'` succeeds before bundling.
```

**Comment by harlanhaskins** [comment]
And I can successfully `sudo gem install sqlite3`

**Comment by jpsim** [comment]
Nothing existing, no. Building from a podspec also often requires a network connection and we just fail catastrophically if the network couldn't be reached.

**Comment by jpsim** [comment]
How are you building? `bundle install && bundle exec rake build` should do the trick...

**Comment by harlanhaskins** [comment]
That's from `bundle install` 😢

**Comment by jpsim** [comment]
Maybe ruby experts have an idea? /cc @segiddins

**Comment by segiddins** [comment]
If `gem install sqlite3 -v '1.3.13'` succeeds but `bundle install` fails, thats a bundler issue, if not it's an issue with your ruby installation (likely not looking with the correct library search paths).

**Comment by harlanhaskins** [comment]
I'm using `ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin16]` and `sqlite3 3.16.2 2017-01-06 16:32:41`

**Comment by rcbello** [comment]
I encountered the same error and I had these lines on the mkmf.log file:

>ld: warning: ignoring file /usr/local/opt/sqlite/lib/libsqlite3.dylib, file was built for x86_64 which is not the architecture being linked (i386): /usr/local/opt/sqlite/lib/libsqlite3.dylib
Undefined symbols for architecture i386:
  "_sqlite3_libversion_number", referenced from:
      _t in conftest-265d8e.o
ld: symbol(s) not found for architecture i386

>ld: warning: ignoring file /usr/local/opt/sqlite/lib/libsqlite3.a, file was built for x86_64 which is not the architecture being linked (i386): /usr/local/opt/sqlite/lib/libsqlite3.a
Undefined symbols for architecture i386:
  "_sqlite3_libversion_number", referenced from:
      _t in conftest-265d8e.o
ld: symbol(s) not found for architecture i386

From this comment, https://github.com/sparklemotion/sqlite3-ruby/issues/152#issuecomment-91941970, I was able to solve the issue by just removing the two files.

`rm /usr/local/opt/sqlite/lib/libsqlite3.a`

`rm /usr/local/opt/sqlite/lib/libsqlite3.dylib`

**Comment by harlanhaskins** [comment]
@rcbello Thank you! It's working for me and I can test my patch.

**Comment by cbm-mghebaji** [comment]
Hello,

I have question about using CI Badge, i use Bitrise for CI so i want to get the status of the build.
The default index.html file use Travis, i can change it with the Bitrise URL but when i regenrate the doc i will use Travis. 
How can i deal with it to use always Bitrise ?
