### ISSUE TITLE
"show in GitHub" button

### ISSUE THREAD

**Issue by galorlanczyk** [realm/jazzy#729]
Hi,

I am new to jazzy, I generated docs for my project and all is created fine.
Now I saw on other jazzy docs a button under each variable named "Show in Github" that directs the user to the GitHub implementation.
Any help would be appreciated! 

Thanks,
Gal

**Comment by 1ec5** [comment]
These links show up if you specify the `github-file-prefix` option.

**Comment by galorlanczyk** [comment]
Can you help me with a small example how to use this? couldn't find this tag in the documentation.

Thanks a lot

**Comment by friedbunny** [comment]
`jazzy --help` says:

> `--github-file-prefix PREFIX`  GitHub URL file prefix of this project (e.g. https://github.com/realm/realm-cocoa/tree/v0.87.1)

Here’s how [realm-cocoa](https://github.com/realm/realm-cocoa/blob/2caec0737ab5bf6365ccb19c685a7643505d6e55/build.sh#L261) and [Mapbox](https://github.com/mapbox/mapbox-gl-native/blob/4ce8d3e4e313fd436d2c8bc233d44ab90d23c64d/platform/ios/scripts/document.sh#L41) use this flag.

**Comment by galorlanczyk** [comment]
@1ec5 @friedbunny Thanks a lot!
