### ISSUE TITLE
Jazzy.yml scheme with spaces

### ISSUE THREAD

**Issue by bolismauro** [realm/jazzy#731]
I'm trying to create a jazzy.yml file that contains a custom scheme to use in `xcodebuild`. The problem is that the scheme has a whitespace

I tried the following
`xcodebuild_arguments: [-workspace,Project.xcworkspace,-scheme,Scheme iOS]`
`xcodebuild_arguments: [-workspace,Project.xcworkspace,-scheme,SchemeiOS]`
`xcodebuild_arguments: [-workspace,Project.xcworkspace,-scheme,Scheme_iOS]`
`xcodebuild_arguments: [-workspace,Project.xcworkspace,-scheme,Scheme-iOS]`

`xcodebuild_arguments: '-workspace Project.xcworkspace -scheme Scheme\ iOS'`
`xcodebuild_arguments: '-workspace Project.xcworkspace -scheme Scheme iOS'`

But I always receive this error

```
A compile error prevented <function> from receiving a unique USR. Documentation may be incomplete. Please check for compile errors by running `xcodebuild `.
```

If I run
```
xcodebuild -workspace Project.xcworkspace -scheme Scheme\ iOS
```
everything works

I've read this 
https://github.com/realm/jazzy/issues/111

but to be honest I haven't managed to figure out how to do it

PS: is there a way to see the xcodebuild output? just to understand if the issue is really related to the xcodebuild parameters as I suspect?

Thanks

**Comment by jpsim** [comment]
> PS: is there a way to see the xcodebuild output? just to understand if the issue is really related to the xcodebuild parameters as I suspect?

jazzy shells out to [SourceKitten](https://github.com/jpsim/SourceKitten), so if you figure out how your `xcodebuild_arguments` get converted to a `sourcekitten` command, you can invoke it directly, which will log the location of the xcodebuild log file:

> Saved `xcodebuild` log file: /path/to/xcodebuild.log

**Comment by bolismauro** [comment]
Alright it was a combination of mistakes I've made. Nothing related to jazzy.
I close this
