### ISSUE TITLE
Could not parse compiler arguments from `xcodebuild` output.

### ISSUE THREAD

**Issue by nareshkommana** [realm/jazzy#736]
`Running xcodebuild
Could not parse compiler arguments from `xcodebuild` output.
Please confirm that `xcodebuild` is building a Swift module.
Saved `xcodebuild` log file: /var/folders/h_/3nl4prlj0fd73l47kfrl8zy00000gp/T/xcodebuild-6D8CD983-607D-48C4-9777-2625E9D3B2F2.log
Failed to generate documentation
/Library/Ruby/Gems/2.0.0/gems/jazzy-0.7.3/lib/jazzy/executable.rb:36:in `execute_command': /Library/Ruby/Gems/2.0.0/gems/jazzy-0.7.3/lib/jazzy/SourceKitten/bin/sourcekitten ["doc", "--"] (RuntimeError)

Running xcodebuild

Could not parse compiler arguments from `xcodebuild` output.

Please confirm that `xcodebuild` is building a Swift module.

Saved `xcodebuild` log file: /var/folders/h_/3nl4prlj0fd73l47kfrl8zy00000gp/T/xcodebuild-6D8CD983-607D-48C4-9777-2625E9D3B2F2.log

Failed to generate documentation
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.7.3/lib/jazzy/sourcekitten.rb:147:in `run_sourcekitten'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.7.3/lib/jazzy/doc_builder.rb:65:in `block in build'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.7.3/lib/jazzy/doc_builder.rb:63:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.7.3/lib/jazzy/doc_builder.rb:63:in `build'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.7.3/bin/jazzy:15:in `<top (required)>'
	from /usr/local/bin/jazzy:23:in `load'
	from /usr/local/bin/jazzy:23:in `<main>'`

**Comment by jpsim** [comment]
@nareshkommana did you look at the log saved in `/var/folders/h_/3nl4prlj0fd73l47kfrl8zy00000gp/T/xcodebuild-6D8CD983-607D-48C4-9777-2625E9D3B2F2.log`, as the error message indicated?

Could you please post the contents of the log here so we can tell you why this failed?

**Comment by nareshkommana** [comment]
Build settings from command line:
    CODE_SIGN_IDENTITY = 
    CODE_SIGNING_REQUIRED = NO

=== CLEAN TARGET FMDB OF PROJECT _Pods WITH THE DEFAULT CONFIGURATION (Release) ===

Check dependencies
The file “FMDB.xcconfig” couldn’t be opened because there is no such file. (/Users/nareshbabukommana/WorkSpace/Voltron/Voltron-iOSSDK/Voltron-iOSSDK-Github/Voltron-iOSSDK-Github_Express/Target Support Files/FMDB/FMDB.xcconfig)
error: unable to read module map contents from 'Target Support Files/FMDB/FMDB.modulemap': Error Domain=NSCocoaErrorDomain Code=260 "The file “FMDB.modulemap” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/nareshbabukommana/WorkSpace/Voltron/Voltron-iOSSDK/Voltron-iOSSDK-Github/Voltron-iOSSDK-Github_Express/Target Support Files/FMDB/FMDB.modulemap, NSUnderlyingError=0x7fabed92c520 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}

** CLEAN FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
=== BUILD TARGET FMDB OF PROJECT _Pods WITH THE DEFAULT CONFIGURATION (Release) ===

Check dependencies
The file “FMDB.xcconfig” couldn’t be opened because there is no such file. (/Users/nareshbabukommana/WorkSpace/Voltron/Voltron-iOSSDK/Voltron-iOSSDK-Github/Voltron-iOSSDK-Github_Express/Target Support Files/FMDB/FMDB.xcconfig)
error: unable to read module map contents from 'Target Support Files/FMDB/FMDB.modulemap': Error Domain=NSCocoaErrorDomain Code=260 "The file “FMDB.modulemap” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/nareshbabukommana/WorkSpace/Voltron/Voltron-iOSSDK/Voltron-iOSSDK-Github/Voltron-iOSSDK-Github_Express/Target Support Files/FMDB/FMDB.modulemap, NSUnderlyingError=0x7fabede2c7a0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}

** BUILD FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
 @jpsim

**Comment by jpsim** [comment]
There's your problem.

**Comment by nareshkommana** [comment]
@jpsim 
From log I observed that it is searching for **FMDB.xcconfig** from 
**Path1** : **/Users/nareshbabukommana/WorkSpace/Voltron/Voltron-iOSSDK/Voltron-iOSSDK-Github/Voltron-iOSSDK-Github_Express/**Target Support Files/FMDB/FMDB.xcconfig

but **FMDB.xcconfig** is present in 
**Path2** : **/Users/nareshbabukommana/WorkSpace/Voltron/Voltron-iOSSDK/Voltron-iOSSDK-Github/Voltron-iOSSDK-Github_Express/**Example/Pods/Target Support Files/FMDB/FMDB.xcconfig

FMDB is installed from pods hence the path for it is present under **Path2** then why it is looking in **Path1**

**Comment by reitzig** [comment]
For me, this happened when the Jazzy-called `xcodebuild` could not find dependencies that XCode could. Apparently, in some project (or folder?) setups, specifying the module name is not enough. I added

```yaml
xcodebuild_arguments:
    - "-project"
    - "MyProject.xcodeproj"
    - "-scheme"
    - "MyScheme"
```

to the config and it worked.

**Comment by coooliang** [comment]
I have the same problem
would you tell me how to solved?

**Comment by sanaD13** [comment]
Run this and try again. It did for me.
```
sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
```

**Comment by johnfairh** [comment]
Closing this one, would prefer new issues to be raised.  [This comment](https://github.com/realm/jazzy/issues/736#issuecomment-318309708) shows one approach to make sure `xcodebuild` is actually building the module you want to document.

**Comment by DanBurkhardt** [comment]
Thanks @sanaD13, solved it for me!
