### ISSUE TITLE
Bump minimum Ruby version to v2.1.0?

### ISSUE THREAD

**Issue by friedbunny** [realm/jazzy#747]
As of jazzy v0.7.4, the effective minimum Ruby version became v2.1.0 — https://github.com/realm/jazzy/commit/b0e5c4b7cfa05c41d43feb3b3e2ca2c9efbcd410#diff-598546a0c342527401dade0e669b6772R431 switched to `Psych.safe_load()`, which was added in v2.1.0.

It would be trivial to fix Ruby 2.0.0 support:

```diff
diff --git a/lib/jazzy/config.rb b/lib/jazzy/config.rb
index af3fafd..2c072f4 100644
--- a/lib/jazzy/config.rb
+++ b/lib/jazzy/config.rb
@@ -428,7 +428,12 @@ module Jazzy
     def read_config_file(file)
       case File.extname(file)
         when '.json'         then JSON.parse(File.read(file))
-        when '.yaml', '.yml' then YAML.safe_load(File.read(file))
+        when '.yaml', '.yml' then
+          if YAML.respond_to?('safe_load') # ruby >= 2.1.0
+            YAML.safe_load(File.read(file))
+          else
+            YAML.load(File.read(file))
+          end
         else raise "Config file must be .yaml or .json, but got #{file.inspect}"
       end
     end
```

... but, given that Ruby 2.0 has been deprecated [for a year](https://www.ruby-lang.org/en/news/2016/02/24/support-plan-of-ruby-2-0-0-and-2-1/), should jazzy bump its Ruby requirement to 2.1.0 instead?

Refs https://github.com/mapbox/mapbox-gl-native/issues/8119.

/cc @jpsim @kkaefer

**Comment by kkaefer** [comment]
2.0 seems to be the version that is installed by default on macOS.

**Comment by friedbunny** [comment]
For clarity/posterity, here is the error you encounter when running jazzy v0.7.4 with Ruby 2.0.0:

```
/Library/Ruby/Gems/2.0.0/gems/jazzy-0.7.4/lib/jazzy/config.rb:431:in `read_config_file': undefined method `safe_load' for Psych:Module (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.7.4/lib/jazzy/config.rb:393:in `parse_config_file'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.7.4/lib/jazzy/config.rb:341:in `parse!'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.7.4/bin/jazzy:15:in `<top (required)>'
	from /usr/local/bin/jazzy:23:in `load'
	from /usr/local/bin/jazzy:23:in `<main>'
```
