### ISSUE TITLE
Generating Docset Feed XML?

### ISSUE THREAD

**Issue by jemmons** [realm/jazzy#749]
Does Jazzy generate Docset Feed XML for Dash (as described [here](https://kapeli.com/docsets#dashdocsetfeed))? I don't see it, but maybe there's some combination of options I'm missing?

If not, is there any reason this couldn't be generated, say in the `docsets` directory? It seems like all we'd need to make the file is the `module_version` and the relative location of the docset tgz, both of which Jazzy should have access to.

Generating this file would make it trivial for teams to share docsets after publishing via github pages or the like. As it is, this is an extra bit of friction requiring YA build script or manual coding to work around.

**Comment by segiddins** [comment]
https://github.com/realm/jazzy/blob/master/lib/jazzy/docset_builder.rb#L33
I think jazzy should do it if given a version and a root URL

**Comment by jemmons** [comment]
Yup! I was missing `root_url`. Thanks for the help!
