### ISSUE TITLE
Conflicting type declarations issues when project is under /private

### ISSUE THREAD

**Issue by cassdeckard** [realm/jazzy#755]
We have a project we are using `jazzy` to generate docs for, and it normally works fine but if the project is checked out to any directory descendent of `/private`, we get the following error per each class:
```
Found conflicting type declarations with the same name, which may indicate a build issue or a bug in Jazzy: class ClassName, class ClassName
```
And all members for every class are documented as being global in addition to members of their respective classes.

This is easily reproducible just by creating a basic Xcode project with at least one documented class under `/private/var/`.

The real pain this causes is that OS X Jenkins slaves tend to put workspaces under `/private/var/jenkins/workspace` so anyone trying to run `jazzy` as part of a Jenkins job is likely to run into this issue (that is how we discovered it)

**Comment by jpsim** [comment]
lol, really? If this is actually a bug, it's one of the more interesting ones I've seen. Let's investigate.

**Comment by mattdeckard** [comment]
Yep it's pretty weird. It really seems to only be in subdirectories of `/private` too. I tried creating another root-level directory with all of the same permission bits (including the extended attributes) and the same problem did not occur with its subdirectories.

**Comment by jpsim** [comment]
Does the same thing happen when running `sourcekitten doc` directly? I'd suspect so, but even then it's surprising.

btw, I've been using jazzy with Jenkins since first writing it 2+ years ago without issue, so 🤷‍♂️

**Comment by mattdeckard** [comment]
@jpsim Sorry, just got around to trying this.

Running `sourcekitten doc` on the project in `/var/test` doesn't produce any errors, but it does produce different JSON output than running on the same project in my home directory. The output when run in `/var/test` does seem to have duplicate entries which I'm sure is what is leading to jazzy getting confused. So this appears to be an issue with sourcekitten. I'm about to open up a ticket with them. Thanks!

**Comment by johnfairh** [comment]
Looks to have been fixed by something in the past 5 years!
