### ISSUE TITLE
Could not parse parameters correctly with '_' underscore in name

### ISSUE THREAD

**Issue by pcpLiu** [realm/jazzy#756]
Hi,

I met a problem that when I named the parameters of a function with `_` underscore in it. The generated doc could not be parsed correctly. I tried to use escape like `\_`, but not working.

```
 /**
    - Parameters:
         - sample_dim: Optional. The dimension of the data sample.
  */
 public convenience init(sample_dim: Int) {
        ......
    }

```

Generated doc:
![image](https://cloud.githubusercontent.com/assets/3357328/23584243/65c98434-0129-11e7-9ee2-127a3496b624.png)

Is there any way to solve this or I have to use camel case?

**Comment by SDGGiesbrecht** [comment]
Good catch, @pcpLiu.

There are several aspects to your question.

## Best Practice

The [Swift API Design Guidelines](https://swift.org/documentation/api-design-guidelines/) strongly recommend camel case:

```swift
/// - Parameters:
///     - sampleDimension: Optional. The dimension of the data sample.
public convenience init(sampleDimension: Int) {
    self.init()
}
```

It would be wise to do so whenever possible. That being said, I realize in some cases there are good reasons for deviating from the guidelines, such as the following usage case that will probably sting me in the near future. As such I am marking this issue as a bug.

```swift
// Greek distinguishes case, so this is legible:
let _ = /**/ Παράδειγμα(πρώτηΠαράμετρος: "ένα", δεύτερηΠαράμετρος: "δύο") /**/

// Hebrew has no case distiction, so this is illegible:
let _ = /*‏*/ דוגמה(פרמטרראשון: "אחת", פרמטרשני: "שתיים") /*‏*/
// This would be better:
let _ = /*‏*/ דוגמה(פרמטר_ראשון: "אחת", פרמטר_שני: "שתיים") /*‏*/
```

## Scope of the Bug

While I was testing, I realized Xcode’s Quick Help has a similar bug.

![failed underscore](https://cloud.githubusercontent.com/assets/23425673/23598254/d4a21a4e-01fe-11e7-8649-cbd0fb3a53ce.png)

I suggest you file a bug with Xcode as well.

## Workaround

Until the two bugs (Xcode and Jazzy) are fixed, the best workaround I can figure out is the following. It is sub‐optimal, but at least all the information is there and intact.

```swift
/// ## Parameters:
/// `sample_dim`: Optional. The dimension of the data sample.
public convenience init(sample_dim: Int) {
    self.init()
}
```

The results in Xcode:

![workaround](https://cloud.githubusercontent.com/assets/23425673/23598363/94e25940-01ff-11e7-95bf-a537c8d7884a.png)

The results in Jazzy:

![workaround jazzy](https://cloud.githubusercontent.com/assets/23425673/23598444/2b429562-0200-11e7-8a74-b932cb9853bb.png)

**Comment by pcpLiu** [comment]
Thanks for the great explanations!

Guess I'll follow the guidelines.
