### ISSUE TITLE
Crash With ObjC Methods Following Some Odd Naming Rules

### ISSUE THREAD

**Issue by ThatsJustCheesy** [realm/jazzy#759]
Who likes random corner-cases?! ;)

Jazzy will crash with a SourceKit error under the following (very odd) circumstances:
* SDK is macOS and AppKit is imported into the current file
* This file contains a class interface (with or without a prefix)
* In this interface, there is a _class_ method with the following naming scheme:
```
+launch[classname][…]
```
Where _classname_ is the name of the defining class with prefix stripped, and _…_ being, optionally, any other text.
* In this same interface, there are _no_ instance methods _whatsoever_ conforming to this same naming scheme.

Here's an example you can test:
```objc
// Without this import, everything's dandy
#import <AppKit/AppKit.h>
// Cocoa/Cocoa.h has the same effect

/// Represents a special process.
@interface EXSpecialProcess : NSObject

+ (void)pingSpecialProcess; // Just fine
+ (void)pingSpecialProcessWithParam:(id)anyOlParam; // Also fine

+ (void)launchSpecialProcess; // SourceKit crashes
+ (void)launchSpecialProcessWithParam:(id)anyOlParam; // Ditto

+ (void)launchNotSoSpecialProcess; // Fine

// Add an instance method with the same naming pattern, and everything works... for some reason
// Instance methods do not cause the crash on their own
// - (void)launchSpecialProcess; // Uncomment this line and it works again

@end
```

Save this to a file and generate docs with
```
jazzy --objc --sdk macosx --umbrella-header myfile.h
```

SourceKit then proceeds to crash with no explanation:
```
sourcekit: [1:connection-event-handler:9731: 0.0000] Connection interrupt
sourcekit: [1:pingService:9731: 0.0009] pinging service
/Library/Ruby/Gems/2.0.0/gems/jazzy-0.7.4/lib/jazzy/executable.rb:36:in `execute_command': /Library/Ruby/Gems/2.0.0/gems/jazzy-0.7.4/lib/jazzy/SourceKitten/bin/sourcekitten ["doc", "--objc", "/path/to/myfile.h", "--", "-x", "objective-c", "-isysroot", "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk", "-I", "''"] (RuntimeError)

sourcekit: [1:connection-event-handler:9731: 0.0000] Connection interrupt

sourcekit: [1:pingService:9731: 0.0009] pinging service
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.7.4/lib/jazzy/sourcekitten.rb:193:in `run_sourcekitten'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.7.4/lib/jazzy/doc_builder.rb:67:in `block in build'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.7.4/lib/jazzy/doc_builder.rb:65:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.7.4/lib/jazzy/doc_builder.rb:65:in `build'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.7.4/bin/jazzy:15:in `<top (required)>'
	from /usr/local/bin/jazzy:23:in `load'
	from /usr/local/bin/jazzy:23:in `<main>'
```

Thoughts? I haven't the slightest clue as to why or how this crash happens; I just encountered it when trying to generate docs for someone else's framework and managed to narrow it down to these truly bizarre rules.

**Comment by jpsim** [comment]
Could you please run that again with `export SOURCEKIT_LOGGING=3` before running `jazzy --objc --sdk macosx --umbrella-header myfile.h`? This is likely a SourceKit/swiftc bug and having those extra logs might help you get sufficient information to file an issue over at https://bugs.swift.org

**Comment by ThatsJustCheesy** [comment]
I just dug through the log that that spit out, and as it turns out, the problematic methods are being imported into Swift as `launch()` and `launch(withParam:)`, while the others are being imported without modification (e.g. `pingSpecialProcess(withParam:)`). I don't know whether any AppKit classes define a method called `launch()` (I'm not a heavy user of Swift), but if they do, that might be the root of the problem. Should I go file a bug at swift.org? Or an Apple radar? Or, both?

**Comment by jpsim** [comment]
Apple likely won't do much unless you can translate what you're seeing into a bug that they can reproduce with only Apple-provided tools (e.g. `swiftc` or Xcode).

**Comment by ThatsJustCheesy** [comment]
Sorry for the noob-ish question, but… isn't SourceKit a closed-source Apple thing? So, what good would filing a Swift bug do? Or am I completely wrong and SourceKit is in fact controlled by the open-source Swift initiative in some way?

**Comment by jpsim** [comment]
It's open source 😄 

https://github.com/apple/swift/tree/master/tools/SourceKit

**Comment by ThatsJustCheesy** [comment]
Great to know, and thanks for being so helpful!
I've filed the bug as [SR-4311](https://bugs.swift.org/browse/SR-4311). I'll close this now, as it isn't directly related to Jazzy. Thanks again.

**Comment by jpsim** [comment]
Thanks for filing that!
