### ISSUE TITLE
Extensions don't show correct documentation

### ISSUE THREAD

**Issue by stephencelis** [realm/jazzy#76]
Extensions of native types do this:

![screen shot 2014-11-01 at 8 51 14 am](https://cloud.githubusercontent.com/assets/658/4872318/f495424e-61de-11e4-8a1d-57be1ec2a9ee.png)

My own extensions just re-render the original declaration.

None of the new functions or protocols included in the extensions show up.

**Comment by jpsim** [comment]
This is no longer the case.
