### ISSUE TITLE
Help me please

### ISSUE THREAD

**Issue by santieduardo** [realm/jazzy#763]
`Building native extensions.  This could take a while...
ERROR:  Error installing jazzy:
	ERROR: Failed to build gem native extension.

    current directory: /Library/Ruby/Gems/2.0.0/gems/redcarpet-3.4.0/ext/redcarpet
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -r ./siteconf20170327-6279-1cduu7i.rb extconf.rb
creating Makefile

current directory: /Library/Ruby/Gems/2.0.0/gems/redcarpet-3.4.0/ext/redcarpet
make "DESTDIR=" clean

current directory: /Library/Ruby/Gems/2.0.0/gems/redcarpet-3.4.0/ext/redcarpet
make "DESTDIR="
make: *** No rule to make target `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/include/ruby-2.0.0/universal-darwin15/ruby/config.h', needed by `autolink.o'.  Stop.

make failed, exit code 2

Gem files will remain installed in /Library/Ruby/Gems/2.0.0/gems/redcarpet-3.4.0 for inspection.
Results logged to /Library/Ruby/Gems/2.0.0/extensions/universal-darwin-15/2.0.0/redcarpet-3.4.0/gem_make.out`

**Comment by segiddins** [comment]
Building redcarpet (one of Jazzy's dependencies) seems to have failed

**Comment by santieduardo** [comment]
I have redcarpet installed already, but I still can't install the jazzy :(

**Comment by jpsim** [comment]
@santieduardo could you please follow the steps from #409 and report back?

**Comment by johnfairh** [comment]
Closing, inactive - maybe the Xcode-more-modern-than-OS problem.
