### ISSUE TITLE
Downloading coverage badge fails in 0.7.4 and above

### ISSUE THREAD

**Issue by mgrebenets** [realm/jazzy#765]
Hi there, I've installed `0.7.5` recently and noticed that `jazzy` fails when trying to download a coverage badge.

```
Showing the recent process error output.  Show more
[12:20:58]downloading coverage badge
[12:20:58]/Users/tcagent/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http.rb:879:in `initialize': getaddrinfo: nodename nor servname provided, or not known (SocketError)
[12:20:58]	from /Users/tcagent/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http.rb:879:in `open'
[12:20:58]	from /Users/tcagent/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'
[12:20:58]	from /Users/tcagent/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/timeout.rb:74:in `timeout'
[12:20:58]	from /Users/tcagent/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http.rb:878:in `connect'
[12:20:58]	from /Users/tcagent/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http.rb:863:in `do_start'
[12:20:58]	from /Users/tcagent/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http.rb:852:in `start'
[12:20:58]	from /Users/tcagent/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http.rb:583:in `start'
[12:20:58]	from /Users/tcagent/.rvm/gems/ruby-2.2.2/gems/jazzy-0.7.5/lib/jazzy/doc_builder.rb:267:in `download_badge'
[12:20:58]	from /Users/tcagent/.rvm/gems/ruby-2.2.2/gems/jazzy-0.7.5/lib/jazzy/doc_builder.rb:133:in `build_site'
[12:20:58]	from /Users/tcagent/.rvm/gems/ruby-2.2.2/gems/jazzy-0.7.5/lib/jazzy/doc_builder.rb:161:in `build_docs_for_sourcekitten_output'
[12:20:58]	from /Users/tcagent/.rvm/gems/ruby-2.2.2/gems/jazzy-0.7.5/lib/jazzy/doc_builder.rb:78:in `build'
[12:20:58]	from /Users/tcagent/.rvm/gems/ruby-2.2.2/gems/jazzy-0.7.5/bin/jazzy:15:in `<top (required)>'
[12:20:58]	from /Users/tcagent/.rvm/gems/ruby-2.2.2/bin/jazzy:23:in `load'
[12:20:58]	from /Users/tcagent/.rvm/gems/ruby-2.2.2/bin/jazzy:23:in `<main>'
[12:20:58]	from /Users/tcagent/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `eval'
[12:20:58]	from /Users/tcagent/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `<main>'
[12:20:58]
[12:20:58]Process exited with code 1
```

This doesn't just happen on TeamCity build server, but also on my development machine, which has more connectivity to outside world.

Our build agents have very restricted connectivity to external resource, so I wonder if badge downloading (and any other n/w calls) could be controlled via a command line switch?

**Comment by johnfairh** [comment]
Don't know if this helps but you can do "jazzy --hide-documentation-coverage" -- this prevents download of the badge but also means the coverage % is not displayed in the docs.

**Comment by jpsim** [comment]
I think this is how connectivity errors from downloading the badge are reported.

I was briefly wondering if the fact that you're on Ruby 2.2.2 had any effect, but I just ran jazzy locally with that version of Ruby and it downloaded the badge just fine.

**Comment by mgrebenets** [comment]
@johnfairh that would work, but we actually need the coverage %. We grep it from index HTML and use as a metrics value :)

@jpsim I guess that's related to our internal n/w and all kinds of security limitations around it. What is the shield URL? I could try to curl it directly or try to pull it from Ruby script and potentially find a workaround.

**Comment by jpsim** [comment]
Here's how the URL is generated: https://github.com/realm/jazzy/blob/v0.7.5/lib/jazzy/doc_builder.rb#L265-L266

**Comment by mgrebenets** [comment]
So I can see that the badge downloading was added in `0.7.5` compared to `0.7.3`.

Interestingly, I can successfully run `curl` like so:

```shell
curl https://img.shields.io/badge/documentation-75%25-yellow.svg
```

Even behind the proxy.

But when I run `jazzy` command, it fails with the error I posted in the issue description.

As if it can't resolve the host name.
Could it be that `Net::HTTP.start` doesn't respect HTTP proxy env vars by default?
I have all 4 env vars set: `HTTP[S]_PROXY` and `http(s)_proxy`.

Documentation seems to imply that `Net::HTTP.new` will respect env vars, but doesn't mention the same for `Net::HTTP.start`. Maybe this is the root cause?

In any case, even if proxy issue is solved, it will only work on my dev machine, but I also need to make it work on build server, which can't connect to `shields.io` with or without proxy.

So could it be one of these options:
- Fall back to using simple text if badge download fails
- Add option to disable badge download

I know that i can use `--hide-documentation-coverage` but that's not exactly what I need.
I really need to coverage information, but I could do without SVG badge.

**Comment by jpsim** [comment]
added in d895379: `jazzy --no-download-badge`

**Comment by Mozahler** [comment]
No worries, but I got a similar message.
downloading coverage badge
/Users/Alex/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/net/http.rb:882:in `rescue in block in connect': Failed to open TCP connection to img.shields.io:443 (getaddrinfo: nodename nor servname provided, or not known) (SocketError)
	from /Users/Alex/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/net/http.rb:879:i

**Comment by vicng** [comment]
This is the error I've been getting with v0.8.2:
```
downloading coverage badge
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:921:in `connect': SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: sslv3 alert handshake failure (OpenSSL::SSL::SSLError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:921:in `block in connect'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:52:in `timeout'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:921:in `connect'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:862:in `do_start'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:851:in `start'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:582:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.8.2/lib/jazzy/doc_builder.rb:265:in `download_badge'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.8.2/lib/jazzy/doc_builder.rb:133:in `build_site'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.8.2/lib/jazzy/doc_builder.rb:158:in `build_docs_for_sourcekitten_output'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.8.2/lib/jazzy/doc_builder.rb:78:in `build'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.8.2/bin/jazzy:15:in `<top (required)>'
	from /usr/local/bin/jazzy:22:in `load'
	from /usr/local/bin/jazzy:22:in `<main>'
```

I think "--no-download-badge" should be default and you should specify a flag to download it. The feature is a nice-to-have, but it makes jazzy harder to use and is causing all sorts of errors.

**Comment by jpsim** [comment]
No. The solution to this specific issue is to avoid using the very outdated OpenSSL used by macOS's system Ruby. Perhaps shelling out to `curl` would be an acceptable solution.

**Comment by vicng** [comment]
It also assuming connectivity when jazzy is being run.

Again, "avoid using the very outdated OpenSSL" makes it harder to use jazzy -- I have to actively go fix that problem to fix this problem.

**Comment by jpsim** [comment]
> Again, "avoid using the very outdated OpenSSL" makes it harder to use jazzy -- I have to actively go fix that problem to fix this problem.

Not if we do what I suggested in my previous comment.

**Comment by jpsim** [comment]
Done in #830.
