### ISSUE TITLE
Warnings with "unknown" source

### ISSUE THREAD

**Issue by muffe** [realm/jazzy#769]
Hey there,

in the project I'm currently working on we have a few strange jazzy warnings of undocument code. 
The problem is, the undocumented.json isn't really telling me where.

```
{
  "warnings": [
    {
      "file": "/Users/MobileCI/.jenkins/jobs/myApp/workspace/myApp/AppDelegate.swift",
      "line": null,
      "symbol": "AppDelegate",
      "symbol_kind": "source.lang.swift.decl.extension",
      "warning": "undocumented"
    },
    {
      "file": "/Users/MobileCI/.jenkins/jobs/myApp/workspace/myApp/AppDelegate.swift",
      "line": null,
      "symbol": "AppDelegate",
      "symbol_kind": "source.lang.swift.decl.extension",
      "warning": "undocumented"
    },
    {
      "file": "/Users/MobileCI/.jenkins/jobs/myApp/workspace/myApp/AppDelegate.swift",
      "line": null,
      "symbol": "AppDelegate",
      "symbol_kind": "source.lang.swift.decl.extension",
      "warning": "undocumented"
    }
  ]
}
```

Every line in the AppDelegate.swift is properly documented, so I'm kind of out of ideas right now.

**Comment by johnfairh** [comment]
This means that jazzy thinks there are 3 extensions of a type AppDelegate, and that AppDelegate itself does not have a doc comment.  It sounds like you have documented that -- if really so then I think we need to see the project/recreated example to figure it out.

**Comment by muffe** [comment]
We have an extra file (`AppDelegateExtension.swift`) with 3 `AppDelegate` extensions that look something like this:

```
/// Additional Functions for AppDelegate
extension AppDelegate {
    ....
}

@available(iOS 10, *)
/// Extension for UNUserNotificationDelegate
extension AppDelegate : UNUserNotificationCenterDelegate {
    ....
}

/// Extension for Firebase Messaging Delegate
extension AppDelegate : FIRMessagingDelegate {
    ....
}
```
Anything wrong with that?
But there are no extensions in the `AppDelegate.swift` itself.

**Comment by johnfairh** [comment]
Looks fine!  How is the AppDelegate class itself declared though? -- that is where the tools think there is a missing doc comment.

This works fine for me on jazzy 0.8.2 with a dummy two-file project, file 1:
```swift
import Foundation
/// Removing this comment causes the extensions to register as undocumented
class AppDelegate: NSObject {}
```

file 2:
```swift
import UserNotifications

/// Additional Functions for AppDelegate
extension AppDelegate {
    /// something
    func f1() {}
}

@available(iOS 10, *)
/// Extension for UNUserNotificationDelegate
extension AppDelegate : UNUserNotificationCenterDelegate {
    /// something
    func f2() {}
}
```

(I think your issue must be more complex somehow because your undocumented.json paste above does not have the AppDelegate itself in it...)

**Comment by muffe** [comment]
This is the `AppDelegate` class.

```
import UIKit

@UIApplicationMain

/// The main app delegate class which handles different methods for app activities
class AppDelegate: UIResponder, UIApplicationDelegate {

    /// The main windows
    var window: UIWindow?

   ....
}
```

**Comment by johnfairh** [comment]
Aha!  Move the doc comment above the `@UIApplicationMain`.

This is how Swift/SourceKit work: annotations are part of the declaration so the doc comment must be earlier in the file.

**Comment by muffe** [comment]
`100% documentation coverage with 0 undocumented symbols`

Lovely, thank you very much.
