### ISSUE TITLE
Parameter parsing needs to strip quotes

### ISSUE THREAD

**Issue by reitzig** [realm/jazzy#771]
On the shell, it's prudent to enclose parameter strings into double quotes. While `--author`
deals with them in the expected fashion, passing

	--author_url "<URI>"

to Jazzy leads to a rather graceless exception because the URI parsing method is called with `"<URI>"` instead of `<URI>`. I assume that other parameters have the same issue with the quotes ending up in the wrong places.

**Comment by segiddins** [comment]
This sounds like an issue with your shell rather than with jazzy

**Comment by reitzig** [comment]
I used bash like so:

```bash
command="jazzy ... --author_url \"<URI>\""
exec ${command}
```

(Whichever the cause, I use a config YAML now which does not have the problem.)

**Comment by jpsim** [comment]
closing for the reason Sam shared above.
