### ISSUE TITLE
Giving error while referring to Public nested files

### ISSUE THREAD

**Issue by ankitthakur** [realm/jazzy#774]
<img width="1105" alt="screen shot 2017-04-24 at 12 24 43 pm" src="https://cloud.githubusercontent.com/assets/75362/25325407/0f0f8750-28e9-11e7-8bef-cdb3b1625bbd.png">
I am having files in public folder, and using synx(https://github.com/venmo/synx), I have organized XCode groups with file system folders.

But when I am compiling the creating jazzy doc, it is giving error that public file is not found.

**Comment by jpsim** [comment]
I'm happy to look at this if you share all the info I'd need to be able to reproduce.

**Comment by johnfairh** [comment]
Closing this now, inactive.
