### ISSUE TITLE
Jazzy/SourceKitten fails to parse compiler arguments from `xcodebuild` output.

### ISSUE THREAD

**Issue by Laptopmini** [realm/jazzy#781]
Using the following command
```
jazzy \
  --clean \
  --author MyName \
  --author_url https://mydomain.com/ \
  --xcodebuild-arguments -workspace,My-App.xcworkspace,-scheme,My-App \
  --output docs/swift_output \
  --theme docs/themes
```

I get the following output
```
Could not parse compiler arguments from `xcodebuild` output.
Please confirm that `xcodebuild` is building a Swift module.
Saved `xcodebuild` log file: /var/folders/0v/dcycxcpd077_f6kfmrsl4_843dnlsl/T/xcodebuild-1829F6C3-7E62-41EE-86B7-826741D160FB.log
Failed to generate documentation
/Users/XXX/.rvm/gems/ruby-2.2.4/gems/jazzy-0.7.2/lib/jazzy/executable.rb:36:in `execute_command': /Users/XXX/.rvm/gems/ruby-2.2.4/gems/jazzy-0.7.2/lib/jazzy/SourceKitten/bin/sourcekitten ["doc", "--", "-workspace", "My-App.xcworkspace", "-scheme", "My-App"] (RuntimeError)
```

When I check the log, it ends with the following
```
** BUILD SUCCEEDED **
```

It seems that it is failing to parse the arguments passed in for `xcodebuild`. After reading #758, @jpsim seems to claim that "C99 [does not allow] for module names including hyphens".

My module name includes a hyphen, are you sure this is true? Is it possible to resolve this without having to modify the project name?
For other reasons (internal), I need to keep this module name.

**Comment by Laptopmini** [comment]
As instructed in #764, I ran the following commands
```
export SOURCEKIT_LOGGING=3
sourcekitten doc -- -workspace My-App.xcworkspace -scheme My-App
```
Yielding the same output as above, with a successful build. 

I'm not at liberty to upload the full log file at this time, I hope I have provided enough information. Thanks for any help.

**Comment by Laptopmini** [comment]
I attempted to duplicate the scheme using the name `MyAppTemp` and run jazzy using the new hyphen-less scheme, with no success.

I have doubts the hyphen is the problem at this point.

**Comment by Laptopmini** [comment]
I've found the source of my problem. The wrong workspace was being used, my bad.

I ran into other problems, I will be opening a separate ticket as the information above is not relevant anymore.

**Comment by Laptopmini** [comment]
My mistake, I thought I had found the origin of the problem, but it was just resolved by a clean build. 

This problem still remains. I am very confused at this point.

**Comment by jpsim** [comment]
Jazzy expects the module name to match the scheme name, so if they don't match, you'll need to explicitly specify the module name:

```
jazzy \
  --clean \
  --author MyName \
  --author_url https://mydomain.com/ \
  --xcodebuild-arguments -workspace,My-App.xcworkspace,-scheme,My-App \
  --output docs/swift_output \
  --theme docs/themes
  --module My_App
```

**Comment by Laptopmini** [comment]
That worked! Making progress!

I am getting to the following
```
5% documentation coverage with 52 undocumented symbols
building site
```

Followed by an error
```
/Users/XXX/.rvm/gems/ruby-2.2.4/gems/mustache-0.99.8/lib/mustache/settings.rb:142:in `read': No such file or directory @ rb_sysopen - /Users/XXX/Documents/iOS Repository/REDACTED/docs/themes/templates/doc.mustache (Errno::ENOENT)
```

Which seems to be cause by "invoking Jazzy with a nonexistent custom theme"
according to https://github.com/realm/jazzy/issues/550#issuecomment-233789879

For which the root cause seems to be because the "readme's example command uses a custom theme, so new users pasting example commands without too much thought will experience this."

I resolved this by removing the line
```
--theme docs/themes \
```
from my jazzy command.

Thanks for the help!

**Comment by vijayvirEfuel** [comment]
@Laptopmini I am facing issue, when pod is install and workspace is there. The documentation is not made. any clue where is problem
