### ISSUE TITLE
Problems compiling documentation for Objective-c framework

### ISSUE THREAD

**Issue by nrbrook** [realm/jazzy#791]
Here's my command for Jazzy to create documentation for my pre-compiled framework `MyFramework.framework`:
```
jazzy \
  --clean \
  --author Nick \
  --author_url https://nickbrook.me \
  --objc \
  --sdk iphoneos \
  --umbrella-header MyFramework/MyFramework.h \
  --framework-root . \
  --module MyFramework \
  --module-version "1.0.0" \
  --documentation ../docs/include/*.md \
  --output ../docs/objc_output
```
Firstly, what is the `--framework-root` option? The help says
```
--framework-root PATH        The root path to your Objective-C framework.
```
So is the 'root' the MyFramework.framework directory or the directory containing it? I assume the former, but your AFNetworking example uses `.`, so I'm not sure what directory that is.

Secondly, what is the `--umbrella-header` option? The help says
```
--umbrella-header PATH       Umbrella header for your Objective-C framework.
```
Is that the path to the header relative to the framework? Or the import path e.g. `MyFramework/MyFramework.h`?  In your AFNetworking example you use `--umbrella-header AFNetworking/AFNetworking.h`, so I assume the latter.

I think the help/documentation could be improved on both those options, perhaps with examples.

With both those assumptions, the command does not work. I get the error
```
error: error reading '/Users/nick/Documents/MyFramework/MyFramework.framework/MyFramework/MyFramework.h'
```
So it looks like Jazzy is using the `umbrella_header` as a relative path to the framework root. So if I use `--umbrella-header Headers/MyFramework.h` I then get:
```
/Users/nick/Documents/MyFramework/MyFramework.framework/Headers/MyFramework.h:11:9: fatal error: 'MyFramework/IncludedFile.h' file not found
```
The import statement is `#import <MyFramework/IncludedFile.h>`. What am I doing wrong?

**Comment by SketchK** [comment]
Could your share your `command line` or `.jazzy.yaml` ?

**Comment by nrbrook** [comment]
I did, at the top. The only different being the umbrella header path changed to Headers/MyFramework.h which seems to get further. I don't think it needs to be ./ as it finds the umbrella header and the example isn't. I think framework imports such as `#import <MyFramework/IncludedFile.h>` are not being mapped correctly to the Headers directory.

**Comment by nrbrook** [comment]
Does anybody have any more help with this?

I also tried this command:

```
jazzy \
  --objc \
  --clean \
  --author Nick \
  --author_url https://nickbrook.me \
  --module-version 1.0.0 \
  --sdk iphoneos \
  --umbrella-header MyFramework/MyFramework.h \
  --framework-root . \
  --xcodebuild-arguments --objc,MyFramework/MyFramework.h,--,-x,objective-c,-isysroot,$(xcrun --show-sdk-path --sdk iphoneos) \
  --module MyFramework \
  --output docs/objc_output
```

But it fails as the `-I` option is not valid. Removing all the `-I` generation from sourcekitten.rb gets past that, but then fails with the same error as before: `fatal error: 'MyFramework/IncludedFile.h' file not found`

**Comment by mgrebenets** [comment]
@nrbrook It looks related to https://github.com/realm/jazzy/issues/636 in some ways.

In your last example, the `MyFramework/IncludedFile.h` is not found, because `--umbrella-header`, `--module` and `--framework-root` options are ignored. Ignored because you have explicitly specified `--xcodebuild-arguments`. So you would have to provide all the `-I` options as part of xcodebuild options too.

There's more info in #636 discussion.
There is also a very interesting workaround here https://github.com/Instagram/IGListKit/pull/93, which may help.

On the side note, I find `--xcodebuild-arguments` name a bit confusing, because technically those are passed to `clang`, not to `xcodebuild`. At least that seems to be the case with Objective-C code.
Probably those should be called `--clang-arguments` or `--compiler-arguments`...

**Comment by mgrebenets** [comment]
I can also see you output Objective-C documentation in separate directory.
Just curious, have you dealt with mix-and-match frameworks yet (those that have both Swift and ObjC)?
We have one particular framework with both languages and I'm looking for the best way to generate documentation. It's either having 2 documentation sets and publishing them separately, or somehow finding a way to merge the two together, if possible.

**Comment by nrbrook** [comment]
Thanks for the reply @mgrebenets , but it seems like jazzy is discovering all my headers with the --xcodebuild-arguments option, it's just SourceKitten or something it calls doesn't like the -I options any more, and errors out. I'll have a go at moving the headers directory as I really need to get this working. Thanks

**Comment by nrbrook** [comment]
@mgrebenets I'm not sure, the output path was from the example

**Comment by nrbrook** [comment]
Ok, I've not got most of the way there. Previously I was using an old version of sourcekitten, so some of my problems can be ignored. With 0.8.1, after renaming the binary out the way and renaming the Headers directory to MyFramework jazzy works, however it outputs the errors

```
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.3.sdk/usr/include/sys/cdefs.h:761:2: error: Unsupported architecture
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.3.sdk/usr/include/machine/types.h:37:2: error: architecture not supported
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.3.sdk/usr/include/machine/_types.h:34:2: error: architecture not supported
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.3.sdk/usr/include/sys/_types.h:55:9: error: unknown type name '__int64_t'
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.3.sdk/usr/include/sys/_types.h:56:9: error: unknown type name '__int32_t'
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.3.sdk/usr/include/sys/_types.h:57:9: error: unknown type name '__int32_t'
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.3.sdk/usr/include/sys/_types.h:60:9: error: unknown type name '__uint32_t'
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.3.sdk/usr/include/sys/_types.h:61:9: error: unknown type name '__uint32_t'
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.3.sdk/usr/include/sys/_types.h:62:9: error: unknown type name '__uint64_t'
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.3.sdk/usr/include/sys/_types.h:68:9: error: unknown type name '__darwin_natural_t'
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.3.sdk/usr/include/sys/_types.h:70:9: error: unknown type name '__uint16_t'
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.3.sdk/usr/include/sys/_types.h:71:9: error: unknown type name '__int64_t'
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.3.sdk/usr/include/sys/_types.h:72:9: error: unknown type name '__int32_t'
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.3.sdk/usr/include/sys/_types.h:73:9: error: unknown type name '__uint32_t'
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.3.sdk/usr/include/sys/_types.h:74:9: error: unknown type name '__int32_t'
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.3.sdk/usr/include/sys/_types.h:75:9: error: unknown type name '__uint32_t'
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.3.sdk/usr/include/sys/_types.h:76:9: error: unknown type name '__uint32_t'
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.3.sdk/usr/include/machine/endian.h:37:2: error: architecture not supported
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.3.sdk/usr/include/sys/types.h:95:9: error: unknown type name 'u_int64_t'
```

I believe this is the same as issue https://github.com/realm/jazzy/issues/420

I think this is because the architecture is not being passed to xcodebuild, but after a couple hours trying to pass it as an argument to jazzy (failed, not recognised) then editing sourcekitten.rb to pass it to SourceKitten (also failed) then setting environment variables before calling jazzy (also failed) then editing sourcekitten.rb to directly set the environment variables for SourceKitten (also failed) then finally trying to edit the SourceKitten code and recompile sourcekitten (after much messing around, got stuck when the executable can't load libswiftSwiftOnoneSupport.dylib), I've given up.

Here's the variables I'm trying to pass:
```
env['VALID_ARCHS'] = 'arm64'
env['CURRENT_ARCH'] = 'arm64'
env['ARCHS'] = 'arm64'
env['ONLY_ACTIVE_ARCH'] = 'NO'
```

**Comment by mgrebenets** [comment]
@nrbrook Have you tried `--sdk iphonesimulator` instead?
I'd assume for the purpose of generating documentation the target platform should not matter.

**Comment by RockLobster** [comment]
Did you manage to fix this?

**Comment by nrbrook** [comment]
My script which works now looks like this:

```bash
mv $FRAMEWORK_PATH/{$FRAMEWORK_NAME,a}
mv $FRAMEWORK_PATH/{Headers,$FRAMEWORK_NAME}

jazzy \
  --clean \
  --author Author \
  --author_url https://website.com \
  --hide-documentation-coverage \
  --objc \
  --sdk iphonesimulator \
  --umbrella-header $FRAMEWORK_PATH/$FRAMEWORK_NAME/$FRAMEWORK_NAME.h \
  --framework-root $FRAMEWORK_PATH \
  --module $FRAMEWORK_NAME \
  --module-version $version \
  --source-directory "source_dir" \
  --documentation "docs/include_processed/include/*.md" \
  --copyright "© 2018 Author" \
  --readme docs/include_processed/README.md \
  --output docs/objc_output

mv $FRAMEWORK_PATH/{$FRAMEWORK_NAME,Headers}
mv $FRAMEWORK_PATH/{a,$FRAMEWORK_NAME}
```
I've not checked if it has been fixed in jazzy.

**Comment by johnfairh** [comment]
Going to close this now, this is the #667 scenario where include paths do not match in the filesystem.

**Comment by mathieutozer** [comment]
Is it possible to ignore header files imported from other frameworks with the current release? I have objc imports of headers from 3rd party precompiled frameworks that source kitten cannot find and fails with the documented command to generate objcDoc.json

```
doc --objc $(pwd)/MyApp/SomeHeader.h       -- -x objective-c  -isysroot $(xcrun --show-sdk-path --sdk iphonesimulator)       -I $(pwd) -fmodules > objcDoc.json
```

**Comment by johnfairh** [comment]
You will need to add additional `clang` compiler flags to that example command to make it work for your framework.  Prefer you to open new issues to ask for help on new problems.
