### ISSUE TITLE
I can't seem to find a way to create a custom group for Enums and Structs

### ISSUE THREAD

**Issue by rsabau** [realm/jazzy#792]
Does anybody know of a way to group enums and structs like using custom_categories ? is there a roadmap for adding this feature?

**Comment by reitzig** [comment]
What do you mean by "like"? Using custom categories, you can group enums and structs.

**Comment by jpsim** [comment]
@rsabau is there anything else we can help you with?

**Comment by johnfairh** [comment]
Closing as answered.
