### ISSUE TITLE
SourceKitten not happy with 🍒 emoji

### ISSUE THREAD

**Issue by Mozahler** [realm/jazzy#794]
It took me way too long to find out why my project wouldn't compile. I have emoji in other files, and they don't cause this:
Parsing Dummy.swift (24/25)
	from /Users/Alex/.rvm/gems/ruby-2.3.3/gems/jazzy-0.7.5/lib/jazzy/sourcekitten.rb:216:in `run_sourcekitten'
	from /Users/Alex/.rvm/gems/ruby-2.3.3/gems/jazzy-0.7.5/lib/jazzy/doc_builder.rb:67:in `block in build'
	from /Users/Alex/.rvm/gems/ruby-2.3.3/gems/jazzy-0.7.5/lib/jazzy/doc_builder.rb:65:in `chdir'
	from /Users/Alex/.rvm/gems/ruby-2.3.3/gems/jazzy-0.7.5/lib/jazzy/doc_builder.rb:65:in `build'
	from /Users/Alex/.rvm/gems/ruby-2.3.3/gems/jazzy-0.7.5/bin/jazzy:15:in `<top (required)>'
	from /Users/Alex/.rvm/gems/ruby-2.3.3/bin/jazzy:22:in `load'
	from /Users/Alex/.rvm/gems/ruby-2.3.3/bin/jazzy:22:in `<main>'
	from /Users/Alex/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `eval'
	from /Users/Alex/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `<main>'

I extracted the crucial code and attached it.  This file causes the above error. (I have moved on by deleting the 🍒 ) Please let me know if I should have reported this in the SourceKitten repository. I put it here because I was running jazzy.
[Dummy.swift.zip](https://github.com/realm/jazzy/files/966464/Dummy.swift.zip)

**Comment by Mozahler** [comment]
It turns out I have another file which causes a different error, but I believe it is related (it has many cherries in it).  All 24 files are parsed without errors, and then I get a pile of them:
Parsing AirDropUtilities.swift (24/24)
A compile error prevented PDFsByFolder.coreDataConnection from receiving a unique USR. Documentation may be incomplete. Please check for compile errors by running `xcodebuild `.
A compile error prevented PDFsByFolder.model from receiving a unique USR. Documentation may be incomplete. Please check for compile errors by running `xcodebuild `.
A compile error prevented PDFsByFolder.filteredDataOrSearchResults from receiving a unique USR. Documentation may be incomplete. Please check for compile errors by running `xcodebuild `.
A compile error prevented PDFsByFolder.defaultCalendar from receiving a unique USR. Documentation may be incomplete. Please check for compile errors by running `xcodebuild `.
A compile error prevented PDFsByFolder.fetchedResultsController from receiving a unique USR. Documentation may be incomplete. Please check for compile errors by running `xcodebuild `.
A compile error prevented PDFsByFolder.bookkeeping(_:) from receiving a unique USR. Documentation may be incomplete. Please check for compile errors by running `xcodebuild `.
A compile error prevented PDFSearchUtilities.findByName(_:moc:) from receiving a unique USR. Documentation may be incomplete. Please check for compile errors by running `xcodebuild `.
A compile error prevented PDFSearchUtilities.fetch(_:moc:) from receiving a unique USR. Documentation may be incomplete. Please check for compile errors by running `xcodebuild `.
A compile error prevented PDFSearchUtilities.findByPath(_:moc:) from receiving a unique USR. Documentation may be incomplete. Please check for compile errors by running `xcodebuild `.
A compile error prevented PDFSearchUtilities.findByFolder(_:moc:) from receiving a unique USR. Documentation may be incomplete. Please check for compile errors by running `xcodebuild `.
A compile error prevented PDFSearchUtilities.findRecent(_:moc:) from receiving a unique USR. Documentation may be incomplete. Please check for compile errors by running `xcodebuild `.
A compile error prevented PDFSearchUtilities.findAllPDFDocs(_:) from receiving a unique USR. Documentation may be incomplete. Please check for compile errors by running `xcodebuild `.
94% documentation coverage with 18 undocumented symbols
I've attached the file without cleanup (it is a couple of years old, the only changes have been to get it to compile with language updates along the way 🙄)
[PDFsByFolder.swift.zip](https://github.com/realm/jazzy/files/966466/PDFsByFolder.swift.zip)

**Comment by johnfairh** [comment]
The latest version of sourcekitten has no problem with this file.  The version of sourcekitten included with jazzy does crash as you've discovered.  Looks like jpsim/sourcekitten#350.

**Comment by Mozahler** [comment]
Great news.  Thanks.

**Comment by jpsim** [comment]
Let's keep this open until jazzy itself has the fix. I'm updating jazzy's SourceKitten binary now.
