### ISSUE TITLE
0% documentation coverage

### ISSUE THREAD

**Issue by eSoftist** [realm/jazzy#803]
This is my first experience with jazzy and it's not seems to be working. Before generating documentation of my actual project, I'm trying jazzy with a sample project. I've added a class from this article [Swift Documentation](http://nshipster.com/swift-documentation/) but it's not working. Everytime I run jazzy, I get "0% documentation coverage". Here's screenshot:

![screen shot 2017-05-05 at 4 10 14 pm](https://cloud.githubusercontent.com/assets/22093797/25743660/de3125fc-31ae-11e7-85cf-72ec0f5ef0b5.png)

**Comment by johnfairh** [comment]
Please try `jazzy --min-acl private` -- by default jazzy only documents 'public' declarations.

**Comment by eSoftist** [comment]
Not even internal? How can I set this as default?

**Comment by johnfairh** [comment]
`min_acl: private` In the config file .jazzy.yaml -- see [the readme](https://github.com/realm/jazzy#usage) for more tips.

**Comment by eSoftist** [comment]
Alright. Thanks.

**Comment by eSoftist** [comment]
@johnfairh sorry for not getting how to use .jazzy.yaml. I couldn't find it in my project at any level. Therefore I created a new file and set --min-acl to private. However, it gave me the error:
![screen shot 2017-05-08 at 12 57 03 pm](https://cloud.githubusercontent.com/assets/22093797/25795267/0ab34db2-33ee-11e7-8366-6998e723021e.png)

**Comment by johnfairh** [comment]
The .jazzy.yaml file should contain `min_acl: private`.

You can see what the config file keys are for each CLI option in `jazzy --help config`.

**Comment by eSoftist** [comment]
Alright. Got it.
