### ISSUE TITLE
Auto-linking HTML-escaped operators

### ISSUE THREAD

**Issue by reitzig** [realm/jazzy#805]
Say I have code like this:

```swift
indirect enum Expr {
	case .number(Int)

	/**
		- Seealso: `Expr.&(...)`
	*/
	case .and(Expr, Expr)

	static func &(lhs: Expr, rhs: Expr) -> Expr {
		return .and(lhs, rhs)
	}
}
```

How do I refer to `&` in a way that auto-links? 

Neither `&` (locally), `Expr.&`, `Expr.&(...)`, nor `Expr.&(lhs:rhs:)` work.

**Comment by johnfairh** [comment]
The most reliable way is, in this case, `+(_:_:) or `Expr.+(_:_:)` -- the part after the period is the name that jazzy thinks the symbol has, as show in its doc page.

I also found that `Expr.+(...)` worked for me, the ... works as a sort of wildcard.

**Comment by reitzig** [comment]
Hm... did you also try it in the callout? I'm on v0.8.1, if that's relevant. 

I'm looking at the generated doc right now, and there's no link. (Things are called by different names, but that shouldn't be a problem? My operator is `&`.)

**Comment by johnfairh** [comment]
You're right, '&' doesn't work -- it's coming in as `&amp;` to a routine that is not expecting that :/

![screen shot 2017-05-11 at 14 04 02](https://cloud.githubusercontent.com/assets/26768470/25950392/bb165c74-3652-11e7-951c-e7daa3866292.png)

**Comment by reitzig** [comment]
Ahh, oh my! Editing the original post so it's immediately clear what the issue is.

Given that Swift allows Unicode identifiers, apparently some hardening has to happen.

**Comment by SDGGiesbrecht** [comment]
Does the flag `--use-safe-filenames` handle the ampersand? When it is turned on, Jazzy sanitizes any characters that are bad to use in URLs (the definition of which characters are “bad” is left up to Ruby).

**Comment by SDGGiesbrecht** [comment]
P.S. At least with `--use-safe-filenames` on,  I can reliably link with things like `×(_:_:)` and `√(_:)`, so this is related to HTML, not Unicode.

**Comment by johnfairh** [comment]
That flag doesn't help here: the problem happens before generating the link, code is matching html-escaped text from markdown output against real declaration names. Yes general unicode is fine, it's just the html escapes & < > that cause problems AFAICT.

**Comment by SDGGiesbrecht** [comment]
I just verified it. @johnfairh, you are right on all counts. I stand corrected.

**Comment by johnfairh** [comment]
Fixed in master.
