### ISSUE TITLE
Updated Xcode and now sourceKitten unable to find xcode swift version

### ISSUE THREAD

**Issue by smacnabb3** [realm/jazzy#808]
I updated Xcode to 8.3.2 and now I am getting the 'run_sourcekitten': Unable to to find an Xcode version with 3.1.  I am using the most up to date Swift version and have double checked to see that is what is indeed installed on the machine.  I also am using the most up to date version of Jazzy, so I'm confused as to what the issue would be. 

/Library/Ruby/Gems/2.0.0/gems/jazzy-0.8.1/lib/jazzy/sourcekitten.rb:210:in `run_sourcekitten': Unable to find an Xcode with swift version 3.1. (RuntimeError)
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.8.1/lib/jazzy/doc_builder.rb:67:in `block in build'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.8.1/lib/jazzy/doc_builder.rb:65:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.8.1/lib/jazzy/doc_builder.rb:65:in `build'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.8.1/bin/jazzy:15:in `<top (required)>'
	from /usr/local/bin/jazzy:23:in `load'
	from /usr/local/bin/jazzy:23:in `<main>'

**Comment by johnfairh** [comment]
You might try *not* setting `--swift-version`.  I think this error means you are currently setting that flag and then XCInvoke is not finding Xcode (maybe because spotlight hasn't re-indexed since the install??)

**Comment by smacnabb3** [comment]
thank you for responding so quick.  I figured that was the issue but couldn't see a clear way of solving it on my end.  I did already try removing --swift-version out of it and I get an odd error of: 

Unrecognized arguments: -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I, -I

this is how i'm generating them:  (also everything had been working just fine till I updated Xcode grrr)
jazzy \
    --clean \
    --objc \
    --author redacted \
    --author_url AE \
    --root-url AE/v$STRIPPED_SDK_VERSION/class-docs \
    --module redacted \
    --module-version $STRIPPED_SDK_VERSION \
    --framework-root $SRCROOT \
    --umbrella-header $UMBRELLA_HEADER \
    --theme apple \
    --xcodebuild-arguments --objc,$UMBRELLA_HEADER, objective-c,-isysroot,`xcrun --show-sdk-path --sdk iphonesimulator`, $SRCROOT\AE.xcodeproj,-destination 'platform=iOS Simulator,OS=10.3,name=iPhone 7' \
    --output $DOCS_ROOT/v$STRIPPED_SDK_VERSION/class-docs

**Comment by johnfairh** [comment]
I don't know much about the objc side -- there are quite a few open+closed issues similar to this that might help you though.  

If you set --xcodebuild then you should not set --framework-root or --umbrella-header because you put those in the -x content and they cause the -I proliferation.

I might try:
jazzy
--clean --objc --author ... --author_url ... --root-url ... --module ... --module-version ... --theme apple
-x --objc,$UMBRELLA_HEADER,--,-x,objective-c,-isysroot,\`xcrun --show-sdk-path --sdk iphonesimulator\`,-I,$SRCROOT
--output ...

...and add any more "-I,path" pairs for subdirectories accessed by the umbrella header.

**Comment by smacnabb3** [comment]
So i've been struggling with this for a while and i'm finally just going to ask.  Is the blank (--,) command still in use.  I keep getting an `parse_command_line`:invalid option: --,    (optionParser::InvalidOption) when using this

**Comment by smacnabb3** [comment]
I forgot to mention, when I do remove the --, parameter, I then get the exact error but with -isysroot.

**Comment by johnfairh** [comment]
Jazzy doesn't have a `--` option.  The `--` above is supposed to be part of the sourcekitten args that are comma-separated following the `-x`.

I did a v. bad job of formatting that previous post, sorry -- I've added fixed-pitch formatting now that I hope makes it clearer.

**Comment by johnfairh** [comment]
Closing this one, advice to original problem added to readme.
