### ISSUE TITLE
Set version of generated Docset

### ISSUE THREAD

**Issue by reitzig** [realm/jazzy#810]
If I import the generated Docset into "Docs for Xcode", I see `Version (null) (null)`. `module_version` is set in the Jazzy config file.

**Comment by jpsim** [comment]
Xcode docsets aren't generated... are you using Dash? Can you share more information?

**Comment by reitzig** [comment]
I don't use Dash (what is that?), but a Docset still appears in `<build>/docsets`.

I call Jazzy with options `--clean`, `--config <my file>` and `--sdk iphoneos`. In the config file, I set the output directory, custom categories, documentation, readme and abstract, plus some meta data.

**Comment by jpsim** [comment]
The Docset is a Dash-format docset: https://kapeli.com/dash

Jazzy doesn't generate Xcode-formatted docsets.

You say you see `Version (null) (null)`, but you don't say where you see that... 🤔

**Comment by reitzig** [comment]
Ah, okay. I tried opening it with XCode or whatever tool macOS has by default. If that's not supposed to work, this ticket is void.
