### ISSUE TITLE
Crash generating docs from Swift code, backtrace involves fileprivate

### ISSUE THREAD

**Issue by barrypress** [realm/jazzy#814]
I'm getting a crash as follows on the project I'm documenting:

> Stormwind:sim press$ jazzy --author "Barry Press" --min-acl private --no-skip-undocumented
Running xcodebuild
Parsing Args.swift (1/15)
Parsing CSVRead.swift (2/15)
Parsing Option.swift (3/15)
Parsing CommandLine.swift (4/15)
Parsing Events.swift (5/15)
Parsing AVLTree.swift (6/15)
Parsing StringExtensions.swift (7/15)
Parsing Digital.swift (8/15)
Parsing Engine.swift (9/15)
Parsing SimValue.swift (10/15)
Parsing Extensions.swift (11/15)
Parsing Vector.swift (12/15)
Parsing QueueEntry.swift (13/15)
Parsing StreamReader.swift (14/15)
Parsing main.swift (15/15)
/Library/Ruby/Gems/2.0.0/gems/jazzy-0.7.0/lib/jazzy/source_declaration/access_control_level.rb:18:in `initialize': cannot initialize AccessControlLevel with 'source.lang.swift.accessibility.fileprivate' (RuntimeError)
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.7.0/lib/jazzy/source_declaration/access_control_level.rb:26:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.7.0/lib/jazzy/source_declaration/access_control_level.rb:26:in `from_doc'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.7.0/lib/jazzy/sourcekitten.rb:298:in `block in make_source_declarations'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.7.0/lib/jazzy/sourcekitten.rb:268:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.7.0/lib/jazzy/sourcekitten.rb:268:in `make_source_declarations'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.7.0/lib/jazzy/sourcekitten.rb:253:in `make_substructure'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.7.0/lib/jazzy/sourcekitten.rb:303:in `block in make_source_declarations'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.7.0/lib/jazzy/sourcekitten.rb:268:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.7.0/lib/jazzy/sourcekitten.rb:268:in `make_source_declarations'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.7.0/lib/jazzy/sourcekitten.rb:270:in `block in make_source_declarations'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.7.0/lib/jazzy/sourcekitten.rb:268:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.7.0/lib/jazzy/sourcekitten.rb:268:in `make_source_declarations'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.7.0/lib/jazzy/sourcekitten.rb:537:in `parse'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.7.0/lib/jazzy/doc_builder.rb:141:in `build_docs_for_sourcekitten_output'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.7.0/lib/jazzy/doc_builder.rb:75:in `build'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.7.0/bin/jazzy:15:in `<top (required)>'
	from /usr/local/bin/jazzy:23:in `load'
	from /usr/local/bin/jazzy:23:in `<main>'

In addition, even with the command line options shown, not all of the project is picked up. For example, I have a protocol PrintingEvent that derives from Event, which itself has no parent. Both are in the same file; Event happens to be before PrintingEvent. PrintingEvent shows up in the generated documentation; Event does not.

I can send you the entire project if you like; I'm not clear from the guidelines just how you'd otherwise want the code stripped down, nor if it's necessary that stripped code actually be capable of compiling. The code build that generates the above error compiles and runs successfully.

**Comment by johnfairh** [comment]
Jazzy 0.7.0 is from about a year ago - pre full swift 3 (including fileprivate) support.
If you're still seeing problems on latest jazzy then it's easiest to point at / send the project if possible -- yes it needs to be buildable to run.

**Comment by johnfairh** [comment]
Closing as answered.

**Comment by barrypress** [comment]
Yes, thanks.

Thanks

Barry

---
"They laughed at Columbus, they laughed at Fulton, they laughed at the Wright Brothers. But they also laughed at Bozo the Clown." - Carl Sagan
