### ISSUE TITLE
Responsive Web Design

### ISSUE THREAD

**Issue by segiddins** [realm/jazzy#82]

**Comment by jpsim** [comment]
@yoshyosh what do you think needs to be done for this?

**Comment by yoshyosh** [comment]
We would need to settle on a style for this. Maybe something like a left navigation panel that's hidden by a hamburger type menu? Do you have some screen shots of how dash has handled those cases? I think nesting is where things can potentially get tricky as well.

@mrh-is may be helping with jazzy fixes as well. We will be discussing more tomorrow.

**Comment by jpsim** [comment]
> @mrh-is may be helping with jazzy fixes as well. We will be discussing more tomorrow.

:smile: :smile: :smile:

**Comment by istx25** [comment]
Do we still have plans to do any of this?

**Comment by jpsim** [comment]
> Do we still have plans to do any of this?

Maybe? This is such a fuzzy request, it's hard to say exactly when this would be "complete" or even what we could do to improve the current situation. I'm terrible at web design, so I don't know.

**Comment by istx25** [comment]
Same, though I'm sure we could reach out to open source contributors who are and invite them to contribute to Jazzy. I don't have a lot of experience with web design but it's something I would like to work on learning and getting better at. We can put it on the back burner for now.

**Comment by johnfairh** [comment]
Covered by 'jony' theme.
