### ISSUE TITLE
Generate ObjectiveC documentation from swift code

### ISSUE THREAD

**Issue by vnramachandra** [realm/jazzy#820]
Hi,

I have a framework **written in swift**. I am using jazzy to generate the documentation. 
But the document generated will only have for Swift. Equivalent ObjectiveC documentation is not getting generated for any of the content. 

Could you please assist us in resolving the issue? 

PFA, a sample framework source which I created and also the documentation generated from it which now **has only for Swift**. Please let us know how could I get it for **both Swift and Objective C.**

[MyFramework.zip](https://github.com/realm/jazzy/files/1009919/MyFramework.zip)

Regards,
Ram

**Comment by johnfairh** [comment]
Jazzy doesn't generate the ObjC versions of declarations for Swift projects.

You might be able to get something usable by running jazzy in ObjC mode against the Xcode-generated header file for your framework (MyFramework-Swift.h, in DerivedData) -- this would be a separate website though; I haven't tried it.

**Comment by johnfairh** [comment]
Closing this one, feature requested covered in #136 it turns out.
