### ISSUE TITLE
Display top-level Swift declaration in Objective-C docs

### ISSUE THREAD

**Issue by ulukaya** [realm/jazzy#827]
https://firebase.google.com/docs/reference/ios/firebasecore/api/reference/Classes/FIRApp

In this example swift name of FirApp is FirebaseApp defined with NS_SWIFT_NAME.

But there is no way to find that out from docs.

**Comment by jpsim** [comment]
This is already being done:

![image](https://cloud.githubusercontent.com/assets/474794/26367369/29920d2a-3fa3-11e7-931b-22a0f664ae25.png)

**Comment by ulukaya** [comment]
In the declaration, but not the class name in Header or Left nav.

**Comment by ulukaya** [comment]
![pjegnfehbeh](https://cloud.githubusercontent.com/assets/821349/26371415/a64ff852-3fc8-11e7-809f-976dd6a53b76.png)

**Comment by ulukaya** [comment]
It wouldn't hurt to have both swift and objc interfaces and header as "FIRApp (FirebaseApp in Swift)" etc

**Comment by jpsim** [comment]
That's a distinctly different request than what you filed. I'll update your ticket to reflect that.

The "FIRApp (FirebaseApp in Swift)" in the sidebar can potentially be quite verbose and I'm not sure it'd be wise to unconditionally do that.

**Comment by ulukaya** [comment]
Absolutely, only if there is (manual name overriding)NS_SWIFT_NAME statement exist.

I see the concern on the verbosity, maybe only the declaration for now then.

**Comment by ulukaya** [comment]
Actually if I can create a Swift-first doc from objc headers, that'd do my work. By swift-first I mean, both header and Nav names using the Swift names instead of objc-names where they differ.

**Comment by johnfairh** [comment]
Old issue cleanup: jazzy 0.12 added the Swift declaration to the declaration and properly supported `--hide-declarations objc` to generate a 'pure swift' api docset from objc sources.
