### ISSUE TITLE
Tips for integration with other documentation schemes

### ISSUE THREAD

**Issue by pottmi** [realm/jazzy#834]
I am documenting some swift libraries.  The documentation needs to to suitable for developers as well as business analysts (technical, but not developers).   The BAs will look at the configuration aspects of the code rather than the code itself.

It seems Jazzy is really good at producing reference documentation for the code.

Does anyone have tips for integrating other documentation schemes with Jazzy to create documentation that goes beyond reference documentation?

Here are some samples of what I would like:
1.  import images.

2. mark code fragments and have them imported as code blocks in the documentation.

3. Make arbitrary .md files that are subsequently processed into linkable .html files.

**Comment by SDGGiesbrecht** [comment]
Unless I misunderstand you, all of these are already possible.

First, documentation comments are in a [Swift flavour of Markdown](https://developer.apple.com/library/content/documentation/Xcode/Reference/xcode_markup_formatting_ref/#//apple_ref/doc/uid/TP40016497-CH2-SW1). (That document describes two distinct, albeit related kinds of markup. Jazzy currently supports what the document calls “symbol documentation” (`///`) but not what the document calls “playground documentation” (`//:`).)

You can read about Jazzy’s features on the main [read‐me](https://github.com/realm/jazzy) and get more details by running `jazzy --help` or `jazzy --help config`.

Regarding your specific questions:

1. Import Images

Use `![Alternate text](url.of/resource)`. You will need to host the image separately, but it will be displayed as long as the URL is accessible.

2. Mark Code Fragments

Fence the code block like this:

    ```swift
    This will be treated as code.
    ```

3. Arbitrary Markdown Files

Pass them to the `--documentation` flag. For example:

```shell
jazzy --documentation=Documentation/*.md
```

Using the above, every file ending in `.md` in the folder named `Documentation` will be processed. By default, you will see them at the top of the of the navigation sidebar under “Guides”, but you can customize that using categories.

**Comment by pottmi** [comment]
You hit the mark on #1 and #3.

For #2 here is what I am looking for:

In the code:
// @BeginCodeBlock sample1
enum Example {
    case A
    case B
    case C
    case D
}
// @EndCodeBlock

Then in the markup do something like this:
~~~
## sample enumeration
@CodeBlock sampl1
~~~
Which would be equivalent to (but without the redundancy):

~~~
## sample enumeration
~~ ~
enum Example {
    case A
    case B
    case C
    case D
}
~~ ~
~~~

The reason I am asking for that is because I can do that in doxygen.

**Comment by SDGGiesbrecht** [comment]
@pottmi, no, Jazzy cannot do #2 on its own.

I think [Workspace](https://github.com/SDGGiesbrecht/Workspace/blob/master/Documentation/Examples.md) can team up with Jazzy to accomplish what you want in at least some situations.

**Comment by pottmi** [comment]
Workspace looks very interesting and useful for people making tutorials.

I am going to leave this ticket open for comment for a while longer to see if we can draw additional comments about Jazzy integration with other documentation tools.

**Comment by johnfairh** [comment]
Closing this one now.
