### ISSUE TITLE
@see tags don't automatically link to references in ObjC

### ISSUE THREAD

**Issue by gw280** [realm/jazzy#835]
I'm using Jazzy to document an Objective-C project and so far it's been great. One big limitation I've found though is that @see tags don't automatically generate links.

I could hack around it by doing something like
    `@see [Method](#bookmarkformethod)`

But this would be pretty tedious.

Are there any plans to support link generation for @see?

**Comment by johnfairh** [comment]
If you put the symbol inside backticks `` `Method` `` then jazzy will try to 'autolink' to the definition if it's in your project -- there are some issues but it generally works.

**Comment by gw280** [comment]
Thanks! That seems to work well for cross referencing APIs in the same interface, but I can't seem to get it to work for referencing methods in other classes. Is that possible?

**Comment by johnfairh** [comment]
Yes - the syntax is like `` `-[OtherClass removeAll]` ``, or `` `-[OtherClass removeWithId:]` `` -- post the code if you still have problems.

**Comment by johnfairh** [comment]
Closing as answered.
