### ISSUE TITLE
What could be the jazzy commands for objective C project? and Swift project which has objective C file also?

### ISSUE THREAD

**Issue by NarayanaMV** [realm/jazzy#838]
I have my Swift project which contains some objective C files also. When I tried using

jazzy --objc --umbrella-header JazzyPOC/JazzyPOC-Bridging-Header.h  --framework-root . --sdk iphonesimulator

above command, docs folder has been created but without having any content. Excluding objective C files, docs was getting created with proper documentation content.
![screen shot 2017-06-16 at 7 20 34 pm](https://user-images.githubusercontent.com/26486965/27229414-30652568-52c9-11e7-9fe3-3304d2e4c1e2.png)

And for the objective C project alone I am unable to execute command. Could you please help me in getting docs getting created with proper content in both the cases.

**Comment by NarayanaMV** [comment]
**jazzy --min-acl internal**    when I use this command, Only Swift code related documentation is getting created as documentation.

**jazzy --objc --umbrella-header JazzyPOC/JazzyPOC-Bridging-Header.h  --framework-root . --sdk iphonesimulator**.  When I use this command, Only objective C file.h documentation alone is getting prepared in docs.


But How would I get entire project documentation (including Swift, objective C.h and .m files )

**Comment by johnfairh** [comment]
It looks like you've found the right commands for both modes.

Jazzy isn't really able to handle projects containing a mixture of both ObjC and Swift code.

On the objective C side, only the .h files included from the `--umbrella-header` are used to generate documentation -- declarations & comments in .m files are not processed.  The idea is that it's the interface to your module that is being documented.

**Comment by NarayanaMV** [comment]
**jazzy --min-acl internal** , This is working for complete swift files which has swift and objective C files in that project..

**jazzy --objc --umbrella-header JazzyPOC/JazzyPOC-Bridging-Header.h --framework-root . --sdk iphonesimulator** , It is working only in Swift project that contains objective C files. In that project, Jazzy is documenting only objective C files that too .h files only.

I want SWIFT project that has Objective Files completely need to be documented.  If not possible,

I need command for documenting complete OBJECTIVE C project.  

Any favours?

**Comment by johnfairh** [comment]
> **jazzy --objc --umbrella-header JazzyObjC/ViewController.h --framework-root  .**  , This is working for objective C project but only ViewController.h(only this one .h file) file alone is getting documented? Am I giving wrong umbrella header? If so, What can be given as umbrella header to get entire documentation for Objective C project?

In objective C mode, jazzy documents only .h files.  It takes the file passed as `--umbrella-header` and documents everything in there as well as stuff included from there.  So you need to give it a header that includes all the headers you want documented.  If your bridging header doesn't import them all then you could create a special one that does, just for feeding to jazzy.

**Comment by jpsim** [comment]
Closing as answered.
