### ISSUE TITLE
Is there any way to include the source file location in generated doc?

### ISSUE THREAD

**Issue by pcpLiu** [realm/jazzy#839]
Hi realm team,

Is there any option or trick to automatically output the source file location for in generated docs? And even auto linking to repo location?like:

> Defined in source/system/MyClass.swift:Line 192

 

Just see some python doc system has this function, so wondering if it is possible in jazzy.

Thanks.

**Comment by johnfairh** [comment]
If your repo is github then, using `--github-file-prefix` will add a link from every declaration.  If your repo is not github then you could probably use the option anyway and then sed the jazzy-generated html to fix up the URLs to suit.  The ‘Show on GitHub’ text comes from the theme which you could customize, or edit that text along with the URLs.

**Comment by pcpLiu** [comment]
johnfairh , Thanks!
