### ISSUE TITLE
Could not build module 'Foundation' with Objective C++

### ISSUE THREAD

**Issue by eddielong** [realm/jazzy#840]
I'm having problems running Jazzy on my Objective C code base. I keep getting:

> MyHeader.h:10:9: fatal error: could not build module 'Foundation'
> Found conflicting type declarations with the same name, which may indicate a build issue or a bug in Jazzy: function NS_ENUM, function NS_ENUM, function NS_ENUM, function NS_ENUM, function NS_ENUM, function NS_ENUM, function NS_ENUM, function NS_ENUM, function NS_ENUM
> Found conflicting type declarations with the same name, which may indicate a build issue or a bug in Jazzy: unexposed , unexposed , unexposed , unexposed , unexposed , unexposed , unexposed , unexposed , unexposed , unexposed 
> building site
> building search index
> 62% documentation coverage with 68 undocumented symbols
> included 179 symbols
> jam out ♪♫ to your fresh new docs in

From my investigations various places indicate I need to turn on modules. I've attempted to Enable Modules in my project but I have quite a lot of Objective C++ and I can't seem to get the compiler flag -fcxx-modules working. My jazzy command is as follows (I've removed the names of the project as it is a company's product):

> jazzy \
>   --objc \
>   --author MyProj \
>   --author_url http://testing.com \
>   --module MyModule \
>   --module-version 2.0.0 \
>   --umbrella-header Headers/MyProj.h \
>   --framework-root . \
>   --sdk iphoneos \
>   --output $DOCUMENTATION_DIRECTORY \
>   --no-download-badge \
>   --docset-icon=$SCRIPT_DIR/icon.png \
>   --abstract=$SCRIPT_DIR/Docs/*.md \
>   --readme=$SCRIPT_DIR/Docs/main.md

Any one have any clues?

**Comment by johnfairh** [comment]
Groping in the dark a bit, people probably need to see a minimal failing project.

Don't think you should change any modules settings in your project itself.  Jazzy has recently started passing `-fmodules` but not `-fcxx-modules` -- you could try hacking that option in yourself to sourcekitten.rb inside the jazzy gem as a quick test, although I am not sure that it is required by modern Clang.

**Comment by eddielong** [comment]
You're right, attached is a sample project that hows the problem. Modules are enabled by default in my project and I have the same issue

**Comment by eddielong** [comment]
[TestFramework.zip](https://github.com/realm/jazzy/files/1102515/TestFramework.zip)

**Comment by eddielong** [comment]
Run the GenerateDocumention target in Xcode, you'll see it compile the framework and spit out a Documentation directory in the same directory as the project. You'll see an error in Xcode and also NS_ENUM undefined in the documentation. Maybe it is my build process that's broken but I'm not sure why

**Comment by johnfairh** [comment]
Thanks.  The command needs `--sdk iphonesimulator` not `--sdk iphoneos`.  WorksForMe with that change, Xcode 833, jazzy 082.  It's the SDK to run jazzy with, not the SDK that the project will eventually run on.

**Comment by eddielong** [comment]
Awesome thanks @johnfairh 

Might be worth putting this somewhere on the documentation on the main page: https://github.com/realm/jazzy
