### ISSUE TITLE
Parameters and Returns not being rendered in Xcode 9 Beta with Swift 4

### ISSUE THREAD

**Issue by sergiosette** [realm/jazzy#841]
The Parameters and Returns fields are not being rendered in the documentation.
I've checked and it's working for Xcode 8.2
I've also tried to build from the master src. Pulling the master version for the SourceKitten library did not help :(
Is there any plan to add support for Xcode 9 beta?

Thanks

**Comment by johnfairh** [comment]
I had a go at a fix in sourcekitten for the Parameters part, thanks.

Could you post an example of 'Returns' not working?  It looks OK to me without changes -- Jazzy doesn't rely on the same SourceKit thing for Returns as it does Parameters.

**Comment by sergiosette** [comment]
Sorry, the returns part was working, my mistake.
Thanks for the fix 👍
