### ISSUE TITLE
Some classes in sidebar have anchor links instead of link to full documentation.

### ISSUE THREAD

**Issue by hhartz** [realm/jazzy#844]
Swift 3, Xcode 8.3.3, jazzy 0.8.2

Unfortunately I cannot find the root cause of why this happens, reproduce in a simple project, or provide a link to the (customer private) source repo. Posting here, hoping that it's an issue someone has encountered previously.

The symptom is that the class link becomes (redacted some parts between `<>`;

   `file:///.../docs/Other%20Classes.html#/s:C5module16ClassName`

(`module` being the name of the project's module) instead of the expected

   `file:///.../docs/Classes/ClassName.html`

This is using defaults (i.e. no .jazzy.yaml file). Additionally, the file does not exist at the expected location - so a consequence is that it's not possible to view the full documentation, only the abbreviated expanded listing.

**Comment by johnfairh** [comment]
This means jazzy has not found any children of the `ClassName` type to document: in this case the type does not get a page of its own, it just appears in the category page.  Maybe check you have set `--min-acl` to the right thing and put `public` etc. on the methods of `ClassName` you want to include?

**Comment by hhartz** [comment]
@johnfairh oh. my. I missed the public accessors on members in these classes. My bad, and thanks for the fast and accurate response!
