### ISSUE TITLE
Guides don't work when working directory differs from config file folder

### ISSUE THREAD

**Issue by MatkovIvan** [realm/jazzy#846]
`.jazzy.yaml` file contains the following:
```
documentation: ../Guides/*.md
```

And I trying generate documentation from other folder with command like this:
`jazzy --config ../Documentation/.jazzy.yaml`

Other options (`readme` for example) works fine in this use case.

**Comment by johnfairh** [comment]
Could this be the bug reported in #772 :

> `output` and `readme` seem to be relative to the config file but `documentation` and `abstract` are relative to the current working directory.

?

**Comment by MatkovIvan** [comment]
Yes that's it. Closed it, because it's a duplicate. Could you provide ETA to fix?
