### ISSUE TITLE
Report an error if there are unprocessed program arguments

### ISSUE THREAD

**Issue by drekka** [realm/jazzy#850]
jazzy version: 0.8.3

I have two documents in the root of my project: 'Advanced Tricks.md' and 'Usage Guide.md'. 

I tried adding them using `--documentation ./*.md` but only 'Advanced tricks.html' gets added and listed under Guides. 

If I rename 'Advanced Tricks.md' to 'Advanced Tricks.md.old' then 'Usage Guide.html' is generated and added under Guides.

It appears that `--documentation` is generating a sorted list of files to include, but only including the first one as any subsequent documents are neither covered to HTML or added to the list under Guides.

**Comment by SDGGiesbrecht** [comment]
Odd, I’ve never experienced this problem. Neither can I reproduce it now. I just tested it and `--documentation` works properly for me.

@drekka, I believe there must be something specific to your configuration that is triggering it. Can you provide more information? A bare‐bones sample project that manifests the bug?

**Comment by drekka** [comment]
Here's a test project I just built. It has two guides in it. Only Guide.md gets added by Jazzy. If I rename it to AGuide.md.abc, then AnotherGuide.md is added. 

The coco.sh script is the script I'm using to build it.

[JazzyTest.zip](https://github.com/realm/jazzy/files/1140592/JazzyTest.zip)

**Comment by SDGGiesbrecht** [comment]
@drekka 

Sorry. I should have seen it sooner. I wasn’t reading closely enough I guess.

Change `--documentation *.md` to `--documentation=*.md`.

**Comment by drekka** [comment]
Hmm. Is this different to how other arguments are handled. I ask because I've lodged another issue about how arguments are inconsistent in their naming. I'm wondering if there are consistency issues in how the values are passed to. The `--x=y` syntax feels inconsistent with the way most shell programs take arguments and when I saw it in the docs, I assumed it was a typo because `--documentation *.md` seemed to work (almost :-)

**Comment by johnfairh** [comment]
When you type `--documentation ./*.md` your shell expands the asterisk.  So what jazzy receives is `--documentation ./Foo.md ./Bar.md`.  This is not a valid invocation and jazzy should probably complain that it has a leftover argument `./Bar.md`.

By using the `--documentation=./*.md` syntax you avoid the shell expansion.  You could alternatively single-quote the glob.

I will reopen this to track fixing the 'should complain if there's unprocessed stuff left in arguments' -- that might have pushed you in the right direction originally.

**Comment by drekka** [comment]
Oh. Didn't pick up on the shell expansion issue. Would it also work if I did `--documentation "*.md"`?

**Comment by johnfairh** [comment]
sure!

**Comment by shahdhiren** [comment]
If I include like `--documentation=./*.md`, problem is that it will include all MD files in Alphabetic order and I don't want that. I want to have different order for example, first will be O*.md file than I can have A*.md file.

Is this possible with jazzy?

**Comment by johnfairh** [comment]
Old issue cleanup: at some point we made jazzy give a warning on unprocessed CLI options rather than an error that could break users' working-by-accident setups.

**Comment by richardtop** [comment]
This doesn't help
