### ISSUE TITLE
Unable to copy additional resources for documentation.

### ISSUE THREAD

**Issue by drekka** [realm/jazzy#852]
I have documentation which uses images stored in a directory called 'images'. But I cannot find any way to get this directory added to the generated results directory.

--documentation seems like it cannot be added to the command more than once, so trying something like 

    --documentation *.md --documentation *.png

doesn't work. 

Also tried `--documentation images/*.png` but it crashes Jazzy. As does `--documentation **/*.png`.

**Comment by SDGGiesbrecht** [comment]
@drekka, you will find relevant advice in #799 and #834.

Also, `--documentation` is only for `.md` files, not for images or resources.

Feel free to re‐open if you still need help after reading the linked issues.

**Comment by drekka** [comment]
Hi, I'm thinking this needs to be reopened. Currently I've been adding a bash cp after generating the documentation with Jazzy. The cp copies the images directory into the generated docs. This works ok, but presumably won't get included into the docset Jazzy creates in docs/docset.

I think I'd like to see a new argument to Jazzy. Something like this:

    jazzy --include-files file mask, ...

So I could do this:

    jazzy --include-files images/*.png,images/*.jpg

**Comment by SDGGiesbrecht** [comment]
> Currently I've been adding a bash cp after generating the documentation with Jazzy. The cp copies the images directory into the generated docs. This works ok, but presumably won't get included into the docset Jazzy creates in docs/docset.

Correct. It will not be in the `.tgz`. @johnfairh, any suggestions? It looks from #799, that you script this.

@drekka, you can always host the images separately and use absolute URLs in your `.md` files.

> I think I'd like to see a new argument to Jazzy. Something like this: `jazzy --include-files file mask, ...`

Good idea. Please create a new issue for it and call it something like “Add Flag to Include Resources”, so it is clear from the title and first comment that it is a feature request and unrelated to `--documentation`. (You can copy and paste your last comment. Its description is perfect.)

**Comment by drekka** [comment]
New request added. Thanks.
