### ISSUE TITLE
Types with no documented children do not get their own html pages

### ISSUE THREAD

**Issue by drekka** [realm/jazzy#859]
Is there a debug option in Jazzy that allows us to see more details on the processing of the classes?

In my project I currently have 4 classes. 3 of the those classes get their `classes/classname.html` documents generated. The 4th doesn't. It's listed in the list of classes, but instead of the link going to the `classes/classname.html` file like the other 3, it links to the class's anchor in the `Classes.html` file.

The class in question definitely has doco and it's header comments are displayed in the `Classes.html` file. 

As yet, I've not been able to figure out why it's documentation file is not being generated like the other 3. If there are any criteria which stop a file from being generated, I'd like to know. The class is public and compiles just fine.

**Comment by johnfairh** [comment]
This means jazzy cannot find anything to document in the class.  Check the ACL attributes on the members of the class you expect to see documented?

**Comment by drekka** [comment]
Thanks @johnfairh , I worked out in the end I had to have at least one public function or variable. I think I'd like an option to say document them anyway. Just so the way the html pages work is consistent.

**Comment by jpsim** [comment]
> I think I'd like an option to say document them anyway

`--min-acl private` will do that

**Comment by SDGGiesbrecht** [comment]
> --min-acl private will do that

That will do what @drekka said, but not what he meant.

He wants all (public) type symbols to get their own page, even if they have no public children. He does not want to display private symbols.

His reasoning seems to be having a consistent URL pattern to link to.

**Comment by drekka** [comment]
@SDGGiesbrecht is correct. Also that the way the html page displays the doco when there's no separate page looks funny. Using the doco, I expect clicking on a class name to display a separate page. Instead it opens a list of all classes and expands the section for the class. It's breaks the paradigm. Feels like something's not right. I'd prefer all class doco to open a new page, regardless of whether there are documented functions and variables or not.

**Comment by sstadelman** [comment]
We've run into this as well at SAP, and it's an issue since we have a kitchen-sink app which is attempting to construct the documentation links for the public classes.  

A 'valid' link is: `/SAPFiori/Classes/FUIKPICardView.html `
A problematic link is: `/SAPFiori/Analytics%20Cards.html#/s:8SAPFiori28FUIKPICardCollectionViewCellC`.

Here the `FUIKPICardCollectionViewCell` does not have any children **by design**, because its interface is defined by Swift protocol extensions.  

We were able to work around by adding a pass-through `override`, but this isn't really good practice.

**Comment by johnfairh** [comment]
Old issue cleanup -- addressed this via `--separate-global-declarations` in jazzy 0.13.5.
