### ISSUE TITLE
Autolink enum cases

### ISSUE THREAD

**Issue by reitzig** [realm/jazzy#863]
Say I have something like this:

```swift
/**
	Use `.bar` if you are a pirate, `.spa` if you are a landlubber.
*/
enum Foo {
	case bar, spa
}
```

I would expect the enum cases in the documentation comment to link to the respective cases, but they currently don't.

**Comment by johnfairh** [comment]
This is the same as #865. The name of enum element is just `bar` and needs to be referred to as `` `Foo.bar` `` from that position.
