### ISSUE TITLE
Undocumented items copy declaration from documented parent

### ISSUE THREAD

**Issue by reitzig** [realm/jazzy#864]
For code like this:

```swift
public protocol Foo {
    associatedtype Bar
    var bar: Bar { get }
}
```

Jazzy will not show `Bar` at all.

If we add documentation on `Foo`:

```swift
/// A foo!
public protocol Foo {
    associatedtype Bar: Hashable
    var bar: Bar { get }
}
```
Jazzy copies its declaration over to `bar`:

![screen shot 2017-07-27 at 11 56 04](https://user-images.githubusercontent.com/4246780/28665066-aa7381ec-72c2-11e7-878c-c3124607baa2.png)

**Comment by reitzig** [comment]
Actually, I see undocumented properties getting the declaration of their enclosing type in other places, too, so this may not be related to the associated type.

**Comment by johnfairh** [comment]
The missing `associatedtype` is a SourceKit bug.  If you put a doc-comment on it then sourcekitten will work around & find it.  The wrong declaration is a bug in the jazzy mustache templates, looks like it should say `.declaration` to avoid inheriting from the parent.

**Comment by johnfairh** [comment]
Fixed in master.
