### ISSUE TITLE
Default implementations should not count as undocumented if the implemented protocol method is documented

### ISSUE THREAD

**Issue by reitzig** [realm/jazzy#870]
Jazzy does not count properties implementing protocol properties, like  e.g.`description`, as undocumented as long as the protocol property has documentation. So, for instance, in

```swift
public struct A: CustomStringConvertible {
    public var description = "A"
}
```

symbol `A.description` would not count as undocumented. Nor would it for this:

```swift
public struct A {}
public extension A: CustomStringConvertible {
    public var description: String {
        return "A"
    }
}
```

If, however, the member is defined in a protocol extension, it is counted!

```swift
public protocol B: CustomStringConvertible {}
public extension B {
    public var description: String { return "B" }
}

public protocol C {}
public extension C: CustomStringConvertible {
    public var description: String { return "C" }
}
```

`undocumented.json` lists both `B.description` and `C.description`.

**Comment by johnfairh** [comment]
The `B` example is a swift bug -- see quick help (lack thereof) in Xcode.

Doc comment inheritance into protocol extensions works for `func`s but not `var`/`subscript`/`associatedtype`s.  Opened [SR-5661](https://bugs.swift.org/browse/SR-5661).

(The `C` example is not valid swift for a couple of reasons according to my compiler!)
