### ISSUE TITLE
Display of escaped keywords in declarations is off

### ISSUE THREAD

**Issue by reitzig** [realm/jazzy#871]
If we really have/want to for nefarious reasons, we can use keywords as identifiers in Swift:

```swift
public enum Foo {
    /// While
    case `while`
}
```

Jazzy renders:

![screen shot 2017-08-01 at 13 24 08](https://user-images.githubusercontent.com/4246780/28823209-b83759d6-76bc-11e7-9d30-270b4e9fff60.png)

Arguably, it should drop the backticks and format the identifier just like any other.

**Comment by reitzig** [comment]
Keyword highlighting also shouldn't trigger for parameter labels:

![screen shot 2017-08-01 at 14 54 56](https://user-images.githubusercontent.com/4246780/28826197-76be3d6e-76c9-11e7-8d25-83f63ade8aec.png)

**Comment by johnfairh** [comment]
So, jneen/rouge needs to be enhanced to understand the backticks syntax.  Can use this issue to track that.

Context-sensitive hilighting is also rouge -- I think could be tough for the parser.

On displaying the backticks at all in the declaration, I think it is better to be consistent with Swift's declaration printing policy (see Xcode quick help) in this corner case.  You could open a radar/swift.org bug to discuss whether or not the quick help declaration style should include backticks.

**Comment by johnfairh** [comment]
The backtick syntax is supported in latest rouge; jazzy master will happily use that now.  The whole 'context-sensitive highlighting' part is jneen/rouge#403.  Closing this one.
