### ISSUE TITLE
Jazzy doesn't recognize Xcode 8+ documentation style for ObjC enums

### ISSUE THREAD

**Issue by bdorfman** [realm/jazzy#872]
The style of enum documentation generated by Xcode's `Structure > Add Documentation` menu item is not recognized by jazzy. Using it will cause jazzy to say the enum symbols are undocumented and it will not generate a page for that enum type.

Example:

If you have an enum that looks like this:

```
typedef NS_ENUM(NSInteger, MyEnumType) {
    MyEnumTypeFirstValue,
    MyEnumTypeSecondValue,
};
```

Xcode will generate docs in this style:
```
/**
 <#Description#>

 - MyEnumTypeFirstValue: <#MyEnumTypeFirstValue description#>
 - MyEnumTypeSecondValue: <#MyEnumTypeSecondValue description#>
 */
typedef NS_ENUM(NSInteger, MyEnumType) {
    MyEnumTypeFirstValue,
    MEnumTypeSecondValue,
};
```

But jazzy requires them to be styled like this:
```
/**
 <#Description#>
 */
typedef NS_ENUM(NSInteger, MyEnumType) {
    /// <#MyEnumTypeFirstValue description#>
    MyEnumTypeFirstValue,

    /// <#MyEnumTypeSecondValue description#>
    MyEnumTypeSecondValue,
};
```

I am using jazzy version 0.8.3 and Xcode version 8.3.2

**Comment by johnfairh** [comment]
This is covered by #660.  Xcode has a slightly different opinion to the compilers about where enum doc comments should go.
