### ISSUE TITLE
Spaces being replaced by dashes

### ISSUE THREAD

**Issue by nrbrook** [realm/jazzy#874]
If I write something in round brackets in an included markdown file for jazzy (like this) then it puts dashes between the words (like-this) in the output. I don't think this is normal markdown behaviour. How can I avoid this behaviour?

**Comment by johnfairh** [comment]
My only guess is that the source file does not actually contain a space but some other character -- can you post a link to the .md that is going wrong?

**Comment by nrbrook** [comment]
Renamed to .txt for github. Nothing special as far as I can see.
[README.txt](https://github.com/realm/jazzy/files/1215539/README.txt)

**Comment by nrbrook** [comment]
<img width="291" alt="screen shot 2017-08-10 at 17 03 49" src="https://user-images.githubusercontent.com/1141167/29179910-eb42267a-7ded-11e7-9b9b-463c0070f75a.png">

**Comment by nrbrook** [comment]
Sorry, this is my fault – something I'm doing in a script.
