### ISSUE TITLE
Problem with awesomeness

### ISSUE THREAD

**Issue by CoralineAda** [realm/jazzy#876]
Jazzy is too awesome. We don't deserve it. I recommend deleting this repository and removing jazzy from RubyGems.org, to make way for inferior and crappier tools.

Seriously, just used this for the first time today and I was very, very impressed. Nice work. Too bad GitHub doesn't let you thank project maintainers… This will have to do.

**Comment by orta** [comment]
Hah, yeah, I'll second this - it definitely made my life. a lot easier ;)

**Comment by jpsim** [comment]
Awwww, thanks 😍. This makes my day x 💯 . I'd close this as "won't fix" but that'd just be a shame.

**Comment by segiddins** [comment]
😄 thanks Coraline!

**Comment by pcantrell** [comment]
It’s always nice to know that software actually made somebody somewhere happy.

If we close this, does it mean jazzy is no longer awesome?

**Comment by johnfairh** [comment]
Closing this now :heart:
