### ISSUE TITLE
Generated html pages for operators result in invalid urls

### ISSUE THREAD

**Issue by BenchR267** [realm/jazzy#877]
I generated docs for one of my projects and I'm using some operators that consist of not-valid url-characters like `~`. The documentation is generated but the links to the pages are not valid and result in 404 errors. 
You can try it out here: https://benchr267.github.io/Parsel/ (other operators like `??` are also affected)

**Comment by segiddins** [comment]
Note that it shows up when you URL encode the `??` https://benchr267.github.io/Parsel/Functions/%3F%3F(_:_:).html

**Comment by johnfairh** [comment]
Try `jazzy --use-safe-filenames` ?

**Comment by BenchR267** [comment]
@johnfairh Thanks, that works!

**Comment by BenchR267** [comment]
Oh, that was too fast. It is now working on my machine, but after uploading it to Github, the Github page still can't open the html. It also can't open any other html. Is this a Github issue or also related to jazzy?

**Comment by johnfairh** [comment]
I suspect https://help.github.com/articles/files-that-start-with-an-underscore-are-missing
Skimming the page, no first-hand experience, try creating a .nojekyll ?

There is a minor jazzy issue here: those functions shouldn't have their own separate pages.  The reason they are getting one is to do with the generic type parameters -- not sure if this is a swift/sourcekit change or a seldom-explored corner.

**Comment by BenchR267** [comment]
Great, that works!

**Comment by SDGGiesbrecht** [comment]
Yes `.nojekyll` is necessary for GitHub Pages. I do this by adding a `touch docs/.nojekyll` line right after `jazzy ...` in my scripts.

**Comment by SDGGiesbrecht** [comment]
> The reason they are getting one is to do with the generic type parameters -- not sure if this is a swift/sourcekit change or a seldom-explored corner.

It is not a new change; it is a seldom‐explored corner. Jazzy has been doing that as long as I have been using it (since 0.5.0 or so). I just did not bother me enough for me to report it.

**Comment by BenchR267** [comment]
That's exactly what I added in my script yesterday: https://github.com/BenchR267/Parsel/blob/master/Makefile#L43 :D

**Comment by johnfairh** [comment]
Opened 878 for the web page confusion, will leave this issue around for people searching for invalid URL problems.
