### ISSUE TITLE
A List of Supported Keywords in Objective-C

### ISSUE THREAD

**Issue by SketchK** [realm/jazzy#879]
@jpsim As we all know:

> jazzy currently does not support all Objective-C keywords listed in Apple's HeaderDoc User Guide.

so could you give us **a list of keywords that support Objective-C documentation** ?

_PS: If you don't have much time do this, Could you tell me which file should i read ? I think maybe I can find the answer by accurate file, Even though i don't have much experences with Ruby before._  

Thank you very much!

**Comment by johnfairh** [comment]
This processing happens [in sourcekitten](https://github.com/jpsim/SourceKitten/blob/492510245a177248319436c5c66551edfe863e72/Source/SourceKittenFramework/Clang%2BSourceKitten.swift#L181).  Currently param/return/warning/see/note.

**Comment by SketchK** [comment]
@johnfairh @jpsim Thank You ! 
May I ask you another question? 

HeaderDoc can recognize class, enum, category by top-level tags。Though this is no necessary to write after HeaderDoc 8,  top-level tags still exist and automatically filled by HeaderDoc.

I find that when I use Jazzy to create a ObjC documentation, I also don't need to write a top-level tags. So Could you tell me how it works or who does this, Jazzy, SourceKit or SourceKitten ?

Thank you

**Comment by johnfairh** [comment]
SourceKitten uses libclang to parse ObjC files.  The libclang API identifies the kind of each declaration which SourceKitten maps into its output. [In code, work back from here?](https://github.com/jpsim/SourceKitten/blob/492510245a177248319436c5c66551edfe863e72/Source/SourceKittenFramework/ObjCDeclarationKind.swift#L59)

**Comment by johnfairh** [comment]
Closing - answered.
