### ISSUE TITLE
Compatibility with Xcode9?

### ISSUE THREAD

**Issue by aure** [realm/jazzy#882]
I am getting an error with Xcode 9. Is it me or jazzy?

```
jazzy --theme apple --source-directory ../AudioKit/AudioKit/iOS/ --xcodebuild-arguments -scheme AudioKit
Using config file /Users/aure/Developer/AudioKit/AudioKit/.jazzy.yaml
Running xcodebuild
Could not parse compiler arguments from `xcodebuild` output.
Please confirm that `xcodebuild` is building a Swift module.
Saved `xcodebuild` log file: /var/folders/5d/zkr3lw7x71vd60mckbvrnm_w0000gn/T/xcodebuild-9F175DBB-2B72-45D1-A28C-1FA05E8EF237.log
Failed to generate documentation
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jazzy-0.8.3/lib/jazzy/executable.rb:36:in `execute_command': /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jazzy-0.8.3/bin/sourcekitten ["doc", "--module-name", "AudioKit", "--", "-scheme"] (RuntimeError)

Running xcodebuild

Could not parse compiler arguments from `xcodebuild` output.

Please confirm that `xcodebuild` is building a Swift module.

Saved `xcodebuild` log file: /var/folders/5d/zkr3lw7x71vd60mckbvrnm_w0000gn/T/xcodebuild-9F175DBB-2B72-45D1-A28C-1FA05E8EF237.log

Failed to generate documentation
	from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jazzy-0.8.3/lib/jazzy/sourcekitten.rb:217:in `run_sourcekitten'
	from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jazzy-0.8.3/lib/jazzy/doc_builder.rb:67:in `block in build'
	from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jazzy-0.8.3/lib/jazzy/doc_builder.rb:65:in `chdir'
	from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jazzy-0.8.3/lib/jazzy/doc_builder.rb:65:in `build'
	from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jazzy-0.8.3/bin/jazzy:15:in `<top (required)>'
	from /usr/local/var/rbenv/versions/2.3.1/bin/jazzy:23:in `load'
	from /usr/local/var/rbenv/versions/2.3.1/bin/jazzy:23:in `<main>'
```

**Comment by SDGGiesbrecht** [comment]
@aure,

One problem (not sure if it is the only one) is that you need...

```shell
--xcodebuild-arguments -scheme,AudioKit
```
...instead of...
```
--xcodebuild-arguments -scheme AudioKit
```
(Note the comma.)

***

The way you have it posted, it is asking Jazzy to run...
```shell
$ xcodebuild -scheme
```
...which you can see `xcodebuild` does not like when you run it yourself directly:
> $ xcodebuild -scheme
> xcodebuild: error: option '-scheme' requires an argument

With the comma (which joins the list into a single argument for Jazzy), Jazzy passes the entire list to `xcodebuild`...
```shell
$ xcodebuild -scheme AudioKit
```
...which will hopefully succeed.

***

If that is not enough to solve it, try experimenting with `xcodebuild` directly until you can figure out what arguments are necessary. Then pass those same arguments to Jazzy:

```shell
jazzy [...] --xcodebuild-arguments the,comma,separated,list,of,arguments [...]
```

**Comment by SDGGiesbrecht** [comment]
@johnfairh, since you seem to be in charge now...

I think it would help users debug this sort of usage issue (they seem quite frequent) if Jazzy were to print `xcodebuild`’s specific error in addition to the current message:

> Could not parse compiler arguments from `xcodebuild` output.

What do you think?

**Comment by aure** [comment]
@SDGGiesbrecht Thank you so much for patient and completely correct response to this issue.  Problem solved.

**Comment by johnfairh** [comment]
@SDGGiesbrecht,  I think #850's fix would have reported an unprocessed argument `AudioKit` here.  I do agree on the `xcodebuild` error helping diagnose similar problems -- this is coming from `sourcekitten` though.

(And definitely not 'in charge' - i just have a big mouth.  We're all in this together!)
