### ISSUE TITLE
[Feature Request] Add homebrew support

### ISSUE THREAD

**Issue by gperdomor** [realm/jazzy#883]
please add homebrew support :D

**Comment by johnfairh** [comment]
Do you mean installing jazzy via homebrew or having jazzy document homebrew things in some way?

If the first, previous discussion in #134.  I'm not sure anything has changed since then.
If the second then please say a bit more 😄

**Comment by gperdomor** [comment]
The first one xD

**Comment by jpsim** [comment]
FYI some related discussion in this old ticket: #134

**Comment by jpsim** [comment]
Have you seen [brew-gem](https://github.com/sportngin/brew-gem)? Seems like it would enable you to install jazzy (and others gems) via Homebrew today.

**Comment by BinaryHammer** [comment]
I second adding homebrew support or create standalone version. Installing ruby gems without sudo is problematic, homebrew is mostly an exception and preconfigured on work macs.

**Comment by franklinyu** [comment]
There are very few previous example of any gem available as Homebrew Formula, if any at all. Homebrew is not built with that in mind.

I believe Homebrew Ruby allows you to install gem without sudo.

**Comment by johnfairh** [comment]
Closing this, clear that ruby gems don't belong in home-brew.
