### ISSUE TITLE
Even after installing jazzy succesfully on my system, unable to use on terminal

### ISSUE THREAD

**Issue by arpitjain03** [realm/jazzy#885]
> I have macOS 10.12.6 and Xcode 9
 I installed jazzy on my system using terminal command sudo gem install jazzy
But, when trying to access it through terminal I get -bash: jazzy: command not found

![screen shot 2017-09-27 at 2 56 45 pm](https://user-images.githubusercontent.com/30592234/30906367-4b1d2ffa-a395-11e7-9942-c2fd5e8ea72a.png)

**Comment by jpsim** [comment]
Where does your ruby version install its gems? Is that path in your `PATH` environment variable?

Can you share the output of the following commands?

```bash
$ which ruby
$ echo $GEM_HOME
$ echo $PATH
```

**Comment by arpitjain03** [comment]
Thanks but I have managed to solve it. For everyone's help I have written an article for the same
[Jazzy Tool Usage](https://medium.com/@arpit.cor/easy-documentation-for-your-swift-project-using-jazzy-9117f6a8709a). Hope it helps everyone.

**Comment by jpsim** [comment]
Glad you sorted it out.

**Comment by Rjmaurya13** [comment]
Here is the solution. Install this way.

sudo gem install -n /usr/local/bin jazzy
