### ISSUE TITLE
Extend Jazzy doc of test module with test results

### ISSUE THREAD

**Issue by reitzig** [realm/jazzy#890]
Sometimes we need a proper test report (looking at you, ISO-900x!) which (afaik) XCode can't/won't generate for us.

Jazzy could, when building documentation for test modules (cf #504), run the tests (as an option) and collect the results. The results could be inserted at special placeholders, or as fixed callouts (e.g `- Note: Test passed at <date>` resp. `- Warning: Test failed at <date>`).

**Comment by hermiteer** [comment]
👍

**Comment by johnfairh** [comment]
I've thought about this a few times over the past few years -- given where we are in the docs ecosystem I think DocC is a better target for these requirements: they're putting so much effort into that tooling (to even encompass pure documents like TSPL) that a test suite does not seem out of the question in a not-that-infinite timescale.
