### ISSUE TITLE
`require` Failure (Jazzy 0.8.4 only)

### ISSUE THREAD

**Issue by SDGGiesbrecht** [realm/jazzy#891]
On my machine, running `jazzy _0.8.4_ -version` fails with the following output:

```
~/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- CGI (LoadError)
	from ~/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from ~/.rvm/gems/ruby-2.4.1/gems/jazzy-0.8.4/lib/jazzy/sourcekitten.rb:5:in `<top (required)>'
	from ~/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from ~/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from ~/.rvm/gems/ruby-2.4.1/gems/jazzy-0.8.4/lib/jazzy/doc_builder.rb:19:in `<top (required)>'
	from ~/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from ~/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from ~/.rvm/gems/ruby-2.4.1/gems/jazzy-0.8.4/lib/jazzy.rb:2:in `<top (required)>'
	from ~/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from ~/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from ~/.rvm/gems/ruby-2.4.1/gems/jazzy-0.8.4/bin/jazzy:13:in `<top (required)>'
	from ~/.rvm/gems/ruby-2.4.1/bin/jazzy:23:in `load'
	from ~/.rvm/gems/ruby-2.4.1/bin/jazzy:23:in `<main>'
	from ~/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
	from ~/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'
```

On the other hand, running `jazzy _0.8.3_ -version` succeeds. (Ouput: `jazzy version: 0.8.3`).

I also see that 0.8.4 *does* work [when installed and run on Travis CI’s `xcode9` image](https://travis-ci.org/SDGGiesbrecht/SDGCornerstone/jobs/282585336#L756).

I assume the problem is not really with Jazzy itself, but with my system. However, I have already tried completely wiping and reinstalling Xcode’s command line tools, RVM, Ruby, and Jazzy, and nothing fixed it. I am out of ideas, so any tips on shimming my system back into working order would be appreciated.

In case it matters, I had not tried to use Jazzy since upgrading to Xcode 9, nor had I tried to use 0.8.4 before, so I cannot say for sure if it would ever have worked since either event.

**Comment by SDGGiesbrecht** [comment]
I just tracked the failing line in `sourcekitten.rb` to [this commit](https://github.com/realm/jazzy/commit/c438e5c078cab64c4ccd67ec01749983440ae2d3#diff-25330e59d3f87c23fe23f82231713529R5) between 0.8.3 and 0.8.4.

Still have not found a way to work around it.

**Comment by SDGGiesbrecht** [comment]
Installed Ruby 2.4.2 (which is higher than RVM recommends) to match the working Travis CI build. Then reinstalled Jazzy. Result: Redcarpet seg‐faulted.

Updated all gems. Result: Back to square one with the above output.

**Comment by segiddins** [comment]
@SDGGiesbrecht I'm guessing you have a case-sensitive fs -- the file in the stdlib is `cgi`, not `CGI`

**Comment by SDGGiesbrecht** [comment]
Yes, I just finished manually navigating to `~/.rvm/gems/ruby-2.4.2/gems/jazzy-0.8.4/lib/jazzy/sourcekitten.rb` and changing line 5 from `require 'CGI'` to `require 'cgi'` (based on [this stackoverflow note](https://stackoverflow.com/a/10183090)) and now Jazzy works fine. (I realize hacking an installed gem is not the wisest, but it will suffice for now.)

And now—thanks to your comment, @segiddins—I also understand why.

I will leave this issue open for now so the workaround can more easily be found by other users with the same problem. Once a fix is released, whoever notices first may close the issue.
