### ISSUE TITLE
Jazzy with `.podspec` fails when there is a `test_spec`

### ISSUE THREAD

**Issue by xaverlohmueller** [realm/jazzy#894]
I'm using jazzy to document a cocoapod.

In my `.jazzy.yaml`, I specified the pod using `podspec: <My Pod>.podspec`. This used to work fine until I added a `test_spec` to my `.podspec` file:

```
s.test_spec 'Tests' do |test_spec|
  test_spec.source_files = 'Example/Tests/*.{swift}'
end
```

Now there seems to be a second `xcodebuild` phase that tries to build the target `<My-Pod>-Tests`:
```
/Users/<me>/.rvm/gems/ruby-2.4.2/gems/jazzy-0.8.4/lib/jazzy/executable.rb:36:in `execute_command': /Users/<me>/.rvm/gems/ruby-2.4.2/gems/jazzy-0.8.4/bin/sourcekitten ["doc", "--module-name", "<My-Pod>", "--", "-target", "<My-Pod>-Tests", "SWIFT_VERSION\\=\\\"4.0\\\""] (RuntimeError)
```

How can I ignore this `xcodebuild` phase? I don't need my tests to be documented.
Is there any documentation or best practices on how to use jazzy with a `.podspec` file?

**Comment by johnfairh** [comment]
`test_spec` was new in cocoapods 1.3 and jazzy doesn't handle it properly.  It generates an Xcode unit-test target, which require special treatment to document with jazzy (#504).

I think at least for now we should disable `test_spec`s from contributing to `--podspec`, this is easy enough and probably what most users want?

There aren't any docs you haven't seen: the `--podspec` argument runs jazzy against the spec and all subspecs for all supported platforms, and generates a default readme + metadata (eg. author) from the podspec.

**Comment by jpsim** [comment]
> I think at least for now we should disable `test_spec`s from contributing to `--podspec`, this is easy enough and probably what most users want?

👍
