### ISSUE TITLE
Imported jquery.min.js is old and has known security issues

### ISSUE THREAD

**Issue by mit-mit** [realm/jazzy#901]
The output generated by jazzy includes an import of `jquery.min.js` in a very old version (`jQuery v1.11.1`):
https://github.com/realm/jazzy/blob/master/lib/jazzy/themes/apple/assets/js/jquery.min.js
https://github.com/realm/jazzy/blob/master/lib/jazzy/themes/fullwidth/assets/js/jquery.min.js

All versions of jQuery prior to 3.x have a known security issue:
https://github.com/jquery/jquery/issues/2432

Any chance we can roll jQuery to a more recent version?

**Comment by johnfairh** [comment]
I had a very quick go with latest jquery and all seemed fine including search.  So if you are suffering from audit issues you should be fine replacing it yourself.  Will do a bit more checking.

**Comment by johnfairh** [comment]
Fixed in master with jQuery 3.3.1.

**Comment by mit-mit** [comment]
Most excellent; will there be a release with this in it in the near future?

**Comment by johnfairh** [comment]
Should be in the next few weeks to go with Swift 5.

**Comment by dnfield** [comment]
Any chance this could be done as a patch against the 0.9.5 release?

**Comment by johnfairh** [comment]
You can just drop in the jquery.min.js you want to use, either in your site or via custom theme.
