### ISSUE TITLE
conflicting type declarations with the same name

### ISSUE THREAD

**Issue by sagargondaliya** [realm/jazzy#905]
I have three method with same name but different datatypes. I am trying to create document for project but facing error as below:

Found conflicting type declarations with the same name, which may indicate a build issue or a bug in Jazzy: instance method transform(), instance method transform(), instance method transform()
A compile error prevented AppSDK.deviceDomainService from receiving a unique USR. Documentation may be incomplete. Please check for compile errors by running `xcodebuild `.

skipped 9 private or fileprivate symbols (use `--min-acl` to specify a different minimum ACL)
building site
building search index
jam out ♪♫ to your fresh new docs in `docs`

**Comment by johnfairh** [comment]
This means there was a problem compiling the project.  Does running `xcodebuild` as suggested give you any clues?  Would help to see the project/a cut-down example.

**Comment by johnfairh** [comment]
Closing as old.
