### ISSUE TITLE
Exclude not working

### ISSUE THREAD

**Issue by Ewg777** [realm/jazzy#907]
.jazzy.yaml:
```
exclude:
  - "AppDelegate.swift"
```
![Image of Yaktocat](https://i.imgur.com/LFJpUQL.png)

How to use an exclude parameter?

**Comment by johnfairh** [comment]
See [the README](https://github.com/realm/jazzy#controlling-what-is-documented) - it wants a pathname.  The excluding happens after parsing so your CLI output will still include _Parsing AppDelegate.swift_.

**Comment by Ewg777** [comment]
@johnfairh is there a way to speed up parsing using the excluding? Or do you have another idea?

**Comment by johnfairh** [comment]
Not really, it has to run a chunk of the compiler on the code. Adding `-x -dry-run` might help a bit on the `Running xcodebuild` step.

**Comment by Ewg777** [comment]
@johnfairh Thanks.
Parsing is too slow for big projects. It'd be perfect to exclude some files on this phase.

**Comment by johnfairh** [comment]
Ok!  You could raise an issue against jpsim/SourceKitten about the performance here explaining what 'too slow' means -- maybe there is some scope for parallelism/excludes/other optimisations.

**Comment by glennposadas** [comment]
Hi @johnfairh can you help me out with this? https://github.com/realm/jazzy/issues/619
