### ISSUE TITLE
Autolink to Apple's docs

### ISSUE THREAD

**Issue by sadlerjw** [realm/jazzy#911]
It's entirely possible this is infeasible due to its very large scope, but it would be awesome to autolink to Apple's docs about its own types. For example when explaining that a method returns an `NSOperation`, to be able to click on `NSOperation and arrive [here](https://developer.apple.com/documentation/foundation/nsoperation?language=objc), for example.

**Comment by 1ec5** [comment]
Duplicate of #13.
