### ISSUE TITLE
Xcode 9.1 - unable to find an Xcode with swift version 4.0

### ISSUE THREAD

**Issue by mgrebenets** [realm/jazzy#912]
I've started seeing this error more and more often lately:

> Unable to find an Xcode with swift version 4.0. (RuntimeError)

I've checked and there's quite a few related issues open since Xcode 7.3:
https://github.com/realm/jazzy/issues?utf8=%E2%9C%93&q=is%3Aissue+Unable+to+find+an+Xcode+with+swift+version

For me this started happenning on a machine that has only Xcode 9.1, but no Xcode 9.0.
All our projects use `4.0` in their `.swift-version` for CocoaPods as well as `SWIFT_VERSION=4.0` in project build settings.

However, `swift --version` output for me is `4.0.2`, so unless I tell `jazzy` to use this option: `--swift-version 4.0.2` it will fail with the error.

Somehow this feels very confusing. If I'm understanding semantic versioning correctly, if my project is building with Swift 4.0, then it will be built as well with 4.0.2.

The Xcode project build settings offer me this drop-down:
![image](https://user-images.githubusercontent.com/350654/33252539-e4d08fca-d392-11e7-9ac6-c5c348dc7b57.png)
Which gets translated into `4.0` raw value.
![image](https://user-images.githubusercontent.com/350654/33252548-ef6a97fa-d392-11e7-82fe-e58abf345d02.png)
So if I were to read `SWIFT_VERSION` from my project and pass it to `jazzy` (which I did), it'd start failing as soon as actual Swift version becomes `4.0.1` (which it does).

The somewhat crazy workaround I've found is to get "exact" Swift version via command like 

```ruby
exact_swift_version = `swift --version | cut -d' ' -f 4 | xargs`.chomp
```

So now I can pass this version to `jazzy` and it will work reliably.

**Comment by mgrebenets** [comment]
I spoke too soon :/
The "fix" with reading exact Swift version only worked on my local machine.
On CI agents with multiple Xcode apps available it fails for the same reason.
When `DEVELOPER_DIR` points to Xcode `9.0` installation, the `swift --version` prints out `4.0`, which then results into same error as before:

> .rvm/gems/ruby-2.2.2/gems/jazzy-0.9.0/lib/jazzy/sourcekitten.rb:214:in `run_sourcekitten': Unable to find an Xcode with swift version 4.0. (RuntimeError)

This error started happening only recently and occurs only on some agents from the agents pool. So I wonder if it is related to spotlight indexing as some other issues have mentioned. In any case I can access build agents and do any changes there. Unless there's some command I can run as part of the build to do something with indexing?

**Comment by johnfairh** [comment]
You can see if a system is suffering from 'the spotlight problem' by running `mdfind 'kMDItemCFBundleIdentifier == com.apple.dt.Xcode'`.

I may have not understood properly, but I'm not sure that your build needs to pass the `--swift-version` flag to jazzy: it is optional; if unset then jazzy should just use whatever `DEVELOPER_DIR` / `xcode-select` says without consulting spotlight.

Not convinced the Swift language versions follow semver.  Can't find a reference though.  Not sure yet if the right thing to do is make jazzy/xcinvoke autofill the 'patch' version if omitted - seemed to get through the Xcode 8.patch + Swift 3.0.patch series OK last year; I think it's simpler as a "exact language version to use if default is no good for some reason".

**Comment by mgrebenets** [comment]
So I've managed to reproduce it on my laptop too.
The setup is pretty much straightforward.
Xcode `9.1` is installed at `/Applications/Xcode.app`
Xcode `9.0` is installed at `/Applications/Xcode-9.app`

Then I have a very basic Swift framework project.
Next I try using Xcode `9.0`:

```shell
export DEVELOPER_DIR=/Applications/Xcode-9.app/Contents/Developer
jazzy --output docs \
--module FrameworkName \
--module-version 0.1.0 \
--swift-version 4.0 \
-x -workspace,FrameworkName.xcworkspace,-scheme,FrameworkName
```

This gives me an error.
I double checked output of `swift --version` too:

> Apple Swift version 4.0 (swiftlang-900.0.65 clang-900.0.37)
> Target: x86_64-apple-macosx10.9

So then I try with Xcode `9.1`:

```shell
export DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer
jazzy --output docs \
--module FrameworkName \
--module-version 0.1.0 \
--swift-version 4.0.2 \
-x -workspace,FrameworkName.xcworkspace,-scheme,FrameworkName
```

This time everything works as expected.

**Comment by mgrebenets** [comment]
@johnfairh Missed your comment yesterday :)
You are right, I also was under impression that passing no swift version flag to `jazzy` should just work fine, since I have my `DEVELOPER_DIR` set properly.
But that's not the case unfortunately. First time I've faced this issue when I didn't even know `jazzy` had `--swift-version` flag.

I dug a bit deeper, and it boils down to `find_swift_version` method in [xcinvoke](https://github.com/segiddins/xcinvoke) gem.

The method is like so:

```ruby
    def self.find_swift_version(swift_version)
      swift_version = Gem::Version.create(swift_version)
      select { |xc| xc.swift_version == swift_version }.sort.last
    end
```

If will take in the Swift version I pass or specify in my `.jazzy.yaml` or the one `jazzy` assumes by default, then will try to find matching Xcode installation for it.

So I stuck a few `puts` statements there:

```ruby
    def self.find_swift_version(swift_version)
      puts "find_swift_version: #{swift_version}"
      swift_version = Gem::Version.create(swift_version)
      puts "Gem::Version: #{swift_version}"
      each { |xc| puts "xc: #{xc}\nxc.swift_version: #{swift_version}" }
      select { |xc| xc.swift_version == swift_version }.sort.last
    end
```

And this is what I get:

```
find_swift_version: 4.0
Gem::Version: 4.0
xc: #<XCInvoke::Xcode:0x007f91422a46a0>
xc.swift_version: 4.0
xc: #<XCInvoke::Xcode:0x007f914229e5e8>
xc.swift_version: 4.0
```

This looks just right, I do have 2 Xcodes, but I would expect Xcode 9.0 to have Swift 4.0 and Xcode 9.1 to have Swift 4.0.1. Instead, both of them say they have 4.0, so depending on how my Xcode.app are named in `/Applications` I may select the right or the wrong Xcode.

This explains why of all the CI agents, the issue happens only on one of them, it just happens to pick invalid Xcode on that agent in particular.

I'm still puzzled though, because all our agents have same number of Xcode installations, all named in similar manner and I think Ruby sort is deterministic. 

In any case, the final result depends on naming, which is no good, because all Xcode 9.x so far will be marked as Swift 4.0 in `xcinvoke` gem implementation.

**Comment by mgrebenets** [comment]
@johnfairh Thanks for the tip.
I was able to confirm that on unhealthy agent the output of `'kMDItemCFBundleIdentifier == com.apple.dt.Xcode'` is blank, while on healthy agents it gives me full list of Xcode installations.

Feels like rebooting an agent is one way to fix it.

I wonder if there's a way to repair spotlight search index via command line without restart?

**Comment by mgrebenets** [comment]
Alternatively, if `DEVELOPER_DIR` is set, we know where to look for Xcode.
Even if it's not set, we can always use `xcode-select --show-path`, so I wonder if this approach could be used instead of using `xcinvoke`'s `find_swift_version`?

**Comment by johnfairh** [comment]
Looks like `mdutil -E` to re-index a volume.

If `xcrun swift` is already the right version then we don't need the user to set `--swift-version` (but it should be fine if they do).  Spotlight problem aside, do you think this works?  If not then we should debug.  For me, it seems fine (using xcode-select or DEVELOPER_DIR).

So far I think this issue shows we should improve the docs for `--swift-version` and add some troubleshooting advice for the spotlight problem.

**Comment by mgrebenets** [comment]
I have removed `--swift-version` recently and I relying on `jazzy` to figure it out.
Works reliably on machines that have no spotlight issues.

There's one thing though, I'm piloting some of our fastlane lanes on BuddyBuild and I'm seeing this problem there. With 3rd party services like BuddyBuild I don't get to setup my build agents and pre-run the `mdutil`.

I'll try to dig a bit deeper if I have more time.

**Comment by mgrebenets** [comment]
OK, so even though I removed the `--swift-version` option, I still got `swift_version: 4.0` in `.jazzy.yml`, which is why jazzy was taking the "xcinvoke" path and it then failed on BuddyBuild, cause I don't really know how BuddyBuild provisions their agents.... could be there's no spotlight index available at all for various reasons.

**Comment by johnfairh** [comment]
Added advice to readme.
