### ISSUE TITLE
Changing the "Undocumented" text for functions that are not documented

### ISSUE THREAD

**Issue by akhillies** [realm/jazzy#913]
Is there a way to change the "Undocumented" text that shows up for undocumented functions? I want it to either be blank or a different default comment (like "init function")
I know having undocumented functions is bad and all, but these functions are autogenerated without any docs (a limitation of the framework we are using). I need these functions to be visible so I can't just skip all undocumented.

Thanks in advance!

**Comment by johnfairh** [comment]
The string is hard-coded right now - would be a simple (+ I think good) change to make it settable.

**Comment by akhillies** [comment]
PR here: https://github.com/realm/jazzy/pull/914

**Comment by akhillies** [comment]
I am getting this error: Perceived complexity for process_undocumented_token is too high because I added an if statement in an if statement
is there a better way I can do this?

**Comment by akhillies** [comment]
implemented and pushed :) (https://github.com/realm/jazzy/pull/914)
