### ISSUE TITLE
Doesn't generate proper docset without --module

### ISSUE THREAD

**Issue by hollanderbart** [realm/jazzy#921]
With several internal projects I experience the issue where the docset simple isn't generated. The folders stays empty and I'm using the default build instruction. Can I get insight in some jazzy logging? `xcodebuild` runs fine and HTML looks fine also.

**Comment by johnfairh** [comment]
Try `ls -a` in the `docs/docsets/` directory?  The only gotcha I can see is that if you do not give jazzy  `--module` then it uses an empty string for the docset name, accidentally creating hidden files.

I think we should skip docset creation + warn if the module name is not set: the name is used in various dash metadata as well as filenames so defaulting to 'Jazzy' or something doesn't feel right + won't point users towards what to fix.  I doubt anyone is currently relying on the oddly named docsets.

**Comment by hollanderbart** [comment]
Providing the `-- module` or `-m` parameter solved it! Thanks!

**Comment by johnfairh** [comment]
I'm going to keep this open to do some code changes to avoid/warn about this.

**Comment by hollanderbart** [comment]
Great to see that you're going to improve the experience! 👍
