### ISSUE TITLE
The copyright markdown layout when having multiple lines is not correct in the Apple theme

### ISSUE THREAD

**Issue by FabienLydoire** [realm/jazzy#925]
When using the following .jazzy.yaml, the copyright layout notice at the bottom of the page is not correct.
```
module: TestDoc
copyright: 'Line 0<br>
Line 1<br>
Line 2<br>'
min_acl: private
```

It is correct using the fullwidth theme.

See screenshots attached.

<img width="996" alt="capture d ecran 2017-12-14 a 18 10 06" src="https://user-images.githubusercontent.com/373452/34013515-11884d5e-e118-11e7-8ecc-61405e58960f.png">
<img width="565" alt="capture d ecran 2017-12-14 a 18 10 30" src="https://user-images.githubusercontent.com/373452/34013530-1dd6fbc8-e118-11e7-809e-b79003ab4007.png">

**Comment by johnfairh** [comment]
Fixed in master by #1039.
