### ISSUE TITLE
How to jazzy for an objc++ project ?

### ISSUE THREAD

**Issue by RingoD** [realm/jazzy#926]
I try to use jazzy to replace appledoc, but it failed while `xcodebuild`ing the objc++ header.

My repo is at: https://github.com/Tencent/wcdb . Here is jazzy script:
```
jazzy \
    --objc \
    --clean \
    --author sanhuazhang \
    --author_url sanhuazhang@tencent.com \
    --github_url https://github.com/Tencent/wcdb \
    --xcodebuild-arguments --objc,WCDB/WCDB.h,--,-x,objective-c++,-isysroot,`xcrun --show-sdk-path --sdk iphoneos` \
    --root-url https://github.com/Tencent/wcdb \
    --source-directory apple/ \
    --skip-undocumented \
    --copyright "Copyright © 2017 Tencent. All rights reserved." \
    --output docs/
```

I try to add `-x,objective-c++` to avoid C++ error, but it still results in `WCDB/WCDB.h:28:9: fatal error: 'WCDB/abstract.h' file not found`

**Comment by johnfairh** [comment]
Jazzy (actually sourcekitten) doesn't support C++ declaration types so unfortunately this will not work. 

The file-not-found above is due to not setting up clang to map 'WCDB/abstract.h' to an actual filesystem path -- this is stopping you getting far enough to see the actual fatal error.

**Comment by johnfairh** [comment]
Closing then.
