### ISSUE TITLE
Local file references aren't maintained

### ISSUE THREAD

**Issue by jshier** [realm/jazzy#932]
Due to the loss of CocoaDocs, we moved the Alamofire documentation to manually generated Jazzy docs [on GitHub](https://alamofire.github.io/Alamofire/). However, our recent attempt to refactor our `README` into separate files [doesn't seem to work](https://alamofire.github.io/Alamofire/Documentation/Usage.md) with the generated documentation. Is there any way to make these sorts of file references work both within the Jazzy documentation and GitHub directly? Perhaps Jazzy could replace the direct `.md` file links with links to rendered versions?

**Comment by jpsim** [comment]
Take a look at how Siesta handles this:

* https://github.com/bustoutsolutions/siesta/blob/master/.jazzy.yaml
* https://github.com/bustoutsolutions/siesta/tree/master/Docs
* http://bustoutsolutions.github.io/siesta/api/

**Comment by jshier** [comment]
I don't see how that `.jazzy.yaml` generates the docs from the `md` files. It just seems to have custom categories for the API documentation. That also doesn't seem to maintain the ability to browse the documentation directly on GitHub, instead going through the rendered docs all the time. Which I suppose we could do...

**Comment by pcantrell** [comment]
>  I don't see how that .jazzy.yaml generates the docs from the md files. 

It doesn’t. Siesta uses a [separate custom script](https://github.com/bustoutsolutions/siesta/blob/gh-pages/_scripts/build-user-guide.rb) for generating the [nicely formatted user guide](http://bustoutsolutions.github.io/siesta/guide/) from the [raw `md` files](https://github.com/bustoutsolutions/siesta/tree/master/Docs). (The generated user guide is actually still md files, which GitHub Pages knows how to serve directly via Jekyll. Our custom process just sanity checks the table of contents and adds next section links, and lets Jekyll [do](https://github.com/bustoutsolutions/siesta/tree/gh-pages/_layouts) [the](https://github.com/bustoutsolutions/siesta/tree/gh-pages/_sass) [formatting](https://github.com/bustoutsolutions/siesta/tree/gh-pages/_includes). This way the generated guide looks great, but the raw user guide is still decently readable directly from the source tree.)

The end result is that our `gh-pages` branch looks like this:

    api/      ← generated by Jazzy
    index.md  ← generated by script linked above
    guide/    ← generated by script linked above
    specs/    ← generated by a separate testing report script

**Comment by johnfairh** [comment]
> Perhaps Jazzy could replace the direct `.md` file links with links to rendered versions?

I think this is a good idea - same kind of thought as #775.

**Comment by johnfairh** [comment]
Closing, dup #775.
