### ISSUE TITLE
Swift declarations doesn't get NS_SWIFT_NAME properly from Objc headers if the class coming from another file and referenced as @class XXX;

### ISSUE THREAD

**Issue by ulukaya** [realm/jazzy#934]
https://github.com/firebase/firebase-ios-sdk/blob/master/Firebase/Core/Public/FIRApp.h#L24
is where it gets sourced.

https://github.com/firebase/firebase-ios-sdk/blob/master/Firebase/Core/Public/FIROptions.h#L25
is where it's defined with swift name.

So in FIRApp.html you get `@NSCopying var options: FIROptions { get }` in Swift declaration instead of `@NSCopying var options: FirebaseOptions { get }`

When swift name is on same file or header include it works fine. When it's declared as it'll be defined (@class), it doesn't follow it through.

Sourcekit may not have the metadata, but it should be easy to find the right header and get the right name.

**Comment by johnfairh** [comment]
This is the same as #609 - the header files are compiled individually in order to get the Swift versions so stuff that is not directly #included is not seen.
