### ISSUE TITLE
NoMethodError when executing jazzy with yaml

### ISSUE THREAD

**Issue by Christian-Seiler** [realm/jazzy#935]
When I try to execute jazzy using a yaml config file I'm getting the following error:

```
Using config file ~/Developer/Repository/.jazzy.yaml
/Library/Ruby/Gems/2.0.0/gems/jazzy-0.9.1/lib/jazzy/config.rb:421:in `parse_config_file': undefined method `each' for #<String:0x007fc14c83cc18> (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.9.1/lib/jazzy/config.rb:363:in `parse!'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.9.1/bin/jazzy:15:in `<top (required)>'
	from /usr/local/bin/jazzy:23:in `load'
	from /usr/local/bin/jazzy:23:in `<main>'
```

**Comment by johnfairh** [comment]
This probably means the yaml file has the wrong format -- [example of a working yaml config file](https://github.com/bustoutsolutions/siesta/blob/1665db77a35b0e5c60269825d2e9b4d6971b81b5/.jazzy.yaml).  If that doesn't help then maybe share your config file?

**Comment by johnfairh** [comment]
Closing this one now.
