### ISSUE TITLE
0% documentation coverage with 0 undocumented symbols

### ISSUE THREAD

**Issue by Senocico** [realm/jazzy#938]
I have a project named Xerox (Xcode 9.2, Swift 4):

![screen shot 2018-01-29 at 12 35 04](https://user-images.githubusercontent.com/6379089/35506111-ec14ec4c-04f0-11e8-8688-d09959ebd27d.png)

The main code Xerox group looks like:

![screen shot 2018-01-29 at 12 35 11](https://user-images.githubusercontent.com/6379089/35506151-0620ed2a-04f1-11e8-89a3-4f829644e154.png)
Even I run in terminal `jazzy` or `jazzy --min-acl internal/private` the logs are always the same: 
```
Running xcodebuild
0% documentation coverage with 0 undocumented symbols
building site
building search index
jam out ♪♫ to your fresh new docs in `docs`
```
All the code is properly commented using Xcode Markup Formatting Reference.
No documentation is generated. I've searched for hours, but the result are always the same...
Any suggestions?

**Comment by johnfairh** [comment]
Probably the default `xcodebuild` is not building the module you want to document (either first or at all).  Try setting `--module <whatever>`, and/or maybe `-x -target,<whatever>` ?  If no joy then look at the output from `xcodebuild clean build`: you will need to pass jazzy `-x` flags to make that output include the build commands for your module.

**Comment by Senocico** [comment]
If I run `jazzy --module Xerox ` the results are the same.
If I run `jazzy -x --module Xerox` or `jazzy -x -target Xerox`

Console prints

```
Running xcodebuild
Could not parse compiler arguments from `xcodebuild` output.
Please confirm that `xcodebuild` is building a Swift module.
Saved `xcodebuild` log file: /var/folders/lm/8y_p4q517l5338h3h_myx1h00000gn/T/xcodebuild-AE5A48B3-DB76-4AD2-96D8-D8A688B2FD62.log
Failed to generate documentation
/usr/local/lib/ruby/gems/2.3.0/gems/jazzy-0.9.1/lib/jazzy/executable.rb:36:in `execute_command': /usr/local/lib/ruby/gems/2.3.0/gems/jazzy-0.9.1/bin/sourcekitten ["doc", "--", "--module"] (RuntimeError)

Running xcodebuild

Could not parse compiler arguments from `xcodebuild` output.

Please confirm that `xcodebuild` is building a Swift module.

Saved `xcodebuild` log file: /var/folders/lm/8y_p4q517l5338h3h_myx1h00000gn/T/xcodebuild-AE5A48B3-DB76-4AD2-96D8-D8A688B2FD62.log

Failed to generate documentation
	from /usr/local/lib/ruby/gems/2.3.0/gems/jazzy-0.9.1/lib/jazzy/sourcekitten.rb:225:in `run_sourcekitten'
	from /usr/local/lib/ruby/gems/2.3.0/gems/jazzy-0.9.1/lib/jazzy/doc_builder.rb:66:in `block in build'
	from /usr/local/lib/ruby/gems/2.3.0/gems/jazzy-0.9.1/lib/jazzy/doc_builder.rb:64:in `chdir'
	from /usr/local/lib/ruby/gems/2.3.0/gems/jazzy-0.9.1/lib/jazzy/doc_builder.rb:64:in `build'
	from /usr/local/lib/ruby/gems/2.3.0/gems/jazzy-0.9.1/bin/jazzy:15:in `<top (required)>'
	from /usr/local/bin/jazzy:23:in `load'
	from /usr/local/bin/jazzy:23:in `<main>'

```

**Comment by johnfairh** [comment]
The command I suggested would be `jazzy -x -target,Xerox` which is not exactly what you pasted -- give that a go; if not then try looking at the xcodebuild log file that is mentioned.

**Comment by johnfairh** [comment]
Closing this one now.

**Comment by hasanabuzayed** [comment]
I have the same issue, so I've tried almost every command available in all the different issues, and non seems to work!

macOS: 10.14.2 (18C54)
Xcode:  10.1 (10B61)
Swift: 4.2.1
Jazzy: 0.9.5
Ruby: ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]

**Comment by johnfairh** [comment]
@hasanabuzayed if you open a new issue with your project/minimal recreate along with jazzy command and full output then we can take a look.
