### ISSUE TITLE
Not generating full markdown in README.md

### ISSUE THREAD

**Issue by mikeKane** [realm/jazzy#939]
I am using `documentation: Sources/*/README.md` to allow my README to display full markdown. I want to show a table. I am just adding in the generic example:

` | Tables        | Are           | Cool  |
 | ------------- |:-------------:| -----:|
 | col 3 is      | right-aligned | $1600 |
 | col 2 is      | centered      |   $12 |
 | zebra stripes | are neat      |    $1 |`

but it doesn't render in markdown at all. 

Any help would be appreciated. Thanks!

**Comment by SDGGiesbrecht** [comment]
@mikeKane, tables like that are not part of the markdown specification, they are a GitHub extension.

If I remember correctly, you can use an HTML table in the markdown file and it will result in a table both in Jazzy and on github.com. The downside is that it is more cluttered when viewed in a raw text editor.

`<table><tr><td>This</td><td>is</td><td>such</td><td>a</td><td>table</td><td>.</td></tr></table>`

↓

<table><tr><td>This</td><td>is</td><td>such</td><td>a</td><td>table</td><td>.</td></tr></table>

**Comment by mikeKane** [comment]
ah thank you! Yes, I have html table rendering on jazzy, I wasn't sure how it would look if I pushed to git. Thank you

**Comment by johnfairh** [comment]
Just to note that jazzy does enable the tables extension for its markdown processing.  The example table markdown given renders OK on the latest version (jazzy 0.9.1 / redcarpet 3.4.0):
![screen shot 2018-01-31 at 16 24 29](https://user-images.githubusercontent.com/26768470/35634326-54637558-06a3-11e8-95ac-8168f4066054.png)

Redcarpet is picky about indentation though: the leading pipes must be column 0 (or column 4 for 1 bullet of indent etc.)

**Comment by mikeKane** [comment]
That is good to know. I am adding functions that changed so the table would read 1.0|1.1 and then function names. So it could get a bit oversized. 

jazzy doesn't have any build in deprecation syntax? or changelog?

**Comment by SDGGiesbrecht** [comment]
> Jazzy does enable the tables extension for its markdown processing.

Neat. I did not know that.

But then, it has been over a year since I tried to use such tables. I guess it is no surprise that my information is out of date. :smile:

***

@mikeKane,

> Jazzy doesn’t have any built in deprecation syntax? Or changelog?

There are the [standard callouts](https://developer.apple.com/library/content/documentation/Xcode/Reference/xcode_markup_formatting_ref/Attention.html#//apple_ref/doc/uid/TP40016497-CH29-SW1) (see the side bar).

And you can point [`documentation`](https://github.com/realm/jazzy#guides) at `CHANGELOG.md`.

That is all I am aware of.

**Comment by mikeKane** [comment]
Fantastic!

**Comment by mikeKane** [comment]
Does jazzy include the CHANGELOG.md to the formatted html docs? I do not see it show up

**Comment by johnfairh** [comment]
Closing this, answered.
