### ISSUE TITLE
Getting Error while generating docs for Objective-C framework 

### ISSUE THREAD

**Issue by ChengappaMoEngage** [realm/jazzy#958]
I used the following command in my framework project's directory:
`jazzy --objc --umbrella-header MoEngage/MoEngage.h --author "MoEngage Inc." --author_url "https://moengage.com" --github_url "https://github.com/moengage/MoEngage-iOS-SDK" --module "MoEngage" --module-version 4.0.1 --sdk iphone`

Getting this Error :
`xcodebuild: error: SDK "iphone" cannot be located.
xcrun: error: unable to lookup item 'Path' in SDK 'iphone'
warning: no such sysroot directory: '' [-Wmissing-sysroot]
/Users/Chengappa/Documents/MoEngage/MoEObjC/MoEFramework/MoEngage/MoEngage/MoEngage.h:9:9: fatal error: 'Foundation/Foundation.h' file not found
63% documentation coverage with 42 undocumented symbols
included 114 symbols
building site
building search index
jam out ♪♫ to your fresh new docs in `docs``

Am I missing something here?

**Comment by jpsim** [comment]
There is no iphone SDK. Did you mean iphonesimulator or iphoneos?

**Comment by ChengappaMoEngage** [comment]
Sorry for the delay. I corrected the command to specify `iphonesimulator`. So, I tried to generate docs in two ways and getting error in both the cases. 

**One with my framework project :**  
Command Used : `jazzy --objc --umbrella-header MoEFramework/MoEngage/MoEngage/MoEngage.h --author "MoEngage Inc." --author_url "https://moengage.com" --github_url "https://github.com/moengage/MoEngage-iOS-SDK" --module "MoEngage" --module-version 4.0.1 --sdk iphonesimulator`

Error : `/Users/Chengappa/Documents/MoEngage/MoEObjC/MoEFramework/MoEngage/MoEngage/MoEngage.h:26:9: fatal error: 'MoEngage/MOPayloadBuilder.h' file not found
62% documentation coverage with 44 undocumented symbols
included 116 symbols
building site
building search index`

**Here `MOPayloadBuilder.h` is one of the public headers imported in umbrella header.**

**And I also tried with the framework created for CocoaPods :** 

Command Used : `jazzy --objc --umbrella-header MoEngage/MoEngage.framework/Headers/MoEngage.h --author "MoEngage Inc." --author_url "https://moengage.com" --github_url "https://github.com/moengage/MoEngage-iOS-SDK" --module "MoEngage" --module-version 4.0.1 --sdk iphonesimulator --framework-root MoEngage --podspec MoEngage-iOS-SDK.podspec --xcodebuild-arguments --objc`

Error : `Analyzing dependencies
Fetching podspec for `MoEngage-iOS-SDK` from `/Users/Chengappa/Documents/MoEngage/MoEngageCocoaPod`
Downloading dependencies
Installing MoEngage-iOS-SDK (4.0.1)
Generating Pods project
Skipping User Project Integration
Pod installation complete! There is 1 dependency from the Podfile and 1 total pod installed.
Running xcodebuild
Could not parse compiler arguments from `xcodebuild` output.
Please confirm that `xcodebuild` is building a Swift module.
Saved `xcodebuild` log file: /var/folders/84/x7w62tg940nfdtzb3_m8ltdm0000gn/T/xcodebuild-AFB0454B-3A24-4F33-A025-F7BEC01D03FE.log
Failed to generate documentation
/usr/local/lib/ruby/gems/2.3.0/gems/jazzy-0.9.2/lib/jazzy/executable.rb:36:in `execute_command': /usr/local/lib/ruby/gems/2.3.0/gems/jazzy-0.9.2/bin/sourcekitten ["doc", "--module-name", "MoEngage_iOS_SDK", "--", "-target", "MoEngage-iOS-SDK", "SWIFT_VERSION\\=\\\"4.0\\\""] (RuntimeError)

Running xcodebuild

Could not parse compiler arguments from `xcodebuild` output.

Please confirm that `xcodebuild` is building a Swift module.

Saved `xcodebuild` log file: /var/folders/84/x7w62tg940nfdtzb3_m8ltdm0000gn/T/xcodebuild-AFB0454B-3A24-4F33-A025-F7BEC01D03FE.log

Failed to generate documentation
	from /usr/local/lib/ruby/gems/2.3.0/gems/jazzy-0.9.2/lib/jazzy/sourcekitten.rb:230:in `run_sourcekitten'
	from /usr/local/lib/ruby/gems/2.3.0/gems/jazzy-0.9.2/lib/jazzy/podspec_documenter.rb:32:in `block (3 levels) in sourcekitten_output'
	from /usr/local/lib/ruby/gems/2.3.0/gems/jazzy-0.9.2/lib/jazzy/podspec_documenter.rb:28:in `map'
	from /usr/local/lib/ruby/gems/2.3.0/gems/jazzy-0.9.2/lib/jazzy/podspec_documenter.rb:28:in `block (2 levels) in sourcekitten_output'
	from /usr/local/lib/ruby/gems/2.3.0/gems/jazzy-0.9.2/lib/jazzy/podspec_documenter.rb:23:in `chdir'
	from /usr/local/lib/ruby/gems/2.3.0/gems/jazzy-0.9.2/lib/jazzy/podspec_documenter.rb:23:in `block in sourcekitten_output'
	from /usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.5.0/lib/cocoapods/config.rb:41:in `with_changes'
	from /usr/local/lib/ruby/gems/2.3.0/gems/jazzy-0.9.2/lib/jazzy/podspec_documenter.rb:18:in `sourcekitten_output'
	from /usr/local/lib/ruby/gems/2.3.0/gems/jazzy-0.9.2/lib/jazzy/doc_builder.rb:62:in `build'
	from /usr/local/lib/ruby/gems/2.3.0/gems/jazzy-0.9.2/bin/jazzy:15:in `<top (required)>'
	from /usr/local/bin/jazzy:23:in `load'
	from /usr/local/bin/jazzy:23:in `<main>'` 

**I'm getting Please confirm that `xcodebuild` is building a Swift module, even though I'm mentioning `--objc`**

**Comment by johnfairh** [comment]
Stick with the first (non-podspec) form -- the command is missing the `--framework-root` parameter.

**Comment by ChengappaMoEngage** [comment]
@johnfairh I added framework root as suggested by you but still getting error : 
Command : 
```jazzy --objc --umbrella-header MoEFramework/MoEngage/MoEngage/MoEngage.h --author "MoEngage Inc." --author_url "https://moengage.com" --github_url "https://github.com/moengage/MoEngage-iOS-SDK" --module "MoEngage" --module-version 4.0.1 --sdk iphonesimulator --framework-root MoEFramework/MoEngage
```

Error : 
```
/Users/Chengappa/Documents/MoEngage/MoEObjC/MoEFramework/MoEngage/build/MoEngage.build/Debug-iphonesimulator/MoEngage.build/module.modulemap:1:18: error: redefinition of module 'MoEngage'
/Users/Chengappa/Documents/MoEngage/MoEObjC/MoEFramework/MoEngage/build/MoEngage.build/Release-iphonesimulator/MoEngage.build/module.modulemap:1:18: note: previously defined here
/Users/Chengappa/Documents/MoEngage/MoEObjC/MoEFramework/MoEngage/build/MoEngage.build/Debug-iphonesimulator/MoEngageAppFwk.build/module.modulemap:1:18: error: redefinition of module 'MoEngageAppFwk'
/Users/Chengappa/Documents/MoEngage/MoEObjC/MoEFramework/MoEngage/build/MoEngage.build/Release-iphonesimulator/MoEngageAppFwk.build/module.modulemap:1:18: note: previously defined here
/Users/Chengappa/Documents/MoEngage/MoEObjC/MoEFramework/MoEngage/build/MoEngage.build/Release-iphoneos/MoEngage.build/module.modulemap:1:18: error: redefinition of module 'MoEngage'
/Users/Chengappa/Documents/MoEngage/MoEObjC/MoEFramework/MoEngage/build/MoEngage.build/Release-iphonesimulator/MoEngage.build/module.modulemap:1:18: note: previously defined here
/Users/Chengappa/Documents/MoEngage/MoEObjC/MoEFramework/MoEngage/build/MoEngage.build/Release-iphoneos/MoEngageAppFwk.build/module.modulemap:1:18: error: redefinition of module 'MoEngageAppFwk'
/Users/Chengappa/Documents/MoEngage/MoEObjC/MoEFramework/MoEngage/build/MoEngage.build/Release-iphonesimulator/MoEngageAppFwk.build/module.modulemap:1:18: note: previously defined here
/Users/Chengappa/Documents/MoEngage/MoEObjC/MoEFramework/MoEngage/build/MoEngage.build/Debug-iphoneos/MoEngage.build/module.modulemap:1:18: error: redefinition of module 'MoEngage'
/Users/Chengappa/Documents/MoEngage/MoEObjC/MoEFramework/MoEngage/build/MoEngage.build/Release-iphonesimulator/MoEngage.build/module.modulemap:1:18: note: previously defined here
/Users/Chengappa/Documents/MoEngage/MoEObjC/MoEFramework/MoEngage/build/MoEngage.build/Debug-iphoneos/MoEngageAppFwk.build/module.modulemap:1:18: error: redefinition of module 'MoEngageAppFwk'
/Users/Chengappa/Documents/MoEngage/MoEObjC/MoEFramework/MoEngage/build/MoEngage.build/Release-iphonesimulator/MoEngageAppFwk.build/module.modulemap:1:18: note: previously defined here
/Users/Chengappa/Documents/MoEngage/MoEObjC/MoEFramework/MoEngage/MoEngage/MoEngage.h:26:9: fatal error: 'MoEngage/MOPayloadBuilder.h' file not found
62% documentation coverage with 44 undocumented symbols
```

As mentioned earlier ** MOPayloadBuilder.h is one of the public headers imported in umbrella header.**

**Comment by johnfairh** [comment]
Jazzy is just running the compiler against your umbrella header file with the include search path set to everything under the framework root directory.  If that is not going to match 'MoEngage/MOPayloadBuilder.h' (etc.) then you may need to do some alias directory creation - see eg.  #667.  I think you have all the jazzy flags set correctly now, hopefully that explanation of what is happening is enough to let you work through the build issues.

**Comment by johnfairh** [comment]
Closing this one now.
