### ISSUE TITLE
Conditional Conformance

### ISSUE THREAD

**Issue by lightsprint09** [realm/jazzy#964]
It looks like conditional conformance does not render correctly.

[This conformance ](https://github.com/lightsprint09/Sourcing/blob/master/Source/DataProvider/SectionTitles/Array%2BSectionIndexTitles.swift) results in [this documentation](https://lightsprint09.github.io/Sourcing/Extensions/Array.html#/s:8Sourcing18SectionIndexTitlesP07sectioncD0SaySSGSgvp)

**Comment by johnfairh** [comment]
Jazzy doesn't have this info right now (same for extension generic conditions).  A workaround I've used is to stick a doc comment on the extension 'These methods are available only when ....'

I've an idea how to push the info up to jazzy, but I'm not sure what to do with it then: do you have any thoughts on the visual design for these kinds of things?  Imagine your project contained a couple or more different conditional conformances for `Array` to display.

**Comment by lightsprint09** [comment]
I think for the beginning the Swift syntax is quite nice. 

Array where Element == String:  SomeProtocol would be enough

**Comment by lightsprint09** [comment]
Maybe highlighting the implemented protocol would be a good idea

**Comment by SDGGiesbrecht** [comment]
Subset of #717 and #881 (extension constraints).

Some discussion has already taken place there.

**Comment by johnfairh** [comment]
Oh yes - let's use 717 then.
