### ISSUE TITLE
Jazzy fails when compiling a coreml model, due to double quoting the swift version.

### ISSUE THREAD

**Issue by galli-leo** [realm/jazzy#970]
I have a framework that includes some coreml models. Unfortunately, jazzy fails to build the documentation. Xcode build log shows the following:

```
=== BUILD TARGET NemosyneSDK OF PROJECT Pods WITH THE DEFAULT CONFIGURATION (Release) ===

Check dependencies
Error preparing CoreML model "classifier.mlmodel" for code generation: coremlcompiler: Error: unrecognized Swift version ""4.0"".  Expected one of: 3.0, 3.1, 3.2 or 4.0
coremlcompiler: Error: usage: coremlcompiler <command> <inputdocument> <outputpath> [options ...]

Error preparing CoreML model "sphereface.mlmodel" for code generation: coremlcompiler: Error: unrecognized Swift version ""4.0"".  Expected one of: 3.0, 3.1, 3.2 or 4.0
coremlcompiler: Error: usage: coremlcompiler <command> <inputdocument> <outputpath> [options ...]

```

Seems like instead of setting SWIFT_VERSION="{VERSION}" it should be SWIFT_VERSION={VERSION}:

```
/usr/local/lib/ruby/gems/2.4.0/gems/jazzy-0.9.2/bin/sourcekitten ["doc", "--module-name", "NemosyneSDK", "--", "-target", "NemosyneSDK", "SWIFT_VERSION\\=\\\"4.0\\\""]
```

This also happens if I manually specify the swift version with `--swift-version`.

**Comment by johnfairh** [comment]
One set of the double quotes is from the error message itself.  The problem is the other apple tools support (one set of) double quotes here -- I'm guessing they were required at some point in the past which is why they were added.  Can you use the non-`--podspec` invocation of jazzy for your project?

[hmm we should probably support the new[ish] cocoapods swift_version DSL as well...]

**Comment by galli-leo** [comment]
Can confirm that compilation works without the podspec.

**Comment by 1ec5** [comment]
#1004 fixes this issue in a minimal way. It doesn’t adopt CocoaPods’ `swift_version` option.
