### ISSUE TITLE
Feature request: Reuse documentation comments for protocols on implementation.

### ISSUE THREAD

**Issue by galli-leo** [realm/jazzy#971]
Not sure if this is doable, but when declaring a protocol that is used by many classes, it gets annoying having to copy paste most of the documentation. Thus I would propose an option, which uses the documentation of a function / property from the protocol itself, if no doc comment is on the actual implementation.

Example:
```
protocol MyProtocol {
  /// Does awesome stuff!
  func myAwesomeFunc()
}

extension String: MyProtocol {
  func myAwesomeFunc() {
    self = "awesome"
  }
}
```

Jazzy could then create the following documentation info on `myAwesomeFunc()` for String: "Does awesome stuff!"

**Comment by johnfairh** [comment]
This is oft-requested, tracked by #190. Implementation not entirely straight-forward which is why it hasn't been done yet!
