### ISSUE TITLE
Can the Xcode "Issue Navigator" work with the "undocumented.json" file output by Jazzy?

### ISSUE THREAD

**Issue by Mozahler** [realm/jazzy#973]
I'm so used to clicking on a warning or error in Xcode's issue navigator and having the editor bring me to the correct spot in the file. 
<img width="285" alt="issuenavigator" src="https://user-images.githubusercontent.com/9641531/40128689-352d114e-5900-11e8-8093-d4af0b1718d5.png">

I was wondering whether it is possible for Xcode to present the undocumented.json file output in a similar way.  If not, is there a tool which can open this file and present it the way the compiler output is presented in Xcode? (you click on an item and it brings up the line in the editor) It would be so convenient you must admit. And almost all of the work has been done already.  I'm trying to finish a project right now, but I'll look into it further as soon as I can if no one has any suggestions...
([(https://stackoverflow.com/questions/50360319/is-there-a-way-to-get-xcode-to-use-the-output-of-jazzys-undocumented-json-fil)])

**Comment by SDGGiesbrecht** [comment]
🇩🇪DE:

@Mozahler,

> I was wondering whether it is possible for Xcode to present the undocumented.json file output in a similar way.

Dafür sind drei Sachen nötig:

1. Es muss jedes Mal tatsächlich `undocumented.json` geben, und zwar in frischem Stand. Jazzy erzeugt selbst einen Bau des Ziels. Das heißt als Bauphase würde es es in einem unbrechbaren Kreise landen. Man müsste es also als Teil eines anderen Ziels ausführen.

2. Man müsste die `undocumented.json` zergliedern können. Das ist relativ leicht. [Arbeitsbereich](https://github.com/SDGGiesbrecht/Workspace#workspace) tut es momentan [so](https://github.com/SDGGiesbrecht/Workspace/blob/bfda41695fc549b6f0da8471b346abde0d8c68f1/Sources/Interface/External%20Tools/Third%20Party/Jazzy.swift#L133-L159). (Arbeitsbereich leitet es aber nicht zurück an Xcode, sondern stellt es dem Benutzer direkt dar.)

3. Dann müsste man die Fehler zu Xcode ausgeben. Das ist ist auch relativ leicht. [So](https://github.com/SDGGiesbrecht/Workspace/blob/bfda41695fc549b6f0da8471b346abde0d8c68f1/Sources/Interface/Proofreading/Reporters/XcodeProofreadingReporter.swift#L35-L50) leitet Arbeitsbereich andere Fehlersorten an Xcode weiter.

Verbesserungen (zu Jazzy oder Arbeitsbereich), die diesem Vorgang erleichtern, wären höchstwahrscheinlich Willkommen.

***

🇬🇧🇺🇸EN: Above are tips on setting it up, which is doable, but not straightforward. If someone wants English instructions, ping me. Pull requests which make process simpler would likely be welcome.

**Comment by Mozahler** [comment]
Thank you so much! I'll get on it as soon as I can. As you say, the information you're referencing is straightforward. I need to finish my current project first, though.
