### ISSUE TITLE
generated HTML links are irregular when no public interface in Swift file

### ISSUE THREAD

**Issue by sstadelman** [realm/jazzy#974]
## Summary
We've run into an issue at SAP, where the links for types with no children are "messy".  It looks like a new page is not generated for these type. This is an issue since we have a kitchen-sink app which is attempting to construct the documentation links for the public classes.  We expect the links to be (easily) predictable.

A 'valid' link is: `/SAPFiori/Classes/FUIKPICardView.html `
A problematic link is: `/SAPFiori/Analytics%20Cards.html#/s:8SAPFiori28FUIKPICardCollectionViewCellC`.

This appears related to #859 .

## Example
Here the `FUIKPICardCollectionViewCell` does not have any children **by design**, because its interface is defined by Swift protocol extensions.  The interface of the generic parameter (`FUIKPICardView`) is invoked by calls to the interface on the collection view cell.

This is the entire implementation:

```swift
open class FUIKPICardCollectionViewCell: FUIBaseDrawingCollectionViewCell<FUIKPICardView> {

    // internal
    override func setup() {
        super.setup()
        // setup procedure
    }
}
```

## Workaround
We were able to work around by adding a pass-through `override`, but this isn't really good practice.

```swift
open class FUIKPICardCollectionViewCell: FUIBaseDrawingCollectionViewCell<FUIKPICardView> {

    /// The style class property.
    override public var nuiClass: String? {
        set {
            super.nuiClass = newValue
        }
        get {
            return super.nuiClass
        }
    }
    // ...
}
```

**Comment by johnfairh** [comment]
@sstadelman did you mean to write something here?

**Comment by sstadelman** [comment]
@johnfairh yes, updated.

**Comment by johnfairh** [comment]
Thanks!  Closing this in favor of #859.  Renamed that issue to make it clearer what it is tracking.
