### ISSUE TITLE
`Fatal error: not text` with HTML tags in Obj-C comments

### ISSUE THREAD

**Issue by lilyball** [realm/jazzy#976]
Trying to run `jazzy --objc` against my project is erroring out with `Fatal error: not text: CXCommentKind(rawValue: 3)`. It appears that a raw value of `3` corresponds to `CXComment_HTMLStartTag`, and sure enough, my Obj-C documentation has plenty of HTML tags (`<tt>foo</tt>` for multi-word inline code spans).

**Comment by jpsim** [comment]
I’m usually in favor of closing duplicate issues but in this case I’d like to keep open, since the dupe is across two different projects.

**Comment by MosheBerman** [comment]
Leaving a note here that this is an issue for me as well.

**Comment by lilyball** [comment]
This is still an issue for me and prevents me from producing Obj-C documentation for my hybrid framework.

**Comment by johnfairh** [comment]
Fixed in jazzy 0.13.1 via jpsim/SourceKitten#634.
