### ISSUE TITLE
Question about server-side Swift

### ISSUE THREAD

**Issue by crspybits** [realm/jazzy#978]
This may just be out-of-scope for `jazzy`, but do you support documentation for projects that don't have Xcode projects but are written in Swift? e.g., for server-side Swift? Thanks!

**Comment by SDGGiesbrecht** [comment]
Same as #487? (Regardless, there is lots of relevant information in and linked from that issue, @crspybits.)

**Comment by crspybits** [comment]
Thanks-- cool! Allowing Swift package manager projects is definitely what I'm talking about so, yes-- this is a duplicate.
