### ISSUE TITLE
Is it possible to generate an API diff between two versions of a framework?

### ISSUE THREAD

**Issue by richellis** [realm/jazzy#980]
I used Jazzy to generate docs for version 1.0 of my framework. I'm preparing to release version 2.0 and would like to generate a "diff" document showing API that has been added/deleted/modified. Is this possible to do with Jazzy? Or perhaps could someone recommend a different tool that could generate a diff based on jazzy's output files?

Thus far I have been doing a manual diff of the generated HTML as a way to keep tabs on API changes, but I'm looking for something that would be generated automatically and could be published as part of my 2.0 documentation.

Thanks for an amazing tool!

**Comment by 1ec5** [comment]
[apidiff](https://github.com/material-motion/apidiff/) may be useful for generating this kind of output. Like jazzy, it’s powered by SourceKitten. It would be great if jazzy could support integrating apidiff’s output directly inside the docset, similar to what Apple Developer does these days.

**Comment by johnfairh** [comment]
I'm going to close this as out of scope for jazzy at this stage of its life - it feels like something the public DocC will eventually support given Apple have something like it for their internal SDKs.
