### ISSUE TITLE
Way to get the documentation coverage

### ISSUE THREAD

**Issue by hollanderbart** [realm/jazzy#983]
We use Jazzy in our CI to generate documentation which works great. I'm wondering if it's possible to have an export of the documentation coverage that is notated in percent on the static HTML page?

We would like to use this information to get a brief understanding if the documentation coverage is going down and to act on it.

Is this possible to do? Thanks!

**Comment by johnfairh** [comment]
Can you take it from the CLI output (eg. "10% documentation coverage with 2 undocumented symbols") or parse (grep) it out of the docs/badge.svg ?

**Comment by SDGGiesbrecht** [comment]
@hollanderbart, if you want more specific information, you can also look in (or parse) `undocumented.json`, which is at the root of the output. It would give you the *number* instead of the *percentage* of symbols which are undocumented, but that still tells you if coverage is dropping.

**Comment by hollanderbart** [comment]
Great! Thanks for this information. I'll start experimenting with it.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by johnfairh** [comment]
Closing then.
