### ISSUE TITLE
Getting error from xcodebuild arguments.

### ISSUE THREAD

**Issue by eciftcioglu** [realm/jazzy#984]
Hello. I have tried every solution thats related to this error but I just can't seem to figure out whats going on.

Using config file /Users/Emir/Documents/BuyBuddy/SDK/buybuddy-sdk-swift/.jazzy.yaml
Running xcodebuild
Could not parse compiler arguments from `xcodebuild` output.
Please confirm that `xcodebuild` is building a Swift module.
Saved `xcodebuild` log file: /var/folders/wq/10c1jdbs1_gfl14wvpmw88440000gn/T/xcodebuild-E324B78E-9B66-493A-9952-727DA153DEA2.log
Failed to generate documentation
/Library/Ruby/Gems/2.3.0/gems/jazzy-0.9.3/lib/jazzy/executable.rb:36:in `execute_command': /Library/Ruby/Gems/2.3.0/gems/jazzy-0.9.3/bin/sourcekitten ["doc", "--module-name", "BuyBuddySDK", "--", "-project", "BuyBuddySDK.xcodeproj", "-target", "BBIoTKit", "-target", "BBCoreKit", "-target", "BBUIKit"] (RuntimeError)

Running xcodebuild

Could not parse compiler arguments from `xcodebuild` output.

Please confirm that `xcodebuild` is building a Swift module.

Saved `xcodebuild` log file: /var/folders/wq/10c1jdbs1_gfl14wvpmw88440000gn/T/xcodebuild-E324B78E-9B66-493A-9952-727DA153DEA2.log

Failed to generate documentation
	from /Library/Ruby/Gems/2.3.0/gems/jazzy-0.9.3/lib/jazzy/sourcekitten.rb:230:in `run_sourcekitten'
	from /Library/Ruby/Gems/2.3.0/gems/jazzy-0.9.3/lib/jazzy/doc_builder.rb:66:in `block in build'
	from /Library/Ruby/Gems/2.3.0/gems/jazzy-0.9.3/lib/jazzy/doc_builder.rb:64:in `chdir'
	from /Library/Ruby/Gems/2.3.0/gems/jazzy-0.9.3/lib/jazzy/doc_builder.rb:64:in `build'
	from /Library/Ruby/Gems/2.3.0/gems/jazzy-0.9.3/bin/jazzy:15:in `<top (required)>'
	from /usr/local/bin/jazzy:22:in `load'
	from /usr/local/bin/jazzy:22:in `<main>'

Adding the log file also:
[xcodebuild-B3B21F00-2EDA-4EAA-845D-26275B360043.log](https://github.com/realm/jazzy/files/2141375/xcodebuild-B3B21F00-2EDA-4EAA-845D-26275B360043.log)

**Comment by johnfairh** [comment]
Take a look at the xcodebuild output: it shows no sign of any Swift code being built.  For the arguments it looks like you're giving it needs to include a swift compiler step with the arg `-module-name BuyBuddySDK`. Maybe need to adjust the xcodebuild targets being passed?

**Comment by LittleGreenViper** [comment]
Yeah, I went and built Jazzy from the current master branch.

Still happens.
[xcodebuild-CE2BE741-C145-4BFA-B0DC-96346D718126.log](https://github.com/realm/jazzy/files/2442960/xcodebuild-CE2BE741-C145-4BFA-B0DC-96346D718126.log)

**Comment by johnfairh** [comment]
Closing, inactive.
