### ISSUE TITLE
Embedding Screenshot Images in Generated HTML

### ISSUE THREAD

**Issue by JUSTINMKAUFMAN** [realm/jazzy#987]
Is it possible to extend Jazzy to automatically include an in-line image in generated docs (i.e. an <img) in the html file) for classes when a PNG with a file name matching the class name exists in the same directory?

My project already automatically snapshots all of its views and adds PNGs to the project structure according to the schema described above, so it would be a big value add if Jazzy could automatically generate rich docs with that content.

Ideas?

**Comment by SDGGiesbrecht** [comment]
@JUSTINMKAUFMAN

> Ideas?

Are you already aware of the normal way of [including images](https://developer.apple.com/library/archive/documentation/Xcode/Reference/xcode_markup_formatting_ref/Images.html#//apple_ref/doc/uid/TP40016497-CH17-SW1) in documentation?

If you want to automate it, you could write a script that searches for `class X` and adds `/// ![...](.../x.png)` to the preceding line if it is not there already.

Note that the URLs must be absolute, and the images must be hosted separately. Though you could still copy them into the output directory afterward if that is where you want to host them from.

(For discussion about embedding the image files themselves, see #853.)

**Comment by JUSTINMKAUFMAN** [comment]
@sdggiesbrecht I am aware of that method. And it would be great if only Xcode supported inline images in projects (not just Playgrounds). Since it does not, I was hoping to automate the inclusion of those images in html. Does that make sense?

**Comment by SDGGiesbrecht** [comment]
>  if only Xcode supported inline images in projects

Officially it does (see the link above). But you are right that it is broken in the current version of Xcode.

> Since it does not, I was hoping to automate the inclusion of those images in html. Does that make sense?

Makes perfect sense. Maybe you could try post‐processing the HTML? Unfortunately I have no better ideas for the interim.

You can try submitting a pull request if you want, but there is a reasonable chance Xcode will have been fixed by the time your request gets reviewed, merged and then eventually released. It is up to you.

**Comment by JUSTINMKAUFMAN** [comment]
Thanks for the response. 

I don’t see any mention of inline images being officially supported outside of Xcode Playgrounds - which is an important distinction from full fledged Xcode projects.

**Comment by SDGGiesbrecht** [comment]
@JUSTINMKAUFMAN 

> I don’t see any mention of inline images being officially supported outside of Xcode Playgrounds [...]

From the [Markup Formatting Reference](https://developer.apple.com/library/archive/documentation/Xcode/Reference/xcode_markup_formatting_ref/Images.html#//apple_ref/doc/uid/TP40016497-CH17-SW1):

***

> # Images
> [...]
> 
> Works with:
> 
> [...]
> ✓ Symbol documentation

***

> ## Quick Help Example
>
> `/**`
> `  An example of using *images* to display a web image`
>
> `  ![Xcode icon](http://devimages.apple.com.edgekey.net/assets/elements/icons/128x128/xcode.png "Some hover text")`
>
> `  */`

**Comment by JUSTINMKAUFMAN** [comment]
That whole “works with” list is nested under the line: “Include inline images from your _playground_ project.”

And while both of the listed approaches do work in a playground project, neither work in a regular project (nor have I seen it advertised by Apple that they should).

That said, it seems like the sort of thing that could probably be hacked into working in a regular project by an Xcode guru.

**Comment by SDGGiesbrecht** [comment]
@JUSTINMKAUFMAN,

Admittedly some statements in the document are written only with the wording for one or the other, which can make it confusing. But it *is* the definitive guide for each.

From the [summary section of the document](https://developer.apple.com/library/archive/documentation/Xcode/Reference/xcode_markup_formatting_ref/MarkupFunctionality.html#//apple_ref/doc/uid/TP40016497-CH54-SW1):

> Some of the delimiters are used for both rendered playground documentation and in Quick Help. Other delimiters are used with either playgrounds or with Quick Help. The documentation for each delimiter includes information on where it can be used.

1. The “Works with” section at the top of each page tells you which of the two places a particular feature is supported. Under “Images”, both are checked:

    > Works with:
    >
    > ✓ Playgrounds
    > ✓ Symbol documentation

2. The syntax for each type of markup is mutually exclusive ([`//:` vs `///`](https://developer.apple.com/library/archive/documentation/Xcode/Reference/xcode_markup_formatting_ref/SingleLineComment.html#//apple_ref/doc/uid/TP40016497-CH102-SW1)). The “Images” section has examples using both syntax types.

3. There is also a table in the [summary section](https://developer.apple.com/library/archive/documentation/Xcode/Reference/xcode_markup_formatting_ref/MarkupFunctionality.html#//apple_ref/doc/uid/TP40016497-CH54-SW1) contrasting what is available where. The “Images” row clearly has a checkmark under Quick Help.

4. Xcode just ignores truly unsupported things (such as videos or custom callouts); their source is displayed as if it were text for humans. On the other hand, Xcode attempts to handle images. For a long time it just worked. Then in a recent version it started to fail and the entire documentation comment would become invalid and refuse to display. The current version (Xcode 9.4.1) fails a little more gracefully, as the failed image is hidden and the rest of the documentation comment continues to work as normal.

—actually, isn’t that exactly what you were asking for; visible in Jazzy, omitted in Xcode?

**Comment by johnfairh** [comment]
Closing this now, answered.
