### ISSUE TITLE
Objective-C files not found when using folders

### ISSUE THREAD

**Issue by jeffwatkins** [realm/jazzy#988]
New behaviour in Xcode creates file system folders to mimic the projects folder structure. While this is nice from an organisational standpoint, this makes it challenging for Jazzy to process these projects.

Attached is a super simple example that demonstrates this problem. I'm **totally** willing to believe I've just misconfigured my command line arguments, but I've tried it with both the simple approach and the more complicated `--xcodebuild-arguments`.

Really, this should just work as folder backed groups are now the default.

[JazzyTest.zip](https://github.com/realm/jazzy/files/2157550/JazzyTest.zip)

**Comment by jeffwatkins** [comment]
This seems to be bubbling up from `sourcekitten` not finding the files in the first place, because when I try to replicate the same command line that Jazzy is creating, I come up with:

    Support/vendor//bundler/ruby/2.3.0/gems/jazzy-0.9.3/bin/sourcekitten doc --objc JazzyTest/JazzyTest.h -- -x objective-c -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.0.sdk -I JazzyTest/JazzyTest -I JazzyTest/JazzyTest/Folder
    JazzyTest/JazzyTest.h:5:9: fatal error: 'JazzyTest/Thing.h' file not found
    [
    
    ]
 
That kinda explains why Jazzy isn't finding the files.

Again, it's totally possible I've crafted the wrong command line for sourcekitten and that explains why nothing is working.

**Comment by johnfairh** [comment]
This is an example of the 'headermap problem': there is no filesystem location matching 'JazzyTest/Thing.h' so the build will not work without a clang headermap to resolve it.

Ugly workaround is to create symlinks or use `xcodebuild` / `hmaptool` from clang sources to create the various hmap files and pass them directly to clang.  We might get sourcekitten to automate the latter approach one day.

Tracked in jazzy by #667 as the earliest of these.
