### ISSUE TITLE
A compile error prevented R.segue.vc.show(segue:) from receiving a unique USR. Documentation may be incomplete. Please check for compile errors by running `xcodebuild `

### ISSUE THREAD

**Issue by Ewg777** [realm/jazzy#990]
For some reasons your amazing library is now working with https://github.com/mac-cain13/R.swift
Getting an error like this:
`
A compile error prevented R.segue.vc.show(segue:) from receiving a unique USR. Documentation may be incomplete. Please check for compile errors by running `xcodebuild `
`
Is it a jazzy's issue?

**Comment by johnfairh** [comment]
Old, but: this means the thing xcodebuild is being asked to do the wrong thing.  `R` looks like it involves code generation so might take a bit of effort to get working - would need a complete example.

**Comment by johnfairh** [comment]
Closing, inactive.
